### ISSUE TITLE
Removing search in filter breaks rows refresh

### ISSUE THREAD

**Issue by pito2901** [DataTables/DataTables#1003]
Hi !

My datatables works with Ajax and when I make a search in the filter input and delete my search, it returns only the number of rows were filtered.

For example : 

I have
- element 1
- element 2
- element 3

Then, I searched "3", that returns : 
- element 3

But, if I remove my search : "3", it returns only : 
- element 1

Or I want to get back : 
- element 1
- element 2
- element 3

Do you have any idea ?

BTW, the pageResize doesn't work anymore..

Thanks for reading.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
