### ISSUE TITLE
datatable api adding new row for flashing with activated sorting api

### ISSUE THREAD

**Issue by jjhesk** [DataTables/DataTables#1004]
There is an issue when using table with sorting api and row create callback. using the latest version dtable js.

here is the code
```javascript

 window.dt_table = $('#metaTable').DataTable({
        "formatNumber": function (toFormat) {
            if (typeof window.dtable_formatNumber === "function") {
                return window.dtable_formatNumber(toFormat);
            } else {
                return toFormat;
            }
        },
        "createdRow": function (row, data, index) {
            if (typeof window.dtable_row_create_callback === "function") {
                window.dtable_row_create_callback(row, data, index);
            }
        }
    });

```

```javascript


window.dtable_row_create_callback = function (row, data, index) {
    window.console.log(row, index, data);
    $(row[index]).addClass("flashNewItem");
};

```

the expected is result is to able to add the additional class css for the dom tr with "flashNewItem" when the new data row is inserted into the table. however, when the sorting function is activated i.e. the time is listed by desc and there is no way to determine which row to be added with the class name. Are there any solution for this? thank ahead. 
  
read from the topic #981,#789 and it looks promising.

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please?

Also, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
