### ISSUE TITLE
Add Expand/Collapse button

### ISSUE THREAD

**Issue by vislogurov** [DataTables/DataTables#1005]
How would I implement the functionality that will allow me to collapse and expand all rows in a datatable with just the click of a button?

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

This is a question that has been asked a number of times in the forums, so you'll be able to find an answer there.
