### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by mguinness** [DataTables/DataTables#1006]
Got error below when using DataTables editor:

```
Cannot use 'in' operator to search for 'length' in {}
    at isArrayLike (jquery-2.2.4.js:534)
    at Function.each (jquery-2.2.4.js:362)
    at FileReader.reader.onload (dataTables.editor.js:4061)
```

The problem was that my ajax.data was `return JSON.stringify(d);` which meant a string was then being assigned to a variable used in `$.each` function.

My mistake using stringify, but defensive type check `typeof ret !== 'string'` could be added to code:

```Javascript
// Handle the case when the ajax data is given as a function
if ( typeof ajax.data === 'function' ) {
	var d = {};
	var ret = ajax.data( d );

	// Allow the return to be used, or the object passed in
	if (ret !== undefined && typeof ret !== 'string') {
		d = ret;
	}

	$.each( d, function ( key, value ) {
		data.append( key, value );
	} );
}
```

**Comment by DataTables** [comment]
Can you show me the code that triggered the error please?

**Comment by mguinness** [comment]
I can share this snippet which should help you recreate.  The problem was that I hadn't defined the ajax url for the upload field, so it was using the ajax from the editor which returns a string.  Adding ajax to the upload field fixed the problem (commented out below).

Whilst it was my mistake, the library should be fixed to prevent that error (as per my suggestion above).  Otherwise someone else may have to go through a debugging session to determine what is occurring.

```Javascript
editor = new $.fn.dataTable.Editor({
    ajax: {
        url: "/api/Save",
        type: "POST",
        contentType: "application/json",
        data: function (d) {
            return JSON.stringify(d);
        }
    },
    table: "#results",
    idSrc: "ID",
    fields: [{
        label: "Name:",
        name: "name"
    }, {
        label: "Photo:",
        name: "photo",
        type: "upload",
        //ajax: "/api/Upload",
        display: function (file_id) {
            return file_id;
        }
    }]
});
```

**Comment by DataTables** [comment]
Thanks. That looks like a good change to me. It will be in Editor 1.7.1 which will be released later this month.
