### ISSUE TITLE
Bug: jQueryUI Download Builder links are broken

### ISSUE THREAD

**Issue by dknacht** [DataTables/DataTables#1007]
Hi,
First of all I want to thank you for creating and maintaining such an amazing project.

I found out that the lines generated in the [download builder](https://www.datatables.net/download/index) for NPM, Yarn and Bower are wrong.
They are generated in the following format: 
```shell
yarn add datatables.net-ju
```
But after executing it the following error is showed:
```shell
error Couldn't find package "datatables.net-ju" on the "npm" registry.
```
I search and the repositories in fact don't exist. I didn't find any information about it nor someone that seemed to have the same problem so I decided to find out the solution.
I searched for the repositories and it seems that the problem is that they are saved with the `-jqui` prefix instead of the `-ju` that the download builder is generating. I tested all the links changing the prefix and it worked completely ok for yarn, bower and NPM.

So the solution is as simple as changing that prefix in all generated code eg: `yarn add datatables.net-ju` would become `yarn add datatables.net-jqui`, `yarn add datatables.net-autofill-ju` would become `yarn add datatables.net-autofill-jqui` and so on. (In fact I've just realized that in the [Bower download page](https://datatables.net/download/bower), the suffixes are put correctly when selecting jQueryUI Option)

I didn't find if the download builder code is in github so I did't find how to fix it direclty
If you want, tell me where i can make the correction (if i can) and I'll gladly do it. 

Thank you so much and best regards.

**Comment by DataTables** [comment]
Thanks! Its fixed now.

The download builder's source isn't available on GitHub which is why you won't have found it there.
