### ISSUE TITLE
border on bootstrap 4

### ISSUE THREAD

**Issue by ThibaultMartinPenbase** [DataTables/DataTables#1008]
Hello,
On bootstrap 4
`border-collapse: separate !important;`
Duplicate border and not bootstrap template
https://www.noelshack.com/2018-03-4-1516271209-table.png

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by ThibaultMartinPenbase** [comment]
http://www.monde-rp.fr/test.html

**Comment by DataTables** [comment]
Thanks! [Fix committed](https://github.com/DataTables/DataTablesSrc/commit/2b0dce5b4e285e9c09b9c59293df363e99fffc76).

A workaround would be to add `cellspacing="0"` in your `<table>`.

**Comment by morrow95** [comment]
Shouldn't this be changed to : 

border-collapse: collapse !important;  and forget about the newly added border-spacing:0;?

With this new change the border-spacing:0 is correcting the border-collapse:separate... you could just change it to border-collapse:collapse and problem is solved.

**Comment by DataTables** [comment]
No - border-collapse: collapse makes the width calculations and setting of width if scrolling is activated virtually impossible. It has to be separate.
