### ISSUE TITLE
Request drop of "border-collapse: separate !important;" in Bootstrap 4 css

### ISSUE THREAD

**Issue by SubiyaCryolite** [DataTables/DataTables#1010]
Hello,

I'm writing to request that the property "border-collapse: separate !important;" under "table.dataTable" is dropped. This line causes Bootstrap4 tabes to render invisible vertical borders which mess with Bootstrap 4s default Look and Feel.

The screenshots show how my tables render with and without that particular entry.

![before](https://i.imgur.com/3A9xDrk.png)
![after](https://i.imgur.com/VRlO3ZT.png)

Thanks for the great work

**Comment by DataTables** [comment]
See [this issue](https://github.com/DataTables/DataTables/issues/1008) which covers this.

The fix is not to remove the `border-collapse` style, but rather to add `border-spacing`.
