### ISSUE TITLE
Datatable.js is crashing for the more than 40 records 

### ISSUE THREAD

**Issue by Prateek-Havanur** [DataTables/DataTables#1011]
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
 $('#ContentPlaceHolder1_gv_pnotes').DataTable({
                scrollY: Math.round($(window).height()) - 350,
                scrollX: true,
                "bSort": false,
                "bLengthChange": true,
                "lengthMenu": [[25, 50, -1], [25, 50, "All"]],
                "pagingType": "full_numbers_icon",
                order: [1, 'desc'],
            });

Above is the way i am using Datatable. The error will come up only if the number of records exceed 40. below is the error

![image](https://user-images.githubusercontent.com/33024468/35511027-733dcaa2-0520-11e8-9ba7-f52dab1a2ebe.png)

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
