### ISSUE TITLE
Feature : Option to set scrollY to number of rows

### ISSUE THREAD

**Issue by mojimi** [DataTables/DataTables#1014]
When you're dealing with dynamic data, specially server-side, the scrollY option is very limited, I haven't had any sucess in making it work both in desktop and mobile screens.

Would be great if we could simply set the scrollY to display X number of rows, following the paging principle.

**Comment by DataTables** [comment]
If you know the height of the rows, you could just use a multiplier to calculate the right pixel height. Having that built into DataTables is not something I'm currently considering.
