### ISSUE TITLE
Error setting up a Datatable

### ISSUE THREAD

**Issue by prasoc** [DataTables/DataTables#1016]
Line 4811 of `jquery.datatables.js` 

```javascript
		for ( var i=0, ien=lengths.length ; i<ien ; i++ ) {
			select[0][ i ] = new Option(
				typeof language[i] === 'number' ?
					settings.fnFormatNumber( language[i] ) :
					language[i],
				lengths[i]
			);
		}
```

Error: `Uncaught TypeError: Failed to set an indexed property on 'HTMLSelectElement': The provided value is not of type 'HTMLOptionElement'.`

creating a "new Option" is giving me an error, because it isn't of type HTMLOptionElement (it's an "Option" object)

**Comment by DataTables** [comment]
Can you give me a link to a page that shows the error please? It sounds like you might have something that is redefining what `Option` is?

**Comment by prasoc** [comment]
Wow you are right on the mark. We have already got an "Option" class (unbeknownst to me) Thanks @DataTables
