### ISSUE TITLE
rows() filter bugs when the rowSelector has an array with an id of 0

### ISSUE THREAD

**Issue by dagadbm** [DataTables/DataTables#1019]
I found a bug on the datatables Api (I am using version 1.10.3 so I am not sure this is already fixed or not).

This bug happens when I use the rows() method with the following configuration:

table.rows([0,1,2], {search: 'applied});

When inside the __row_selector function here:

```
if ( selInt !== null && $.inArray( selInt, rows ) !== -1 ) {
  // Selector - integer
  return [ selInt ];
}
else if ( ! sel ) { // this is the problem
  // Selector - none
  return rows;
}
```

Since 0 is one of the Ids of the rows he assume there is no selector and just returns the displayedRows instead of continuing with the logic.

Please let me know how I can get around this if possible .

Thank you!

**Comment by DataTables** [comment]
[Yes its already fixed](https://github.com/DataTables/DataTablesSrc/blob/dbef58ea49ae1bb32df2e5bf055d1b5b47016223/js/api/api.rows.js#L36). Always worth trying the latest version :).

**Comment by dagadbm** [comment]
thanks :)
