### ISSUE TITLE
Setting .visible(true/false) to a column already visible/invisible has a impact in performance

### ISSUE THREAD

**Issue by jimerino** [DataTables/DataTables#1020]
If a put a .visible(true/false) to a column who is already visible/invisible has a severe impact in performance.

This issue was tested on a +40k row. I suppose all caches are refreshed without checking if it's necessary do it (if I execute a .visible(true) to an already visible column think don't need refresh any cache because the column is already visible).

I need to put this code to check if the column is already visible/invisible to have a decent performance:

var visibilityState = false;
...
(an algorithm who determines if visibilityState is true or false)
...
if (column.visible() != visibilityState) {
    column.visible(visibilityState);
}

**Comment by DataTables** [comment]
Use the second parameter available to `column().visible()` to disable the column width calculations that are being performed. Indeed, if you are doing this in a loop you would _really_ want to do that, and then call `columns.adjust()` once the loop has finished.

In future, could you post support requests in the [DataTables forums please](//datatables.net/forums).

**Comment by jimerino** [comment]
True! Thanks! Next time I will use the support forums
