### ISSUE TITLE
 Why different servers, the results returned are not the same

### ISSUE THREAD

**Issue by JackLeeChinaJapan** [DataTables/DataTables#1021]
itemTable.row().data()
linux:      id:11 ←number
windows:  id:"11" ←string

**Comment by JackLeeChinaJapan** [comment]
please help me

**Comment by DataTables** [comment]
I'd be happy to help. Per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

**Comment by JackLeeChinaJapan** [comment]
I now use the following execution statement

```
	$("#item-table tr").each(function() {
			if(this.firstChild.nodeName === "TD") {
				var dbuf = itemTable.row(this).data();
				if($('td', this).eq(0).text() === "-") {
					if(arrExpScoId.indexOf(dbuf.id) < 0) {
						arrExpScoId.push(dbuf.id);
					}
				}
			}
		});
```

The result returned by this place
         var dbuf = itemTable.row(this).data();
i see this execution  result 

![image](https://user-images.githubusercontent.com/24803231/36418197-8239da3e-1671-11e8-8ba9-a4e4be5f2027.png)

and 
![image](https://user-images.githubusercontent.com/24803231/36418233-9a085334-1671-11e8-9da0-531fa6461c8d.png)

**Comment by JackLeeChinaJapan** [comment]
Why yellow data types are not the same?  number and string ...why?

**Comment by JackLeeChinaJapan** [comment]
I want their data type to be string    can you tell me why
