### ISSUE TITLE
Fixed column showing scrollbar and duplicating column on Bootstrap 4

### ISSUE THREAD

**Issue by mojimi** [DataTables/DataTables#1025]
I'm using the latest nightly for fixedColumns (3.2.4) and this issue appears when the horizontal overflow of the table is triggered.
 
Example :

![image](https://user-images.githubusercontent.com/10172340/36558294-557a5d1a-17e9-11e8-9eb7-f8aeb375d53d.png)

In the css of the element .DTFC_LeftBodyLiner the overflow-y is set to scroll which seems to be the culprit, setting it to none has seemingly solved the issue for me.

My init options are :
```

                                paging : true,
				pageLength : 7,
				pagingType : 'numbers',
				scrollX: '100%',
                                fixedColumns: {
					leftColumns: 1
				},
```

Worth nothing that the container in which my table resides is a resizable floating panel, and if I stretch it too much, this other issue happens :

![image](https://user-images.githubusercontent.com/10172340/36558516-0dd1db4a-17ea-11e8-80d4-d701614d4555.png)

The fixed column doubles, this seems to be because there is in fact two first columns, one is the fixed and the other is from the original table, but they are misaligned.

And if I force the table to redraw this happens :

![image](https://user-images.githubusercontent.com/10172340/36562987-86a51ba6-17f7-11e8-88ea-4bd8339954e4.png)

This one I haven't found a solution

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

**Comment by mojimi** [comment]
@DataTables I can try to rig up an example as a last effort, just wondering if there's another way I could do it? A video of the error maybe? I can't just copy our environment so it would take some time to replicate the error

**Comment by DataTables** [comment]
A video isn't something I can debug unfortunately. I would need an example page or a JSFiddle or similar showing the issue so I can debug it.

**Comment by mojimi** [comment]
@DataTables issue fixed, turns out I was using the regular .js instead of the Bootstrap4 one, you can close this, and thank you for your attention.

**Comment by mojimi** [comment]
@DataTables Well turns out I was using the regular .js instead of the Bootstrap 4 one, but, switching to the fixed columns for bootstrap 4 made the fixed column stop working, here's the fiddle :

https://jsfiddle.net/rm70fgde/18/

Worth noting that the original issue I posted only happens when you significantly increase/decrease the table width, so you'd need to increase the output window width and use the jsPanel resize controls to see it.

**Comment by DataTables** [comment]
You need to do two things here:

1. Add `width:100%"` to the table, either as a `style` attribute or a `width` attribute (just in the CSS isn't enough I'm afraid, as that isn't easy to read as a percentage value)
2. Call [`columns.adjust()`](https://datatables.net/reference/api/columns.adjust()) when the panel is resized. I don't know what the callback or event will be for that in jsPanel, but I'm sure there will be one, and that is where you would call it.

**Comment by mojimi** [comment]
@DataTables  thank you, hadn't thought about that, you can close it.
