### ISSUE TITLE
Filtering issue with Fixed Header in internet explorer

### ISSUE THREAD

**Issue by vinay-sowdri** [DataTables/DataTables#1026]
Please open the below mentioned link in IE (internet Explorer)

https://datatables.net/extensions/fixedheader/examples/options/columnFiltering.html

Increase the records to 100 and try to filter the datatable by entering some text in the search filter of any column.
1.Issue 1 - After entering the first text, I am either not able to enter the other characters or it prepends my next character.
 2.Issue 2 -Now try and clear the search text using backspace . it doesn't work.

Thanks in advance.

**Comment by DataTables** [comment]
[This is your post on the forums](https://www.datatables.net/forums/discussion/48021/) on this topic where I've added a reply.
