### ISSUE TITLE
Multiple DataTables with seperate Custom filter for each table on same page

### ISSUE THREAD

**Issue by NaveenJayaram94** [DataTables/DataTables#1029]
Hi,
I have 2 tables in same page, let say
```
$('#report-table1').DataTable();
$('#report-table2').DataTable();
```
No I want to add custom filter for each datatable using 

```
$.fn.dataTable.ext.search.push(
    function( settings, data, dataIndex ) {
       
    }
);
```
but above filter works only for one table. How to add different filter function for each datatables in same page. Please help me. Thanks in advance

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

Your question has already been asked a number of times in the forums, which are fully searchable. [For example](https://datatables.net/forums/discussion/comment/68478/#Comment_68478).
