### ISSUE TITLE
SQL Injection: $where in examples/server_side/scripts/ssp.class.php

### ISSUE THREAD

**Issue by lochv** [DataTables/DataTables#1030]
What about SQL Injection: $where in examples/server_side/scripts/ssp.class.php

**Comment by DataTables** [comment]
As far as I am aware, there are none. All parameters that can be user input go [through the binding function](https://github.com/DataTables/DataTables/blob/master/examples/server_side/scripts/ssp.class.php#L426).

If I'm wrong and you are aware of an issue, please use responsible disclosure and let me know directly ([contact](//datatables.net/contact)) so I can patch it and issue a security update release.
