### ISSUE TITLE
Pagination focus

### ISSUE THREAD

**Issue by edrakitin** [DataTables/DataTables#1032]
Hi.
I have a problem with focused page style.
When the table has many pages page numbers can slide left and right after navigation. The focus being restored to the <li> according to idx, we then have one <li> with the active class (the one we are on, we clicked on, but which moved) and another one with the focus.
I have changed css of focused and active elements and got this in mozilla
![mozilla](https://user-images.githubusercontent.com/12526739/37535880-16db549c-295a-11e8-8ae2-f62fb496c466.png)
But in chrome all are very bad
![chrome](https://user-images.githubusercontent.com/12526739/37535911-2ac027a8-295a-11e8-9fb5-6022c83c1a69.png)
I think that it's bootstrap influence. 
How can I get same picture in chrome that is in mozilla?

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
