### ISSUE TITLE
how to save pagination state on ordering?

### ISSUE THREAD

**Issue by Jonston** [DataTables/DataTables#1033]
How to solve the problem of resetting the current page when sorting?Is there an option to implement this?

**Comment by DataTables** [comment]
Programmatically use `table.order( newOrderDetails ).draw( false );`

Via the built in click on a header, no that isn't possible. You'd need to modify the code if you wanted to retain the page position.

In future, please ask support questions in the forums as requested in the new issue template.

**Comment by Jonston** [comment]
Why not enter an input parameter solving this problem?

**Comment by DataTables** [comment]
It would be something I would consider doing if there are enough votes for it. At the moment it isn't something that has been requested much (I can't say never since it probably has been over the last 10 years, but I can't recall them at the moment).
