### ISSUE TITLE
missing css from fix:  Bootstrap 4 needs border-spacing:0

### ISSUE THREAD

**Issue by raydlevel5** [DataTables/DataTables#1036]
With regards to fix #1008 & #1010 -- The minified css file (listed below) does not appear to have `border-spacing: 0;` as referenced in the fix.  Basically, I still have to drop either `border-collapse: separate !important;`, add `cellspacing: "0"`, or manually add `border-spacing: 0;` to my local css (one of those options).

Isn't the minified version (listed below) supposed to have `border-spacing: 0;` ?

the file, https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css, was obtained via "Step 3. Pick a download method", here:  https://datatables.net/download/

**Comment by DataTables** [comment]
Its in the [source here](https://github.com/DataTables/DataTablesSrc/blob/master/css/dataTables.bootstrap4.scss#L9). This is a distribution repo (really a legacy one now). 1.10.17 is due for release soon which will contain the fix.
