### ISSUE TITLE
Sponsorship 

### ISSUE THREAD

**Issue by MikhailTatsky** [DataTables/DataTables#1042]
Is it possible to become sponsor of project and to place link of our product?
FancyGrid - JavaScript grid library for Enterprise
https://fancygrid.com

**Comment by DataTables** [comment]
I'm going to assume that you aren't just pulling my leg ;-). The sponsorship options for DataTables are [available here](https://datatables.net/purchase/index).

**Comment by MikhailTatsky** [comment]
So this will be ok if we will purchase 99$ support support license?
I am wondering since we present competitive product to DataTables...
So I am not sure that you will accept our help.

**Comment by DataTables** [comment]
I don't have any "moral" objection - I'm just somewhat surprised that you would want to sponsor the DataTables project! Most sponsors use DataTables in some way (unless you use it for your internal tools ;-) ).

In all seriousness, FancyGrid is a superb product and if you'd like to sponsor DataTables, it would be a great initial link between us.

**Comment by MikhailTatsky** [comment]
Paid.
I am looking forward to see our logo between your supporters ;)

**Comment by DataTables** [comment]
Its up on the [supporters page now](https://datatables.net/supporters/). Thanks!
