### ISSUE TITLE
[Bug] PDF Export Button Uncaught Malformed table row, a cell is undefined

### ISSUE THREAD

**Issue by XiaoPro** [DataTables/DataTables#1044]
Hi,

There is a bug on HTML 5 PDF export button is **pressed** when there is no data available on tbody. Console.log will print
`Uncaught Malformed table row, a cell is undefined.`

I have created a jsfiddle to reproduce the bug, the original source code is clone from https://datatables.net/extensions/buttons/examples/html5/simple.html

https://jsfiddle.net/1o9vcv3r/2/

Expected behavior - The PDF export button should work properly likes other export buttons do even though no data is available.

![123](https://user-images.githubusercontent.com/16956532/39743961-3a0d92b4-52d5-11e8-9fa0-e07c6248da2d.PNG)

**Comment by DataTables** [comment]
It was [fixed in the Buttons repo](https://github.com/DataTables/Buttons/commit/912d605b7f65e05f28444742c62447e9fd72a972).
