### ISSUE TITLE
checkbox sort issue

### ISSUE THREAD

**Issue by karimmoun** [DataTables/DataTables#1050]
I have an error when trying to use checkbox dom sort 

Uncaught TypeError: oSettings.oApi._fnGetTrNodes is not a function
    at m.fn.init.$.fn.dataTableExt.afnSortData.dom-checkbox

here is my code:
$.fn.dataTableExt.afnSortData['dom-checkbox'] = function  ( oSettings, iColumn )
{
    var aData = [];
    $( 'td:eq('+4+') input', oSettings.oApi._fnGetTrNodes(oSettings) ).each( function () {
        aData.push( this.checked==true ? "1" : "0" );
    } );
    return aData;
};

    $('#table').DataTable({
 

"searching": false,
 "columns": [
            null,
            null,
            null,
            null,
            { "orderDataType": "dom-checkbox" }
        ]
 }); 

Could you help me with that please
thank you

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
