### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'aoColumns[ srcCol ].aDataSort')

### ISSUE THREAD

**Issue by Shakell** [DataTables/DataTables#1051]
I am using DataTables with Angular 5 and jQuery.
When I use ngFor to bind datas, it appears this error.
`TypeError: undefined is not an object (evaluating 'aoColumns[ srcCol ].aDataSort')`
```
<table id="datatables" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
   <thead>
       <tr>
         <th *ngFor="let element of dataTable.headerRow"> {{element}}</th>
       </tr>
   </thead>
</table>
```
But if I use interpolation for binding datas, it works.

```
<table id="datatables" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
      <thead>
          <tr>
            <th>{{ dataTable.headerRow[0] }}</th>
            <th>{{ dataTable.headerRow[1] }}</th>
            <th>{{ dataTable.headerRow[2] }}</th>
            <th>{{ dataTable.headerRow[3] }}</th>
          </tr>
      </thead>
</table>
```

It is odd, has anyone met this problem or someone know the solution. Thanks.

**Comment by Shakell** [comment]
And if I use like this:
```
      <thead>
          <tr>
            <th>{{ dataTable.headerRow[0] }}</th>
            <th>{{ dataTable.headerRow[1] }}</th>
            <th>{{ dataTable.headerRow[2] }}</th>
            <th>{{ dataTable.headerRow[3] }}</th>
            <th *ngFor="let element of dataTable.headerRow"> {{element}}</th>
          </tr>
      </thead>
```
The part of datas bound by ngFor will not appear.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
