### ISSUE TITLE
e.preventDefault() doesn't work for 'select' event

### ISSUE THREAD

**Issue by bmclain** [DataTables/DataTables#1054]
Pretty easy to reproduce:

```
table.on('select', function (e, dt, type, indexes) {
    e.preventDefault();
});
```

My use case is that I need to prevent certain rows from being selectable. My work around has been to manually remove the `selected` class from each <tr> that should be disabled after the select() event fires. The problem is that in the background DataTables will still display that a number of rows are selected when they really aren't.

**Comment by DataTables** [comment]
You are correct - that event doesn't operate with `preventDefault` I'm afraid.

The way to stop the user from selecting rows is the [`user-select` event](https://datatables.net/reference/event/user-select).

Another option is to use the [`select.selector` option](https://datatables.net/reference/option/select.selector) to refine the selection to just the parts of the table you want.
