### ISSUE TITLE
Error provided by custom server-side processing "ajax" is not used anywhere

### ISSUE THREAD

**Issue by mdziekon** [DataTables/DataTables#1055]
I'm currently working on applying server-side pagination in some tables that the project I'm currently working on uses. According to the [server-side](https://datatables.net/manual/server-side) documentation page, the "API call" can return an ``error`` message. However, it seems that when using a custom ``ajax`` function property to DataTables (so an implementation completely controlled by me, no by the built-in AJAX request generator), passing ``error`` property to the ``callback`` in ``ajax: function (data, callback, settings)``does absolutely nothing - the error property is not used anywhere; it's not passed to the logger, it's not used to display an error message (what happens instead, is that DataTables displays the "No rows matched" message; this is most likely caused by the fact that I'm forced to pass an empty array as ``data`` property, otherwise DataTables throws an error, which is counter-intuitive BTW).

With custom ``ajax`` implementation, I'm obviously able to provide my own error handling implementation, however it would be nice to include some sort of facility into DataTables to display a simple error message instead of the "no rows" message (which is obviously wrong in this case - we don't know if there are any rows at all, all we have is the error from the API call). There would be no need to do that if DataTables would provide an ability to inject manually created rows into the table, however doing that in ``serverSide`` mode and using ``row.add() & draw()`` calls seems to invoke another ``ajax`` call, ultimately leading to an infinite recursion (unless... I'm missing some other solution here).

DataTables version used: 1.10.16.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
