### ISSUE TITLE
Child Row not working inside custom tabs

### ISSUE THREAD

**Issue by bjmercado** [DataTables/DataTables#1062]
Hello community child rows are not working inside my custom tabs, heres the print screen the **View** beside the checkbox is the one that must toggle but its not working, i am using laravel

![image](https://user-images.githubusercontent.com/25813633/51582455-18a1cd80-1f07-11e9-9a1f-cb1330dd0f56.png)

below here is the javascript code

`      $('.tab-1').click(function(){
        dataTbl(null);
    });

    $('.tab-2').click(function(){
        dataTbl('MOA1');
    });

    let tb;
    
    const dataTbl = (status) => {

        let table;
    
        if(status === null){
          table = $('#otTblPending');
        }else if(status == 'MOA1'){
          table = $('#otTblApproved');
        }

        tb = table.DataTable({
	      	dom: '<"dt-custom">frtip',
  	    	pageLength: 10,
  	    	processing: true,
  		    serverSide: true,
		      destroy: true,
  		    ajax:{
		         type: 'POST',
		         data: {
			     _token: '{{ csrf_token() }}',
			     status: status,
		         },
  		    url:'{{ route("ack.otlist") }}',
  		    },
  	    	columns: cols(status),
            order: [[1, "desc"]]
         });
    };

    const cols = (status) => {
        if(status === null){
             const pending = [
              {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": 'View'
        },
               {data: 'check', name: 'check', orderable: false, searchable: false},
               {data: 'fullname', name: 'fullname' },
  		         {data: 'reason', name: 'reason' },
 		           {data: 'date', name: 'date' },
  		         {data: 'created_at', name: 'created_at' },
               {data: 'actions', name: 'actions', orderable: false, searchable: false}
            ]  
                 return pending;   
        }else if(status == 'MOA1'){
            const approved = [
              {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": 'View'
        },
               {data: 'fullname', name: 'fullname' },
  		         {data: 'reason', name: 'reason' },
 		           {data: 'date', name: 'date' },
  		         {data: 'created_at', name: 'created_at' },
               {data: 'actions', name: 'actions', orderable: false, searchable: false}
            ]
                  return approved;
        }
    };

     /* Formatting function for row details - modify as you need */
     function format ( d ) {
        // `d` is the original data object for the row
        let tblHtml;
            $.ajax({
              type: 'POST',
              data: {
                _token: '{{ csrf_token() }}',
                x: d.id
              },
              url: '{{ route("depthead.otshow") }}',
              success: function(data) {
                tblHtml = `
                    <tr>
                      <td>Full name:</td>
                      <td>${data['userinfo'].lname}, ${data['userinfo'].fname}</td>
                    </tr>
                `;

                $('.test tbody').html(tblHtml);
              }
            })

        return `<table class="table test">
                  <thead>
                    <tr>
                      <th>Information</th>
                      <th>Details</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
               </table>`;
    }`

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
