### ISSUE TITLE
Alignment problem using sScrollX + sScrollY 

### ISSUE THREAD

**Issue by DiogoDoreto** [DataTables/DataTables#228]
Hello, Allan!

I'm having a problem when using sScrollX and sScrollY with Bootstrap. The calculated widths are not being respected by the browsers, ending with bad aligned header and body.

Here I have an example:
http://jsbin.com/ICOCiSe/1/edit?html,css,js,output

Tested on IE10, Chrome and Firefox on Windows 8.

Thanks!

**Comment by DataTables** [comment]
Going to close this now as I don't have a way to reproducing the issue.

**Comment by chanewad** [comment]
Hello, Allan!
![mismatched](https://cloud.githubusercontent.com/assets/25612664/22694731/603a1958-ed6e-11e6-98bf-0af5b10a1fa1.jpg)

                   I am using DataTable, but in firefox only, if the data column contains images then the width of header column and data column mismitched(as shown in snapshot)

**Comment by dinkar2010** [comment]
Hi I have dataTable version 1.10.13 containing footer and table header also. But on applying 
"scrollY":  "200px",   "scrollX":true , table header and footer get misaligned. Please someone suggest me how to fix it.

**Comment by DataTables** [comment]
Please post support questions in the [DataTables forums](//datatables.net/forums) with a link to a test case showing the issue and using the latest version. Thanks.
