### ISSUE TITLE
ColVis Table Width in Internet Explorer 8

### ISSUE THREAD

**Issue by jimmyheaddon** [DataTables/DataTables#27]
This has been discussed on the DataTables forum previously but I wanted to raise this as an issue here so that you could track it easier.

The forum post can be found here:

http://www.datatables.net/forums/discussion/5364/colvis-table-width/p1

And a live example of the problem can be found in your demo site here on Internet Explorer 8:

http://datatables.net/release-datatables/extras/ColVis/style.html

This happens with previous and the latest version of jQuery and the latest development versions of DataTables and ColVis.

Cheers!

**Comment by DataTables** [comment]
Going to close this now - years later - sorry! ColVis is defunct, replaced by the Buttons extension now.
