### ISSUE TITLE
FixedHeader is not responsive

### ISSUE THREAD

**Issue by smartcorestudio** [DataTables/DataTables#413]
FixedHeader behaviour is incorrect on resize http://datatables.net/release-datatables/extensions/FixedHeader/examples/simple.html (try to resize browser window)

**Comment by kshipp** [comment]
Same issue.  It's extremely frustrating to see all the same issues and threads, yet most are marked "closed" or "solved", but they are NOT solved using the current versions.  All the tips on using fnAdjustColumnSizing doesn't work because that function is no longer defined!  Why can't this JUST WORK!?   ugh.

**Comment by DataTables** [comment]
I'm sorry it is frustrating - I know this all to well myself. I really hope to get the fix for this integrated into the software soon - I've just had other things to do unfortunately. I'll try to make time for it tomorrow as this has been open way too long.

**Comment by jhfrench** [comment]
"Sorry"? You're "*sorry*"? For what?! For tirelessly devoting uncompensated time to a project that has made hundres, maybe thouseands, of websites better?

I don't accept your apology.

**Comment by DataTables** [comment]
Slapped down...! ;-). More good work coming up!

**Comment by phillc73** [comment]
I would also like to raise this issue. I have come across it when using the [R library DT](https://github.com/rstudio/DT), which wraps DataTables.

I [logged an issue](https://github.com/rstudio/DT/issues/60) with the DT team, but it looks like an upstream problem.

Thanks for taking the time to look into this.

**Comment by DataTables** [comment]
Note to self for when doing this - I think it should simply be a case of listening for the `column-visibility` event in FixedHeader and then redrawing based on that.

I'm going through the process of updating all of the extensions for 1.10's API at the moment - there is a lot of code and a _lot_ of documentation to write so it is taking a while, but I'll make sure this is in the next version of FixedHeader which will likely be a major release.

**Comment by stravanato** [comment]
The kshipp's workaround worked for me, also in Chrome.

**Comment by johnmorsley** [comment]
Yes, keep up the good work DataTables, you are a star. My Account Managers have loved what I've done with my tables! Just in case you are unaware, fixedHeaders seems to go wrong for me when I change the change the number of entries to show. Thanks kshipp, your fix worked for me, except with the above issue... :)

**Comment by DataTables** [comment]
Just been looking into this and I believe the issue has actually been fixed already by 7e72ac7c981.

I've also just added an example that uses DataTables/Responsive to the repo and that appears to work nicely.

Could one or more of you try the [nightly version](http://datatables.net/download/build/dataTables.fixedHeader.nightly.js?_=1fb2806bc93f1cb8fad13ad92aaae2db) for FixedHeader and let me know how you get on with it please? If all looks good I'll package it up and release, as I'm going to be starting work on a rewrite of this plug-in soon.

**Comment by stravanato** [comment]
The resizing issue seems fixed to me. I tried with Chrome.
I still notice the "wrong width of columns" problem.
The workaround for this is to call FixedHeader in fnInitComplete callback.
```
  var table = $('#datatable').dataTable({
    processing: true,
    serverSide: true,
    pageLength: 25,
    ajax: "ajax/server_processing.php",
    fnInitComplete: function (settings, json) {
      new FixedHeader(table);
    },
    columns: [
      {data : "name"},
      {data : "position"},
      {data : "office"},
      {data : "extn"},
      {data : "start_date"},
      {data : "salary"}
    ]
  });
```

**Comment by DataTables** [comment]
I believe that is fixed in the _3_ branch which is a ground up rewrite (and not fully backwards compatible). It is still a work in progress though.

Until then, using fnInitComplete looks good - or using the fnUpdate method in fnInitComplete.

I'll probably release the current state as the final release release of the 2.x series, unless anyone has found any issues with the responsive aspect of the current code.

**Comment by DataTables** [comment]
[Example](https://datatables.net/extensions/fixedheader/examples/integration/responsive.html) of FixedHeader and Responsive working together.

**Comment by Misiu** [comment]
There is still one but on Your site, when You shrink browser to be less than 800px width You'll get this behavior - incorrect positioned header:![snap 2016-09-28 at 22 52 20](https://cloud.githubusercontent.com/assets/1741838/18931860/4911b90a-85ce-11e6-8e29-d08c4edc4ebf.png)

Except this tiny bug FixedHeader and Responsive works together greate.

**Comment by DataTables** [comment]
That's actually a but with my site rather than FixedHeader (it removes the fixed nav at the top of the page when small). Thanks for pointing it out!

**Comment by Misiu** [comment]
@DataTables I've noticed it happens only on Your site, sorry I didn't wrote that before. FixedHeader works fine 😄

**Comment by cromartie1984** [comment]
Hi, fixed header and responsive do not work on chrome, i don't have the expand buttons and i go this error with this 

> new $.fn.dataTable.FixedHeader( users_table )

-> Cannot read property 'top' of undefined
