### ISSUE TITLE
provide i18n support for plugins

### ISSUE THREAD

**Issue by petri** [DataTables/DataTables#422]
It would be very useful if plugins could be i18n'd as well. Given DataTables has facility for i18n, it would be convenient if the facility was extended so it's modular in a way that plugin authors could use it & provide translations within their own packages. Or via some other means.

**Comment by syshex** [comment]
any idea when this issue will be dealt with ?

**Comment by DataTables** [comment]
Oops - I forgot to update this issue. It is already done: http://datatables.net/reference/api/i18n() .
