### ISSUE TITLE
Incorrect calculation of column widths when th is wider than td (affects Bootstrap)

### ISSUE THREAD

**Issue by abeverley** [DataTables/DataTables#455]
When a column's title is wider than the data it contains, the available width is sometimes calculated incorrectly.

The reason is that when the header is cloned, it does not include the associated ```<tr>``` element, and when the column headers are subsequently appended to it they are appended directly to the ```<thead>```.

So the source table is ```<thead><tr><th>```, but the clone is ```<thead><th>```.

This is a problem when the former has different padding to the latter (as in the case of Bootstrap). In this case (if the data in the cells is small), the cloned table is narrower than the original, and thus too many columns are sometimes shown.

I was hoping to provide a patch, but have failed to produce a nice solution. I have fixed it as follows:

```-    var clonedHeader = $( dt.table().header().cloneNode( false ) ).appendTo( clonedTable );```
```+    var clonedHeader = $( dt.table().header().cloneNode( true ) ).appendTo( clonedTable );```

Which kind of works, but it results in the cloned table having 2 header rows. I couldn't work out how to ensure that the cloned header keeps its associated row.

Thanks,

Andy

**Comment by DataTables** [comment]
Finally [fixed here](https://github.com/DataTables/Responsive/commit/98e8a9ddd333f96). There was an error in how the width calculation table was being constructed that in Bootstrap meant that the cell header padding wasn't being counted, thus it was particularly noticeable there.

Thanks for flagging this up and sorry for the slow response to the issue!

**Comment by abeverley** [comment]
Oooh, thanks for that, I'd completely forgotten! I did mean to move the issue to the other repo, but appreciate you fixing it nonetheless. Many thanks.
