### ISSUE TITLE
language.paginate treats input as html, not text

### ISSUE THREAD

**Issue by SimenB** [DataTables/DataTables#456]
Se here: https://github.com/DataTables/DataTables/blob/31670cc1c58995deb214da1d287731817f0e963d/media/js/jquery.dataTables.js#L14174

This might be obvious, but I thought it was treated as text.

We had this
```
'paginate': {
    'first': '<<',
    'previous': '<',
    'next': '>',
    'last': '>>'
}
```
which didn't work in IE8, but worked fine in other browsers. Now using 
```
'paginate': {
    'first': '&lt&lt',
    'previous': '&lt',
    'next': '&gt',
    'last': '&gt&gt'
}
```

Which isn't as readable.

My point with this issue is that you should either make clear in the docs that the input in language is interpreted as HTML, or escape the text or use ``jQuery.text()`` instead of ``jQuery.html()``.

If it's already obvious in the docs, then I'm just blind, and I apologize :smile:

**Comment by DataTables** [comment]
Finally updated the documentation [here](https://github.com/DataTables/DataTablesSrc/commit/9c33b362e7b3a). Will be deployed to the site soon.
