### ISSUE TITLE
Search funcionality does not work in IE7 v1.10.4

### ISSUE THREAD

**Issue by nicoabie** [DataTables/DataTables#459]
calling $('#table').DataTable().search('something').draw(); does not work.

As it just fails in IE7, I've been debugging it using "alerts" and what I've found is that when the this.api method is invoked when search is called, the context of "this" is not the same as when the datatables were initialized, that does not happens in the rest of the browsers.

**Comment by DataTables** [comment]
Haven't received a test case I'm afraid, so going to close this for now as searching appears to work as best I can tell in IE7. Please post a link to a test case if this is still causing issues.
