### ISSUE TITLE
Support Template to render the table?

### ISSUE THREAD

**Issue by icai** [DataTables/DataTables#469]
templdate：
	{
	            HROW: '<th>{{hcell}}</th>',
	            BODY: '<tbody>{{brow}}</tbody>',
	            BROW: '<tr>{{cell}}</tr>',
	           ...
	}

if support this, that the plugin will be more powerful.

example:
 HROW: '<th>{{hcell}} I can add some element in here</th>'

**Comment by DataTables** [comment]
Sorry I forgot to post back on this at the time! I currently don't have any plans to integrate such a template option into DataTables. A plug-in might be something I work on in future, but there is a massive list of other features I plan to work on first. As such, going to close this one for now.
