### ISSUE TITLE
publish npm package

### ISSUE THREAD

**Issue by theofidry** [DataTables/DataTables#477]

**Comment by DataTables** [comment]
https://www.npmjs.com/package/datatables ?

**Comment by theofidry** [comment]
Indeed sorry I didn't see it, I didn't see it in the Installation section neither in the link to which it refers.

**Comment by DataTables** [comment]
I'm working on a number of changes for installation and packaging DataTables and its extensions on the various package managers that are available. Likely it will take a few months before they are fully deployed as there are a number of other things I'm working on as well. Going to close this bug in the mean time.
