### ISSUE TITLE
column().search() documentation

### ISSUE THREAD

**Issue by benbro** [DataTables/DataTables#478]
```
Search for data the selected column.
```
should be (missing in)
```
Search for data in the selected column.
```

http://datatables.net/reference/api/column%28%29.search%28%29

**Comment by DataTables** [comment]
Thanks for pointing this out - [fixed here](https://github.com/DataTables/DataTablesSrc/commit/2301ecbdbded512284b078838d9b2be274786670). I'll be redeploying the site with the fix in the coming week.
