### ISSUE TITLE
"Index column" documentation typo

### ISSUE THREAD

**Issue by jhfrench** [DataTables/DataTables#482]
The ["Index column"](http://www.datatables.net/examples/api/counter_columns.html) documentation has a typo:

"A fairly common requirement for highly interactive tables which are displayed on the web is to have a column which with a 'counter' for the row number."

Suggest:

"Highly-interactive web tables often require providing a 'counter' column that holds the row's number."

I'm enforcing a bias against the word "display" out of respect for screen-readers, but you certainly need not subscribe to that bit of pedantry.

**Comment by DataTables** [comment]
Thanks for pointing this out. I've just [committed a fix](https://github.com/DataTables/DataTablesSrc/commit/1d2fed795373) and I'll deploy it to the site soon.

Out of interest, do you use a screenreader yourself? I'm always on the lookout for feedback on how DataTables behaves which screenreaders, and why I can experiment with them myself, as I don't use one all the time, I'll never be able to create the proper "effect".

**Comment by jhfrench** [comment]
1. Thanks for fixing; had I been on the ball I would have seen that the documentation was included within the sourcecode and I would have forked/fixed/pull-requested and saved you the trouble.
 2. I do not use a screen-reader. Thankfully. I'm fairly certain that my feeble brain would become lost in the audible forest, particularly without the benefit of a visual aid.
