### ISSUE TITLE
Header with multiple table rows [v1.9.4]

### ISSUE THREAD

**Issue by Kureev** [DataTables/DataTables#487]
Hi all,

I have a project to maintain with 1.9.4 version of the library. Does it possible to make a multi-rows `thead` block with the first row order? I.e. now if I use your plugin with such HTML as

```html
<table>
  <thead>
    <tr class="header">
      <th>...</th>
      <th>...</th>
    </tr>
   <tr class="subheader">
      <th>...</th>
      <th>...</th>
    </tr>
  </thead>
  <tbody>...</tbody>
</table>
```

I have a sorting assigned to the first row instead of the second one (to `.header` instead of `.subheader`). Could it be some option that I missed or any workaround without moving to 1.10.x version?

**Comment by DataTables** [comment]
Yes, in 1.9 you can use the [bSortCellsTop option](http://legacy.datatables.net/ref#bSortCellsTop).

In future, please use the [DataTables forums for support requests](//datatables.net/forums). The github issue tracker is used for bugs only.
