### ISSUE TITLE
How to reload sourced data with button ?

### ISSUE THREAD

**Issue by darkcyber** [DataTables/DataTables#488]
here is my html table
```
<table role="grid" class="display responsive hover" id="categoriesTable" width="100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
<tbody>
<tr>
<td>name1</td>
<td>slug1</td>
<td>description1</td>
<td>action1</td>
</tr>
<tr>
<td>name2</td>
<td>slug2</td>
<td>description2</td>
<td>action2</td>
</tr>
.... and so on , proccessed by php loop
</tbody>
</table>
```

here is my javascript
```
        var dataTable = $('#categoriesTable').dataTable({
            "pageLength": 5,
            "lengthMenu": [[5, 10, 25, 50, 100], [5, 10, 25, 50, 100]],
            "bSort": false,    
            responsive : true
        });
```

my refresh button function
```
$("#refreshTable").click(function(){
dataTable.fnClearTable(); // this work and table clear.
// whats next ? to reload recent data without refresh the page
});
```

and yes, my table work like expected.

but how i can load recent data with button ? assume I force delete data from database, and I click refresh button, it should load recent table with new data of course without refreshing the page. how i can do this ?

**Comment by DataTables** [comment]
If you want to add data using the legacy API you would use [fnAddData](//legacy.datatables.net/ref#fnAddData).

In the new API it is [rows.add()](//datatables.net/reference/api/rows.add()).

In future, can you post support requests in the [DataTables forums](//datatables.net/forums) please. GitHub issues are used for bugs only and not support questions.
