### ISSUE TITLE
AJAX Bug using $().serialize/.serializeArray() in DataTables v1.10.3

### ISSUE THREAD

**Issue by vol7ron** [DataTables/DataTables#490]
http://datatables.net/forums/discussion/25884/datatables-odd-ajax

**Important! The implications of following problem results in ServerSide processing being inaccessible, making it seemingly impossible to work with large datasets**

When passing in `$('form').serialize()` for AJAX params, it is breaking up the string and sending each character its own value.  

    {
        ajax: { 
           url:  window.location.pathname,  // calling the correct url
           data: $('form').serialize(),     // am sure this is resolving to a string, like 'key=value&key2=value2'
           type: 'POST'                     // tried GET, JSON, and leaving it blank
        },
        ...
    }

So given the serialized example above of `key=value&key2=value2`, debugging in Firebug shows DataTables is breaking the string into tokens and sending each as an individual set of arguments to make it look like token index is the key and the characters are the value:

    1 k
    2 e
    3 y
    4 =
    5 v
    ...etc

I'm curious if this has anything to do with Rails putting in special form UTF-8 values.  The only way I can get this to work is to execute a look up separately using `$.ajax()` and creating the datatable in the callback (somewhat assuring me special characters aren't at fault); the following works:

    $.ajax({
       url:  window.location.pathname,
       data: $('form').serialize(),
       type: 'POST'
       success: function(response){
          createDataTable( response.data );
       }
    });

The HTTP request using the jQuery ajax function above works as expected and passes the arguments like so `key : value`, `key2 : value2`.  So why would DataTables break up the string?  This leads me to believe there is a bug somewhere, which would render the AJAX functionality useless.

---

### Even Odder

`data: $('form').serializeArray()` works, but if I try to store it in a variable and add a parameter to the array, I get funny results in the request.  An example of doing this is:

    var form_data = $('form').serializeArray();
    form_data.push({ 'name' : 'dynamic_param', 'value' : 'dynamic_param_value' });
    // DataTable({ ajax : { ..., data: form_data }, ...)

Now in the debugger the parameters look like this, notice it's back to using the index, but has also started using the object property as the HTTP param key:

    0[name]  key
    0[value] value
    1[name]  key2
    1[value] value2
    2[name]  dynamic_param
    2[value] dynamic_param_value

To make sure there's nothing wrong with the form, calling the same from `$.ajax()` still formats the request params as expected:

    key            value
    key2           value2
    dynamic_param  dynamic_param_value

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please? The description above seems to relate directly to jQuery methods, but I'm not sure where DataTables come into play with it. It doesn't effect or override the jQuery base methods.

**Comment by vol7ron** [comment]
I'll try to create an example using your suggested jsbin link.  I hope I can reproduce it on a public web server.  

The main reason I created a ticket here is because of the fact that when I use the native `jQuery.ajax` method, it creates the correct HTTP request, but if I take the same code and put it in the DataTable ajax option, it doesn't work.  I believe it should.

I'm not as familiar with 1.10, as I was with 1.9, and I'm not sure what's changed in 1.10.4 vs 1.10.3 (the version I'm using).  Because I'm not as familiar with how DT operates behind the scenes anymore, I was hoping you had experience with Rails and could test whether the utf8/authenticity values might be encoded in such a way that is is screwing up DT parsing.

In the meantime, thanks for responding and I will try and come up with an example as soon as I can.

**Comment by DataTables** [comment]
I don't have any Rails experience but I don't see how its character set would cause issues for a jQuery method. I'm also not clear on how DataTables (any version) would effect how the jQuery serialise method works if it isn't calling DataTables. An example would be great!

**Comment by vol7ron** [comment]
It's very well possible I'm screwing it up somehow, I tried to go off your example on datatables.net.  

For example see here: http://live.datatables.net/qaniduxo/1

Check out the post params using Firebug (or other net analysis utility).  What I've discovered in trying to give you a lot to look at is DataTables only accepts ajax.data in the form of an object of key/value pairs; this is different from jQuery.ajax, which accepts a serialized string, or an array of objects, as .serialize() or .serializeArray() yields, respectively.

If this is the intended expectation, I suggest (1) that we update the example on the website and clarify what DataTables's ajax expects as an argument to the data property; (2) a possible enhance would be to accept the results of serialize() or serializeArray() to perform how jQuery does — this could further be enhanced to store form elements and update the table when one of the inputs change.

**Comment by DataTables** [comment]
The [`ajax.data` documentation](http://datatables.net/reference/option/ajax.data) doesn't list a string as a valid data type for that parameter, So `$('form').serialize() + '&key99=value99',` (and the other string forms) is unexpected input and hence why it doesn't work. Did you find any documentation to suggest it would? If so, if you could point me to it so I can fix it that would be great.

Generally speaking, given that the input can be changed by a user you will want to use the `ajax.data` option as a function to it is evaluated whenever DataTables makes an Ajax request.

**Comment by vol7ron** [comment]
@DataTables — To answer your question, no; it didn't explicitly say anywhere that it accepts a string as a valid data type.  

### Confusion Point 1
> DataTables will construct a data object internally...
So this is great.  This means that it's taking input (*type not yet mentioned* — I'm already thinking a type other than an *object*) and constructing an object so the internal functions have a known structure to work with.

It seems the only place it helps to know what is happening internally is when describing the function data type, since I think that's where the API can access the internal object.  Knowing what's going on behind the scenes isn't really necessary elsewhere since it's more system documentation than user (of plugin) documentation.

### Confusion Point 2
> In principle it operates in exactly the same way as jQuery's $.ajax.data property
Except, as my example shows, it does not operate in *exactly the same way*.  jQuery's `$.ajax.data` accepts the array of objects, as well as a string; basically the results of its *serialize/Array* methods.

I think this line is what really threw me off.  In order to manipulate serverSide requests, a form/input is generally used — why require a function to create input when jQuery already does it?  In this case my function would be deconstructing the string or serializeArray result into what DataTables expects.  Since DataTables sits over jQuery, I would think it would do this internally, or be able to handle a jQuery object of form elements to build params from.

### Other Updates

    "data": {
        "user_id": 451
    }

The current example of the expected object is simple.  It shows one key and one value.  The documentation might benefit from also seeing a more elaborate example.  For instance, if you want to pass in multiple keys/values,  or parameters with the same name.  I suspect it would look something like:

    "data": {
        "user_id": 451,
        "blog_id": 187,
        "comments[]": ["thank you", "troller", ";)"]
    }

--- 
Unrelated/Off-Topic:  Was the use of *451* an allusion to Fahrenheit 451?

**Comment by DataTables** [comment]
> Except, as my example shows, it does not operate in exactly the same way.

Fair point! There was always going to be an edge case I guess... The reason a string can't be used is that DataTables could potentially need to deserialise it in order to add its own parameters (for example if server-side processing is being used).

I'll update the documentation note that it is almost the same!

> why require a function to create input when jQuery already does it?

It _has to be_ a function so that the data is evaluated on each request. If you just evaluate the form values when the table is initialised, any changes to the inputs would not be reflected in any future requests.

> The current example of the expected object is simple. It shows one key and one value.

Intentionally so. But good point about adding another more complex example. Having said that, the static case (not a function) is fairly limited (as noted above).

> Unrelated/Off-Topic: Was the use of 451 an allusion to Fahrenheit 451?

haha! I wish it was, but no. Just coincidence.

**Comment by vol7ron** [comment]
> It has to be a function so that the data is evaluated on each request.

For some reason I was thinking if it accepted a jQuery object as a form (e.g., `$('form')`), or form elements (e.g., `$(':input')`), it could do the serialization.  This would be more of an extra feature and probably not something that is of absolute importance.

I'm just happy to know that DataTables is working as expected and that it's my misunderstanding that was at fault — not any special values created by Rails, or something unexpected in DT internally.  My table has gotten so large that it's about time to look into serverSide processing.

**Comment by RipCurrent** [comment]
Hi vol7ron,
running into the exact same issue. Are you code as per Example#5 or did you find way to wrap form.serialize into format that can be used by DataTables?
Thanks for the detailed example code!!

**Comment by vol7ron** [comment]
@RipCurrent
I cannot recall what I did specifically; but, I can look it up, if you're really interested.  As Allan/@DataTables stated, the expected value is an object, or function.  If memory serves me correctly, I think that I used a function, which created and returned an object, using `jQuery.serializeArray` to create that object.

**Comment by RipCurrent** [comment]
@vol7ron thanks for taking time to reply, was unfamiliar to .serializeArray, will give this a go. thx

**Comment by sriharsha1235** [comment]
Hi,

I also faced the similar issue, instead of serializeArray write a function as given here it works. http://jsfiddle.net/rFzyQ/

**Comment by tungstencarbide** [comment]
Funny thing, if for whatever reason you just want to send a fixed string in your data, instead of:
```javascript
...
    "data" : "someparam=somevalue",
...
```
Just do this:
```javascript
...
    "data" : function () { "someparam=somevalue"; },
...
```
And it works just fine. Apparently it really wants a function. :smiley:

**Comment by wgasparin** [comment]
Same problem here. I used the same function serializeObject showed by @sriharsha1235.
