### ISSUE TITLE
Make it easier to use Bootstrap

### ISSUE THREAD

**Issue by ircer** [DataTables/DataTables#492]
Hi @DataTables 

I use Bootstrap a lot in my work and I also use DataTables and Editor.

One of the main points that always bugged my is how complicated (in terms of includes/lines) it is to use Bootstrap integration. For example especially with Editor you have to include something like 10+ CSS/JavaScript includes!

Is there anyway that this can be made simpler for example `theme:  "Bootstrap",` and let DataTables/Editor do the rest in the background?

Obviously, creating a website using Bootstrap requires 1 CSS include and 1 JavaScript include ;-) so I don't understand why DataTables/Editor needs so many.

Keep up the good work! :+1:

**Comment by DataTables** [comment]
Hi,

To some extend the Editor Bootstrap integration is as simple as the DataTables Bootstrap integration - you include Editor and the integration files, just as you have to include DataTables + its integration files.

However, I do take the point that the combination of this is they you end up with a lot of includes... Something I very much have in mind going forward and a plan to address in future. On my time chart it is a few months away. In the mean time I'm going to close this issue as it isn't a bug as such.

**Comment by ircer** [comment]
Hi @DataTables 

Thanks for your speedy reply!

I hope soon it will be much simpler, glad it is on your plan :+1: 

Thanks :-)
