### ISSUE TITLE
column.orderData does not accept integer value as the documentation says 1.10.4

### ISSUE THREAD

**Issue by adrienducos** [DataTables/DataTables#495]
https://datatables.net/reference/option/columns.orderData

If you put 
"orderData" : 0 (as the documentation says)
it does not work, but if you put
"orderData" : "0"
It works

Exemple on fiddle:
http://jsfiddle.net/ztwyzn5n/4/

If you click on "manpower" the ordering process does not work (in fact it does nothing)
Now if we add slashes arround the 0 => "0"
http://jsfiddle.net/ztwyzn5n/5/

and we click on "manpower" again the ordering process works perfectly.

2 possibilities : the documentation is not correct or the functionality does not work correctly.

**Comment by DataTables** [comment]
This a bug. Thanks for letting me know about this. [Fix committed here](https://github.com/DataTables/DataTablesSrc/commit/0d84d8797af60826) and I'm just about to rebuild the nightly with the fix.
