### ISSUE TITLE
data-order doesn't work (probably because of dynamically added row?)

### ISSUE THREAD

**Issue by dexcell** [DataTables/DataTables#496]
Hi,

I'm trying to sort the column using `data-order` but the row doesn't sorted as expected.
The row is created dynamically using `datatable.row.add` method.

````
// Get search table
var table = $('#table-search').DataTable();

// Add row to table (add html as row using jquery object)
table.row.add($('#table-search-row')).draw();
````

Here is the screenshot of the html and it's `data-order` value when i sort asc by clicking the column header.
![1](https://cloud.githubusercontent.com/assets/41800/6200335/7621dc6e-b4a5-11e4-945e-19087b128a0d.jpg)

Any help?
Thank you

**Comment by DataTables** [comment]
Can you link to a test case showing the issue so it can be debugged please.

**Comment by dexcell** [comment]
Here is the fiddle.
http://jsfiddle.net/4pry7og5/3/

If you see, the number column doesn't sort as expected even tough there is data-order declared in `td`.

Thank you

**Comment by morrow95** [comment]
I'm not seeing a problem here - both columns are sorting fine in your fiddle from what I see.  You are also generating random strings as well... perhaps defined strings instead of random would make your fiddle more clear and show exactly what row(s) you see are out of place.

**Comment by Misiu** [comment]
@dexcell I know that this isn't directly related to issue, but I saw Your code and noticed two places that You can easily improve.

1. Don't call draw inside loop, call in after You add all rows, table object also has `draw()` method.
2. If You want to replace all occurrences use `.replace(/{{number}}/g, number)`, this way You won't have to call same function over and over.

Here is Your code with those fixes:
http://jsfiddle.net/4pry7og5/6/

I added small timing information, so You will see difference with and without my fixes.

**Comment by Misiu** [comment]
@dexcell I also fixed Your issue by moving DataTable initialization after for loop:
http://jsfiddle.net/4pry7og5/7/

This solves Your issue, but as You wrote, when using `datatable.row.add` DataTables is "skipping" `data-*` attributes.

@DataTables is this by design or a bug?

**Comment by DataTables** [comment]
> is this by design or a bug?

Neither really! The table is empty when it is initialised so DataTables can't automatically detect any attributes for sorting, filtering, etc. Then new rows are added, which is fine, but DataTables doesn't automatically look for attributes in newly added rows - only when the table is initialised.

So I guess you could say it is by design - it is working as I would expect.

What you can do is tell DataTables to expect attributes using the `columns.render` option:

```js
        columnDefs: [
            {
                targets: -1,
                data: {
                    _: "1.display",
                    sort: "1.@data-order",
                    type: "1.@data-order"
                }
            }
        ]
```

[Updated fiddle](http://jsfiddle.net/4pry7og5/8/).

Inspecting rows on add for automatically detecting attributes is not something I currently want to add into DataTables, so this manual option is currently the only way.

**Comment by dexcell** [comment]
Thank you so much for your help and tips

**Comment by Tklaversma** [comment]
@DataTables I would like to discuss the solution you gave by using collumnDefs as a solution to use data-order on dynamically loaded content. I do not know if this is the correct place, but here goes..

<b>I updated the Fiddle you gave, which you can view [here](http://jsfiddle.net/4pry7og5/18/), to having three columns, but this gives an error. Can you help me out?</b>

My actual problem is the same as @dexcell described above...using data-order on dynamically loaded content.  My actual code can be viewed below, but the updated Fiddle should suffice.
```
    // Initialize DataTable
    $(mpcTableSelector)

        // Show processing message and hide table until DataTables is loaded
        .on('processing.dt', function(e, settings, processing) {
                if (processing) {
                    $(mpcTableSelector).css('display', 'none');
                } else {
                    $(mpcTableSelector).removeAttr('style');
                }
            })

        // When DataTables is loaded, hide processing message and show table
        .dataTable(
        {
            // Localization
            language    : {
                emptyTable    : mpc.translations.datatables.event.emptyTable,
                info          : mpc.translations.datatables.event.info,
                infoEmpty     : mpc.translations.datatables.event.infoEmpty,
                infoFiltered  : mpc.translations.datatables.event.infoFiltered,
                infoPostFix   : '',
                thousands     : '.',
                lengthMenu    : mpc.translations.datatables.event.lengthMenu,
                loadingRecords: mpc.translations.datatables.event.loadingRecords,
                processing    : mpc.translations.datatables.event.processing,
                search        : mpc.translations.datatables.event.search,
                zeroRecords   : mpc.translations.datatables.event.zeroRecords,
                paginate      : {
                    first   : mpc.translations.datatables.event.first,
                    last    : mpc.translations.datatables.event.last,
                    next    : mpc.translations.datatables.event.next,
                    previous: mpc.translations.datatables.event.previous
                },
                aria          : {
                    sortAscending : mpc.translations.datatables.event.sortAscending,
                    sortDescending: mpc.translations.datatables.event.sortDescending
                }
            },

            // Features
            ordering    : true,
            paging      : true,
            searching   : true,
            columnDefs  : [
                {
                    targets   : 'nosearch',
                    searchable: false
                },
                {
                    targets : 'nosort',
                    sortable: false
                },
                {
                    targets      : 'radio',
                    orderDataType: 'dom-radio'
                }
            ],

            // Callbacks
            initComplete: function() {

                // Remove pagination if there is only one page
                var wrapper = $(mpcTableSelector).parent();
                if ($('.dataTables_paginate > span a', wrapper).length < 2) {
                    $('.dataTables_info', wrapper).remove();
                    $('.dataTables_paginate', wrapper).remove();
                }
            },

            // Options
            dom         : '<"top"lr>t<"bottom"ip>',
            order       : [[$('th.sort').index(), 'asc']],
            pageLength  : 10,
            processing  : true
        }
    );
```

**Comment by DataTables** [comment]
If you could post support questions in the [DataTables forums](//datatables.net/forums) please. Thanks!

**Comment by Tklaversma** [comment]
DataTables post can be found [here](https://datatables.net/forums/discussion/28714/how-to-use-data-order-on-dynamically-added-rows-with-three-or-more-columns).

**Comment by Tklaversma** [comment]
To answer the question:

The 1 (in the example below) is the key where the data-order attribute listens to.
```
        columnDefs: [
            {
                targets: [1],
                data: {
                    _: "1.display",
                    sort: "1.@data-order",
                    type: "1.@data-order"
                }
            }
```
So when you change your target to ``ThisIsMyNewTarget`` for example, then you should also change your data to the following:
```
        columnDefs: [
            {
                targets: ThisIsMyNewTarget,
                data: {
                    _: "ThisIsMyNewTarget.display",
                    sort: "ThisIsMyNewTarget.@data-order",
                    type: "ThisIsMyNewTarget.@data-order"
                }
            }
```

**Comment by iuyiuy** [comment]
This worked for me:
```
table.rows().invalidate().draw();
```

**Comment by Tomino2112** [comment]
@iuyiuy This should be somewhere in huge bold red letters... After hours of searching - leaving it- coming back to it- routine, finally this worked for me

**Comment by iuyiuy** [comment]
@Tomino2112 I completely agree. Do we need to open a new bug report or can we reopen this one?

**Comment by singhhrpreet** [comment]
@iuyiuy Dude! Thats works! But why didn't the author hinted this. But worked fine in my case..

**Comment by nasospsa** [comment]
Is there a way to do that on multiple keys at once? without defining a new target for each

**Comment by DataTables** [comment]
No - sorry. You have to do it one at a time. The only other option would be to have a function do the bulk of the work for you for each target.

**Comment by nasospsa** [comment]
Ok I thought so but the data function is used for all kinds of operation
and I don't know what to return for each occasion. Is there a documentation
for that or at least a solid example? The "price" one is not very helpful
