### ISSUE TITLE
XSS Venerability (includes jsFiddle demo)

### ISSUE THREAD

**Issue by chrisjacob** [DataTables/DataTables#497]
In Rails 4, if I run "to_json" on my data it converts this:
```
"</script><script>alert('PWNED!!!')</script>"
```
into this
```
"\u003c/script\u003e\u003cscript\u003ealert('PWNED!!!')\u003c/script\u003e"
```
which (to my understanding) makes it safe to put the RAW json data into my view (i'm using Mustache templates)
```
<script>
{{{json_here}}}
</script>
```
... I don't get an alert when loading the page (see jsFiddle: https://jsfiddle.net/fL4Leded/)

But when that "safe" data is loaded into DataTables the script gets executed as seen in this jsFiddle: 
http://jsfiddle.net/obycm88g/1/

Is there a way to avoid this XSS venerability in DataTables? ... or am I doing something stupid?

**Comment by DataTables** [comment]
I'm afraid I don't see how this is an XSS vulnerability in DataTables. You are telling it to explicitly display a script tag in the HTML. You would have exactly this issue in any HTML page if you inserted an unescaped `<script>` tag. I would suggest escaping the HTML entities in the data source or possibly removing HTML tags completely (the exact method of combating this is up to yourself and the requirements for your app / site).

If you need DataTables to do the escaping for you you could use the [`columns.render` option](//datatables.net/reference/option/columns.render) and escape the HTML entities in the string there.

**Comment by chrisjacob** [comment]
Hi @DataTables 

Sorry my ticket description may have made it unclear (or I'm confused - it was 3am here). 

The ```<script>``` tag in my ticket description was just there to explain that I was outputting ```html_safe``` JSON onto my page. And at that point the script would not be executed (because HTML tags like ```<``` were correctly escaped via Rail's to_json - as seen in my 2nd code block).

p.s. It didn't help that the first link in the ticket was incorrect (sorry!)... The jsFiddle was mean't to look like this: https://jsfiddle.net/fL4Leded/1/

Assuming that the bad data made it into my database, and now has been put onto the page (escaped) inside script tags (or loaded via ajax), it's when that data is processed by datatables (i.e. loaded via ```data``` and injected into the rendered table) that the escaped evil code gets executed...

Compare these two jsFiddles:
http://jsfiddle.net/obycm88g/1/
http://jsfiddle.net/obycm88g/2/

... or is this simply not adequately escaped data? (and if not, how should it look?)

```
"\u003c/script\u003e\u003cscript\u003ealert('PWNED!!!')\u003c/script\u003e"
```

**Comment by morrow95** [comment]
What you need to remember is data tables only shows what YOU output to it.  If you are outputting script into your columns and are concerned about its integrity then you need to do that check on your own.  Also, it is not clear if you want this script to actually run or you just want to display it visually.  I am guessing the latter... in which case if you were passing correctly escaped data to datatables it would have no chance to actually execute when it is time to display it in the table.

This is a little different, but the principle is the same.  I use this to escape all my data in the ssp class (I am using server side) just in case there is some bad data being stored in the db.  I would think this would also work for your case as it would no longer be outputting <script>...</script> 

```
                if ( isset( $column['formatter'] ) )
                {
                    //$row[ $column['dt'] ] = $column['formatter']( $data[$i][ $column['field'] ], $data[$i] );
                    
                    //escape the output before formatter hits it
                    $row[ $column['dt'] ] = $column['formatter']( htmlspecialchars($data[$i][ $column['field'] ], ENT_QUOTES, 'UTF-8'), $data[$i] );
                }
                else
                {
                    //$row[ $column['dt'] ] = $data[$i][ $columns[$j]['field'] ];
                    
                    //escape the output
                    $row[ $column['dt'] ] = htmlspecialchars($data[$i][ $columns[$j]['field'] ], ENT_QUOTES, 'UTF-8');
                }

```

**Comment by chrisjacob** [comment]
Hi @DataTables,

My apologies. It seems you're right - this is not a DataTables issue. 

Here is a demo using plain ```jQuery.html()``` - https://jsfiddle.net/fL4Leded/6/

The solution was for me to run ```html_escape_once(data)``` across all my data fields before converting the entire hash ```to_json```. The docs explain the conversions http://api.rubyonrails.org/classes/ERB/Util.html

The final result looks like this (which is safe to use in DataTables)
```
\u0026lt;/script\u0026gt;\u0026lt;script\u0026gt;alert(\u0026#39;PWNED!!!\u0026#39;)\u0026lt;/script\u0026gt;
```

**Comment by chrisjacob** [comment]
Thanks you @morrow95 - you are right, I wasn't html escaping my data (I thought the ```json_escape``` used by ```to_json``` was enough to make me safe - the unicode escaped form gave me false hope - plus the docs here confused me http://api.rubyonrails.org/classes/ERB/Util.html ...this example is a bit miss-leading:

```
<script>
  var currentUser = <%= raw json_escape(current_user.to_json) %>;
</script>
```

because if I latter do the following then any evils scripts on ```currentUser.first_name``` would be run:

```
$('#target').html(currentUser.first_name) 
```

.... unless each piece of data inside the ```current_user``` hash had ```html_escape(s)``` or ```html_escape_once(s)``` run over it BEFOREHAND e.g. 

``` ruby
@current_user['first_name'] = html_escape_once(row.first_name)
```

**Comment by morrow95** [comment]
Glad you got it sorted out.  Depending on your use case you could also just replace the data as well.  For instance, if you never wanted to display data with `<script>` you could run a regex on it and replace it with 'script found - content hidden' or something to those likes.

**Comment by morrow95** [comment]
Yes, if you are unsure of the data stored then you definitely need to put checks in place - especially for user generated data stored in the db.

I use pdo and bind all my values when inserting into the db (prevents sql injection) then do more checks when I pull it out if it is to be used, displayed, etc such as the escaping.  The latter would prevent script execution for example if I were to display it.

**Comment by rally25rs** [comment]
Old topic, but for those that get here from Google and are looking for a possible solution, I found here: [https://www.datatables.net/forums/discussion/32150/xss-prevention-from-unsanitized-server-input](https://www.datatables.net/forums/discussion/32150/xss-prevention-from-unsanitized-server-input)
that the render function can be set on each column to force it to render as text, which takes care of the escaping of HTML characters.

Instead of setting this on every single column, you can set it to be the default column renderer by running this code at the beginning of your app before any datatables are created:

```
  $.extend( true, $.fn.dataTable.defaults, {
    column: {
      render: $.fn.dataTable.render.text()
    }
  });
```

This causes all future datatables to use that text renderer. If you have a column that you don't want to render as text, then just add a `render: function(){...}` to that specific column and it will overwrite this default.

**Comment by ItCampRaulLedesma** [comment]
thks @rally25rs!!! It worked like a charm!!!

**Comment by gustinmi** [comment]
Inside columns definition, you can use this:
` "render": $.fn.dataTable.render.text()`
You can call it also like a static function, anywhere you like:
`$.fn.dataTable.render.text().display("<script>alert(1)</script>")`
