### ISSUE TITLE
What could cause the datatables to forget the pagination on page refresh (with stateSave: true) (yadcf related)

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#499]
Hi,

For some reason when applying my [yadcf](https://github.com/vedmack/yadcf) plugin to a table which got `stateSave: true` the pagination state does not getting saved,

test case: 
1) go to [showcase page](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_Ajax_Multiple_1.10.html) and inspect the first table

2) sort by any column

3) paginate to the second page

4) hit F5 and observe

expected results: table sorted by that column and showing page 2

actual results: table is sorted by that column on first page

Any ideas on what did I do wrong in my [yadcf](https://github.com/vedmack/yadcf) plugin?

https://github.com/vedmack/yadcf/issues/155

**Comment by DataTables** [comment]
Are you calling `draw()` or the old `fnDraw()` method anywhere during your initialisation? That might cause the issue.

The show case is currently using a minified version of DataTables. Could you have it load the debug one so I can add some break points into the code?

**Comment by vedmack** [comment]
Maybe, I will check that, thanks (updated with non minified)

**Comment by vedmack** [comment]
I do have a call for `oTable.fnDraw();` , can I call it without making the datatables to loose the pagination? Because the other saved stuff like sorting are being saved regardless of the `oTable.fnDraw();` call...

**Comment by DataTables** [comment]
Yes, call `fnDraw( false );` [docs](http://legacy.datatables.net/api#fnDraw).

**Comment by vedmack** [comment]
I tried with `false` (followed the docs) but it didn't work, now after seeing the source code I noticed the 

```
		this.fnDraw = function( complete )
		{
			// Note that this isn't an exact match to the old call to _fnDraw - it takes
			// into account the new data, but can old position.
			this.api( true ).draw( ! complete );
		};
```

You are doing the `!` on the argument, so I tried `.fnDraw(true);` and it works (pagination gets remembered) my `true` becomes `false` , Is it ok? or its a bug in 10.x version?

**Comment by DataTables** [comment]
Yup - a bug for certain. Thanks for spotting that. i've just committed the fix and the nightly is now up to date.

Allan

**Comment by DataTables** [comment]
Fix was here: https://github.com/DataTables/DataTablesSrc/commit/dd25f35b6a51a6a7a

**Comment by vedmack** [comment]
@DataTables , Thanks! works now http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html
