### ISSUE TITLE
Search filter produces incorrectly nested HTML

### ISSUE THREAD

**Issue by WartookMan** [DataTables/DataTables#506]
The "dataTables_Filter" results in an incorrectly nested HTML wrapper:
```javascript
	<div id="DataTables_Table_0_filter" class="dataTables_filter">
		<label>Search:
			<input type="search" class="form-control" placeholder="" aria-controls="DataTables_Table_0">
		</label>
	</div>
```
The code to produce this is listed on lines:
```javascript
	var str = language.sSearch;
	str = str.match(/_INPUT_/) ?
		str.replace('_INPUT_', input) :
		str+input;

	var filter = $('<div/>', {
			'id': ! features.f ? tableId+'_filter' : null,
			'class': classes.sFilter
		} )
		.append( $('<label/>').append( str ) );
```
This should be:
```javascript
	var str = language.sSearch;
	str = str.match(/_INPUT_/) ?
		str.replace('_INPUT_', input) :
		str;

	var filter = $('<div/>', {
			'id': ! features.f ? tableId+'_filter' : null,
			'class': classes.sFilter
		} )
		.append( $('<label/>').append( str ) ).append( input );
```
Which thus produces:
```javascript
	<div id="DataTables_Table_0_filter" class="dataTables_filter">
		<label>Search:</label>
		<input type="search" class="form-control" placeholder="" aria-controls="DataTables_Table_0">
	</div>
```

**Comment by DataTables** [comment]
i'm not seeing how the HTML that it produces at the moment is incorrect? You've unnested the input from the label, but it is perfectly valid HTML as it is. The HTML 5 specification says:

> If the for attribute is not specified, but the label element has a labelable element descendant, then the first such descendant in tree order is the label element's labeled control.

HTML 4 called it an explicit link between the input and label.

Could you clarify the problem please?

**Comment by WartookMan** [comment]
Apologies... just checked the W3C specifications, and both are valid. I will change my CSS to account for both options. Thank you.

**Comment by DataTables** [comment]
No worries - thanks for checking in on this. Accessibility is a key part of DataTables.
