### ISSUE TITLE
data-order is completely ignored if a <th> contains another <table>

### ISSUE THREAD

**Issue by mus65** [DataTables/DataTables#508]
The `data-order` attribute is ignored for all columns if one of the table headers contains another table.

See testcase here:
https://jsfiddle.net/nagq0qcy/

1. Notice how the first column is not ordered according to the data-order attribute.
2. Remove the table from the second `<th>`
3. First column is now ordered correctly.

This does not seem to happen if the table exists within a `<td>`.

btw, my use case for this is that I want to show user generated content in a Bootstrap Popover on the headers and it makes sense for the popover content to be within the header. The content is HTML code generated by CKEditor and may therefore also contain other tables.

**Comment by DataTables** [comment]
Nice one - thanks for the test case! [Fix committed here](https://github.com/DataTables/DataTablesSrc/commit/6c60a9429fa)

Update to your test case using the DataTables nightly with this fix: https://jsfiddle.net/nagq0qcy/1/
