### ISSUE TITLE
fnFilter vs aoPreSearchCols = "" + fnDraw

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#509]
I was wondering how safe is to use the 

```
table_arg.fnSettings().aoPreSearchCols[column_number].sSearch = '';
table_arg.fnDraw();
```
instead of `table_arg.fnFilter("", column_number_filter);`

To reset column filter

**Comment by DataTables** [comment]
> I was wondering how safe is to use [.... private objects]

Not. :-)

If you have access to the public API, why would you not use it (even if it is the legacy API)?

The properties in the settings object can, will and do change between versions. If you can avoid using them, you absolutely should.

**Comment by vedmack** [comment]
The reason that I use `table_arg.fnSettings().aoPreSearchCols[column_number].sSearch = '';` with `table_arg.fnDraw();` is  because I need to reset several filters at once (using the legacy API) , is there any other way to reset / set a value in several filters at once with the legacy API?

**Comment by DataTables** [comment]
Not with the legacy API - it will always call the draw function when `fnFilter` is called. I guess what you could do is check to see if the new API is available - if so then use it, if not, use the private options (since they won't be changing now - it is unsupported).

Out of interest, when do you plan to drop support for 1.9-?

**Comment by vedmack** [comment]
By "private options" you mean the way I do it now?

Regarding the 1.9 support, I haven't thought about it actually, but already started to develop features that require 1.10+ and I guess I'll keep going in this direction...

**Comment by DataTables** [comment]
"private options" as in anything inside the settings object. If you do need to use the private options (which is sometimes unavoidable unfortunately, although should be avoided as much as possible) then I would suggest putting whatever access made to them into a plug-in API method so there is only one point of failure when the internal API changes.

**Comment by vedmack** [comment]
Thanks
