### ISSUE TITLE
IE9 rendering issue when hovering over row with hScroll enabled

### ISSUE THREAD

**Issue by csturm83** [DataTables/DataTables#510]
This issue is isolated to IE9 and related to the IE9 bug outlined <a href="http://blog.brianrichards.net/post/6721471926/ie9-hover-bug-workaround">in this blog post.</a> It adds additional white space to the bottom of the inner table on each row hover.

Here is an <a href="http://jsfiddle.net/pjkix/86Lfv/">existing jsfiddle</a>  that demonstrates the issue (albeit not using DataTables). Again, the issue only exists in IE9.

I was able to workaround this issue by adding the following CSS to my own stylesheet:

.dataTables_scrollBody
{
      min-height:0%;
}

**Comment by DataTables** [comment]
I haven't been able to reproduce that issue in IE9 with my scrolling examples:

* http://datatables.net/examples/basic_init/scroll_y.html
* http://datatables.net/examples/basic_init/scroll_x.html

Does IE9 break for you in those examples?

**Comment by csturm83** [comment]
I just realized that the blog post and jsfiddle mention what triggers the bug, but I left it out in my initial description. The bug is triggered by a hover style applied to an element inside the table. 

This selector should do the trick:

table.table tbody tr:hover td {
background-color:#ecfaff;
}

**Comment by DataTables** [comment]
My examples use a `td` class on hover ([css](https://github.com/DataTables/DataTablesSrc/blob/master/css/jquery.dataTables.scss#L252)).

Can you link me to an example page that uses DataTables that shows this problem please?

**Comment by csturm83** [comment]
I had to do some tweaking to get this issue to reproduce <a href="https://jsfiddle.net/csturm83/8fe5hsb6/">in a jsfiddle.</a>

I had to manually add the class that DataTables was generating for my table:

class="display table table-bordered table-striped dataTable no-footer"

**Comment by DataTables** [comment]
I hate to say it, but that example appears to work okay for me in IE9. I am using IE11 and changing the browser mode using the dev tools. Does it have to be pure IE9 perhaps? What are you using?

**Comment by csturm83** [comment]
I am using IE9 (v. 9.0.8112.16421) on Win7.  I work for an organization that uses a base Win7 image which includes IE9 and has Group Policy applied. I was able to recreate this issue on multiple machines in my office. However, I had a coworker (developer) who was not able to reproduce this issue on his machine (IE9), but was able to login to other machines (IE9) and reproduce it on those machines. 

Seems like it might be a (machine level) IE9 confguration or GPO setting???

Do you feel the min-height workaround I am using is safe to use with DataTables for the time being?

**Comment by DataTables** [comment]
Yes, I think the min-height hack is perfectly safe. I can't see any issues with it, although I am reluctant to include potentially redundant CSS (and a hack) in the core DataTables stylesheet.

It would be interesting to know what is causing this but if different IE9 machines are showing different behaviour... These are the times when being a web-dev makes one slightly crazy(er) :-).

I'm going to close this just now, but if I have any more reports of this problem I'll look into adding your patch into the core stylesheet.

**Comment by csturm83** [comment]
Agreed. Why add the unnecessary.

Thanks for your time with this, and thanks for DataTables!
