### ISSUE TITLE
Browser on mac is recognized as ie67

### ISSUE THREAD

**Issue by turja12** [DataTables/DataTables#512]
We are having some problems with height of table on mac in safari and chrome. Height of table is set to 0 sometimes.  This  problem is happening when the scrollbars are hidden.  When we switch system to always show scrollbars, then  problem will disappear. 
We were investigating it and for some reason chrome and safari on mac is identified as 'ie67'
Problematic part of code is this: 
if ( ie67 ) {
                    divBodyStyle.height = _fnStringToCss( tableEl.offsetHeight+barWidth );
                }
If we change expression to one which is used on another places for recognizing ie67 then the table is working correctly. Code which works for us is below. But we are not sure if will not broke support of ie6/7. 
if ( ie67 && (table.find('tbody').height() > divBodyEl.offsetHeight ||
                    divBody.css('overflow-y') == "scroll") {
                    divBodyStyle.height = _fnStringToCss( tableEl.offsetHeight+barWidth );
}
Can this if condition can be used also on this place?
Thanks

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

Thanks,  
Allan

**Comment by turja12** [comment]
Thanks for fast reply during setuping test case we find out that we were setting 'scrollY', false; but it doesnt works correct because in code of DT is  if ( ! scrollY )  so after evaluation it was true and it  jumps to if(ie67 section .... When we set it with string then it works correctly. 
But it is a bit strange solution. But bug can be closed I think.
