### ISSUE TITLE
Cant use datatables with webpack BowerWebpackPlugin

### ISSUE THREAD

**Issue by pkorzh** [DataTables/DataTables#513]
bower.json has a wildcard character in 'main' section for images:  "media/images/*.png".
this leads to the following error:

ERROR in DataTables (bower component)
Module not found: Error: Cannot resolve 'file' or 'directory' ./media/images/*.png in bower_components\DataTables
 @ DataTables (bower component) 3:0-31

**Comment by pkorzh** [comment]
can we have all images listed instead of using '*'?

**Comment by DataTables** [comment]
Forgot to close this at the time - sorry.
