### ISSUE TITLE
How to search for exact word when it is substring of another word?

### ISSUE THREAD

**Issue by gnranjith** [DataTables/DataTables#515]
I have a field named marital status(It has two values either married or unmarried) in my database and while married is searched i want to display only  the rows which match 'married'. But even the rows with the value unmarried are getting fetched. Please help me with how to go forward with this problem.

**Comment by DataTables** [comment]
You would use a regular expression to perform the exact match - like in this example: http://datatables.net/examples/api/multi_filter_select.html

In future, please can you post support requests in the [DataTables forums](//datatables.net/forums). The github issue tracker is used for bugs only.

**Comment by gnranjith** [comment]
I am using server side processing so tried [YADCF](https://github.com/vedmack/yadcf) with filter_match_mode as [exact](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L146) but then it doesn't select or matches any row because the data tables plugin queries the database with WHERE condition as LIKE '%^Married$%' and hence i thought it must be a new feature to be added and hence posted it here. Please ignore it if i am wrong. Thanks !

**Comment by DataTables** [comment]
If you are using server-side processing then the script, whatever you are using, needs to do an exact match rather than using a `LIKE` as my default scripts use. If you are using using one of my demo scripts then it would need to be udpated.
