### ISSUE TITLE
reload datatables every x seconds

### ISSUE THREAD

**Issue by ezekel** [DataTables/DataTables#516]
Is it okay to use setTimeout to reload my datatables in every 5 seconds ?
I tried to put in drawcallback

```javascript

"drawCallback": function( settings ) {
          setTimeout(function(){
              mytable.ajax.reload();
 
          },5000);
 
      }

```

**Comment by DataTables** [comment]
I don't see why not. I would use setInterval myself if you want to do it periodically.

In future, please post support requests in the [DataTables forums](//datatables.net/forums). GitHub issues are got bugs only not support.

**Comment by ezekel** [comment]
I apologize.  Thank you I will use setInterval :)
