### ISSUE TITLE
$.fn.DataTable.isDataTable returning incorrect results with multiple tables

### ISSUE THREAD

**Issue by jmakenney** [DataTables/DataTables#518]
Having multiple `<table>` elements on a page and initializing any table other than the first table as a DataTable will result in `$.fn.DataTable.isDataTable` returning `true` when the first table is checked.

JSFiddle here: http://jsfiddle.net/vyms2ddL/4/

This check:
https://github.com/DataTables/DataTables/blob/1.10.5/media/js/jquery.dataTables.js#L8841
effectively ends up checking if the passed in table is equal to `$('table')[0]` as `o.nScrollHead` and `o.nScrollFoot` are both `null`

**Comment by DataTables** [comment]
Doh - that is a big slap on the head moment. Thanks for catching this!

I've just [committed a fix](https://github.com/DataTables/DataTablesSrc/commit/eb54cc637b39) and this is your [Fiddle using the nightly version](http://jsfiddle.net/vyms2ddL/5/)
