### ISSUE TITLE
scroller plugins datatables problem in bootstrap tab

### ISSUE THREAD

**Issue by ezekel** [DataTables/DataTables#519]
HI, I apologize I don't know if this is a bug,I could not use the scroller plugins in bootstrap tab,the data is not loaded.in the second tab. as what I asked here

http://datatables.net/forums/discussion/26679/bootstrap-tab-with-datatables-scroller-plugins-cannot-load-data-properly#latest

**Comment by DataTables** [comment]
Let's continue this discussion in the forum only rather than in two places.

**Comment by ezekel** [comment]
Okay.
