### ISSUE TITLE
Destroy method does not properly release the table unless replaced

### ISSUE THREAD

**Issue by dylanrtt** [DataTables/DataTables#521]
My company has a single page app that uses dozens of grids with the Datatables plugin. In many cases, we create grids and need to fully destroy them. Unfortunately, the destroy() method does not seem to actually destroy the table control until it is replaced with a new instance.

We have reason to believe that the presence of these lurking grids is causing DOM-related event bindings (added by our MV* framework) to persist and ultimately prevent a great deal of our application from being GC'd.

The code below is a simple example of instantiating the datatable control and then destroying it. My memory profiling process with Chrome dev tools consists of first creating and then destroying to get initialization stuff out of the way, then I do snapshot-create-snapshot-destroy until I have 5 or more snapshots.

Objects allocated between snapshots 1 & 2 persist to snapshot 3 which should actually be completely clean. Those objects do not get removed until snapshot 4 which is when the control is instantiated a second time. The resulting 2nd datatable does not get removed in snapshot 5 when destroy() has been called on it, but it does get cleaned up when the control is instantiated the 3rd time in snapshot 6.

```html
<!doctype html>
<html>
<body>
    <button id="createGrid">Create</button>
    <button id="destroyGrid">Destroy</button>
    <table id="dt1">
        <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Age</th>
            <th>Start date</th>
            <th>Salary</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011/04/25</td>
            <td>$320,800</td>
        </tr>
        </tbody>
    </table>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        (function() {
            var dt;

            $('#createGrid').on('click', function() {
                dt = $('#dt1').DataTable();
            });

            $('#destroyGrid').on('click', function() {
                dt.destroy();
            });
        })();
</script>
</body>
</html>
```

Is there currently a way to fully clean up a datatable? This functionality is essential for any single page app that uses this plugin so I am surprised I did not find it anywhere in the docs.

It should be noted that we would not actually use datatables in this way specifically because we are always removing the table from the DOM as well. I fiddled around with multiple test cases involving DOM removal and they all produced the same effect that is happening with the above code, which should NOT leak.

**Comment by jhfrench** [comment]
Ported code into jsFiddle: http://jsfiddle.net/afnu23qq/

**Comment by DataTables** [comment]
I've had [a discussion on the Chrome dev tools list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-chrome-developer-tools/iwBp7Z9bJvI/WWWo2LIkneoJ) about this topic before, which you might find interesting.

The conclusion was that the `destroy()` method is removing all events that DataTables adds, and the clean up is complete, even although the retaining tree in Chrome shows old elements. Personally I don't fully understand that, but I have nothing further to go on. Also there are no events I could find in the tree that are still attached. If you can prove that wrong, I would be very grateful if you could show me where in the dev tools.

Allan

p.s. In future, could you post support requests in the [DataTables forums](//datatables.net/forums) please. It is too difficult to track issues both here and there. Thanks.
