### ISSUE TITLE
Datatables values disappeared after page loaded

### ISSUE THREAD

**Issue by dzarezenko** [DataTables/DataTables#523]
I generate table with PHP and this table is Datatables. But when page is loaded some values are disappeared from table cells. It's happens on JS Datatables level, because I see real values and they are exists.

What can it be and maybe someone have a solution.

Thanks!

**Comment by DataTables** [comment]
Can you link to a test page showing the issue.

Also, in future, please submit support requests in the [DataTables forums](//datatables.net/support).

Thanks,
Allan

**Comment by dzarezenko** [comment]
Thanks, problem is now resolved, it was my fault.
Thanks one more time!
