### ISSUE TITLE
 Table Class "Compact" Has Poor Column Label Layout

### ISSUE THREAD

**Issue by phillc73** [DataTables/DataTables#527]
NB: Originally reported [here](https://github.com/rstudio/DT/issues/36/), but closed and suggested to report upstream.

If applying the Table CSS Class "compact" the column order arrows appear underneath the column labels.

Below are two images to demonstrate this. The first image is "normal" table layout. The second image uses class = 'compact'

![tablelayoutnormal](https://cloud.githubusercontent.com/assets/815126/6941778/98da7678-d87a-11e4-85cf-3cd0174c7554.png)
![tablelayoutcompact](https://cloud.githubusercontent.com/assets/815126/6941784/9d49b282-d87a-11e4-8ebe-b0b01f6ff615.png)

**Comment by DataTables** [comment]
Thanks for noting this! Fixed in the above reference and will be included in 1.10.6/
