### ISSUE TITLE
FixedHeader breaks when any ancestor element of the grid is positioned absolute or relative or fixed.

### ISSUE THREAD

**Issue by mendeza** [DataTables/DataTables#528]
One of the parent elements of this grid has position: absolute. 

![datatablefixedheader](https://cloud.githubusercontent.com/assets/1161280/6967791/b9fd9500-d92f-11e4-9852-8cffab8e4600.png)

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by DataTables** [comment]
Also this should be opened in the [FixedHeader](https://github.com/DataTables/FixedHeader) repo rather than here if you would be so kind.

**Comment by mendeza** [comment]
My apologies.
