### ISSUE TITLE
Stripe classes with scroller should follow virtual index

### ISSUE THREAD

**Issue by larvanitis** [DataTables/DataTables#529]
While using scroller there is a possibility that the stripe classes can change for the displayed rows. For example 
```
                          --- sStripe ---
iRowCount  iDisplayStart  IS   SHOULD BE
2          0              odd  odd
2          1              odd  even
```

The problem can be solved by including the first rendered row number to the calculation of the class.

Change https://github.com/DataTables/DataTables/blob/1.10.5/media/js/jquery.dataTables.js#L2010 from
`var sStripe = asStripeClasses[ iRowCount % iStripes ];`
to
`var sStripe = asStripeClasses[ (iDisplayStart + iRowCount) % iStripes ];`

Now, I guess this could make paged rendering (eg when page size is 5) to weirdly start from `even` instead of `odd`, so maybe you could somehow detect if scroller is in use before using this code.

**Comment by DataTables** [comment]
Hi,

Could you open this on the [Scroller repo](/DataTables/Scroller) please?

Thanks!
Allan
