### ISSUE TITLE
problem trying destroy the table

### ISSUE THREAD

**Issue by spiritdead** [DataTables/DataTables#530]
hi all

this is the original table

$("#example1").dataTable({
    "bDestroy" : true,
    aaSorting: [],
    "aLengthMenu": [[3, 10, 20, 75, -1], [3, 10, 20, 75, "Todos"]],
    "iDisplayLength": 20,
    "bFilter": false,
    "columns":[
        {"title": "Descripcion"},
        {"title": "Prueba"},
        {"title": "Valor"}
    ],
    "language":{
        "url": "//cdn.datatables.net/plug-ins/f2c75b7247b/i18n/Spanish.json"
    },
    "dom": \'T<"clear">lfrtip\',
    tableTools: {
        "sSwfPath": "../themes/adminlte/plugins/TableTools-2.2.4/swf/copy_csv_xls_pdf.swf",
        "aButtons": [
            {"sExtends": "copy", "sButtonText": "Copiar al portapapeles"},
            {"sExtends": "csv", "sButtonText": "Guardar como CSV"},
            {"sExtends": "xls", "sButtonText": "Guardar como Excel"}, //,"sFileName": "*.xls"
            {"sExtends": "pdf", "sButtonText": "Guardar como PDF"},
            {"sExtends": "print", "sButtonText": "Imprimir"}
        ],
    }
});
i try destroy the table for reinitialize again but i cant i receive a error im trying this

var table = $("#example1").dataTable();
table.api().clear();
table.api().destroy();

but when i try destroy i get this error

jquery.dataTables.js:8982 Uncaught TypeError: Cannot read property 'parentNode' of null

any have idea how can fix this

**Comment by DataTables** [comment]
Please link to a test case showing the issue. Also in future, please post support requests in the [DataTables forums](http://datatables.net/forums).

I've just tired to reproduce the issue with the API calls you are using and it works as expected: http://live.datatables.net/simogoji/1/edit .

**Comment by DataTables** [comment]
No test case received - closing issue.
