### ISSUE TITLE
Custom Filtering Data Parameter

### ISSUE THREAD

**Issue by jcuenod** [DataTables/DataTables#532]
I followed the example given (https://datatables.net/examples/plug-ins/range_filtering.html) to set up a custom filter. My one column has spans with classes that I wanted to search for so I added the class names into the `data-filter` tag on the `td` and pushed my custom filter into `$.fn.dataTable.ext.search`. 

This works perfectly in my local rails environment (using jquery-datatables-rails) but when I push to heroku the `data` parameter no longer has my `data-filter` content, it just has html stripped text from the cell.

**Comment by DataTables** [comment]
Could you post support requests on the [DataTables forums](//datatables.net/forums) please. Also, please be sure to include a link to the page that you are having problems with so it can be debugged.
