### ISSUE TITLE
File name with a space "Sorting icons.psd"

### ISSUE THREAD

**Issue by waviaei** [DataTables/DataTables#533]
Could you possibly avoid using a space for this file name?
https://github.com/DataTables/DataTables/tree/master/media/images

I originally posted this issue at below WordPress plugin, but pointed out that this is DataTables issue.
https://github.com/Yoast/google-analytics-for-wordpress/issues/208

**Comment by DataTables** [comment]
Hi,

What is the problem with the space in the file name? It is not an asset that it intended for consumption by a web browser.

**Comment by DataTables** [comment]
Closing issue - no feedback.
