### ISSUE TITLE
dataTable seems does not work when table has hidden Cols...

### ISSUE THREAD

**Issue by justein** [DataTables/DataTables#535]
Recently I have tried this graceful plug-in in my project ,but unfortunately found that it seems not work when the JQuery table has an hidden Col like ‘id’, which shouldn't show but should be exist in table so that I can get it when click an record in the table. THX!

**Comment by DataTables** [comment]
As per the [Contributing document](https://github.com/DataTables/DataTables/blob/master/Contributing.md), support requests should be directed to the [DataTables forums](//datatables.net/forums).

Please also include a link to a test page that shows the problem you are having so it can be debugged.

**Comment by DataTables** [comment]
No test case received - closing issue.
