### ISSUE TITLE
API method destroy() doesn not work as expected

### ISSUE THREAD

**Issue by SunboX** [DataTables/DataTables#537]
I'm trying to destroy and re-init a DataTable like this:

```js
var table;
var tableSettings = {
    language = {}
};
    
tableSettings.language.info = 'Showing 1 to 2 of 3 entries';
    
table = $('#vacation-list').DataTable(tableSettings);
    
table.destroy();
    
tableSettings.language.info = 'Showing 4 to 5 of 6 entries';
       
table = $('#vacation-list').DataTable(tableSettings);
```

This will render / show `Showing 1 to 2 of 3 entries` but it should show `Showing 4 to 5 of 6 entries`

**Comment by DataTables** [comment]
As per the [Contributing.md](Contributing.md) document, please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a test case showing the issue.

**Comment by DataTables** [comment]
Going to close this issue as no test case provided.
