### ISSUE TITLE
Convert aoData to url params

### ISSUE THREAD

**Issue by gogainda** [DataTables/DataTables#538]
I have a button which I am using to pass a datatable's params to the server side. How can I get aoData in that ways ....clients.json?sEcho=3&iColumns=7&...
So far I've found how to get aoData $('#my-clients-table').DataTable.settings[0].aoData . What should I do next?

**Comment by DataTables** [comment]
Per the [contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/support).

Also, please don't use options from the `settings` object unless you know the DataTables code extremely well. It is a private interface and should not be used externally.

If you want to modify the GET parameters that DataTables is sending upon a server-side processing request (which I am guessing you do) then use `ajax.data`: http://datatables.net/reference/option/ajax.data .
