### ISSUE TITLE
I use struts2 How can I receive the params related order just like order[0][column] 2,order[0][dir] asc

### ISSUE THREAD

**Issue by datouzhong** [DataTables/DataTables#540]

**Comment by DataTables** [comment]
Per the [Contributing.md](/DataTables/DataTables/blob/master/Contributing.md) document, please ask support requests in the [DataTables forums](//datatables.net/forums).

In this specific case you might be best asking in a structs2 forum how you can access HTTP GET / POST parameters, as I don't have any experience of using structs2.
