### ISSUE TITLE
Expose jqXHR Object

### ISSUE THREAD

**Issue by mjhasbach** [DataTables/DataTables#542]
The [jqXHR](https://api.jquery.com/Types#jqXHR) object of the most recent AJAX request should be exposed in certain events ([xhr.dt](https://datatables.net/reference/event/xhr), [error.dt](https://datatables.net/reference/event/error), etc.) so that developers can get access to the HTTP status code. Either that, or a new method which exposes the most recent jqXHR should be added to the [ajax](http://datatables.net/reference/api/ajax) namespace. The implication in the xhr.dt documentation is that the HTTP status code should be included in the response body, but that is not standard practice, and is redundant because it is already included [in the first line of the response](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html).

See [this](https://datatables.net/forums/discussion/26742/reading-response-header) forum discussion as well as [this](http://datatables.net/forums/discussion/14564/access-http-response-status-code-in-fnserverdata-error) one.

**Comment by DataTables** [comment]
Sounds like a good idea to have it passed through in the event arguments - thanks for the suggestion.

The `error.dt` event is used for more than just Ajax errors, so I'm not sure it would be appropriate to pass it through as an argument there. I need to have a little think about that and the best way to handle it. I don't really want to expose it in the API, but it might be required.

**Comment by mjhasbach** [comment]
I feel either ```error.dt``` or the API should expose the jqXHR. I am creating an application that returns a 401 (not authenticated) status code when a user without a valid login session requests table data. Imagine if the jqXHR was only exposed in ```xhr.dt```: I would have to handle the authentication error in ```xhr.dt``` and somehow know not to process that same error in ```error.dt```. That would most likely involve setting some object property in a higher scope during ```xhr.dt``` and check / remove it in ```error.dt```. That sounds messy to me.

**Comment by DataTables** [comment]
I've gone for the middle road - the `xhr.dt` event now includes the jqXHR object, and I've also now `xhr.dt` being triggered on error as well as success now (so `xhr.dt` is triggered regardless of the outcome). `error.dt` is still triggered, but doesn't have access to the jqXHR object directly.

[Commit](https://github.com/DataTables/DataTablesSrc/commit/202f83bc74ff49).

This change is now in the nightly version and will be included in the 1.10.7 release that I'm planning to do tomorrow.

**Comment by mjhasbach** [comment]
Regarding [202f83bc74ff49](https://github.com/DataTables/DataTablesSrc/commit/202f83bc74ff49) in the context of my previous comment:

1. ```xhr.dt``` is triggered after an AJAX request. I check the jqXHR for a specific / non-200 status code or error in the response body, then handle the error appropriately.
2. ```error.dt``` is triggered, and I need a way to dismiss the error because it has already been dealt with in ```xhr.dt```. Since ```error.dt``` does not have access to the jqXHR:

>That would most likely involve setting some object property in a higher scope during xhr.dt and check / remove it in error.dt. That sounds messy to me.

Some possible solutions:

- Return ```true``` or ```false``` in ```xhr.dt``` to silence the next ```error.dt```
- API method to silence the next ```error.dt```
- API method to get the most recent jqXHR
- jqXHR argument in ```error.dt```
- Create a new event called something like ```xhrError.dt```
  - Trigger ```xhrError.dt``` if the jqXHR status code matches a code in a configurable array of codes and / or does not match a code in another configurable array of codes
  - Trigger ```xhrError.dt``` if the jqXHR response body matches a string in a configurable array of strings and / or does not match a string in another configurable array of strings.
  - Do not trigger ```error.dt``` if ```xhrError.dt``` is triggered

**Comment by DataTables** [comment]
Thanks for your input on this - much appreciated!

I've added the ability to return `true` from `xhr.dt` to tell DataTables not to trigger the `error.dt` event - [commit](https://github.com/DataTables/DataTablesSrc/commit/98d6286f0f2).

It takes the library to within 25 bytes of my personal "size limit" of 80000 bytes, but I think it is the right thing to do (trying to keep the library from just growing and growing!).

Another option is to use the `$.fn.dataTable.ext.errMode` variable to control the error yourself. You can give it a function and just have it do no operation.

**Comment by mjhasbach** [comment]
Excellent, thanks @DataTables!
