### ISSUE TITLE
jQuery 2.1.4 isArrayLike error

### ISSUE THREAD

**Issue by newenegue** [DataTables/DataTables#546]
I received this error
`Uncaught TypeError: Cannot use 'in' operator to search for 'length' in `

When initializing the datatable with `search: true`
```
$.map(search.match( /"[^"]+"|[^ ]+/g ) || "", function(word) {
...
});
```

It seems that `"length" in obj` returns the error when the `obj == ""`, but it works fine when `obj == [""]`

So if you are using jQuery 2.1.4 or higher then it should be like so:
```
$.map(search.match( /"[^"]+"|[^ ]+/g ) || [""], function(word) {
...
});
```

Below is the `isArraylike()` from jQuery 2.1.4

```
function isArraylike( obj ) {

    // Support: iOS 8.2 (not reproducible in simulator)
    // `in` check used to prevent JIT error (gh-2145)
    // hasOwn isn't used here due to false negatives
    // regarding Nodelist length in IE
    var length = "length" in obj && obj.length,
        type = jQuery.type( obj );

    if ( type === "function" || jQuery.isWindow( obj ) ) {
        return false;
    }

    if ( obj.nodeType === 1 && length ) {
        return true;
    }

    return type === "array" || length === 0 ||
        typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```

**Comment by DataTables** [comment]
Hi. Thanks for reporting this, but I'm afraid I don't fully understand how you are using the search operations in DataTables. Could you please link to a test case showing the issue?

**Comment by crittico** [comment]
Hi, same here. 
I don't pass any 'search' options, my code looks like this:
```
this.table = this.$el.find("table").DataTable({
        "autowidth": false,
        "columns": [
            { "width": "50%" },
            { "width": "50%" },
        ],
        "order": [
          [1, "asc"]
]});
```

The point is that jquery map function (called in media/js/jquery.dataTables.js) takes an array as a first parameter and not a string, so the ```|| ''``` should probably be changed to ```|| ['']``` as pointed out by @newenegue.

**Comment by DataTables** [comment]
Got it! Thanks for the clarification.

I've just [committed the fix](https://github.com/DataTables/DataTablesSrc/commit/485b259e5c) and this repo and the nightly build are now up to date.

Thanks for letting me know about this!

**Comment by Ustes** [comment]
Attempting to use DataTables in a project and I am still receiving this error.  I have attached my plunker,
http://plnkr.co/edit/bJ0RQQpcnX8STsw626mX?p=preview.

When you change the jquery version to 1.8.3 in the cdn link in the html all works well, if you leave as 2.1.4 and view the developer tools you see the following:
     TypeError: Cannot use 'in' operator to search for 'length' in Category

**Comment by DataTables** [comment]
You plunkr shows that you are passing in strings as values for the `columns` array - attached screenshot. That is not valid - see [the documentation](http://datatables.net/reference/option/columns)

![screen shot 2015-09-25 at 16 24 42](https://cloud.githubusercontent.com/assets/278219/10104510/f4ee96f8-63a1-11e5-8818-51125f14d256.png)

For future support requests, please [post in the DataTables forums](//datatables.net/forums).

**Comment by Ustes** [comment]
thanks.  I had to change
     explicitColumns.push($(elem).text());
to
     explicitColumns.push({name : $(elem).text()});
