### ISSUE TITLE
'No data available in table' label is not displaying in internet Explorer

### ISSUE THREAD

**Issue by RatanPaul** [DataTables/DataTables#547]
If there is no record in datatable. In Chrome 42 'No data available in table' label is showing but in Internet explorer it is not visible.

Chrome - 42
![chrome](https://cloud.githubusercontent.com/assets/8724580/7406900/58edc23a-ef28-11e4-90d3-5cabae14abe8.png)

Internet Explorer - 11
![ie](https://cloud.githubusercontent.com/assets/8724580/7406887/2c7ed23e-ef28-11e4-87ef-ddcd654a9ec1.png)

**Comment by MrGeneric** [comment]
It's showing up in IE11 for me. Here's a basic jsfiddle http://jsfiddle.net/84jdeugx/

**Comment by DataTables** [comment]
Works for me as well. @Ratan92Paul Please link to a test case showing the issue.

**Comment by RatanPaul** [comment]
Actually I am using in visualforce page. But this issue exist in only one page.

thanks ..
