### ISSUE TITLE
KeyTable and FixedColumn

### ISSUE THREAD

**Issue by csturm83** [DataTables/DataTables#551]
While using the KeyTable and FixedColumn extensions together on a DataTable I am able to tab/arrow through table cells just fine. However, <i>clicking</i> on multiple cells in the fixed column (consecutively) provides unexpected results. All clicked cells appear to be selected. <a href="http://jsfiddle.net/csturm83/cr3yhee6/" target="_blank">jsfiddle</a>

**Comment by DataTables** [comment]
I've reposted this under the KeyTables repo [here](https://github.com/DataTables/KeyTable/issues/21).

I'm slightly surprised that the two appear to work at all at the moment to be honest. I think there is a fair amount of work needed to be able to integrate the two.
