### ISSUE TITLE
ColVis plugin regression after 1.10.7 update

### ISSUE THREAD

**Issue by irsick** [DataTables/DataTables#553]
Hi Alan,

I use jQuery 1.11.0, ColVis 1.1.2 and DataTables 1.10.6
After upgrading to 1.10.7 I got this error when I show/hide columns via ColVis menu:

> Uncaught TypeError: Cannot read property 'style' of undefined

in this fragment of code (line 4165)

```javascript
            for ( i=0 ; i<visibleColumns.length ; i++ ) {
                column = columns[ visibleColumns[i] ];
    
                headerCells[i].style.width = column.sWidthOrig !== null && column.sWidthOrig !== '' ?
                    _fnStringToCss( column.sWidthOrig ) :
                    '';
            }
```

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please?

**Comment by irsick** [comment]
I cannot reproduce the issue on simple demo data http://jsfiddle.net/irsick/66z27jxu/,
however it exist on my overcomplicated production code which uses almost all plugins and custom sort feature.

I'll close this ticket for now until I'll find a way to reproduce test case. Thanks for quick response.

**Comment by DataTables** [comment]
There is [this thread](https://www.datatables.net/forums/discussion/27612) in the DataTables forums which might be related. I'm going to look into that shortly - you might want to keep an eye on that thread for the fix being posted and then try that version.

**Comment by irsick** [comment]
Thanks for pointing. I got exactly the same issue and I was able to reproduce it.
http://jsfiddle.net/irsick/66z27jxu/2/

The key is
```javascript
 "scrollX": true
```

**Comment by DataTables** [comment]
Good to hear - let's track this just in the forums if that is okay so there is only one thread for the bug.

**Comment by DataTables** [comment]
Fixed in [this commit](https://github.com/DataTables/DataTablesSrc/commit/f6b3bd0e489e976fe). This repo is rebuilding atm.
