### ISSUE TITLE
State save time issue with ColReorder

### ISSUE THREAD

**Issue by rmckeel** [DataTables/DataTables#554]
Hello,

  I have found a somewhat crazy issue that appears to be a bug (I don't see how it wouldn't be).

  Here is the setup: switch case from 1-4 and see how the DT reacts differently.  What is concerning is that setting a timestamp in the near past results in the Column not being reordered properly.  That is, case 2, 3 and 4 should all produce the same results.

See:
http://live.datatables.net/foqivoko/5/

Thoughts?

Thanks!  We love DataTables - what a great front-end product.

  Ryan

**Comment by DataTables** [comment]
Hi,

Thanks for the test case. I'm being a bit thick - can you get me step by step instructions for how to reproduce the error you are seeing? I haven't been able to make the column not reorder correctly with my initial tinkering.

**Comment by rmckeel** [comment]
Hi,

  Sure!  Change 'runCase = 4' to 2, 3 and then 4.  When I built it, runCase 2 and 3 operated the same, but 4 did not.  Now that a certain amount of time has passed, only runCase 3 produces the proper column ordering (Salary, Position, Name, etc).

  A fixed solution would be for runCase 2, 3 and 4 to all have the proper column ordering (Salary, Position, Name, etc).

Thanks,

  Ryan

**Comment by DataTables** [comment]
Changing the `time` to be in the future allows 2 to run as expected for me - the column reordered state is restored.

3 is potentially interesting - it might or might not load the state depending on the clock tick. I think you would need to add a 100mS or so to the timestamp just incase when DataTables runs the same code to get the current time, the clock as ticked on.

4 Should never load the state.

**Comment by rmckeel** [comment]
Can you help me understand why 4 should not load the state?  I have database backed storage of state that I am retrieving, so retrieving my use case will always have a time-in-the-past state unless I tamper with it.

**Comment by DataTables** [comment]
Sure - because it is in the past. Therefore the state has expired / is stale and shouldn't be used.

If you want to load expired state information you would indeed need to tamper with the `time` parameter.

The [`stateDuration` parameter](http://datatables.net/reference/option/stateDuration) can be used to set how long DataTables will set the timestamp for in the future.

**Comment by rmckeel** [comment]
That does seem logical, perhaps I missed that in the documentation, as it took a while to spot this bug - works initially then stops working.

Thanks!

**Comment by DataTables** [comment]
No worries - good to know we got it sorted out!
