### ISSUE TITLE
[Question][Request] server-side search.caseInsensitive setting

### ISSUE THREAD

**Issue by yajra** [DataTables/DataTables#556]
Hello,

I am using DT1.10.7 and I'm wondering if [search.caseInsensitive](https://datatables.net/reference/option/search.caseInsensitive) is indeed not being passed to server side? 

I dumped the input sent by the plugin and below is the output:
```json
{
  draw: "1",
  columns: [
  {
    data: "id",
    name: "id",
    searchable: "true",
    orderable: "true",
    search: {
      value: "",
      regex: "false"
    }
  },
  {
    data: "name",
    name: "name",
    searchable: "true",
    orderable: "true",
    search: {
      value: "",
      regex: "false"
    }
  }
  ],
  order: [
  {
    column: "0",
    dir: "asc"
  }
  ],
  start: "0",
  length: "10",
  search: {
    value: "",
    regex: "false"
    },
    _: "1431571379304"
  }
}
```

**Comment by DataTables** [comment]
It is not - as per the [documentation](http://datatables.net/manual/server-side). If you want it to be set to the server you would need to modify the data being sent using the [`ajax.data` option](http://datatables.net/reference/option/ajax.data).

In future, could you post support requests in the DataTables forums please? Thanks.

**Comment by yajra** [comment]
Noted and thanks! Haven't check the DT forum till now. Sorry for posting at wrong place! :)
