### ISSUE TITLE
(Q')  Is it possible to do OR between column filters?

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#559]
I was asked for such possibility for my [yadcf](https://github.com/vedmack/yadcf) plugin, 

Is it possible to achieve such a thing with dt api? https://github.com/vedmack/yadcf/issues/196

Thanks ahead,

Daniel

**Comment by DataTables** [comment]
Not using the built in search functionality - but a [plug-in](http://datatables.net/manual/plug-ins/search) could do it.
