### ISSUE TITLE
Wrong pagination page background and placement in Bootstrap 3.3

### ISSUE THREAD

**Issue by sergionegri** [DataTables/DataTables#560]
EDIT: solved, I was including both css (for bootstrap and vanilla). You can close the issue and sorry for the inconvenience!

Hello, please see below a screenshot:

![image](https://cloud.githubusercontent.com/assets/10323575/7902212/ce494580-07b1-11e5-96c8-af17bb156553.png)

Inside a Bootstrap modal I'm trying to display a basic DataTables following the instructions here http://datatables.net/examples/styling/bootstrap.html .

What can be seen is that the page numbers are not properly "packed together" and when you hover on one you get that strange very dark background.

You can also see that there are the proper bootstrap icons for sorting, but on top I also have some other arrows.

Am I missing something?

**Comment by DataTables** [comment]
Have a look at [this discussion](https://www.datatables.net/forums/discussion/28056) in the DataTables forums about this topic. It talks about Foundation, but the same applies to Bootstrap.
