### ISSUE TITLE
serverSide not working on ajax option is a function

### ISSUE THREAD

**Issue by harryxu** [DataTables/DataTables#561]
My datatable config is
```javascript
{
    serverSide: true,
    ajax: function(data, callback, settings) {
        $.getJSON(dataUrl, data, function(result) {
            callback({
                draw: result.pageNo,
                recordsTotal: result.totalDaNum,
                recordsFiltered: result.totalDaNum,
                data: result.daListDatas
            });
        });
    }
}
```
I formatted data to datatables' server side object, but it will show 'No matching records found' in the table.

I dig the source code and find the problem may in the [_fnAjaxDataSrc](https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.js#L2731-L2746) function, when ajax option is a function, the `dataSrc` variable in this function will be a empty string.

```javascript
var dataSrc = $.isPlainObject( oSettings.ajax ) && oSettings.ajax.dataSrc !== undefined ?
			oSettings.ajax.dataSrc :
			oSettings.sAjaxDataProp; // Compatibility with 1.9-.
```
And the function will return the origin json object from my ajax function, not the data list array. 

My temporary solution is add `settings.sAjaxDataProp = 'data';` to ajax function, but sAjaxDataProp is a deprecated option.

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a test case showing the issue so it can be debugged.

Your configuration looks fine to me. I would need a link to a test case showing the issue to be able to offer any help.

**Comment by harryxu** [comment]
I think the issue is casued by angular-datatables.
