### ISSUE TITLE
Unable to change column width in DataTables

### ISSUE THREAD

**Issue by Cr3z** [DataTables/DataTables#562]
Hi! I actually use Datatables plugin on my website with inputs-research area in each column header.
It works well but the column width is fixed at 169px (probably due to the search inputs) and I don't know how to resize it to fit to my data width.

Can you help me please?

Here's my .js:
 
```
$(document).ready(function() {

    // Setup - add a text input to each header cell
    $('#maTable thead .search').each( function () {
        var title = $('#maTable thead .header_title').eq( $(this).index() ).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'"/>' );
    } );
  
    // DataTable
    var table = $('#maTable').DataTable();
     
    // Apply the search
    table.columns().every( function () {
        var that = this;
        $( 'input', this.header() ).on( 'keyup change', function () {
            that
                .search( this.value )
                .draw();
        } );
    } );
});
```

Here's a view of the result:
![capture](https://cloud.githubusercontent.com/assets/12269381/7930843/3484d52a-090c-11e5-878a-c3fe616ecf09.PNG)

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a test case showing the issue so it can be debugged.

In this case, my guess is that CSS somewhere is forcing the inputs to a certain width. Try `th input { width: 90% }` - but without a test case that is a guess.

**Comment by Cr3z** [comment]
I've already post on DataTables forums 3 days ago but I get 0 answer that's why I try here ;)

**Comment by DataTables** [comment]
Perhaps you could give a link to the thread you created so I can take a look.

**Comment by Cr3z** [comment]
http://datatables.net/forums/discussion/28042

**Comment by Cr3z** [comment]
PS: I already tried to modify width in the CSS but it doesn't work. Maybe is it a default build configuration in the dataTables.js ?
