### ISSUE TITLE
Random load from LocalStorage (SaveState) issue IE8

### ISSUE THREAD

**Issue by mrbokx** [DataTables/DataTables#567]
Sometimes, a (reloaded) datatable with column filtering results in a empty datatable in IE8. It's a DataTable with:

- Column filtering
- AJAX / POST (ServerSide)
- SaveState
- paging (20 records per page)

It happens randomly, on different pages. I saw at the server that the post call didn't contain the filtered / sorted columns. After a page refresh, the datatable get's drawed again and correctly, with all variables.

 I've already blamed IE8 wich contains some strange randomly Ajax Post Issue (http://stackoverflow.com/questions/4796305/why-does-internet-explorer-not-send-http-post-body-on-ajax-call-after-failure). But the provided solutions didn't work.

The page isn't in public domain, so it's hard to recreate the situation. But the initialisation is as follows:

    $(document).ready(function () {
        var columnDefs = [];
        $("#tableResultaat th").each(function(index, value) {
            columnDefs[index] = {
                'name': value.innerText,
                'visible': $("#filterRow input:nth-child("+(index+1)+")").attr("type") != 'hidden',
                'searchable': true,
                'sortable':  ($(value).attr("data-allowsort") ? $(value).attr("data-allowsort") == "false" ? false : true : true),
                'render': ($(value).attr("data-render") ? Function("data", "type", "row", "meta", $(value).attr("data-render")) : undefined),
                'targets': index
            };
        });

        var tableResultaat = $('#tableResultaat').DataTable({
            "language": { "url": "/js/external/dataTables/dataTables.dutch.lang.js" },
            "pagingType": "full_numbers",
            "dom": 'tp',
            "autoWidth": false,
            "stripeClasses": ['even', ''],
            "columnDefs": columnDefs,
             'pageLength' : '20', 
             'paging' : true,
             'processing': true,
             'serverSide': true, 
             'ajax' : {'url':'/Journaal/FilterJournaal',
             'type':'POST'},
             'order': [[ '1', 'desc' ]],
             stateSave: true,
             'createdRow': function( row, data, dataIndex ) {   if (data[15] > 0 )       $('td:nth-child(8)', row).addClass('red');},'footerCallback': function( tfoot, data, start, end, display ) {    var api = this.api();    $('#AantalRecords').html(api.page.info().recordsDisplay);} });
        var initializing = true;
        $('#filterRow input').on('keyup', function (e) {
            var index = $("#filterRow input").index(this);
            var code = e.keyCode || e.which;
            if (code != '9' && code != '16') // 9 = tab 16 = shift (for shirt-tab)
            {
                var column = tableResultaat.column(index);
                if($(this).hasClass("backred") && !tableResultaat.serverSide && this.value.length > 0) 
                    column.search('^(?:(?!' + this.value + ').)*$', true, false);                    
                else
                    column.search(this.value);
                if(!initializing)
                    column.draw();
            }
        }).trigger('keyup');
        initializing = false;
    });

Maybe something with LocalStorage or some strange IE8 AJAX POST initialisation issue?

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Test cases are also very useful so it can be debugged (I know it can be a pain sometimes to need to create one).

**Comment by mrbokx** [comment]
This issue has nothing to do with Datatables but with the IE8 POST BUG (https://support.microsoft.com/en-us/kb/895954). Sometimes the POST parameters (body) are not sent to the server because of instable connections... The reason that we're using a POST request  instead of GET is beacuse our request is too long for a get request in IE8.

To overcome this issue, we've scripted a fallback solution that resents the post request on failure...

**Comment by DataTables** [comment]
Thanks for updating the issue.
