### ISSUE TITLE
Radio button can't be checked on first line when a column is hidden

### ISSUE THREAD

**Issue by Seb33300** [DataTables/DataTables#569]
Hi,

When we add checked radio button in the first line of a datatable which has hidden column, an issue make the radio button not checked on the first line only.

Example here: https://jsfiddle.net/p2t4bgpw/2/

**Comment by DataTables** [comment]
Unfortunately this is due to the clone that DataTables makes of the rows to calculate the column widths to use. It also clones the HTML and inserts that into the document, which the browser sees as a group.

I need to modify that code to strip the `name` attributes.

Until then, you can use `autoWidth: false` to stop this.

**Comment by Seb33300** [comment]
Do you think you will have the time to fix it soon?

**Comment by DataTables** [comment]
I can't say when as things are rather busy at the moment. The sooner the better obviously :-)

**Comment by smoral** [comment]
+1

**Comment by DataTables** [comment]
Finally fixed :-)

**Comment by naguveeruNBC** [comment]
Still having this issue.

**Comment by DataTables** [comment]
Please provide a test case showing the issue.

**Comment by ebonit** [comment]
I also still have this problem. 

When I click the radio button of the first row, all seems fine. However when I refresh the page afterwards, the checked radio is blank. But.. what I notice  is that in the source I see checked="checked" it just does not show as checked.

<script>
$(function() {
    $('#addresses-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('adresses.userlist') !!}',
        order: [[ 2, 'desc']],
        columns: [
            { data: 'address', name: 'address' },
            { data: 'times_used', name: 'times_used' },
            { data: 'created_at', name: 'created_at',  width: '300px' },
            { data: 'active', name: 'active' },
            { data: 'delete', name: 'delete' },
        ]
        
    });
});
</script>

public function useraddresslist(){
        $user = Auth::user();
        
        return Datatables::of(Paymentaddress::getDataTablesList($user->id))->make(true);
}

public static function getDataTablesList($user_id){
        $result = self::where('user_id', $user_id)->get();
         
         foreach($result as $row){
            $checked = '';
            if($row->active === 1){
                $checked = "checked='checked'";
            }
            $row->active = "<input type='radio' value='{$row->id}' name='activeaddress' class='activeaddress' {$checked} onclick='addressMakeActive({$row->id});'>";
            $row->delete = "<button onclick='deleteAddress($row->id)'>Delete</button>";
         }
         return $result;
    }

**Comment by ebonit** [comment]
I also notice, that when I sort the table differently, the checked button, which is now the lowest row, shows correcty. I ti s just with the initial rendering of the table when this occurs.

**Comment by nguoksiong** [comment]
Issue is fixed in default mode (without other dataTables plugins) but when responsive plugins is added, the issue still occur.
