### ISSUE TITLE
Server-side processing don't send "start" parameter

### ISSUE THREAD

**Issue by riverstore** [DataTables/DataTables#570]
Hi! I'm using DataTables 1.10.7 and here is my code

http://pastebin.com/WQUhiicx

Everything is work fine just a problem is that when I click on a page number the ajax request don't send "start" paramerter to the server.

Anyone know the problem please help me. Thanks a lot.

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.
