### ISSUE TITLE
Nondescript error when root is not table

### ISSUE THREAD

**Issue by tsu-complete** [DataTables/DataTables#572]
Error expected since root is not a table, however error reads: "TypeError: settings is null" - the first function provides null as settings to log which forwards it to callback fire which attempts to read the not yet existent table reference from it.

Screenshots of the stack trace 

![screen shot 2015-06-09 at 9 55 12 pm](https://cloud.githubusercontent.com/assets/12189295/8073428/bff788d2-0ef2-11e5-8f4b-7565381f74ed.png)
![screen shot 2015-06-09 at 9 55 30 pm](https://cloud.githubusercontent.com/assets/12189295/8073427/bff6fbc4-0ef2-11e5-9933-62f22f0037f3.png)
![screen shot 2015-06-09 at 9 55 40 pm](https://cloud.githubusercontent.com/assets/12189295/8073426/bff5ad00-0ef2-11e5-96c9-d232c078f7b9.png)

**Comment by DataTables** [comment]
Thank you! [Fixed here](https://github.com/DataTables/DataTablesSrc/commit/222280683bf) and this repo is rebuilding now.
