### ISSUE TITLE
Major performance optimization for large DOM

### ISSUE THREAD

**Issue by alexandruionescu** [DataTables/DataTables#574]
Hi,

Not an issue, but an improvement: 
For large DOM sizes, saving the aDom.length in a separate variable greatly reduces the time spend in the _fnAddOptionsHtml function. In my sample of 1500 rows and 12 columns it went from 9s down to 0.03s.

var domLength = i < aDom.length;
            for (var i = 0 ; i < domLength ; i++) {

Cheers!
Alex

**Comment by DataTables** [comment]
[This line](https://github.com/DataTables/DataTablesSrc/blob/master/js/core/core.draw.js#L512)?

Can you give me a link to a before and after? I don't make putting that change in (although with tracing in all modern Javascript runtimes it shouldn't make any difference), but I can't see how it would provide a 9s to 0.03s change!

**Comment by Robinson7D** [comment]
Agreed (that should not make a major difference). Especially since `aDom` here is just the characters of `sDom`, which is typically fairly short. 

HOWEVER:
What would make it faster is if he actually used the exact code in the original post (`var domLength = i < aDom.length;`)

In strict mode, that will throw an error - `i` is not defined. Outside of strict mode it will resolve false (e.g. assuming `aDom.length` is 5, `undefined < 5 // => false`); and so later, the loop will be ignored entirely (`i = 0; i < false; i++` , first iteration of `0 < false` resolves false, so skips the loop).

Hence the time saved.

**Comment by DataTables** [comment]
Good catch - I missed that point. DataTables should be executing in strict mode, so the above is nice and fast as it just throws an error... Even out-side of strict mode it wouldn't be executing the loop.

Alex - please can you provide a link.

**Comment by alexandruionescu** [comment]
Whoops... sorry for that! Indeed, with the JavaScript corrected there's no difference in performance. 

An interesting thing is that datatable was still getting initialized and my ordering headers and footer search filters were still functioning, which is what I needed the most. 

With the js corrected I have to wait an extra 9 seconds to have the pagination controls available. I wonder if there's a way to call datatable() and avoid this expensive function.

**Comment by DataTables** [comment]
9 seconds sounds like a very long time for initialisation of a table. Can you link to the page so I can profile it please.

**Comment by alexandruionescu** [comment]
I can't give you the page since it has confidential data and lives in our intranet. 
Does this help?
![ie10 profiler](https://cloud.githubusercontent.com/assets/10131641/8086890/03f987a6-0f98-11e5-8109-b715eb916e45.png)

I could build a html file for you tomorrow if you need it.

**Comment by DataTables** [comment]
A test page I can do performance testing on would be very useful. Thanks.

**Comment by alexandruionescu** [comment]
Here's a complete page
https://www.dropbox.com/s/auzx6tx0h4aipyj/for%20debug.zip?dl=0

Call 
$('.datatable-sorting-footers').dataTable()
from console to see behavior.

Thanks!

**Comment by DataTables** [comment]
Thanks! That shows that it is the column width calculation that is taking a long time. Try adding `autoWidth: false` to your table initialisation to see a speed increase. Ajax loading with deferred rendering enabled will also provide a significant speed increase.

**Comment by alexandruionescu** [comment]
Awesome. Thank you very much!

**Comment by Robinson7D** [comment]
I've noticed `autoWidth` being a slow, as well. 

I'm not sure if you've looked at it yet, but I did send a pull request that greatly speeds it up in cases where you want a half-and-half solution (i.e. you can provide a fixed width for most columns (e.g. dates that are always the same width, range-bound numbers, icons, etc.), but maybe 2 or 3 can be auto-width in the remaining space -- or one can stretch to fill the remaining):

https://github.com/DataTables/DataTablesSrc/pull/33

With those 10 lines changed, I've been able to have tables (with obviously way too much data) that took over a second to load work in 150-250ms.

It's not a perfect solution, of course, but it might be a cheap fix for some people.
