### ISSUE TITLE
Issue with DataTables sorting with fuzzy time.

### ISSUE THREAD

**Issue by matisoffn** [DataTables/DataTables#575]
I have different tables throughout my project that all use DT.

In one table, the column is "Days Ago" and some of the values are:

```
-2 days ago, -1 days ago, 0 days ago, 1 day ago
```

Why can datatables not sort this properly?

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.
