### ISSUE TITLE
Setting language interferes with columns().every() context callback 

### ISSUE THREAD

**Issue by alexandruionescu** [DataTables/DataTables#576]
If I select a language file in the datatable options the context callback is set to the table instead of the column. 

I'm using 
table.columns().eq(0).each( function ( index ) 
as a workaround.

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by alexandruionescu** [comment]
Here's a jsFiddle that shows the problem:

http://jsfiddle.net/qxc3zf1o/

The code is straight out of the example on your website:
https://datatables.net/examples/api/multi_filter.html

Uncomment the language parameter and try the footer filter again to see the issue.

**Comment by DataTables** [comment]
Thank you. The issue there is that loading language via Ajax makes the table initialisation asynchronous. Use `initComplete` to address this: http://jsfiddle.net/qxc3zf1o/1/ .

**Comment by alexandruionescu** [comment]
Nice!
