### ISSUE TITLE
Numeric OrderDataType Issue

### ISSUE THREAD

**Issue by NYPD** [DataTables/DataTables#579]
I think I have come across some unexpected behavior in the datatables built in html numeric ordering.

When one loads a page with a table containing numeric inputs and each of those inputs contain a "value" attribute, data tables sorts it perfectly as expected. However, when a user changes the values in those input and tries to sort again, it will only sort based on the values that got loaded in the "value" attribute.

An example can be found here: http://jsfiddle.net/tn9kzLr9/1/  (change the middle input to a diffrent value and try sorting).

I have a page where users are able to change those values and send an ajax save call that saves those newly inputted values back to the database, however, I noticed when trying to order that input column again without refreshing the page it only orders by the previous set of numbers.

I'm not exactly sure how the sorting algorithm functions in the back, but if it perhaps uses the "value" attribute to get the numbers, it could instead use the DOM value prop which contains the real time value (.prop() vs .attr() in jQuery). I'm not sure though.

**Comment by DataTables** [comment]
The live DOM sorting plug-ins are not included in the DataTables core file. You need to include them like in [this example](http://datatables.net/examples/plug-ins/dom_sort.html).
