### ISSUE TITLE
Possible bug: DataTables not working with JQuery 1.11.3

### ISSUE THREAD

**Issue by schmidt-chris** [DataTables/DataTables#580]
Hey guys,
i just wanted you to know that after the upgrade to JQuery 1.11.3 DataTables 1.10.7 is not working anymore. You always get this error message: TypeError: invalid 'in' operand a

When you switch back to JQuery 1.11.2 DataTables is working again. More Information is available under: http://stackoverflow.com/questions/30912605/typeerror-invalid-in-operand-a#

Best regards
Peter

**Comment by DataTables** [comment]
Can you try the nightly please. I believe this is already fix by [this commit](https://github.com/DataTables/DataTablesSrc/commit/12134bf7404f80b3c).

**Comment by DataTables** [comment]
Oops - reopening until you can confirm that it is working, or show it not working with a test case.

**Comment by schmidt-chris** [comment]
It's working in the new version. Issue can be closed. Thanks for the information.
