### ISSUE TITLE
RequireJS can't access functions

### ISSUE THREAD

**Issue by pixedd** [DataTables/DataTables#581]
Hi I'm using requireJs and dataTable plugin that I initialize in my App, after that I require a module and pass the reference of my dataTable in it, like that:

                require(["controller/search"], function (search) {
                    table.search = search;
                    table.search .init(that.dataTable);
                });

The strange thing is that I can access some basics informations in my search module like:

this.dataTable.page.info();

but I can't access:

this.dataTable.search( this.value ).draw(); -> return is not a function()

Am I doing something wrong ?

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.

**Comment by DataTables** [comment]
No feedback on this issue. If you are still having this issue, please reopen with a link to a test case.
