### ISSUE TITLE
api.draw(false) incorrectly invokes sort and filterComplete

### ISSUE THREAD

**Issue by toc777** [DataTables/DataTables#584]
_fnReDraw is not working correctly, See this excerpt from _fnReDraw: 
```
function _fnReDraw( settings, holdPosition ) {    
var
    features = settings.oFeatures,
    sort     = features.bSort,
    filter   = features.bFilter;

   if ( sort ) {
       _fnSort( settings );
   }

   if ( filter ) {
       _fnFilterComplete( settings, settings.oPreviousSearch );
  }
  //rest of code
}
```

If sorting and filtering are enabled, it will always call _fnSort and _fnFilterComplete. It looks like the function was designed to use the holdPosition parameter to decide if it should call _fnSort and _fnFilterComplete.

This is a major bottleneck when using datatables with a large number of rows and a pagination plugin like bootstrap that needs to call `api.page('next').draw(false)` in order to render the next page.

**Comment by DataTables** [comment]
Performing a sort and filter is correct and intended when `draw( false )` is executed. The `false` simply tells DataTables to retain the current paging position - it does not tell it to not perform sorting etc.

However, I fully acknowledge that this is going to cause a performance hit on each page change. I'm wondering if the correct thing to do would be to add another optionally parameter to the `page()` method that will cause it to redraw (without the additional processing - which you can do with the internal methods).

Let me have a little think about it - also feedback is welcome :-)

**Comment by toc777** [comment]
I don't understand why sorting and filtering are necessary to redraw the table. This seems to me like an option that should be passed to draw rather than page.

**Comment by DataTables** [comment]
The [documentation for `draw()`](http://datatables.net/reference/api/draw()) says:

> Note that calling draw() will result in a full re-sort and re-filter of the table being performed.

This is basically so any changes in the data will be reflected in the table.

In retrospect perhaps I should have called it something else! But its been that way since v1.0 so unfortunately a little late to change now (ah legacy code just isn't what it used to be... ;-) ).

However, I absolutely see the need for a new type of draw that will simple refresh the display, rather than doing a refilter and resort.

Possibly `draw()` could be overloaded with a string parameter that would allow various options - `'full`, `static` and `simple` perhaps. But I'm not sure I like that implementation overly much...

**Comment by DataTables** [comment]
I've just [committed the required change](https://github.com/DataTables/DataTablesSrc/commit/51d29bc6e2be). You can now pass in `'page'` as the parameter to `draw()` which will cause it to do a simple redraw. The Bootstrap integration has also been updated to reflect this.

Thanks for flagging this up!

**Comment by joaquin-becerra** [comment]
Hello!
Sorry for asking here, but I think it's related.

I try to change the page in this example :

https://datatables.net/examples/basic_init/zero_configuration.html

Using

$('#example').DataTable().page(3).draw('false')

I am trying to use the stateSave option also saving the current page, but it is not working

But it does not seem to work, am I doing something wrong?

Thanks

**Comment by DataTables** [comment]
You should be using boolean `false` not a string value. See the [documentation and examples here](https://datatables.net/reference/api/draw()).
