### ISSUE TITLE
Unable to get API instance in initComplete callback

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#587]
Using DataTables 1.10.7 with the code below:

```
$('#example').DataTable({
    'initComplete': function(settings, json){
       var api = new $.fn.dataTable(settings);
       console.log(api);
    }
});
```

Getting the error in the console `this.each is not a function` in jquery.datatables.js, line 6092.

See [JSFiddle](http://jsfiddle.net/zw31vg4y/1/) for an example.

Is this an expected behavior? It seems that API instance could be retrieved with `this.api()` or `$('#example').DataTable()` instead in `initComplete` callback. Documentation for [initComplete](http://datatables.net/reference/option/initComplete) doesn't mention that API instance cannot be retrieved with `new $.fn.dataTable`.

**Comment by DataTables** [comment]
An API instance can never be retrieved with `new $.fn.dataTable()`. As the [documentation](http://datatables.net/manual/api#Accessing-the-API) [notes](http://datatables.net/reference/type/DataTables.Api#Accessing-the-API) it is `new $.fn.dataTable.Api()`.

**Comment by mpryvkin** [comment]
Then the example on [DataTables.Settings](http://datatables.net/reference/type/DataTables.Settings) page is incorrect, see below:

    $('#example').dataTable( {
       "drawCallback": function( settings ) {
          var api = new $.fn.dataTable( settings );
  
          // Output the data for the visible rows to the browser's console
          // You might do something more useful with it!
          console.log( api.rows( {page:'current'} ).data() );
       }
    } );

**Comment by DataTables** [comment]
Doh. Yes it is. Sorry.

Corrected now.

**Comment by mpryvkin** [comment]
Great, thanks!

**Comment by mpryvkin** [comment]
Is this a correct place to report other typos in the documentation?

**Comment by DataTables** [comment]
Yes this will do just fine :-)
