### ISSUE TITLE
Errors when using ColVis and Scroller

### ISSUE THREAD

**Issue by joshuadwire** [DataTables/DataTables#588]
When I use ColVis to show a column that was previously hidden, I get the error `Cannot read property 'style' of undefined`. This seems to be because `_fnAdjustColumnSizing` tries to resize the header befure the th for the new column has been added back in.

Changing the function to the following seems to fix the issue (notice how `_fnScrollDraw` is called at the beginning instead of the end):

	function _fnAdjustColumnSizing ( settings )
	{
		var scroll = settings.oScroll;
		if ( scroll.sY !== '' || scroll.sX !== '')
		{
			_fnScrollDraw( settings );
		}
		
		/* Not interested in doing column width calculation if auto-width is disabled */
		if ( settings.oFeatures.bAutoWidth !== false )
		{
			var columns = settings.aoColumns;
	
			_fnCalculateColumnWidths( settings );
			for ( var i=0 , iLen=columns.length ; i<iLen ; i++ )
			{
				columns[i].nTh.style.width = columns[i].sWidth;
			}
		}
	
		_fnCallbackFire( settings, null, 'column-sizing', [settings] );
	}

**Comment by DataTables** [comment]
Can you confirm which version of DataTables you are using please? If not [1.10.8-dev](//datatables.net/download/#DataTables) please try that as this issue should already be resolved there.

**Comment by joshuadwire** [comment]
I was using 1.10.7. Upgrading to 1.10.8-dev fixed the issue. Thanks!
