### ISSUE TITLE
Sorting icons positioning problems

### ISSUE THREAD

**Issue by Alex-Sokolov** [DataTables/DataTables#589]
If we create table, and headers will be not only one-liners - sorting icons for one-liners positioning badly. 

![datetables-headers-bug](https://cloud.githubusercontent.com/assets/4497128/8476228/10ba4be2-20c8-11e5-9751-ca6e2f61f880.PNG)

I think maybe better make all for show at the bottom?

P.S.: Using jquery 1.11.3, dataTables 1.10.7

**Comment by DataTables** [comment]
Thank you - I hadn't realised before that vertical-align:bottom was the default for Bootstrap table headers.

I've [committed the required change](https://github.com/DataTables/DataTablesSrc/commit/eb041c31f08) and it will be released with the next version of DataTables.
