### ISSUE TITLE
DataTables responsive and knockout binding

### ISSUE THREAD

**Issue by Purush0th** [DataTables/DataTables#590]
While using dataTables with Knockout, the binding is not working when resizing the table.Find the sample fiddle where you can click on the colors. 
http://jsfiddle.net/Purushoth/2zrx2jf0/

Re-size the output window then click on the color and binding will not work.
![u3sf7 1](https://cloud.githubusercontent.com/assets/1386902/8510480/6664c1c8-2305-11e5-89ac-69a06d1886b1.png)

**Comment by DataTables** [comment]
I would not expect this to work with Responsive in the way you describe. The information shown in the child row is a copy of the data data shown in the DataTable - _not_ the original element. So if you want an event listener on it, you would need to add an event listener.

The other option would be to write a custom renderer that does use the original elements.

Going to close this here - it is working as expected at the moment (even if not desired). If you would like to see this feature in future, a feature request in the Response repo would be the correct place to fine it.

**Comment by Purush0th** [comment]
Here is a solution/workaround for this issue. 
http://clanjs.com/2015/10/23/knockout-binding-issue-with-responsive-datatables/
