### ISSUE TITLE
Option orderType and Multi-column ordering example page

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#591]
[Multi-column ordering](http://datatables.net/examples/basic_init/multi_col_sort.html) example page mentions that:

> Using the `columns.orderData` option to specify a multiple column order by default (for example `[ [0,'asc'], [1,'asc'] ]`).

See [this JSFiddle](http://jsfiddle.net/L5gbck06/) for demonstration of the problem. Sort by the second column and look for error in the console.

It appears that `columns.orderData` only accepts array of indexes without sorting method. That is also stated on the [columns.orderData](http://datatables.net/reference/option/columns.orderData) page.

So the problem is that [Multi-column ordering](http://datatables.net/examples/basic_init/multi_col_sort.html) example page contradicts with the manual.

Aslo see [discussion on StackOverflow](http://stackoverflow.com/questions/31248861) regarding this issue.

**Comment by alvarotrigo** [comment]
+1

**Comment by DataTables** [comment]
Hi,

Thanks for flagging this up. I'ved [committed a fix for this](https://github.com/DataTables/DataTablesSrc/commit/4f1b9dafc09) in the docs (which were wrong) and will be deploying it to the site soon.
