### ISSUE TITLE
_fnBrowserDetect incorrect offset calcuation

### ISSUE THREAD

**Issue by IhrS** [DataTables/DataTables#594]
Hello There,

Recently on our project where we use DataTable plugin we have noticed an issue where in 'Column Header' gets misaligned by 17px. What we have found, function **_fnBrowserDetect** which tests scroll  bar location side (left/right) calculates it wrongly. We are using a plugin which creates off-canvas menu called  [Sidr](http://www.berriart.com/sidr/). This plugin alters page body with style: 
    `style="position: absolute; left: 375px;`.
_fnBrowserDetect creates new element 'absolute' positioned to the body.
Then it tests offset and below comparison works incorrectly:
`browser.bScrollbarLeft = Math.round(test.offset().left) !== 1; `

As a fix which works for us we suggest to change position from absolute to fixed for new test element.
 
from:
`		var n = $('<div/>')
			.css( {
				position: 'absolute',`
to:
`		var n = $('<div/>')
			.css( {
				position: 'fixed',`

**Comment by DataTables** [comment]
Interesting! Are you able to give a link to a test page showing the issue? However, I don't see any issue with changing the text element to position fixed.

**Comment by ieaglle** [comment]
Hi,
I've created a sample [here](http://embed.plnkr.co/ot0PvpM2rpF1OG8zPwyK/preview).
To reproduce you need to click "**Drop**" button and then "**Create**".
You'll see that header is misaligned by 17px with:
`padding-left: 17px;`
