### ISSUE TITLE
Alert when table row drawing

### ISSUE THREAD

**Issue by Alex-Sokolov** [DataTables/DataTables#595]
Making a table for listing users. And sometimes started `alert(1)` display.
After some debugging time found that one of objects in array contain:
```json
{
      "ObjectId":"5966996c-0186-412d-911f-8b2a22e775fe",
      "IdClientProfile":10099,
      "Organization":"<script>alert(1);</script>",
      "Department":"department_775.756",
      "EMail":"email@domain186958.d"
}
```
And when we switch to page with that row, or searching and row in search results - will be alert in browser window. That's valid JSON, but I think this is bug.

![08 07 2015-1](https://cloud.githubusercontent.com/assets/4497128/8572923/c9b965fa-2597-11e5-9481-c65a53820ab8.png)

P.S.: Using jquery 1.11.3 and dataTables 1.10.7

**Comment by DataTables** [comment]
Hi,

Could you clarify what you would expect the correct behaviour to be? To my mind this looks correct as it is at the moment - you are telling the table to insert a script tag that performs an action - it does that. If you don't want that, the HTML should be suitable escaped.

**Comment by Alex-Sokolov** [comment]
I expect that in table cell will be `<script>alert(1);</script>` text and nothing from raw data will be executed (now alert executed and table cell is empty)

**Comment by DataTables** [comment]
In that case you need to escape the HTML - i.e. use `&lt;script&gt;alert(1);&lt;script&gt;`. DataTables writes to the cell using `innerHTML` - hence why you are seeing what you are. If it did not do that it would be impossible to inject complex HTML into the table cells.

Going to close this issue as it is working as I would expect.
