### ISSUE TITLE
columns.searchable blocks column searching

### ISSUE THREAD

**Issue by fkurth** [DataTables/DataTables#597]
If the option
`searchable: false` 
is set to a column definition, then this column is excluded in the global search:
`table().search('searchterm')`
This is expected.
But the search within that column, selected by its index:
`table().column(2).search('searchterm')`
always leads to an empty table. I expect the column-local search to work, even if the column is excluded from the global. This was the behaviour in 1.9.

**Comment by DataTables** [comment]
The behaviour in 1.9 was incorrect if that was what happened. If you disable search for a column, to disable search for that column.

The real fix would perhaps be to have an option to disable for global search and column search independently. But that is not a feature that is in DataTables at this time. It isn't one I have planned to work on, but PRs are welcome.

**Comment by fkurth** [comment]
But how to achieve then the 1.9 behaviour:
A global search over columns (with an `or` condition, if i do `table().columns([0,2])`, its an `and` condition) 
(A global search input, working on selected columns)
and be able to search in single columns as well
(Search input fields)

**Comment by DataTables** [comment]
There is no option for that in DataTables 1.10. As I say, that "feature" in 1.9 was unintentional and a bug. You would need to modify the code to perform the OR search, or use a custom search plugin.
