### ISSUE TITLE
cell().data() set operations don't work on columns generated by function

### ISSUE THREAD

**Issue by jgillmanjr** [DataTables/DataTables#598]
Hello!

Not sure if I'm missing something in the docs or not, but it appears that attempts to set data on a cell that had it's data initially generated by a function are unsuccessful.

Here is a [jsfiddle](https://jsfiddle.net/jgillmanjr/14o3u0j9/) for demonstration.

**Comment by DataTables** [comment]
Generally speaking, I would _very_ much recommend not using the `columns.data` option as a function. If you do you need to also add logic for its 'setter' action. If you just want to effect the data on the output - I would suggest using `columns.render` as the formatting function.

In future, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums.
