### ISSUE TITLE
scrollY, scrollCollapse, filtering and child rows make the table unusable

### ISSUE THREAD

**Issue by ruhley** [DataTables/DataTables#599]
If I have the following config ```{ scrollY: '350px', scrollCollapse: true }``` and then filter the table down to only 2 rows, and then click a row it creates some child rows, the table height is still only 2 rows high and almost impossible to use.

I have created a [jsfiddle](http://jsfiddle.net/hxg0ja9h/) based off of the [child rows](http://datatables.net/examples/api/row_details.html) example. Search for Doris and click the first cell in the row to expand it.

**Comment by DataTables** [comment]
Thank you for the fiddle. it might be a little bit of time before I can look into this properly due to lack of resources at the moment (an overwhelming overwhelming number of support requests primarily), but this is something that should be addressed.

**Comment by DataTables** [comment]
A recent change I made to DataTables addresses this - with the dev version: http://jsfiddle.net/hxg0ja9h/1/ .

Thanks again for the fiddle!

**Comment by ruhley** [comment]
:thumbsup:
