### ISSUE TITLE
Columns with null data should not be searchable and sortable by default

### ISSUE THREAD

**Issue by mitar** [DataTables/DataTables#601]
In [this example](https://datatables.net/examples/ajax/null_data_source.html) you use `data: null` for buttons column. I think such columns should by default not be searchable and sortable.

**Comment by DataTables** [comment]
I see the point, however, I don't want to introduce conditional defaults at this time - the default should be only one value. I might revise that in future, but it is value to have such columns (with data generated using the `render` function) as orderable and searchable.
