### ISSUE TITLE
SECURITY FLAW: Veracode identifies php file for external control of File Name or Path

### ISSUE THREAD

**Issue by patrot** [DataTables/DataTables#603]
Veracode reported error CWE-73: External Control of File Name or Path at link http://cwe.mitre.org/data/definitions/73.html

Path: examples/resources/
File: examples.php
Line: 4
Code: echo htmlspecialchars( file_get_contents( '../server_side/'.$_POST['src'] ) );

**Comment by DataTables** [comment]
The line immediately before that performs validation to ensure that the value of $_POST['src'] is valid and correct:

    if ( isset( $_POST['src'] ) && preg_match( '/scripts\/[a-zA-Z_\-_]+\.php/', $_POST['src'] ) !== 0 ) {

How do I tell Veracode that it has already been validated?

**Comment by patrot** [comment]
You would need to contact Veracode on this https://info.veracode.com/web-contact-us.html

**Comment by DataTables** [comment]
Going to close this as the code does do validation on this parameter already.
