### ISSUE TITLE
SECURITY FLAW: Veracode identifies php file that exposes information through error message

### ISSUE THREAD

**Issue by patrot** [DataTables/DataTables#604]
Veracode reported error CWE-209: Information Exposure Through an Error Message http://cwe.mitre.org/data/definitions/209.html

Path: media/unit_testing/performance
File: large.php
Line: 85
Code: $rResult = mysql_query( $sQuery, $gaSql['link'] ) or die(mysql_error());

**Comment by DataTables** [comment]
I think this is valid for a unit test is it not? It is _not_ good code, I'll grant (like all of the unit tests...).

Best thing to do is probably for me to remove the unit tests form this repo - there probably shouldn't be here any more given that there is the source repo for developers now anyway.
