### ISSUE TITLE
Documentation for columns().visible()

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#605]
On the page  for [columns().visible()](http://datatables.net/reference/api/columns%28%29.visible%28%29), single quote in `alert()` should be escaped.

The line below:

    alert( 'Table's column visibility are set to: '+table.columns().visible().join(', ') );

should be changed to:

    alert( 'Table\'s column visibility are set to: '+table.columns().visible().join(', ') );

**Comment by DataTables** [comment]
Good spotting! Thanks for pointing that out. [Fix committed](https://github.com/DataTables/DataTablesSrc/commit/ba3f762e1077) and will be deployed to the site with the next update (hopefully next week).
