### ISSUE TITLE
trim in core.data.js really needed?

### ISSUE THREAD

**Issue by markvantilburg** [DataTables/DataTables#606]
Is this trim really needed?

https://github.com/DataTables/DataTablesSrc/blob/bbf60cb061faab9f34b9db46948f25e9ee75dce7/js/core/core.data.js#L607

In my profiler i see 5000 calls to trim, but the column i'm filtering on does not contain trailing spaces for sure.

**Comment by DataTables** [comment]
Is the call (cumulatively) taking a significant amount of time? It is present just to tidy up the data read from the html.

**Comment by markvantilburg** [comment]
In chrome 2.1ms.

![chrome](https://cloud.githubusercontent.com/assets/4510245/8745173/4d9a6aae-2c7d-11e5-9f9b-235a809617bb.png)

![chrome-bigger-table](https://cloud.githubusercontent.com/assets/4510245/8745222/ebe1c9f0-2c7d-11e5-8698-d4d76e5039da.png)

**Comment by DataTables** [comment]
As that cumulative amount of time spent in that function is very small relative to everything else that is going on, I suspect that optimisation would be better occurring else where. The trim is something that DataTables does as often the HTML might be formatted thus:

```
<td>
    Hello
</td>
```

The trim just tidies that up into what I think would be generally expected as the data for that cell. It is something that DataTables has always done, and I would be wary of removing it as it will break other people's uses of DataTables.

As such, I'm not going to make this change at this time - but thanks for highlighting this. It is something I will keep an eye on. Performance is obviously something that is particularly important to me!
