### ISSUE TITLE
Hidden columns are visible after window resize

### ISSUE THREAD

**Issue by kovacs-tamas** [DataTables/DataTables#607]
When i hide some columns in the DataTable they will be visible when i resize the window (there is a fixed size when appears the problem). After restoring the window to the original size, i can still see the unchecked elements in the column selector but the columns are visible.

<img width="1300" alt="screenshot at jul 22 11-25-43" src="https://cloud.githubusercontent.com/assets/7418668/8822278/80fb76a0-3064-11e5-9c57-446bc2ae84c2.png">

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.

**Comment by bluzioo** [comment]
I am in trouble with the same issue. Was it fixed? I appreciate any help.
