### ISSUE TITLE
Documentation for rows().every()

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#608]
In the example below `rowIdx` is not defined anywhere. Although it may be perfectly valid code with `rowIdx` defined globally, however with this example it makes sense to use something like `var rowIdx = this.index();` inside the function.

<pre>
var table = $('#example').DataTable();
 
table.rows().every( function () {
    this
        .child(
            $(
                '&lt;tr&gt;'+
                    '&lt;td&gt;'+rowIdx+'.1&lt;/td&gt;'+
                    '&lt;td&gt;'+rowIdx+'.2&lt;/td&gt;'+
                    '&lt;td&gt;'+rowIdx+'.3&lt;/td&gt;'+
                    '&lt;td&gt;'+rowIdx+'.4&lt;/td&gt;'+
                '&lt;/tr&gt;'
            )
        )
        .show();
} );
</pre>

**Comment by DataTables** [comment]
The first parameter passed into the `every` function is the row index. I had missed that from the function's parameter list. Thanks for pointing that out.

I've added it [here](https://github.com/DataTables/DataTablesSrc/commit/16ce1f6833) and will push it out to the site soon.

**Comment by mpryvkin** [comment]
Allan, can you also please update the example above on the same page for the sake of clarity so it reads:

> Using `rows().every()` this can be rewritten as:
> <pre>
table.rows().every( function (index) {
    var data = this.data();
    // ... do something with data(), or this.node(), etc
} );
</pre>

**Comment by DataTables** [comment]
Yes - positively sensible that! Thanks :-)

[Committed](https://github.com/DataTables/DataTablesSrc/commit/3fb318b8a2)

Allan

**Comment by cheikhsadbouh** [comment]
hello, guys, can you help me 

table.rows().every( function (index) {
    var data = this.data();
    // ... break ; or return false wich one will stop function ?
} );

**Comment by DataTables** [comment]
None. There is no way to get out of that loop - its a callback that will be executed for every row. If you need some support with a specific function, feel free to [post your question in the forums](//datatables.net/forums).
