### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by ashl1** [DataTables/DataTables#610]
Here I want to collect all errors in DT documentation to qucikly access for them. If you has one - comment it here - I'll add to the list

- [x] [api.column().index()] (https://datatables.net/reference/api/column().index()) The return type is wrong. Should be 'Integer' instead of 'DataTables.Api'
- [x] [api.columns()] (https://datatables.net/reference/api/columns()) The type of 'column-selector' argument should be 'column-selector' instead of 'column-cell'

**Comment by DataTables** [comment]
Hi,

Thanks for flagging this up. Both have been addressed in [this commit](https://github.com/DataTables/DataTablesSrc/commit/bcf5444bdcfef) and will be pushed out to the site with the next update.
