### ISSUE TITLE
Virtual scroll with server side processing

### ISSUE THREAD

**Issue by mikalai-ramashka** [DataTables/DataTables#611]
Hi
I have found example of using server side processing with infinite scroll for legacy version of datatables, but haven't found for virtual scroll. Is there any way to achieve these functionality with current version of datatables?

**Comment by Delgan** [comment]
I think you should use the [Scroller plugin](https://datatables.net/extensions/scroller/) which does exactly what you are looking for.

**Comment by DataTables** [comment]
There is no "infinite scroll" option in DataTables 1.10+ - it was removed in 1.10.0 ([see the upgrade notes](http://datatables.net/upgrade/1.10#bScrollInfinite)).

The closest now is the Scroller plugin that @Delgan mentioned.

In future, could you post support requests in the [DataTables forums](//datatables.net/forums) please.

**Comment by mikalai-ramashka** [comment]
This example https://datatables.net/release-datatables/extensions/Scroller/examples/server-side_processing.html exactly as I need! Thanks!
