### ISSUE TITLE
2 little bugs related to table size and scrollbars

### ISSUE THREAD

**Issue by Delgan** [DataTables/DataTables#612]
Hello. Sorry to bother you again, but I found two little bugs in relation to the issue #609 I previously reported.
I tried to fix it by looking through the code but I did not succeed, so I though it could be interesting to open an issue so you could be aware of it, even if these bugs are not so important and do not require too much attention.

This is tested using the last 1.10.8-dev build.
<br><br>
### Data columns are shifted when `scrollY` is set but not useful
If the `scrollY` option is set to some height, but that the JSON data displayed does not require as much space so there is no vertical scrollbar, then the table's data are slightly shifted to the right.

This seems to come from the data `<table>` because setting `margin-left: 0px` instead of `auto` solves the issue.

[JSFiddle](https://jsfiddle.net/dLm0d1fs/13/)

![shifted](https://cloud.githubusercontent.com/assets/4193924/8926789/d50df2e2-3512-11e5-8fdd-a9eab978528f.png)
<br><br>
### Useless horizontal scrollbar when `scrollY` option is not set
This bug appears using Firefox (tested on 38.0.6) but I found nothing using Chrome.

It is necessary that the size of the page is of a certain size so that the bug occurs (so it is necessary to resize the pannel JSFiddle to make the bug appears).

As showed in the screenshot, this is weird because the width of the `<table>`'s parent `<div>` is good (745px, this is the size of the 5 columns) but the `scrollHead` `<div>` is one pixel smaller, which causes the scrollbar to be displayed (setting it to 745px fixes it).

[JSFiddle](https://jsfiddle.net/dLm0d1fs/14/)

![useless](https://cloud.githubusercontent.com/assets/4193924/8926893/ac1df426-3513-11e5-96e5-bce304c1e322.png)

**Comment by DataTables** [comment]
Scrolling is my nemesis! Thanks for hte test cases - I'll get back to you. These need to be resolved before 1.10.8.

**Comment by DataTables** [comment]
Finally got a chance to dig into this and hopefully get this scrolling stuff put to bed!

The Firefox one was interesting - it was a sub-pixel calculation error which is why it sometimes shows up and sometimes not. Funny that Chrome doesn't show the issue, but there must be something clever going on under the hood for that.

The latest nightly addresses both of these issues:

* https://jsfiddle.net/dLm0d1fs/15/
* https://jsfiddle.net/dLm0d1fs/16/

Doing to be putting out DataTables v1.10.8 on Wednesday unless something goes horrible wrong between now and then (possible!). If you spot anything else, please do let me know :-)

**Comment by Delgan** [comment]
I hope you have not made too many nightmares about these damn scrollbars!
Once again, thank you for your great job. I will never say it enough, but your work is amazing.

I feel bad to give you work again... But it is not about scrolling. :)
Actually, I do not really care about this bug, I just encountered it while playing with [the JSFiddle pannel](https://jsfiddle.net/dLm0d1fs/15/).

If <code>scrollCollapse</code> and <code>scrollY</code> are set, and if the window's height is smaller than the scrollY value, then there is a weird blank line that appears at the bottom of the table.
![Weird space](https://cloud.githubusercontent.com/assets/4193924/9174479/57a5b2e0-3f80-11e5-82b2-8ab55cf5815c.png)

**Comment by DataTables** [comment]
I very much appreciate your testing and letting me know about these issues! This one is another cracker :-).

I've [committed the fix](https://github.com/DataTables/DataTablesSrc/commit/3cb4b4847de) and it is in the [nightly build now](https://jsfiddle.net/dLm0d1fs/15/).

If you find anything else - you know where to find me (hiding in a beer bottle ;-) ).
