### ISSUE TITLE
DeferRender not working

### ISSUE THREAD

**Issue by Oradukuyakatater** [DataTables/DataTables#613]
Hi,

I use dataTable and i came to think that deferRender option have no effect. I log some text in the console when a row is created :
<code>
...
  "createdRow": function( row, data, dataIndex ) {
    console.log("row creation");
  }
...
</code>
and it displays as many lines as there are rows. Everything else is working fine.
Anyone else have this issue ?

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

**Comment by Oradukuyakatater** [comment]
https://jsfiddle.net/1je2qtqm/

Here is the demo !

**Comment by DataTables** [comment]
The table is DOM sourced, so `deferRender` would make no difference since the DOM elements already exist... There is nothing to defer!

**Comment by Oradukuyakatater** [comment]
My bad then, I'll try to figure how to use this option the right way.
Thanks anyway for your great work !
