### ISSUE TITLE
Documentation for createdRow

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#616]
Typo on [createdRow](http://datatables.net/reference/option/createdRow) page:

`Add a cass to the row, conditionally based on the row's data:`

should be 

`Add a class to the row, conditionally based on the row's data:`

**Comment by DataTables** [comment]
Thanks! [Committed here](https://github.com/DataTables/DataTablesSrc/commit/1ddb472859daaf) and will be pushed out to the site soon.
