### ISSUE TITLE
DataTable removes custom-appended elements to the pagination upon sorting any row

### ISSUE THREAD

**Issue by knitevision1** [DataTables/DataTables#617]
I created a codepen to demo the issue
http://codepen.io/knitevision1/pen/mJozwL

I basically appended a custom element to the ```.dataTables_paginate``` (see JS)

**Steps to reproduce:** click to sort on any table column and the button with text "Some custom button" disappears.

It doesn't happen when appending to ```.dataTables_filter```.

Looks like upon every sorting of the table pagination gets updated somehow and it vanished any customly-appended item because it has some kind of template in the source code that must be matched.

Any solution to that? Apart from appending the element on each sorting of the table... Lol

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums.

In this case, do you actually need the button in the paging control, or just next to the table? If next to the table will do, use the `dom` property as explained in [this example](http://datatables.net/examples/advanced_init/dom_toolbar.html).

This isn't a bug, as the pagination control is an internal property and external interaction with it is either expected nor supported. Closing this issue as such.
