### ISSUE TITLE
do I need  another jsfile to make Rlfrtip work?

### ISSUE THREAD

**Issue by ilovezy** [DataTables/DataTables#618]
my js is like this 
$(document).ready(function() {
        $('#example').dataTable({
            "dom": 'Rlfrtip'
        });
    });

but I can't drag the colums 
I saw the source code on your webpage
![qq 20150811153621](https://cloud.githubusercontent.com/assets/8774988/9192570/c16e9b6a-403e-11e5-8e8c-6e67c2ccf5e0.png)
do I need include some other js files?

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.

The code looks fine as far as I can see from them image. We would need a test case.

**Comment by MrGeneric** [comment]
@ilovezy, You can download the colReorder plugin on this page: https://datatables.net/download/index

**Comment by ilovezy** [comment]
thanks, really helps,I find them
