### ISSUE TITLE
when usiing colReorder problem happened

### ISSUE THREAD

**Issue by ilovezy** [DataTables/DataTables#620]
hei.I use colReorder,
when I drag a column over someother colums,
this happend, and the colReorder did not work fine

![qq 20150813210217](https://cloud.githubusercontent.com/assets/8774988/9250332/a8b901f2-41fe-11e5-9095-c6b1d5846c5e.png)

in the js file the problem is here

![qq 20150813210248](https://cloud.githubusercontent.com/assets/8774988/9250342/b3fae5b2-41fe-11e5-811a-5fa2eef17bb6.png)

how can I fix that

**Comment by DataTables** [comment]
Can you link to a page showing the issue please so it can be debugged.

**Comment by ilovezy** [comment]
help me please!
I need this first columns width become more, so that the fonts in this could show in one line
help!!!!!

![qq 20150814131443](https://cloud.githubusercontent.com/assets/8774988/9267727/745f6152-4286-11e5-8aba-8a818e1eaa1d.png)


I use fixedColumns and my js looks like this

$(document).ready(function() {

        // var height = $(document.body).height() / 3

        var table = $('#example').DataTable({
            // "dom": 'Rlfrtip',
            "ordering": false,
            "info": false,
            responsive: true,
            fixedHeader: true,
            paging: false,
            scrollY: '800px',
            scrollX: '100%',
            // scrollCollapse: true,
        })

        new $.fn.dataTable.ColReorder(table)
        new $.fn.dataTable.FixedColumns(table)
    })

**Comment by ilovezy** [comment]
I tried make the  scrollX to 300%, it look better

 
![qq 20150814134813](https://cloud.githubusercontent.com/assets/8774988/9267968/208af3d4-428b-11e5-8f76-b152d39e0753.png)


what did this scrollX mean ?

**Comment by DataTables** [comment]
I would be happy to help. In my previous reply I asked for a link to a page showing the issue so I can debug it and offer the help you are asking for. Please provide that link. If you can't host the page yourself, use JSFiddle or similar to create a test case.

You might also want to consider adding the class `nowrap` to your DataTable to force no wrapping in the cells.

**Comment by ilovezy** [comment]
thanks, I‘m trying, I will try jsFiddle, not familiar with it,and something wrong will my host because of wordpress

**Comment by DataTables** [comment]
Thanks for your reply. No problem - I can wait for the test case. I'll leave this bug open for a bit so you can add one when one is ready.

**Comment by ilovezy** [comment]
hei, I move to the forem now, by the way this is amazing,I mean really cool

**Comment by DataTables** [comment]
Can you link to the thread please?

**Comment by ilovezy** [comment]
oh, not this problem yet, another problem, I need delete a column when click an icon, and it looks not good
about this I will move too,wait a few time please

**Comment by DataTables** [comment]
Okay thanks - please ensure that you link to test cases when you post in the forum. I'm closing this issue now.

**Comment by ilovezy** [comment]
where can I have some cdn, I can't find like fixedColumn.js on bootstrap CND, there is only dataTable.js file

**Comment by DataTables** [comment]
The files are all listed here: http://cdn.datatables.net/fixedcolumns/3.1.0/#Files

**Comment by ilovezy** [comment]
thanks, I forgot that, ouch
