### ISSUE TITLE
row().invalidate() - row.getAttribute is not a function at jquery.dataTables.js:1659

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#623]
Getting the error below when using jQuery DataTables 1.10.8. 

> TypeError: row.getAttribute is not a function at jquery.dataTables.js: 1659: 11

See [this jsFiddle](https://jsfiddle.net/htnanyx2/) for demonstration of the error.

The example above works correctly when using DataTables 1.10.7.

**Comment by mpryvkin** [comment]
Seems like `_fnGetRowElements` call in `_fnInvalidate` function passes internal row object as an argument instead of element node stored in `nTr` property which most likely wasn't noticed until you added this code to `_fnGetRowElements`.


		// Read the ID from the DOM if present
		var id = row.getAttribute( 'id' );
		if ( id ) {
			_fnSetObjectDataFn( settings.rowId )( d, id );
		}

**Comment by DataTables** [comment]
Bother. Thanks for pointing this out. I'll commit the fix tomorrow.

**Comment by DataTables** [comment]
[Fixed committed here](https://github.com/DataTables/DataTablesSrc/commit/7b14969092) and is synced to this repo. The nightly isn't up to date yet as I need to do some work on that build process... But you can pull it from this repo if you like.

The reason why `row.nTr` isn't quite right for all cases is that the `row` can be passed in as either a DataTables internal row model object, or a TR elements. I should really try to normalise that, but it is useful for handling the deferred rendering Ajax case.

Thanks for letting me know about this!

**Comment by mpryvkin** [comment]
I understand, thanks for explaining and fixing it so quickly.
