### ISSUE TITLE
Idea on how to improve datatable performance when loading data from html

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#624]
I noticed that when datatable loads data from html, the table's html is cleared and all the rows are generated from scratch.

Isn't this a waste of resources and performance? Can this be avoided while still caching the nodes?

**Comment by DataTables** [comment]
Hi,

Could you clarify for me why you think a new element is created, as this is not the case. The original TR/TD rows and cells are retained and used if DataTables is read from a DOM source.

This trivial example shows that to be the case: http://live.datatables.net/japulenu/1/edit .

**Comment by jamezamm** [comment]
Thanks for replying... My bad. I wrongly understood the code, since it was firing a created cell and row callback.

**Comment by DataTables** [comment]
Ah yes, no problem. I can see how that would be confusing. I'll add a note to the documentation to qualify that. It is really "created a DataTables row". Thanks for the feedback.
