### ISSUE TITLE
I need delete a column

### ISSUE THREAD

**Issue by ilovezy** [DataTables/DataTables#625]
hei , I use jsfiddle now, and my boss need a icon to delete one line on every th cell
so I add an icon,and when I click one icon, it looks not very good,

![qq 20150817105319](https://cloud.githubusercontent.com/assets/8774988/9297482/b47006e0-44d2-11e5-9915-fac89953d6fa.png)

look up here please, I need your help,It's with jquery
seems not this plugins problem,but help me please

I think it because the thead's width is calculate by js
drag the slidebarX you can see this
![qq 20150817113727](https://cloud.githubusercontent.com/assets/8774988/9297583/5e3f5a1c-44d4-11e5-9e03-9377e1811b89.png)

http://jsfiddle.net/icehota/jm4fo3a2/

**Comment by DataTables** [comment]
I would suggest reviewing [this example](http://editor.datatables.net/examples/simple/inTableControls.html). Even if you don't use Editor the same principle applies.

In future, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums.
