### ISSUE TITLE
scroller plugin is not responsive

### ISSUE THREAD

**Issue by swainsoftware** [DataTables/DataTables#626]
Hello lads, some great work done on tables! Cheers!

I came across an issue with scroller plugin. Once I implement scroller or scroller with any other plugin (like responsive) then table header becomes not responsive. Once user changes container width, then he has to click on column header in order to recalc headers widths. 

like in your example online:
1. build a table in html (or by angular builder or any other way)
2. datatables creates a header for the table with column names from ajax response
3. scroller creates a 2nd instance of a table with copy of a header but height 0px, and body from ajax response
4. visible header (from first table) is not responsive, but it controls sort order of visible tbody
5. invisible header (from second table) is responsive

so in case I want to use scroller with responsive plugin (fantastic combo!) there is a bad header behavior..

**Comment by DataTables** [comment]
Could you link to an example showing the issue please?

**Comment by swainsoftware** [comment]
got it sorted, cheers!
