### ISSUE TITLE
Nightly Js files are outdated & Update Nuget package

### ISSUE THREAD

**Issue by strang91** [DataTables/DataTables#631]
Ex: http://datatables.net/download/build/nightly/jquery.dataTables.js is pointing to 1.10.8-dev
Ex: http://datatables.net/download/build/dataTables.colReorder.nightly.js is pointing to 1.1.4-dev

And could you please update the **jquery.datatables** nuget package to the most recent version 1.10.8

**Comment by DataTables** [comment]
Hi,

I'm in the process of changing how the nightly builds work. They will be out of date for a short while as I make progress with that.

The Nuget package is not published by myself - you'd need to contact whoever the author of that package is.

**Comment by dlandis** [comment]
Hi @DataTables,

Is the build change going to result in an update to https://www.npmjs.com/package/datatables as well? I noticed that was out-of-date too.

Thanks

**Comment by DataTables** [comment]
Oops - yes. Published now :-)

**Comment by DataTables** [comment]
Information on the nightly files is [available on the DataTables site now](http://datatables.net/download/nightly). The old `/download/build` files will no longer be updated.
