### ISSUE TITLE
Example for Bootstrap tabs is Wrong

### ISSUE THREAD

**Issue by dlandis** [DataTables/DataTables#632]
The example [here](https://www.datatables.net/examples/api/tabs_and_scrolling.html) has this code:

    $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
        $.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
    } );

I go an error running that and had to change it to the following:

    $('a[data-toggle="tab"]').on('shown.bs.tab', function(){
        $.each( $.fn.dataTable.tables({visible: true, api: true}), function(_i, table){
            $(table).DataTable().columns.adjust();
	});
    });

**Comment by DataTables** [comment]
What was the error and what version of DataTables are you using. The code in the example requires 1.10.8 - the current release.

**Comment by dlandis** [comment]
I was using 1.10.7. Error was something about `columns` not a valid property. The result of the `$.fn.dataTable.tables( {visible: true, api: true} )` was just an array of DOM elements I believe.
