### ISSUE TITLE
DataTables Core Bug when ColReorder is enabled

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#637]
Test Case: http://live.datatables.net/xijeqige/2/edit

In the example above, I'm adding a text box to the cell through the **createdCell** callback and then checking if the row data (array or object) has changed.

Steps to reproduce the issue:
* Change the value of any text box. 
* In the console, one can see that the row data still has the **value** and **not the text box html**.
* Reorder any column by dragging the column into a different position.
* Change the value of any text box. 
* In the console, one can see that the row data now has the **text box html** and **not the value**. 

Please note that this issue appears only when reordering a column.

**Comment by DataTables** [comment]
Thanks for posting this - I'm going to move it to ColReorder as it isn't a DataTables issue, but rather ColReorder.

[New issue](https://github.com/DataTables/ColReorder/issues/42).
