### ISSUE TITLE
sorting_disabled class is missing 

### ISSUE THREAD

**Issue by dranovsk** [DataTables/DataTables#639]
Setting 'ordering' option to false adds 'sorting_disabled' class to header cells, but I couldn't find corresponding class in any of the css files.

should it be 
.sorting_disabled {
    padding-right: 8px !important;
}

Also, can class name be changed to  sorting-disabled.

Thanks a lot!!!

**Comment by DataTables** [comment]
Hi,

[This little test case](http://live.datatables.net/fuvebafe/1/edit) shows that with `ordering: false` the table header cells have `padding: 10px 18px` by default. Can you tell me why you think they should have the padding right you propose?

> Also, can class name be changed to sorting-disabled

I've love to update DataTables' classes, full and proper BEM support. However, that would be a breaking change, so it won't happen until v2 and even then I'll might introduce a backwards compatibility module to restore the old style for folks would want to continue using it.

I am starting to think about v2 now though - it is no longer just a pipe dream :-).

**Comment by dranovsk** [comment]
Love to here about v2 and really love new Buttons.

Issue I'm having with sort disabled, but right padding on the header cells didn't change - 30px allocated for sort icons,

I'm using 1.10.8 with bootstrap integration.

Thank you!

**Comment by DataTables** [comment]
Thanks for letting me know about this. Addressed now :-)
