### ISSUE TITLE
ajax.json() is always undefined when using ajax function

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#640]
When using the ajax function option, ajax.json() is undefined. (Test Case: http://live.datatables.net/yofadage/3/edit)
This is not the case when using ajax string option (url). (Test Case: http://live.datatables.net/ratoromi/1/edit)

**Comment by DataTables** [comment]
I've [added a note to the documentation](https://github.com/DataTables/DataTablesSrc/commit/4a86361bc472) that states this is the case for the moment. I might try to define a proper API for this in future.

You can add `settings.json = json;` in [the callback](http://live.datatables.net/yofadage/4/edit), but the settings object is considered to be private, so it is possible this might break between releases (although I think in this case probably unlikely).

**Comment by jamezamm** [comment]
Noted. Thanks.
