### ISSUE TITLE
cell().invalidate() strange behaviour

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#643]
I came up with a solution on how to filter and order table containing `select` and `input` elements, see [this answer](http://stackoverflow.com/a/32102854/3549014).

However I wanted to use the code below to invalidate cell data

    $('tbody select, tbody input', table.table().node()).on('change', function(){
        table.cell($(this).closest('td')).invalidate();
    });

But this code produces warning after you change any `input` or `select` and then sort or search the table.

> DataTables warning: table id=example - Requested unknown parameter '1' for row 2. For more information about this error, please see http://datatables.net/tn/4

This code works fine but it invalidates the entire row which I would rather avoid to affect performance.

     $('tbody select, tbody input', table.table().node()).on('change', function(){
         table.row($(this).closest('tr')).invalidate();
     });

See [this jsFiddle](https://jsfiddle.net/wqpqu7u5/) for demonstration.

**Comment by DataTables** [comment]
If you use the 1.10.9-dev nightly version (which is in this repo) the issue has been [resolved](https://jsfiddle.net/wqpqu7u5/1/).

In future, 
Per the [contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums.

**Comment by mpryvkin** [comment]
This wasn't support request, but rather issue with the code similar to #623 I reported earlier. Seems like [this is a commit](https://github.com/DataTables/DataTables/commit/e7e439dd0a8a3cda23e88bd33935ac09764e683c) that fixed the issue.
