### ISSUE TITLE
[BUG] Buttons extension: "Direct insertion" with Ajax population

### ISSUE THREAD

**Issue by temuri416** [DataTables/DataTables#646]
Hi,

"*Direct insertion*" feature at https://datatables.net/extensions/buttons/ does not work if DataTables is using AJAX to fetch data.

```js

var DT = $('#example').DataTable( {
        "ajax": '../ajax/data/arrays.txt'
    } );

DT.buttons().container().appendTo( $('#buttonsContainer') );
```

No buttons are inserted anywhere.

Thanks!

**Comment by DataTables** [comment]
You need to use [`initComplete`](http://datatables.net/reference/option/initComplete) since the Ajax call makes the initialisation asynchronous.

In future, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums.

**Comment by temuri416** [comment]
Sorry for the confusion. I did not think this of support request, it look like a bug.

One of the reasons was that I tried every single event from

http://datatables.net/reference/event/

but I could not find the one that worked. And `initComplete` event isn't mentioned there.

Thanks!

**Comment by DataTables** [comment]
It isn't an event - it is an initialisation callback. The `init` event which is listed in the documentation could be used in its place if you wanted to use events.

**Comment by temuri416** [comment]
so then.. there *is* a bug, because inside the `init` event handler `DT.buttons().container()` was empty.

**Comment by DataTables** [comment]
Can you give a link to a test case showing the issue please.

**Comment by temuri416** [comment]
It would take too long to set up a jsFiddle for you, but here are the steps to reproduce.

I used https://github.com/DataTables/DataTables/blob/master/examples/data_sources/ajax.html as starting point.

- add to scripts:

```html
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.0.1/js/dataTables.buttons.min.js"></script>
```
- add somewhere in the document body:

```html
<div id="buttons" style="background:wheat"></div>
```

- use this JS code to init:

```js
$(document).ready(function() {
    var DT = $('#example').DataTable( {
        "ajax": '../ajax/data/arrays.txt',
        buttons: [
            {
                extend: 'colvisGroup',
                text: 'Office info',
                show: [ 1, 2 ],
                hide: [ 3, 4, 5 ]
            },
            {
                extend: 'colvisGroup',
                text: 'HR info',
                show: [ 3, 4, 5 ],
                hide: [ 1, 2 ]
            },
            {
                extend: 'colvisGroup',
                text: 'Show all',
                show: ':hidden'
            }
        ],
        "initComplete": function(settings, json) {
            // DT.buttons().container().appendTo( $('#buttons') );
            $(this).DataTable().buttons().container().appendTo( $('#buttons') );
          }
    })
/*    .on( 'init.dt', function () {
            // DT.buttons().container().appendTo( $('#buttons') );
            $(this).DataTable().buttons().container().appendTo( $('#buttons') );
    });*/
} );
```

First I've tried `init.dt` and nothing was rendered into `div#buttons`. `DT.buttons().container()` and `$(this).DataTable().buttons().container()` are always empty.

Next, I tried `initComplete`, which did nothing either. And `container()` was empty as well.

Hope this helps!

Thanks.

**Comment by DataTables** [comment]
Thanks for the info. I'll try to find some time in the next couple of weeks to set up a test case myself.

**Comment by senritsu** [comment]
can confirm this issue using DataTables 1.10.9

inside a callback function called from the `initComplete` option or the `init.dt` event, `table.buttons().container()` is an empty selector, even if the `buttons` option was specified during DataTables construction.

**Comment by DataTables** [comment]
It appears to work okay in this test case: http://live.datatables.net/pehamulo/1/edit

It isn't working in the code from @temuri416 above because there is no `B` option in the `dom` property. That results in Buttons being initialised only when the `init` event occurs, which is immediately after the `initComplete` callback.

**Comment by mpryvkin** [comment]
In [this example](https://datatables.net/extensions/buttons/examples/styling/bootstrap.html) you specifically state that the recommended way with Bootstrap styling is avoid using `dom`. The same is also stated [here](https://datatables.net/extensions/buttons/#Direct-insertion)

> It is possible to use the `dom` option to insert the buttons like in the DataTables styled examples, but the default `dom` option used for Bootstrap styling is quite complex and would need to be fully restated.

This is the reason people experience this error because most are using Ajax sourced data instead of HTML sourced data and therefore need to use `initComplete`.
