### ISSUE TITLE
Column.Render called more than once on each cell

### ISSUE THREAD

**Issue by strang91** [DataTables/DataTables#648]
Column.Render is being called more than once per cell. Same as thread https://github.com/DataTables/DataTables/issues/638 but on Column.Render.

Test Case: http://live.datatables.net/wolaxowo/1/edit (Result in console)

**Comment by DataTables** [comment]
This is fully expected an intentional. DataTables will all the render method multiple times - one of each of the [orthogonal data types](http://datatables.net/manual/orthogonal-data) it uses and potentially more often for other aspects (Buttons export for example).

**Comment by strang91** [comment]
When **type == 'display'** it is still called more than once. New Test Case: http://live.datatables.net/wolaxowo/2/edit

**Comment by DataTables** [comment]
This no longer happens with the latest nightly version: http://live.datatables.net/wolaxowo/3/edit . It was one step behind from the fix in #638.

**Comment by strang91** [comment]
Fix confirmed. Thanks.
