### ISSUE TITLE
Add note about dom option in documentation for Bootstrap styling 

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#649]
It's not documented anywhere that Bootstrap styling modifies default `dom` option which causes a lot of confusion when you try to change it, see [this StackOverflow question](http://stackoverflow.com/questions/32252616).

I believe it should be added on [`dom` - Default](https://datatables.net/reference/option/dom#Default) page, similar to note about jQueryUI. Something like:

>The default is changed to be 
`"<'row'<'col-sm-6'l><'col-sm-6'f>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'i><'col-sm-7'p>>"`
 when Bootstrap styling is used.

It may be beneficial to also have this note on the following pages:
* http://datatables.net/manual/styling/bootstrap
* http://datatables.net/examples/styling/bootstrap.html

**Comment by DataTables** [comment]
Thanks for the suggestion - [fixed here](https://github.com/DataTables/DataTablesSrc/commit/6557cfcebf7b7ab26c3d) and will be deployed to the site soon - probably tomorrow now.

I've not updated the other two pages yet, but I will look into that.

I'm getting closer and closer to just pulling the trigger and starting 1.11 (possibly to be called v2) development by renovating this option - it is a pita for everyone!
