### ISSUE TITLE
DataTables Api Problem: Selecting a cell by node

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#653]
Selection of a cell by node (**api.cell(td)**) does not work if the cell is not currently in the DOM (Ex: Cached Node).
```javascript
row = el.parentNode._DT_RowIndex;
```
 The selection does not work because the code above is trying to call its parentNode (which in this case is undefined). 

Can the property *_DT_RowIndex* be stored with the *el* as well as with its parent, so as to avoid this scenario?

Test Case: http://live.datatables.net/gasebeta/1/edit

In this test case, the Name column was hidden and trying to select a cell under this column with the cached node.

**Comment by DataTables** [comment]
Thanks for posting this. I've implemented a slightly different method. not as efficient for this particularly use case, but I think overall it requires less disruptive changes.

**Comment by jamezamm** [comment]
Thanks for the quick fix.

**Comment by jamezamm** [comment]
There's still another scenario where this fails. 

If the hidden cached cell was appended to a different TR Element (ex: A child row), *el.parentNode* will **not be undefined**, but *el.parentNode._DT_RowIndex* will be undefined.

Adding an extra check for el.parentNode._DT_RowIndex will do the trick.

**Comment by DataTables** [comment]
A "hidden cached cell"? Do you mean the td cell itself? You are moving that to a different location in the DOM?

**Comment by jamezamm** [comment]
Yes the td cell itself. And yes it is being moved to a different location
.

**Comment by jamezamm** [comment]
Test Case: http://live.datatables.net/musigeci/2/edit

In this test case, the cached td cell (the column is hidden) was used in the child row. 

To see the result in the console, Click a row and change the value of the text.

**Comment by DataTables** [comment]
Thanks for the test case. That's not an expected interaction - DataTables may or may not correctly reinsert the element into the row at a later time.

It won't just be this part that is broken with this interaction - there will be several other changes required.

I need to decide if this is something I want to support in DataTables. My initial thought is no, it might be a performance hit and add additional code. But I'll have a think about it and what would be involved.

**Comment by strang91** [comment]
I'm having a similar problem regarding cell selection by node.

This can easily be fixed without any major changes by storing the cell index (Both column & row index) in a private property with the cell node (td). Just like it is being done with *_DT_RowIndex* on the row node.

There are mainly 3 function which will have to be amended:

* **_fnCreateTr** - First, where the indexes will have to be registered on the cell
* **row().remove()** or **rows().remove()** - Whenever a row is deleted, update the row part of the cell index.
* **__cell_selector** - Use the cell index, in the cell node's private property, to retrieve the cell by node.  

Apart from fixing this issue, this will also benefit from a quick retrieval of the cell. (No need to traverse the array to find the row index. Referring to  https://github.com/DataTables/DataTables/commit/648726b19e3e846f5b4779ea25f883cf180ed779)

**Comment by DataTables** [comment]
Thanks. Could you link to a test page showing the issue and I'll take a look when I get back from my current travels next week.

**Comment by strang91** [comment]
Thanks for replying. 

What I'm trying to achieve is similar to jamezamm's test case: http://live.datatables.net/musigeci/2/edit
(You can use the same test case)

i.e.: Selecting a cell by node which is now appended to a child row (Not in original row)

If you solve the problem the way I described in the comment above, will kill two birds with one stone.

**Comment by strang91** [comment]
This is what I changed in the script:

**_fnCreateTr** Line starting at 1750
```javascript
function _fnCreateTr ( oSettings, iRow, nTrIn, anTds )
{
    // ...
    nTd = nTrIn ? anTds[i] : document.createElement(oCol.sCellType);
    nTd._DT_CellIndex = { row: iRow, column: i }
    // ...
}
```

**rows().remove(), row().remove()** Line starting at 7884
```javascript
_api_registerPlural( 'rows().remove()', 'row().remove()', function () {
    // ...
    // Update the _DT_RowIndex parameter on all rows in the table
    for ( var i=0, ien=data.length ; i<ien ; i++ ) {
        if (data[i].nTr !== null ) {
            data[i].nTr._DT_RowIndex = i;
        }

        if (!data[i].anCells) continue;

        for (var j = 0, jen = data[i].anCells.length; j < jen; j++) {
            if (data[i].anCells[j]) {
                if (data[i].anCells[j]._DT_CellIndex) {
                    data[i].anCells[j]._DT_CellIndex.row = i;
                }
            }
        }
    }
    // ...
} );
```

**__cell_selector** Line starting at 8551
```javascript
var __cell_selector = function ( settings, selector, opts )
{
    // ...
    // Selector - jQuery filtered cells
    return allCells
        .filter( s )
        .map(function (i, el) {	
            return {
                row: el._DT_CellIndex.row,
                column: el._DT_CellIndex.column
            };
         })
        .toArray();
    // ...
}
```

This solves: 
* Selecting a cell by node that does not exist in DOM (Ex; Column is hidden)
* Selecting a cell by node that is appended to another tr element (Ex: Appended to child row) 

You should double check this solution, as I might not be seeing the whole picture.

**Comment by DataTables** [comment]
Thanks for the reply and extra details. As I noted above I'm not yet sure that I want to support the ability to move cells around the DOM in DataTables - I think it will add a number of additional check that need to be made (such as in the draw function - does the cell need to be drawn in or not - or more generally, under what conditions should be be reinserted into the master table - perhaps there should be a new API method). At the moment I don't think I wish to support this interaction as I think it adds a lot of scope of potential issues - however, it is something I will keep in mind for future development as I can of course see that it could be useful.

**Comment by strang91** [comment]
Thanks for replying. 

> I'm not yet sure that I want to support the ability to move cells around the DOM in DataTables - I think it will add a number of additional check that need to be made (such as in the draw function - does the cell need to be drawn in or not - or more generally, under what conditions should be be reinserted into the master table - perhaps there should be a new API method).

I think you're over complicating things, I'm not asking for functionality to move the cell around or to be automatically inserted back, but just so that the cell selection still work even though the cell has been moved. 

Still **_DT_RowIndex** is saved with the row node for fast lookup, why not do the same for the cell node for fast lookup as well *(as this will solve the above problem)*?

**Comment by DataTables** [comment]
Actually, I think I've over simplified the issue in my above comments. Consider for example if the table were destroyed, who is responsible for cleaning up the event handlers and removing the cell if it has been moved outside of the DataTable.

The more I think about this, the more I am convinced that supporting the ability to have cells moved out of the table by external processes is not something I wish to support in DataTables.

**Comment by strang91** [comment]
I'm not sure we are on the same wave length. Moving the cell around together with its associated problems is my concern and I'm not asking you to cater for it. 

Storing the index with the cell node will not create any side effects to datatables. This way will not only solve my problem but you will also benefit from an increased performance *i.e. Cell fast lookup*.

I hope I'm making myself clear enough in view of this fix being committed.

**Comment by DataTables** [comment]
The selector performance is already quite fast at this point because the cell is a child node of the row. I haven't encountered any issues with this as of yet, so I'm reluctant to introduce additional code for something that I don't currently perceive to be an issue. I reserve the right to be wrong and change my mind in future though :-).

**Comment by strang91** [comment]
Yes it is fast, **if the cell is not hidden** *i.e. when parentNode is null*.

Quoting your comment, in view of fix https://github.com/DataTables/DataTables/commit/648726b19e3e846f5b4779ea25f883cf180ed779 :

> I've implemented a slightly different method. not as efficient for this particularly use case

But you already know that storing the index with the cell node will be more efficient. :-)

**Comment by jamezamm** [comment]
@strang91 has a point. Imagine a possible worst case scenario where there are 10,000 rows, 10 columns and calling api.cell(td) on a hidden cell in a 3x loop. 

The code shown below will loop through ((10,000 rows * 10 cols) for 3 times). This definitely has a major performance issue. 

**Storing the cell index on the cell node is definitely an easy and efficient way of selecting a cell** and the greatest part is that it requires small changes with no repercussions on the datatables itself.

Plus I can confirm that @strang91's change works. Test Case: http://live.datatables.net/gasebeta/6/edit

```javascript
if ( el.parentNode ) {
    row = el.parentNode._DT_RowIndex;
}
else {
    // If no parent node, then the cell is hidden and we'll need
    // to traverse the array to find it
    for ( i=0, ien=data.length ; i<ien ; i++ ) {
        if ( $.inArray( el, data[i].anCells ) !== -1 ) {
            row = i;
            break;
        }
    }
}
```

**Comment by DataTables** [comment]
Yup all good points. I'll consider it for a future revision.
