### ISSUE TITLE
Unable to load a table from a separate HTML file

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [DataTables/DataTables#655]
I'm trying to use datatables with a table that lives in a separate HTML file without luck. 

Consider the minimal example below. When testing it on the browser I get:

>  `DataTables warning: Non-table node initialisation (DIV). For more information about this error, please see http://datatables.net/tn/2`). 

Why?

### `index.html`
``` html
<html>
<head>
  <link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
</head>
<body>
  <div id="table"></div>
  <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
  <script>
    $(function(){
    $("#my_table").load("table.html"); 
    });
  $(function(){
    $("#table").dataTable();
  })
  </script>
</body>
</html>
```

### `table.html`
``` html
  <table id="my_table">
    <thead>
      <tr><th>Sites</th></tr>
    </thead>
    <tbody>
      <tr><td>SitePoint</td></tr>
      <tr><td>Learnable</td></tr>
      <tr><td>Flippa</td></tr>
    </tbody>
  </table>
```

**Comment by DataTables** [comment]
Per the contributing document - please ask support requests int he DataTables forums in future.

It issue here is just like the error says - the table is being initialised on a non `table` element. The DataTables initialisation should be `$('#my_table').DataTable()` and it should happen in the callback for when table.html has been loaded.
