### ISSUE TITLE
npm package doesn't include the bootstrap files

### ISSUE THREAD

**Issue by jmwohl** [DataTables/DataTables#656]
We're using the bootstrap flavor of DataTables, but the bootstrap-related files aren't include in the npm package even though they are in the repo.

Is there any reason not to include the rest of the DataTables files in the npm package? It wouldn't affect users who just want to do `require('datatables')`, but would be helpful for users like me who are using gulp/browserify to do more elaborate builds but still want to keep up-to-date with DataTabes releases and use npm as a package manager — I'm trying to get rid of bower entirely from toolset (the bower package includes these files).

**Comment by DataTables** [comment]
The reason not to include them directly is because it is difficult to include multiple options (Bootstrap, or Foundation, or ...) for the package managers. To resolve that I'm doing to create a distribution repo for each styling option that DataTables supports. I hope to do that in the next couple of weeks.

**Comment by jmwohl** [comment]
Got it, that makes sense — will keep an eye out for the bootstrap-specific distro.

For now I'll just use the latest release tar.gz as the npm dependency rather than the datatables package.

**Comment by timwis** [comment]
For what it's worth, if you included the .js and .css files for all 3 (foundation, bootstrap, jqueryui) I don't think it would be very inconvenient or much different from other repos. It's rather expected that using `npm install` to include a dependency will pull in some files that aren't used (for example, source files in addition to the compiled/minified dist files). For now I'll just do what @jmwohl said and use the tar.gz.

**Comment by tgfisher** [comment]
Ran into the same issue today. I'm currently using the .tar.gz. I agree with @timwis that including them in the main repo wouldn't bother me even if I wasn't planning on using them.

**Comment by DataTables** [comment]
I've published proper NPM and Bower packages for DataTables now - which are [described in this blog post](http://datatables.net/blog/2015-11-09) and has proper support for the styling options.

Sorry for not updating this bug - completely slipped my mind.
