### ISSUE TITLE
Header not scrollable.

### ISSUE THREAD

**Issue by Gersee** [DataTables/DataTables#657]
I use datatables with bootstrap3. If there are too many columns I want to have an horizontal scrolling. It works very fine, but only for my table-body. My table-head is always full shown and breaks out of my surrounding div. The body is scrollable and inside my surrounding div. As example I see all 10 columns of the head but only the first 5 columns of the table body - which I can scroll to see all columns.

$('#datatableid').dataTable( {
  "bProcessing": true,
  "aaData": dataSet,
  "scrollX": true,
  "fixedHeader": true
});

Attribute dataSet contains the correctly displayed data. If I change the options like "fixedHeader":false there isn't any change to my problem.

**Comment by DataTables** [comment]
FixedHeader is not compatible with scrollX at this time - see the [compatibility table](http://datatables.net/download/compatibility).

**Comment by Gersee** [comment]
Thanks for this response, but like I wrote the problem is not the fixedHeader: 
"change the options like "fixedHeader":false there isn't any change to my problem."

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by Gersee** [comment]
<a href="http://www.directupload.net" target="_blank"><img src="http://fs2.directupload.net/images/150907/5m2dspdw.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by DataTables** [comment]
Can you link to a page showing the issue so I can debug it please.

**Comment by Gersee** [comment]
I'm afraid not (and I know it's very difficult to get help without an live-page). Hope there is an idea without a debugging site. The table has correct content and it's correctly displayed if all columns can be displayed at once. Only if my columns are too big there is this issue.
    
This is the html-Snippet:
    <div class="panel panel-default">
		<div class="panel-heading clearfix">
		   	<strong>Results</strong>
		</div>
		<div class="panel-body">
			<div id ="tableForData">
			</div>
		</div>
	</div>

The datatable part (without fixedHeader):
  $('#datatableid').dataTable( {
    "bProcessing": true,
    "aaData": dataSet,
    "scrollX": true,
    "fixedHeader": false
  });

This is the first line of table-definition:
  <table cellpadding="0" cellspacing="0" border="0" class="display" id="datatableid"><thead><tr>

**Comment by DataTables** [comment]
I'm afraid there is very little help I can offer without being able to debug a page showing the issue. I'll try to make some time myself in the next couple of weeks to product a page that shows the issue, but I can't promise anything. If you can use JSFiddle or http://live.datatables.net to show the issue, that would be very useful.

**Comment by nddery** [comment]
Here's an example on JSFiddle where you can see the problem: http://live.datatables.net/pikifuqu/1/edit

Trying to scroll the table while your cursor is on the table `scrollHead`, it won't work. For it to work, you need to have your cursor over the table `scrollBody`.

Hope this helps!

**Comment by nddery** [comment]
An easy workaround is to add the following CSS (assuming that `.dataTables_scrollHead` is 50px tall):

```css
// `.dataTables_scrollHead` is 50px tall
.dataTables_scrollBody {
  padding-top: 50px;
  margin-top: -50px;
}
```

However, if the columns change width, which in turn affect height of the header row, this code won't update..

**Comment by DataTables** [comment]
Thanks for the test case - I'm not sure that it shows the original issue, however, yes I can see that the header does not scroll the table. Interestingly this is the first time this has been raised, so I'm not going to commit a fix for it just yet, but will look for additional feedback on this one.

**Comment by Gersee** [comment]
Thanks for your support @nddery. But it's not the original issue. Your example shows the problem that the header isn't scrollable if I select it. Like you can see on the screenshot the header in my case breaks out of the design and is shown in the full length while the body is scrollable and fits to the design.
However I tried your workaround but for my issue it doesn't work.

**Comment by nddery** [comment]
@DataTables I've opened an issue [in the forums](https://datatables.net/forums/discussion/30217/header-not-scrollable-when-using-scrollx-true) for the issue I've mentioned.

@Gersee Have you tried removing your own CSS from the equation ? Sounds like a CSS issue.

**Comment by Gersee** [comment]
I solved this problem. It was like you both assumed a wrong css-setting. Went through all linked files and found in an *external plug-in* a css part with:

        .dataTables_scrollHead { 
          overflow: visible !important; 
        }

After deleting this part the problem was gone. Thanks for your help!

**Comment by jbarnicle** [comment]
I am having this same issue as well.
