### ISSUE TITLE
dt.order fires also dt.search

### ISSUE THREAD

**Issue by the86freak** [DataTables/DataTables#658]
the dt.order event also fires a dt.search event.

example:
https://datatables.net/examples/advanced_init/dt_events.html

I would expect that a order-event only fires a dt.order event, but not both.
Or am I wrong? :-)

**Comment by DataTables** [comment]
You aren't wrong as such, but this is just how DataTables operates. A sort will always trigger a search because of how DataTables works internally. I may separate them eventually, but don't currently have plans to do so.
