### ISSUE TITLE
on firefox, the copy, excel, these buttons did't showup

### ISSUE THREAD

**Issue by ilovezy** [DataTables/DataTables#660]
hei there,
I need these button showup on the right of the page, on chrome and IE, It works good.
but on firefox, these buttons did not showup.

Is it because of firefox disable the flash?

**Comment by DataTables** [comment]
Possibly. it is impossible to say without a test case. Please link to one. Also, in future, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums.

**Comment by ilovezy** [comment]
yeah, when I install flash, It works well, close this, next time I will move to the forums, sorry

**Comment by DataTables** [comment]
Worth noting that {buttons](http://www.datatables.net/extensions/buttons/examples/html5/index.html) has an HTML5 export option that doesn't require Flash.
