### ISSUE TITLE
Do not bind click.DT, keypress.DT, selectstart.DT to active paginate_button 

### ISSUE THREAD

**Issue by dranovsk** [DataTables/DataTables#662]
Hello Allan,

Is it possible to skip active paginate button when binding click.DT, keypress.DT, selectstart.DT events.

Currently i have to unbind them in the fnDrawCallback to avoid extra draw.

Thank you!

**Comment by DataTables** [comment]
I've just put this little demo together to test this issue: http://live.datatables.net/hamovefo/1/edit .

If you click on the active paging button it doesn't trigger a draw.

Old versions of DataTables did have that issue - it was fixed about half way through 1.10.x I think.

**Comment by dranovsk** [comment]
Sorry, forgot to mention bootstrap integration causing it in my case.

Goes into dataTables.bootstrap.js clickHandler, which calls api.page( e.data.action ).draw( 'page' );

Thanks

**Comment by DataTables** [comment]
Finally fixed now :-)
