### ISSUE TITLE
A new event where extension authors can edit the options passed to datatables

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#663]
Has been moved from https://www.datatables.net/forums/discussion/30115 so it can be easily tracked.

There should be a new event (Ex: **preOptions**) that fires before **preInit** so that extension authors can change options, such as **columns.className**, before being passed & processed by dataTables.

**Comment by DataTables** [comment]
Thanks for suggesting this. Could you give an example of why this would be useful - you noted in the forums about the class name, but I'm not clear on the use case.

Reason I ask, is that I'm not sure about giving the option for software to change values that the user has specified. Imagine for example that they user specifies `info: false`, but the library makes it `info: true`. Is that a bug? I'm not sure :-)

**Comment by jamezamm** [comment]
For example: 
I'm trying to make a simple row grouping plugin/extension and I need: 

* a fixed sort/order on the column being grouped by, and (orderFixed)
* add a class to the cells belonging to the column (columns.className)

**Comment by DataTables** [comment]
Could the end user not simply specify `columns.grouping: true` on the column that should be grouped and also specify a class name if they want it? Could you show me the initialisation you are proposing? I'm very wary of adding this ability for the reason I stated above :-)

**Comment by jamezamm** [comment]
> Could the end user not simply specify columns.grouping: true on the column that should be grouped 

Yes, but how will I instruct dataTables to perform a fixed order from the extension?

> also specify a class name if they want it?

In my case, I'm not hiding the grouped column, but I want to add a class hide-text where it will hide text inside the cells.

> Could you show me the initialisation you are proposing? 

Are you talking about the dataTable options passed by the user or the initialization function inside the extension?

**Comment by DataTables** [comment]
> Yes, but how will I instruct dataTables to perform a fixed order from the extension?

Probably I need to introduce a new API that provides that ability I think. I'll look into adding that next week as that would be useful and something I've been meaning to do.

> Are you talking about the dataTable options passed by the user or the initialization function inside the extension?

By the user. I'm just interested to see how they would use your software.

**Comment by jamezamm** [comment]
> Probably I need to introduce a new API that provides that ability I think. I'll look into adding that next week as that would be useful and something I've been meaning to do.

Thanks that would be useful. i.e. If you're going to create an API method to enable fixed order, make sure you make one to disable it. Now what about the **className**?

> By the user. I'm just interested to see how they would use your software.

I was hoping to use **columns** or **columnDefs**. For example:

```javascript
var table = $('#example').DataTable({
    columns: [
      { groupBy: true },
      null,
      null,
      null,
      null,
      null
    ]
  });
// or...
var table = $('#example').DataTable({
    columnDefs: [ {
      targets: 0,
      groupBy: true
    } ]
  });
```

**Comment by DataTables** [comment]
That looks like a good initialisation to me. Perhaps the class name should be specified by the end user:

    { groupBy: true, className: 'grouping' }, ?

I'll look into adding a method for altering the fixed ordering next week.

**Comment by jamezamm** [comment]
It does not sound like a bad idea. 

But this will mean that the user can choose not to specify a className. Since I am not planning to hide the groupBy column, the column cells will then be left not empty. Will this make sense? I'm not so sure.

**Comment by DataTables** [comment]
That is possible yes. More generally, perhaps you could use `column().nodes()` in a draw callback to specify the class name. That would also make it easy to remove the class name if needed - i.e. you want to add the ability to change the grouping column.

**Comment by jamezamm** [comment]
To tell you the truth I thought of that approach column().nodes()... Maybe that is best approach.

**Comment by DataTables** [comment]
I've just committed an `order.fixed()` method which allows get / set of the table's fixed ordering. The nightly version is rebuilding at the moment.

I'm going to close this issue at the moment as hopefully this will resolve what you need rather than being able to modify the options object.

**Comment by jamezamm** [comment]
Agreed and thanks
