### ISSUE TITLE
FIX Suggested when PHP E_NOTICE is enable in error_reporting function

### ISSUE THREAD

**Issue by ste80pa** [DataTables/DataTables#665]
Hello, 

i have seen if E_NOTICE is enabled the spp.class.php does not work well because the extra output produced by error manger of PHP. I found that the problem depends from this two part of code :

in fileter function near line 175 i added a check for $request['columns']

```php
static function filter ( $request, $columns, &$bindings )
{
   ...
// Individual column filtering

if(isset($request['columns']) && is_array($request['columns'])) // <---- CONTROL ADDED
    for ( $i=0, $ien=count($request['columns']) ; $i<$ien ; $i++ ) {
    ......
   }
   ...
}
```
the second fixes is in the end of  SPP::simple and SPP::complex  functions :

```php
              /*
               * Output
               */

		return array(
			"draw"            => intval( isset($request['draw'])?$request['draw']:0 ), // <----- CONTROL ADDED
			"recordsTotal"    => intval( $recordsTotal ),
			"recordsFiltered" => intval( $recordsFiltered ),
			"data"            => self::data_output( $columns, $data )
		);
```

These are simple fixes but helped me :D

**Comment by DataTables** [comment]
Hi, thanks for this. But both those parameters should be sent by DataTables. Are they not for you?

**Comment by ste80pa** [comment]
'draw'  yes
'columns' sometimes no 
i made this 'patch' also to call directly the endpoint tho check the data transmitted :D

**Comment by DataTables** [comment]
I don't quite understand I'm afraid - DataTables should not be sending data with the columns parameter - that is a bug if it is happening. Can you link to a test case please.

**Comment by ste80pa** [comment]
i found this issue in AdminLTE bootstrap theme

**Comment by DataTables** [comment]
Can you link to a test cadd showing the issue please.

**Comment by DataTables** [comment]
Case*

**Comment by ste80pa** [comment]
I will link it soon

**Comment by ste80pa** [comment]
When i was creating the code to reproduce the issue, i discovered that the problem was generated by a php code included into the script that uses the SPP class.This script overwrites the $_GET['result'] variable with a string or calls unset() on $_GET['result'] under certain conditions. 

At this point, i suppose that these fixes  are useful only to call directly the script that uses SPP :D

**Comment by DataTables** [comment]
I don't see any issue with a bit of defensive programming here, even if it isn't really needed for use with DataTables. I've committed the changes](https://github.com/DataTables/DataTablesSrc/commit/8f37b0e2a10107dc342) into the Src repo.

Thanks for bringing this up.

**Comment by ste80pa** [comment]
Thank you :D
