### ISSUE TITLE
Is there a way to do inline editing with validations?

### ISSUE THREAD

**Issue by cloudybrain** [DataTables/DataTables#670]
I saw that there are validations when you edit on the modal pop-up, but wasn't even to find an example that allows you to validate when performing inline editing

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) that github links to for new issues, please post support requests in the DataTables forums.

Regarding your question, client-side validation can be done using the approach [shown in this example](http://editor.datatables.net/examples/api/clientValidation.html). That applies to inline editing as well as the main editing mode.
