### ISSUE TITLE
ColReorder with ColumnVisibility causing strange CSS problem

### ISSUE THREAD

**Issue by vyruz1986** [DataTables/DataTables#671]
I'm in the progress of upgrading from DataTables 1.10.5 to 1.10.9, mainly because the old flash export tools (TableTools) are no longer working in current browsers.

It's nice to see that all extensions can now be downloaded together with DataTables in one nice clean package, great job! I do however have a problem when combining the ColReorder plugin with the Buttons/ColumnVisibility extensions. When loading the page initially, the column visibility drop down works fine, you can see the columns which are active with a blue background, and the columns which are not with a white background. When you click the column names the drop down options are updated accordingly and the columns appear/disappear fine.

However once you drag a column to change the order, the column visibility drop down options seem to get their styling messed up, they become all white-brackground and don't toggle when clicked anymore. also their height seems to change. The columns are however still disappearing/appearing correctly.

Stranger still, it is not fixed when reloading the page, the only way I found to fix it, is to comment out the colReorder : true line of DataTables config temporarily, refresh the page, then uncomment it again. When you reorder any column the problem appears again.

I've been comparing the styles/classes of a 'correct' (dropdown still working fine) page, with the ones of a broken one, and I cannot spot any differences...

I have managed to reproduce this problem in a JSFiddle using the datatables examples from the website, and my configuration parameters: https://jsfiddle.net/zyq550Ls/

You can see the problem happening when you reorder a column, then click the 'Column Visibility' button.

**Comment by DataTables** [comment]
Thanks for posting this - please, in future, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) post support requests in the DataTables forums.

I will take a look into this when I'm able to do so.

**Comment by vyruz1986** [comment]
I did post it in the forums, last week, no reply since, I bumped the post 2 days but no reponse either.
Since I am confident this is a bug in one of the extensions I decided to create an issue about it

**Comment by DataTables** [comment]
I understand - thanks for the explanation. With 40 new posts a day in the forum, plus many more e-mails it just isn't possible for me to answer every question. Could you give a link to your forum thread so we can link between them should anyone Google and find the page.

**Comment by vyruz1986** [comment]
Oh sorry forgot that, I already linked to the issue in the forum thread: https://datatables.net/forums/discussion/30161/columnvisibility-with-colreorder-styling-issue#latest

**Comment by MuellerMatthew** [comment]
see my pull request here: https://github.com/DataTables/Buttons/pull/28 for a fix for this issue.

**Comment by DataTables** [comment]
See https://github.com/DataTables/Buttons/issues/26 for further information about this. It has been fixed in the Buttons repo.
