### ISSUE TITLE
NPM package includes XSS vulnerability 

### ISSUE THREAD

**Issue by twelvelabs** [DataTables/DataTables#672]
The vulnerability reported in https://github.com/DataTables/DataTables/issues/602 has not yet made it to NPM. Could you please release a new version that includes it so we can upgrade our app?

**Comment by DataTables** [comment]
The reported vulnerability is in the unit tests which are not in the NPM distribution and never has been.

However, I did forget to republish the package for 1.10.9 which I have just done.
