### ISSUE TITLE
https://www.datatables.net/ doesn't work

### ISSUE THREAD

**Issue by DexterHD** [DataTables/DataTables#674]
![website is offline 522 connection timed out 2015-09-22 12-17-24](https://cloud.githubusercontent.com/assets/1532188/10014719/ea0be0b8-6123-11e5-8f09-4b7969ecab4f.png)

**Comment by MrGeneric** [comment]
It's up for me now.

**Comment by DexterHD** [comment]
Hmmm, I think it's my internet provider problem. I have tried to connect from smartphone, and site really works.

**Comment by DataTables** [comment]
http://downforeveryoneorjustme.com/ is perfect for this sort of thing :-)
