### ISSUE TITLE
Forces UTF-8 encoding

### ISSUE THREAD

**Issue by ste80pa** [DataTables/DataTables#675]
Hi, this is not properly an issue but a suggestion.

Since the normal use of  SSP::simple member function is 

```php
..... 
echo json_encode(
    SSP::simple( $_GET, $sql_details, $table, $primaryKey, $columns )
);
```

and considering that json_encode() function fails if there is some non UTF-8 encoded string in the object passed as argument i found useful modify the sql_connect function as follow:

```php
// ADD $force_utf8 
static function sql_connect ( $sql_details, $force_utf8 = TRUE )
	{
		try {
			$db = @new PDO(
				"mysql:host={$sql_details['host']};dbname={$sql_details['db']}",
				$sql_details['user'],
				$sql_details['pass'],
				array( PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION )
			);
			
                       // ADD THIS TO FORCE UTF-8 STRING ENCODING
			if($force_utf8 === TRUE){
			     $db->query('SET CHARACTER SET utf8');
			     $db->query('SET NAMES utf8');
                        }
		}
		catch (PDOException $e) {
			self::fatal(
				"An error occurred while connecting to the database. ".
				"The error reported by the server was: ".$e->getMessage()
			);
		}

		return $db;
	}
```
In this way the UTF - 8 encoding is guaranted : D

**Comment by DataTables** [comment]
Hi,

Thanks for posting this. I isn't something I think I'll include in the SSP file by default, as this is server dependent, but I'm sure others will find it useful when they find this thread.

**Comment by ste80pa** [comment]
Ok, but  i think , is valid for any MySQL database. 

After PHP > 5.3.6 it is possible to add the 
```php
charset=utf8
```
int the dsn connection string. On older version this param it is  silently ignored.

```php
$pdo = new PDO("mysql:host=localhost;dbname=world;charset=utf8", 'my_user', 'my_pass');
```

**Comment by DataTables** [comment]
Sorry I wasn't clear - my point wasn't that it wouldn't always work, but rather that it isn't always needed. If the server has already been correct setup to perform UTF8 data transmission between the client and database then it isn't need. My worry is that including this code would serve to confuse in such cases as well has been unnecessary.

**Comment by ste80pa** [comment]
Yes you're right :D at the end, the better solution is to pass directly to the simple or complex function a PDO object alreay connected. Adopting this solution (passing directly an alreay connected instance  to the simple() funcion)  i found this lille issue thttps://github.com/DataTables/DataTables/issues/677.

**Comment by haiyunx** [comment]
OMG, you saved my life man! The codes work like a magic! I am dealing with database containing wine names (with some special charaters), so I had to change all tables and databases to UFT-8 unicode. Your codes generating the proper encoded json data from mysql. I no longer see any json error message. I really appreciate your help. @ste80pa
