### ISSUE TITLE
sql_exec PDO::FETCH_BOTH

### ISSUE THREAD

**Issue by ste80pa** [DataTables/DataTables#677]
Scenario : i am passing my pdo connection to the SSP::simple function.

using SSP class i noticed this error

Undefined offset: 0' in lib/ssp.class.php on line 250

after a little investigation i founded the problem is caused by this 

```php
....
$recordsFiltered = $resFilterLength[0][0];
...
$recordsTotal = $resTotalLength[0][0];
```

on simple and complex function. printing the queries i noticed che the index [0] is not present 

```php
SQL = SELECT FOUND_ROWS()
Array
(
    [0] => Array
        (
            [FOUND_ROWS()] => 23
        )

)

SQL = SELECT COUNT(`id`) FROM   `table_xxx`
Array
(
    [0] => Array
        (
            [COUNT(`id`)] => 23
        )

)
```

but i fixed soon adding PDO::FETCH_BOTH on 

```php
static function sql_exec ( $db, $bindings, $sql=null )
	{
		.......
		// Return all
		return  $stmt->fetchAll(PDO::FETCH_BOTH);
		
	}
```

I hope this can help

**Comment by DataTables** [comment]
I had thought that FETCH_BOTH was the default. Are you overriding that somewhere, perhaps in your PDO connection configuration?

**Comment by ste80pa** [comment]
Yes, with setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC)

**Comment by DataTables** [comment]
Finally fixed :-)
