### ISSUE TITLE
bug(sort): throw "TypeError: Cannot read property 'aDataSort' of undefined" if no column 

### ISSUE THREAD

**Issue by douglasduteil** [DataTables/DataTables#678]
Hi

Simply executing the dataTable function with no options on an empty table throws the error below

```js
 $('#myTable').DataTable();
// Uncaught TypeError: Cannot read property 'aDataSort' of undefined
```

At https://github.com/DataTables/DataTables/blob/1.10.9/media/js/jquery.dataTables.js#L4524
Demo : http://live.datatables.net/cocikoyo/1/edit (open the console)

Seems like the sort configuration try to access to the columns without testing if there are any.

**Comment by DataTables** [comment]
The table has no columns. Since you can't dynamically add columns to a DataTable, it seems a bit redundant initialising an empty table is it not?

**Comment by douglasduteil** [comment]
Hum yeah. I'm actually codding a work around to do the dynamically columns number thing. So I guess I will just detect that  these is no columns in my code and add a fake one.
Thanks

**Comment by bhumiradixweb** [comment]
i have same issue,if no column,it has to ignore.

**Comment by saimAbdullah** [comment]
gives same issue when have no row in table

**Comment by vinaypost** [comment]
I am facing the same issue..
