### ISSUE TITLE
selector-modifier is not applied in columns().every() 

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#679]
When using [`columns().every()`](http://datatables.net/reference/api/columns%28%29.every%28%29) [`selector-modifier`](http://datatables.net/reference/type/selector-modifier) is not being applied to column referenced by `this` variable.

My workaround currently is to access the column by index with `column()` and applying [`selector-modifier`](http://datatables.net/reference/type/selector-modifier) that way.

    var table = $('#example').DataTable({
       drawCallback: function () {
           var api = this.api();

           api.columns({ search: 'applied' }).every(function (index) {
               var column = api.column(index, { search: 'applied' });
               
               console.log(index, this.nodes().length, column.nodes().length);               
           });
       }        
    });

See [this jsFiddle](https://jsfiddle.net/7mgny9gb/) for demonstration.

**Comment by DataTables** [comment]
Hi,

The selector modifier primarily effects the rows that are selected - so for example `api.columns({ search: 'applied' }).nodes()` would get the cell nodes for all columns (since there is no column selector) and for only the rows which are in the current search result set.

It does not effect the columns that are actually selected. Is that what you were expecting?

**Comment by mpryvkin** [comment]
API method `api.columns({ search: 'applied' }).nodes()` returns correct number of nodes accounting for search query but `api.columns({ search: 'applied' }).every()` sets `this` to an instance that doesn't take into account search query.

See [updated jsFiddle](https://jsfiddle.net/7mgny9gb/2/) for demonstration.

**Comment by DataTables** [comment]
Fantastic - thank you for the test case. I've just [committed a fix](https://github.com/DataTables/DataTablesSrc/commit/b22e92021558eb1bfb221c71ab37c079ba925af0) which is now in the nightly. [Updated fiddle](https://jsfiddle.net/7mgny9gb/4/).

Thanks for highlighting this issue and doubly so for the test cases!

**Comment by mpryvkin** [comment]
Allan, are you sure [this commit](https://github.com/DataTables/DataTablesSrc/commit/b22e92021558eb1bfb221c71ab37c079ba925af0) is related to this issue? There are some many unrelated changes.

**Comment by DataTables** [comment]
This the one. The distribution repo he a lot of changes in the examples because of a change in my build env, and I accidentally committed a change in the commonjs loaded - both have been fixed in the dist repo now

**Comment by mpryvkin** [comment]
That is what I thought, thanks.
