### ISSUE TITLE
Documentation for columns.data

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#685]
Can you please add a note to [http://datatables.net/reference/option/columns.data#function] similar to [http://datatables.net/reference/option/columns.render#function].

>Note that this function might be called multiple times, as DataTables will call it for the different data types that it needs - sorting, filtering and display.

**Comment by DataTables** [comment]
[Committed](https://github.com/DataTables/DataTablesSrc/commit/a06b3f4dffd39d14908e092b61f75bf24a496ed0). Thanks!
