### ISSUE TITLE
Documentation for column().order() and columns().order()

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#686]
In the examples for [column().order()](http://datatables.net/reference/api/column%28%29.order%28%29) and [column().order()](http://datatables.net/reference/api/columns%28%29.order%28%29), it may make more sense for those copying and pasting the examples to add `draw()` method at the end.

There is a reference on the above-mentioned pages that `draw()` is required to perform the ordering, but the example doesn't make it clear enough, IMHO.

For example:

    var table = $('#example').DataTable();
    table.columns( '.status' ).order( 'desc' ).draw();

**Comment by DataTables** [comment]
Makes sense - thanks for pointing that out! [Committed here](https://github.com/DataTables/DataTablesSrc/commit/89c3324edf4abd62709d2d0851087890c8ed9e4a) and will be deployed to the site soon.
