### ISSUE TITLE
Documentation for /plug-ins/sorting/numeric-comma

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#687]
On [this page](http://datatables.net/plug-ins/sorting/numeric-comma):

replace 

> Sort numbers correctly which use a common as the decimal place.

with

> Sort numbers correctly which use a comma as the decimal place.

**Comment by DataTables** [comment]
Thank you. [Fixed here](https://github.com/DataTables/Plugins/commit/ff2e0ed6a568f18229157e2f83e3f8f54c2113ff).
