### ISSUE TITLE
Babel + Browserify bug.

### ISSUE THREAD

**Issue by EssentialDeveloper** [DataTables/DataTables#688]
When you try to using Babel + Browserify, then require('datatables') there is undefined jquery module.

To fix this you need to change path of jquery from:
        module.exports = factory( require( 'jquery' ) );
to
        module.exports = factory( require( './jquery' ) );

**Comment by DataTables** [comment]
It sounds like you need to add a jquery define to your require paths. Putting an absolute path into DataTables would not be the correct answer here I think.

**Comment by EssentialDeveloper** [comment]
Your right thanks.
