### ISSUE TITLE
DataTables doesn't support colspan

### ISSUE THREAD

**Issue by nmilojevic91** [DataTables/DataTables#689]
I had a problem with DataTables on a table which has a TH element with colspan. The part where it breaks is when applying search on columns. I haven't tested if script fails when the search is off.
I edited my script to fit my needs, but it would be good to have an option to add colspan on some THs

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

DataTables does not support colspan or row span in the tbody. Additionally, in the thead it requires that there be a unique cell for each column. See also [this example](http://datatables.net/examples/basic_init/complex_header.html).

**Comment by nmilojevic91** [comment]
Thanks for the answer, but that wasn't acceptable in my case. The code i tried is e.g.:
http://jsbin.com/bunebezelo/edit

**Comment by DataTables** [comment]
Hi,

Thanks for the test case. Unfortunately that is a form that DataTables does not support at this time. Sorry.
