### ISSUE TITLE
Documentation for draw()

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#690]
On page for [`draw()`](http://datatables.net/reference/api/draw%28%29) API method

replace 

> Please note that the string options require or newer

with 

> Please note that the string options require DataTables 1.10.8 or newer

**Comment by DataTables** [comment]
Thanks. Fix [committed](https://github.com/DataTables/DataTablesSrc/commit/88cedc43e50053edfcfd344a8f0dba215c5eb4b2) and will be pushed out soon.
