### ISSUE TITLE
jQuery DataTables Custom data source property for pagination

### ISSUE THREAD

**Issue by touqeershafi** [DataTables/DataTables#691]
I'm working with datatables with client and service side application. But i'm facing an issue with data table, i've search every thing in Datatables documentation but couldn't find my answer.

So the problem is i'm getting response from server as json like this:
![screenshot-192 168 1 167 2015-10-05 10-28-47](https://cloud.githubusercontent.com/assets/4585116/10278241/250f7228-6b75-11e5-82b9-7ad93065ce5b.png)

As you can see in this JSON response, datatables required json is in data.data to set this data source in datatables there is a property which is Custom Data Property and it working fine and shows the rows. Now problem is that datatables is not considering pagination parameters from json which is why it show's this: 
![screenshot-localhost 2015-10-05 10-33-29](https://cloud.githubusercontent.com/assets/4585116/10278255/3abf913e-6b75-11e5-8f8d-c8416d93ee8e.png)

Javascript Code: 
```
$(document).ready(function () {
                        $("#example").dataTable({
                            "ajax": {
                                url: app.getApiUrlWithAccessToken('lead/get_all'),
                                dataSrc: function(json){
                                    return json.data.data;
                                }
                            },
                            "lengthMenu": [1,2,5,10,15],
                            "columns": [
                                { "data": "first_name" },
                                { "data": "last_name" },
                                { "data": "title" },
                                { "data": "email" },
                                { "data": "city" },
                                { "data": "status" }
                            ],
                            "processing": true,
                            "serverSide": true
                        });



                    }
                );
```

**Comment by DataTables** [comment]
Hi - I'd appreciate if, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), you could please post support requests in the [DataTables forums](//datatables.net/forums).

The issue you are seeing is that `ajax.dataSrc` will return the data - it is no way of DataTables therefore to access the paging properties. And indeed, they can't be at all if you are using server-side processing and they aren't in the expected location. You need to either modified the response from the server, use `ajax.dataSrc` to modify the JSON data structure or use `ajax` as a function and make your own Ajax call, returning a JSON structure specifically for DataTables.
