### ISSUE TITLE
JavaScript sourced footer

### ISSUE THREAD

**Issue by nddery** [DataTables/DataTables#693]
First, let me start by saying that I am not sure if this is an issue or if it is by design, or that I'm missing something.

The issue can be seen here: http://live.datatables.net/rewuxowo/1/edit

When initializing a DataTable with JavaScript, you can specify the `data` option, as well as `columns.title` to populate the columns header. However, using `footerCallback`, it seems like you can't add content to the footer, as one is not generated. Seems like there are no options to also generate a footer. I've found that a workaround is to manually initialize your table markup with an empty footer row and cells (meaning you need to know how many columns there are before hand).

**Comment by DataTables** [comment]
Hi - this is by design. Or at least sort of - it just isn't a feature that I have written yet. There is currently no way to add footer cells to a table when initialised using pure Javascript. The workaround is to use the DOM to create a `table` with the footer structure you want and then use that.

**Comment by nddery** [comment]
Got it. Thanks for the quick reply, will insert the footer directly in the HTML!

Cheers!
