### ISSUE TITLE
FixedColumns with multiple tables

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#694]
According to the manual:

>FixedColumns can be initialised and used in two different ways:
>
>  * As part of the DataTables constructor with the fixedColumns configuration option
>  * A `new` constructor

However when working with multiple tables, initialization with `fixedColumns: true` option works for all tables (see [this example](https://jsfiddle.net/omgLswq6/1/)) but initialization with `new` constructor  works for the first table only (see [this example](https://jsfiddle.net/omgLswq6)).

Apparently this is by design, but manual doesn't mention this difference. 

Can a note be added to [Constructor](http://www.datatables.net/extensions/fixedcolumns/#Constructor) section about this difference?

**Comment by mpryvkin** [comment]
Nevermind, the problem was that both tables had the same ID which surprisingly led to this issue.

**Comment by DataTables** [comment]
Yes good point. Thanks. I'll update it shortly.

**Comment by DataTables** [comment]
Finally committed the change. Will be pushed on the site shortly.
