### ISSUE TITLE
render: sort not working in Internet Explorer

### ISSUE THREAD

**Issue by joe-meyer** [DataTables/DataTables#695]
If this is a duplicate of something else feel free to close but I couldn't find anything that explicitly showed this and it's really rather strange.

If I define a `render: { 'sort': 'bla' }` using the column headers to trigger a resort ascending / descending doesn't appear to have any effect when using internet explorer.

http://jsfiddle.net/50x1m4bt/8/

Strangely I have been able to in some cases define an `order` option and it does appear to sort on the initial load but nothing after that, I couldn't seem to replicate this in the fiddle though (maybe since the fiddle isn't on nightly?)

**Comment by DataTables** [comment]
You need to specify the `type` option as well, otherwise the `_` is used for type detection: http://jsfiddle.net/50x1m4bt/10/ .
