### ISSUE TITLE
New data-order values aren't taking effect

### ISSUE THREAD

**Issue by jackbraj** [DataTables/DataTables#700]
I have a table with data-order attribute for sorting. Its working fine initially. 

But then I update the values of data-order programmatically and try to reorder column based on new data-order attribute values but I couldn't get it working.

I tried several API methods like columns(index).reorder() , cell().invalidate('dom') but had no luck.

Please suggest if there is any way to do that without re-initialising whole table

**Comment by DataTables** [comment]
Per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.

The `cell().invalidate()` method should be all that is needed here - if that isn't working, we'd need a test case.

**Comment by mpryvkin** [comment]
See #643 which is possibly related, try to use [nightly](http://datatables.net/download/nightly) version and see if that solved the problem. Alternatively, try to use `row().invalidate('dom')` instead.
