### ISSUE TITLE
Go to page with row

### ISSUE THREAD

**Issue by 57even** [DataTables/DataTables#702]
I have a data tables. I have saved a row's ID in a session. Can I with DataTables change the pagination so the row whose ID is in a session is shown?

Right now I can click a table row to save it's ID in a session, but if I change page, the selected row is no longer visible to the user, so I have to create a button to make the user go back to the page where the selected row is shown.

One option could be to also save the current page when the user clicks a row, but if the user orders the columns, the row is no longer present at the saved page.

**Comment by DataTables** [comment]
Hi,

I'd appreciate if you could ask support questions in the [DataTables forums](//datatables.net/forums) as per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md).

To answer your question hear - yes, use [this plug-in](https://www.datatables.net/plug-ins/api/row().show()).
