### ISSUE TITLE
Documentation for columns.searchable

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#704]
On  [`columns.searchable`](https://datatables.net/reference/option/columns.searchable) page there is a reference to `filter` option, but there is no such.

Apparently this should have been a reference to [`filter()`](https://datatables.net/reference/api/filter%28%29) API method instead.

**Comment by DataTables** [comment]
[Fixed here](https://github.com/DataTables/DataTablesSrc/commit/a1e42ddb03880c134218d033d89b681189925445). There is no `filter` option - the correct reference should have been the `search` option (which was actually already there).

The `filter()` method and `search()` method are not the same - `filter()` will filter an API instance's result set, while `search()` will search the table.

I'll push the update out to the site this week.

Thanks!
