### ISSUE TITLE
Documentation for order

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#705]
On the page for [`order`](http://datatables.net/reference/option/order) option it is said that:

> The order must be an array of arrays

However for single column sorting array also works, see below:

    var table = $('#example').DataTable({
       order: [2, 'desc']    
    });

See [this jsFiddle](https://jsfiddle.net/y78mtqez/) for code and demonstration.

**Comment by DataTables** [comment]
It actually only partly works. It was something I wanted to have that, but it causes issues for some plug-ins so I removed it from the documentation. It is something I would like to make more robust in future, but at the moment I'd rather not have it documented.

**Comment by mpryvkin** [comment]
Do you discourage such use?

**Comment by DataTables** [comment]
Yes :-). It works for basic use, but it can cause issues with more complex tables.
