### ISSUE TITLE
"Next" Pagination Button Only Works On First Page

### ISSUE THREAD

**Issue by joelcdoyle** [DataTables/DataTables#707]
I'm using ajax to get data. All page numbers work fine, filters work fine, info shows the correct number of records, but for some reason the "Next" button only works on the first page. 

I found an old issues here: http://www.datatables.net/forums/discussion/20869/ie8-next-page-not-working
It states that this is solved, but I am still experiencing this issue in Chrome, Firefox, and Safari.

Just like on that page, after clicking the next button once on the first page, it does nothing when clicked on any other page. I'm not using scroller or setting `scrollCollapse` just normal datatable

It works fine in iOS browser on iPhone(which is odd), but I have not tested Android.

I'm using this in conjunction with [angular-datatables](https://l-lin.github.io/angular-datatables/#/welcome), but it should be using the latest stable version of DTs

I've tried disabling a lot of features, to see if there was a conflict, but nothing seems to help.

**Comment by DataTables** [comment]
All of the [examples listed here](http://datatables.net/examples/) appear to work no problem.

Can you link to a test case showing the issue please.

**Comment by joelcdoyle** [comment]
My table is tied up with services and lot's of other thing that prevent me from making a JSBIN or jsfidde.

However, I think I've found the issue. Our server is not returning the correct value for `recordsFiltered`. We misunderstood that this value should account for current page, and not just filters. So, if we are on a page of 50 results, with no filters, then this value should be 50.

On a side note, there *IS* a difference in the settings object of my ajax method when I press the next button vs pressing the second page number:

When I press the next button, the settings object has this field as a string with a leading zero:
```
_iDisplayStart: "050"
```

Whereas when I press the second page button, it is an integer: 
```
_iDisplayStart: 50
```

**Comment by DataTables** [comment]
Sounds like you need to cast the values as numbers.

**Comment by joelcdoyle** [comment]
All numbers that we are sending to the server *are* being cast as numbers. I've also taken this settings field and recast it as a number before the server call is made, with no change in behavior.

I've also noticed that the info text at the bottom is actually not correct. It shows "Showing 51 to 1,682 of 1,682 entries" on the second page, when it should show "Showing 51 to 100 of 1,682 entries". This would explain why the next button doesn't work. It thinks I'm on the last page of results.

Very confusing.... `recordsFiltered` should not return 50 if 50 results are returned purely because of pagination right? I was under the impression that this should only account for actual data filters

**Comment by joelcdoyle** [comment]
Aha! I finally figure out the issue, and it was my fault. I was setting `iDefaultDisplay` to the string "50" instead of the integer 50.

**Comment by akoSalman** [comment]
@joelcdoyle I had the same problem. I was setting `"pageLength": "10"` instead of `"pageLength": 10`.
