### ISSUE TITLE
ColumnVisibility + ScrollX will change columns widths

### ISSUE THREAD

**Issue by hector** [DataTables/DataTables#708]
I have a table with horizontal scroll enabled (`scrollX: true`) and with the column visibility button (`colvis`) enabled.

By default, the table is bigger than the screen, so only a portion is shown and you can scroll to the right:
![image](https://s3.amazonaws.com/f.cl.ly/items/1j352R472K2o0e18030S/Screen%20Shot%202015-10-22%20at%2001.34.00.png)

Then if I use the colvis button:
![image](https://s3.amazonaws.com/f.cl.ly/items/0w1T2V2M3U0K40030K1S/Screen%20Shot%202015-10-22%20at%2001.34.29.png)

And I hide some columns:
![image](https://s3.amazonaws.com/f.cl.ly/items/0b1a3J0h1u471T3T1l1I/Screen%20Shot%202015-10-22%20at%2001.36.03.png)

The table preserves its width. So even though there are very few columns and they could be shown in the page, the table is still scrollable and columns get very wide:
![image](https://s3.amazonaws.com/f.cl.ly/items/3r0C3Y0Q2V221z0v2P2c/Screen%20Shot%202015-10-22%20at%2001.35.01.png)

I think this would be solved if the table width is recalculated every time a column is shown / hidden.
I am afraid the inverse (having few columns shown and then showing more) would also cause problems.

If you give me some clue on how to trigger a table width recalculation or something I can try to solve it :)

**Comment by DataTables** [comment]
Sounds like you have width:100% applied to the table. If not, then please link to a test case showing the issue.

Also, in future, please post support questions int he [DataTables forum](//datatables.net/forums) as requested in the Contributing document that GitHub links to when creating a new issue.

**Comment by hector** [comment]
Thank you for the help, I didn't know about the forum, next time I'll post there.
I have been able to solve it. Mysteriously, it was because I was applying some padding-right to the table. I have been trying to reproduce it from a clean state in jsfiddle but it works good there. I guess it could be interfering with width calculations, but don't really know how.
