### ISSUE TITLE
Still existe fnCellRender function?

### ISSUE THREAD

**Issue by slbtuga** [DataTables/DataTables#711]
Hi.

Before my quetion, you have here an excelent job. I'm very greatfull for that.

With replacement of tabletools with buttons and select in version 1.10, I don't see a substitute for fnCellRender callback.
How can I have the same behavior with new buttons?

Thanks.
Best Regards.

**Comment by DataTables** [comment]
Thank you for your kind words - however, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums) in future.

[This example](https://github.com/DataTables/Buttons/blob/master/examples/html5/outputFormat-orthogonal.xml) shows how it can be done in Buttons. That example hasn't yet been published on my site  as it is part of unreleased software.

**Comment by slbtuga** [comment]
Sorry for insist but this solution have an error if the data value is null.

Give the error:
<code>
Unhandled exception at line 93863, column 5 in http://localhost:49667/Scripts/datatables.js
0x800a138f - JavaScript runtime error: Unable to get property 'replace' of undefined or null reference
</code>

I'am using datatables version 1.10.9

This is where the error occur:
![image](https://cloud.githubusercontent.com/assets/11768600/10766519/db3960a2-7ccf-11e5-8345-b9a081200b2e.png)

Once again, sorry and thanks.

**Comment by DataTables** [comment]
Can you try using the [nightly version of Buttons](//datatables.net/download/nightly) please which should have fixed this issue.

**Comment by slbtuga** [comment]
Now give the following error when I try export to excel:
<code>
Unhandled exception at line 588, column 5 in http://localhost:49667/Scripts/DataTables/Buttons/nightly/buttons.html5.js
0x800a138f - JavaScript runtime error: Unable to get property 'match' of undefined or null reference
</code>

Export to "Copy" and "csv" works fine.

About export to pdf, because the number of columns does not fit on the page in portrait,  the last two columns do not appear in pdf. If I choose landspace looks right.

**Comment by DataTables** [comment]
Can you give me a link to the page so I can debug it please.

**Comment by slbtuga** [comment]
Here an [example](https://jsfiddle.net/1qbxgLyb/) about the error I told before.

Try export to excel and see console.

**Comment by DataTables** [comment]
Excellent - thank you. I'll commit the fix tomorrow morning and update here.

**Comment by DataTables** [comment]
Fixed in 20a972b32d0874518d3cf07b4cf84bf06c2ef920. The other option (which is probably preferable, as I think my fix is really a workaround for invalid data in this case) is to use the `columns.defaultContent` option to tell DataTables what to do with null or undefined data.

**Comment by slbtuga** [comment]
It's ok now.
You was very helpfull.
Thank you very much.
