### ISSUE TITLE
DataTable Sorting 

### ISSUE THREAD

**Issue by Abhayman** [DataTables/DataTables#712]
Hi,

When we try to color code the row in the Datatable and enable sort . Multiple rows gets colored . Here is the script to call the data :--
  ```
    <script>
    $(function () {

    $('#example2').DataTable({
      "ajax": "../json/daily_status.json",
      "fnRowCallback": function( nRow, aData, iDisplayIndex ) {
        /* All cells in 4th row will be bolded  */
        if ( iDisplayIndex == 9 ) {
            $('td', nRow).each(function(){
                           $(this).html( '<td bgcolor="#BE81F7"><b>'+$(this).text()+'</b><td>' );
                        });
        }
        return nRow;
    },
      "scrollX": false,
      "bSort": false,
      "paging": false,
      "info": false,    
      "searching": false,
       dom: 'Bfrtip',
       buttons: [
            'excel'
            ]         
    });
  });
</script>
```
HTML Section :--
   ```     
     <table id="example2" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                       <th>STATUS_CODE</th>
                       <th>Count</th>                       
                      </tr>
                    </thead>
             </table>
```
![7e18101a-6c78-11e5-9cfb-4132df1ef0c6](https://cloud.githubusercontent.com/assets/8066748/10781671/35eeec8e-7d6f-11e5-82fd-6ee9bf419278.png)

Any help on how to keep the sorting enabled still have the color fixed on the Total column 

Regards.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.

In this case, if you want a footer I would suggest using a `tfoot` element to create a footer in the table. I don't know if you have one without a test case, but I'm guessing not.
