### ISSUE TITLE
$(): no access to child rows

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#714]
Documentation for [`$()`](http://datatables.net/reference/api/%24%28%29) states that:

>The selector given to the $() method will be run on all of the tr elements in the table, and **their child elements**, with the found elements being returned as a jQuery object.

However child rows doesn't seem to be included, see [this example](http://jsfiddle.net/veLmewnb/3/).

**Comment by DataTables** [comment]
I think this is a terminology issue - the "child elements" here refers to children in the DOM sense - e.g. `<td><span/></td>`: the span is a child of the `td`.

The child rows (`row().child()`) is not a descendent of the host row, so it is not selected.

I've committed a small change to the documentation to clarify this.
