### ISSUE TITLE
Fixedheader enable/disable result in not a function errors

### ISSUE THREAD

**Issue by BoinKlasik** [DataTables/DataTables#715]
reproducible from your own examples: https://datatables.net/extensions/fixedheader/examples/options/enable-disable.html
Clicking the enable/disable buttons on that page result in errors.

The same is true when using JS acquired from the download tool.  This appears to be because of a mismatch in version provided by the documentation vs what you get when FixedHeader is selected as a download option, enable/disable show as implemented in 3.0.1 of fixedheader but 3.0.0 is the released version.  It is odd for the documentation/example to appear on the site while being unavailable in the "standard" methods of acquiring datatables.  One would have to pull the current files in git to use features advertised on the site.

**Comment by DataTables** [comment]
Yes - this is correct - the methods are available in 3.0.1 and not the current 3.0.0 release. You are absolutely correct that the example shouldn't have been  published and probably not the documentation either. The 3.0.1 release should be make later this week and I'll look at updating my build scripts to not allow this to happen again - thanks for flagging it up.
