### ISSUE TITLE
Support exporting Japanese PDF File

### ISSUE THREAD

**Issue by kotazi** [DataTables/DataTables#716]
Is it supported to export PDF by utf8??
When I try it, Japanese text is not shown.

**Comment by DataTables** [comment]
Yes - Buttons supports UTF8 export. The legacy TableTools extension does not.

This is not the correct place to ask support questions. Please, per the contributing document that GitHub links to when a new issue is opened, post support questions in the [DataTables forums](//datatables.net/forums).
