### ISSUE TITLE
Support exporting Shift_JIS CSV File

### ISSUE THREAD

**Issue by kotazi** [DataTables/DataTables#717]
Hi.
Maybe currently the exported CSV file is UTF-8.

I want to use Shift_JIS. Is it possible?
Thanks!

**Comment by DataTables** [comment]
This is not the correct place to ask support questions. Please, per the contributing document that GitHub links to when a new issue is opened, post support questions in the [DataTables forums](//datatables.net/forums).

Please be sure to include a link to a test page that shows the issue as well.
