### ISSUE TITLE
Documentation for Scroller extension

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#718]
On [this page](http://datatables.net/extensions/scroller/) 

change:

>Scroller is a virtual rendering plug-in for DataTables which allows large datasets to be drawn on screen **every** quickly. 

to

>Scroller is a virtual rendering plug-in for DataTables which allows large datasets to be drawn on screen **very** quickly.

**Comment by DataTables** [comment]
Thanks for pointing that out - fixed now.
