### ISSUE TITLE
Update records without AJAX

### ISSUE THREAD

**Issue by martin-wiseweb** [DataTables/DataTables#719]
I have a dataTable instance that will load before it receives the data it needs to receive. It will not be loaded via AJAX into the dataTable, but instead via a drag and drop function.

How can I replace existing data, and re-draw the table like this?

**Comment by DataTables** [comment]
Use the `clear()`, `rows.add()` and `draw()` methods. Documentation for them, and all other methods is [available in the DataTables API reference](//datatables.net/reference/api).

In future, could you ask support questions in the [DataTables forums](//datatables.net/forums) please.

**Comment by martin-wiseweb** [comment]
I managed to get it working, but the functions you mentioned did not work.

My instance is in `__self.$container.dataTable()`, and the data is in `__self.properties_.values.TableData.data`.

This worked:

    __self.$container.dataTable().fnClearTable();
    __self.$container.dataTable().fnAddData(__self.properties_.values.TableData.data);

This did not:

    __self.$container.DataTable().clear();
    __self.$container.DataTable().row.add(__self.properties_.values.TableData.data);
    __self.$container.DataTable().draw();

**Comment by DataTables** [comment]
Possibly you are using a legacy version of DataTables (pre 1.10)? However, either way, good to hear you for it working.
