### ISSUE TITLE
Error: Cannot resolve module 'datatables.net'

### ISSUE THREAD

**Issue by Tol1** [DataTables/DataTables#722]
CommonJS loader for dataTables.bootstrap tries to load module named "datatables.net", but this module is named "datatables". This throws error `Module not found: Error: Cannot resolve module 'datatables.net'` when building with WebPack or Browserify.
I can fix my build by defining alias 'datatables.net' to resolve as 'datatables', but I think this is not optimal way...

**Comment by DataTables** [comment]
what is `dataTables.bootstrap`? Is that another NPM package? It isn't one that is published by myself is so.

Please see [this link](http://datatables.net/download/npm) for a list of the NPM packages published as part of the DataTables project, for distribution of the software.

**Comment by Tol1** [comment]
I'm talking about this line https://github.com/DataTables/DataTables/blob/master/media/js/dataTables.bootstrap.js#L31

**Comment by DataTables** [comment]
Yes - that line looks correct to me. The `datatables.net` package (which is detailed on the page I linked to above) contains DataTables.

The files in this repo / package aren't really the best point to use DataTables on NPM now which might be what is causing the issue.

**Comment by Tol1** [comment]
Well, I'm using Bower, and because this change was made between patch changes (according semver, 1.10.9 and 1.10.10 should be only bug fixes and 1.10.10 matches '~1.10.7' i have on my bower.json) I now get this broken version without warnings about deprecation (matching bower.json is found on repo, bower registry search finds package pointing at this repo etc). So maybe the deprecated package should be removed from Bower registry then?

**Comment by DataTables** [comment]
Agreed! I'll add that very shortly.

Doing this on a patch release was probably a mistake in retrospect - apologies! If this causes issues else where I might have issue an independent update in this repo that restores the original behaviour...
