### ISSUE TITLE
Initial processing message is shown on column headers instead of in tbody

### ISSUE THREAD

**Issue by Tklaversma** [DataTables/DataTables#723]
Hi Allan,

This isn't a bug, but more a visual improvement or so..

When DataTables uses serverside processing, I'm able to show a processing message. Of course I can style the message however I like. But the problem is that only on the intial load, there isn't any table body to show the processing message on, as you can see [here](http://jsfiddle.net/4pry7og5/94/). It's hard to see, but focus on the column headers and refresh page. In my actual project, loading takes a second or so because of the +/- 10000 rows, that's why I noticed this visual issue.

I already found a workaround for this problem by adding a tbody with a row and cells that have a space in them, so DataTables recognizes there is a row. [Here](http://jsfiddle.net/4pry7og5/95/) you will find my workaround.

But, as you would agree with me, this isn't a very nice solution. For example, when a column is added, you have to add another empty cell and when you delete a column....you get the picture.

Can/will you fix the problem so that the initial processing message isn't shown on the column headers anymore?

Regards,
TK

**Comment by DataTables** [comment]
The reason that this is happening is that the "processing" message's CSS will cause it to display centered over the table (vertically). If the table is empty, then yes, that will show over the header.

[This is the CSS that causes that](https://github.com/DataTables/DataTablesSrc/blob/master/css/jquery.dataTables.scss#L503). You could remove the margin-top if you didn't want it - it would resolve in it being off center when the table is populated, but not by much and you might find that acceptable.

This isn't a change I want to put into DataTables just at the moment, but I will keep it in mind for future styling.

**Comment by Tklaversma** [comment]
@DataTables I understand the positing method you are using and also that I can break/adjust that in anyway I want (already doing this by using bottom:0px; and than give the container of the processing message the height of the tbody and the actual message a display:table-cell with vertical-align:middle).

But that doesn't change the fact that when initially processing on an empty table the message should be shown over the table header. You could for example built in a pre initial processing callback, so that people can adjust it however they want instead of using useless HTML.

I understand that there are more pressing issues then this one, but just accepting this issue as is isn't a solution. I hope you will still address this issue later on when the other more pressing issues are fixed.
