### ISSUE TITLE
Invalid Excel file created when '<' in cell

### ISSUE THREAD

**Issue by ydohogne** [DataTables/DataTables#724]
When a table contains the '<' character, the Excel file created cannot open (unreadable content).
See https://jsfiddle.net/ydohogne/mLg39cfb/

**Comment by DataTables** [comment]
Thank you for pointing this out. I've fixed this in the Buttons repo - https://github.com/DataTables/Buttons/commit/606b5c4b45f2a1b6a3c747f16634dbb4373b09d5 .

Updated version of the fiddle with the nightly version of Button's HTML5 export buttons: https://jsfiddle.net/mLg39cfb/2/ .
