### ISSUE TITLE
jQuery 2.1.4 not working properly

### ISSUE THREAD

**Issue by trollsudd** [DataTables/DataTables#725]
Hi,
I cant get this plugin to work with jQuery 2.1.4. I have read alot about some stuff is missing jQuery v1.11.3 that I can see u running.

I tried to use both version at the same time with jQuery.noConflict(true), but I cant make it work..

Is there a way around it or plans to make it work for 2.1.4.

The error I´m getting is:
onload:
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in 

why I try to change sort order: 
same as above.

after one search..the sort order starts to work.

When I try to filter it does it right, but when I try to backspace back to non input i cant get every line to come back. 
and same error as above.

**Comment by DataTables** [comment]
Are you using the latest version of DataTables (1.10.10)? There was an issue with early versions of 1.10.x which caused the issue you describe, but that has since been correct.y

Please link to a test case showing the issue.

**Comment by trollsudd** [comment]
Yea.. u are right. I used 1.10.5. my bad. 

u can delete this post if u want :) 

Thanks so much for the quick answer! :+1:

**Comment by DataTables** [comment]
No problem - in future please post support questions in the [DataTables forums](//datatables.net/forums).
