### ISSUE TITLE
If the plugin is just setting opacity:0; then maybe you should set the cursor: default;

### ISSUE THREAD

**Issue by jhyland87** [DataTables/DataTables#731]
I just realized that the plugin doesn't actually remove the pagination buttons/links, it just sets the opacity to 0, I noticed this because someone told me there were "weird invisible links that didn't do anything". 

So just a suggestion, maybe after the fadeOut, or whatever it is, completes, execute a callback that sets the cursor to 'default, then back when the pagination controls are visible..

Just an idea

**Comment by DataTables** [comment]
Sorry - what plug-in?

**Comment by jhyland87** [comment]
Oh sorry, I thought this was under the Conditional Paging..
