### ISSUE TITLE
tableTools options for saving do not display on shiny app deployment

### ISSUE THREAD

**Issue by dlennon** [DataTables/DataTables#735]
tableTools does not behave as expected with my shiny app. Instead of showing all options for saving (copy, excel, csv, print), the shiny app only shows a print option:

`output$maintable = DT::renderDataTable(FoodDatabase[, input$show_vars, drop = TRUE], 
extensions = 'TableTools', 
options = list( dom = 'T<"clear">lfrtip',
tableTools = list(sSwfPath = copySWF('www')), 
searchHighlight = TRUE,
pageLength = 5,                         
autoWidth = TRUE,
initComplete = JS(
"function(settings, json) {",
"$(this.api().table().header()).css({'background-color': 'orange', 'color': '#2c2c2c'});",
"}")), filter='top', class="stripe compact nowrap", 
rownames = FALSE, 
server=TRUE
)`

I modeled my code after https://rstudio.github.io/DT/extensions.html.

Any suggestions for changes to my code are appreciated.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. Finally, it is also worth noting that TableTools is retired software and is no longer being actively developer.
