### ISSUE TITLE
filtering with OR condition and regex

### ISSUE THREAD

**Issue by alvarotrigo** [DataTables/DataTables#736]
How can I filter using the OR condition? 
I was trying to make it work this way but doesn't seem to be working.

```javascript
tablePlugin.fnFilterAll('(rating1|rating2)+', 18);
```

I tested the regex in https://regex101.com/ and it seems to be ok as you can see [here](https://regex101.com/r/cZ1mF5/2).

I was not able to find any example in the docs about it.

**Comment by DataTables** [comment]
You need to disable DataTables' own built in smart filtering - see the [API reference](http://datatables.net/reference/api/search()).

In future, could you post support questions in the [DataTables forums](//datatables.net/forums) as requested int he Contributing document that GitHub links to when opening a new issue. Thanks.
