### ISSUE TITLE
Cannot read property 'anCells' of undefined

### ISSUE THREAD

**Issue by lemattmatt** [DataTables/DataTables#737]
Hello, 

I use dataTable (version 1.10.10),keyTable (version 2.1.0) and editor(version 1.5.2). 
I use Excel navigation as in the example on your site : Excel like keyboard navigation
But I have trouble when I arrive on the last page of my navigation table using the navigation keys.
Error : " Uncaught TypeError: Cannot read property 'anCells' of undefined " 

if I change the file code : jquery.dataTables.js (line 8656) 

	_api_registerPlural( 'cells().nodes()', 'cell().node()', function () {
		return this.iterator( 'cell', function ( settings, row, column ) {
	              if(settings.aoData[ row ]){
				var cells = settings.aoData[ row ].anCells;
				return cells ?
					cells[ column ] :
					undefined;
			}
		}, 1 );
	} );

This problem is resolved with this correction. 

I'd like your feedback about this error.

**Comment by DataTables** [comment]
Could you link to a test case showing the issue please. Also, in future, could use use the [forums for support requests](//datatables.net/forums) - thanks.

**Comment by DataTables** [comment]
Going to close for now as no test case has been provided to be able to reproduce the error. If this is still an issue, please reopen with a link to a test case.
