### ISSUE TITLE
bower packages does not ship sort icon

### ISSUE THREAD

**Issue by linquize** [DataTables/DataTables#740]
bower packages does not ship sort icon
DataTables 1.10.10
datatables.net-dt 1.10.9

```
bower install datatables.net
bower install datatables.net-dt
```
I have `js` and `css` folders, but no `images` folder

**Comment by linquize** [comment]
https://github.com/DataTables/Dist-DataTables-DataTables/blob/03c27f9/bower.json

did not put `images` files into `bower.json`

**Comment by DataTables** [comment]
Thank you for letting me know about that. I've [fixed it now](https://github.com/DataTables/Dist-DataTables-DataTables/commit/9988567e0282a15931ae8e5e17dc7d7fa4dd4d2a). The Foundation styling package had a similar issue.

Can bower use files from the HEAD? This fix will be available with 1.10.11 which will probably be released in January.

**Comment by DataTables** [comment]
1.10.11 is now available.

**Comment by linquize** [comment]
:)
