### ISSUE TITLE
Incorrect links for 7-zip and WinZip on DataTables download page

### ISSUE THREAD

**Issue by tomascassidy** [DataTables/DataTables#741]
The DataTables download page has a section at the bottom to notify Windows users about the default unzip software.  The links in this section for 7-zip and WinZip both point to https://datatables.net/download/builder?bs/dt-1.10.10 when they should be pointing to the websites for 7zip and WinZip.

**Comment by tomascassidy** [comment]
![datatables](https://cloud.githubusercontent.com/assets/301402/11773040/711293c8-a278-11e5-883e-e73d913bf13e.png)

**Comment by DataTables** [comment]
Thanks for pointing that out! As soon as any options were changes the links would be altered due to a selector that wasn't selective enough. Corrected now :-)
