### ISSUE TITLE
how to load datatable's data by POST?

### ISSUE THREAD

**Issue by tianxuzhang** [DataTables/DataTables#745]
I can't find a way to load datatable's data by POST some query conditions. How should I do?

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums).

Also, please see this example: http://datatables.net/examples/server_side/post.html .
