### ISSUE TITLE
sort icon is not included in column width calculation

### ISSUE THREAD

**Issue by louking** [DataTables/DataTables#746]
With jqueryui formatting, sort icon pushes into next column header. Local modification of css can be used to pull sort icon into correct header, but column width calculation does not include the icon, causing icon to overlap with column text.

See https://www.datatables.net/forums/discussion/32077/sort-icon-pushes-into-next-column-header for details.

**Comment by DataTables** [comment]
It looks like this was cased by a custom style that removed the padding on the header cell. The padding allowed the space for the sort icon to be shown. See the discussion linked to above.
