### ISSUE TITLE
update npm version

### ISSUE THREAD

**Issue by hugofqueiros** [DataTables/DataTables#747]
A plain npm install --save datatables, points to package version 1.10.9, it should be 1.10.10.
As a workaround, on my package.json, I am declaring it as: "datatables": "DataTables/DataTables"

**Comment by DataTables** [comment]
I would suggest using `datatables.net` - see [DataTables NPM documentation](http://datatables.net/download/npm) - however, yes, this should be updated- thanks.

**Comment by hugofqueiros** [comment]
Thank you for the quick reply.
Will use that package from now on!
I am a little confused thou as why there is a package datatables and another datatables.net, one pointing to version 1.10.9 and the other to 1.10.10.
Installing datatables-responsive (and not the datatables.net-responsive), provided the first hint that something was wrong because it is asking for the datatables.net package.

 * @version     2.0.1-dev
 * @file        dataTables.responsive.js

define( ['jquery', 'datatables.net'], function ( $ ) {

datatables npm package is being dropped? Or rather it can just be used now for plain datatables with no extensions?

No warning on npm installation and no indication on readme file to the DataTables NPM documentation. It would be great if you added that to the Readme file :), and maybe a warning on the old packages/extension packages.

**Comment by DataTables** [comment]
As I say, the 1.10.9 tag is out of date. That needs to be updated.

> datatables npm package is being dropped? 

Deprecated in favour of the new distribution packages. I will update that.

**Comment by hugofqueiros** [comment]
Thank You
