### ISSUE TITLE
Webpack: Uncaught TypeError: Cannot read property 'defaults' of undefined

### ISSUE THREAD

**Issue by simkessy** [DataTables/DataTables#750]
I'm trying to add DataTables to my project using webpack but I'm now getting this error: 

My entry file looks like this: 

```
require('expose?$!expose?jQuery!jquery');
require('datatables.net-jqui');
require('datatables.net');
require('datatables.net-jqui/css/dataTables.jqueryui.css');

```

This was working perfect, then I dunno, stopped working and my webpack bundle kept giving me errors. 

These are the versions I'm working with: 
```
    "jquery": "^1.11.3",
    "jquery-ui": "^1.10.5",
    "datatables.net": "^1.10.10",
    "datatables.net-jqui": "^1.10.10",
```

**Comment by DataTables** [comment]
What errors do you get?

In future, could you post support questions in the [DataTables forums](//datatables.net/forums) as noted in the contributing document. Thanks.

**Comment by simkessy** [comment]
This is pretty much all I get:
>Uncaught TypeError: Cannot read property 'defaults' of undefined

If I inspect further it leads to this area: 
```
/* Set the defaults for DataTables initialisation */
$.extend( true, DataTable.defaults, {
    dom:
        '<"'+toolbar_prefix+'tl ui-corner-tr"lfr>'+
        't'+
        '<"'+toolbar_prefix+'bl ui-corner-br"ip>',
    renderer: 'jqueryui'
} );
```

**Comment by DataTables** [comment]
Odd - I'll try to take a look in the next couple of weeks.

**Comment by simkessy** [comment]
Update, the error  was coming from

require('datatables.net-jqui');

I removed jquery-ui modules to see if I could get DataTables working at all with the styling and the error I get is:

>dataTable is not a function

**Comment by DataTables** [comment]
I've just tried:

```js
require('jquery');
require('datatables.net');
require('datatables.net-jqui');
```

Then: `webpack main.js out.js`

And it builds as expected:

```js
Hash: bd5df46e50612f371716
Version: webpack 1.12.10
Time: 639ms
 Asset    Size  Chunks             Chunk Names
out.js  734 kB       0  [emitted]  main
   [0] ./main.js 78 bytes {0} [built]
    + 3 hidden modules
```

**Comment by simkessy** [comment]
I spent hours trying to get it working this weekend, eventually it just started working again. I have no explanation. I see in my original post that `jqui`was first, maybe that was the issue, I don't know. Thanks a lot for the response.

**Comment by DataTables** [comment]
No worries - good to hear it is working now.
