### ISSUE TITLE
Famous "TypeError: invalid 'in' operand obj" while click on sorting icons

### ISSUE THREAD

**Issue by yurg** [DataTables/DataTables#753]
hi there,

my environment: 
datatables: //cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js 
jquery: jQuery JavaScript Library v1.11.3

all works almost fine (mentioning this since the error in many cases appears right at datatables init), but click on column sort gives  (line 577 col 6 of jquery.js)

 > TypeError: invalid 'in' operand obj
 > return - 1; 

I've seen some bits of advice here and there (incl. multiply instances at stackexchange), but haven't been able to find exact resolution of  sorting issue. Will you please advice? Thanks in advance!

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

**Comment by DataTables** [comment]
Going to close for now. If still an issue please link to a page showing the issue.
