### ISSUE TITLE
How to get the final/formatted data of a cell? (dt 1.9.4)

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#754]
Hi,

How can I get cell displayed data (data that being redneder from aoColumns->mData), 

Till now I got the raw data from `settingsDt.aoData` from `_aData`, I did notice that `asDataSearch ` holds the *formatted data* as the table but its not inside any data structure, but a plain string which make it unusable to me, any ideas on how I can get the final data from the `settingsDt` object?

See test case https://jsfiddle.net/0ztkz9ey/53/

https://github.com/vedmack/yadcf/issues/275

**Comment by DataTables** [comment]
Don't get it from the settings object - get as little as you possibly can from the settings object. Its properties can, will and do change between versions. It is considered to be a private API and a change in it is not considered to be a breaking backwards compatible change.

In this case you want to use the [`cells().render()` API method](http://datatables.net/reference/api/cells().render()) to get the rendered data.

**Comment by vedmack** [comment]
Thanks, but how can I get this info in datatables 1.9(4) ?

**Comment by DataTables** [comment]
There is no option for that in legacy DataTables I'm afraid.
