### ISSUE TITLE
Filter cancel button cut off when using Safari and Foundation styling

### ISSUE THREAD

**Issue by dwsc** [DataTables/DataTables#756]
When using the Foundation styling, the filter cancel button is cut off on the right hand edge of the text input.  This can be seen on the demo page here: https://datatables.net/examples/styling/foundation.html
<img width="687" alt="foundation_datatables_filter" src="https://cloud.githubusercontent.com/assets/6210388/12310110/a4236526-ba0b-11e5-958b-149baac71be1.png">

**Comment by DataTables** [comment]
It appears to work as expected for me:

![screen shot 2016-01-15 at 17 27 15](https://cloud.githubusercontent.com/assets/278219/12360016/3fe0bdea-bbad-11e5-9ad0-36e9c0c13aba.png)

What browser are you using? Mine was Chrome 46 Mac

**Comment by dwsc** [comment]
It only appears in Safari.  I'm seeing it on 9.0.2.

**Comment by DataTables** [comment]
It looks like a bug in Foundation. Here is an example that shows a search input with foundation only - no DataTables: https://jsfiddle.net/zt8o60qf/ . It shows the same issue in Safari.

I'd suggest getting in touch with the Foundation folks about this. I'm not sure if they are maintaining 5.x any more - I doubt it to be honest with 6.x out now. I'm still working on my integration for DataTables and Foundation 6.

**Comment by dwsc** [comment]
Thanks, you are definitely correct on that.  Turns out it's an issue with WebKit itself: https://bugs.webkit.org/show_bug.cgi?id=111843.  I appreciate you pointing me in the right direction.
