### ISSUE TITLE
Uncaught TypeError: Cannot read property 'anCells' of undefined

### ISSUE THREAD

**Issue by panatapattu** [DataTables/DataTables#758]
I am getting this error when I am using the datatable. This error coming from dataTables.fixedColumns.min.js.

How can I fix this. Because it is giving error pop up message.

Either how can I disable all alerts from datatable.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
