### ISSUE TITLE
Feature Request: Add a row at a specific index

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#759]
Is it possible to use row.add() to add a row at a particular index?

Thanks.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums).

If you did a search in the forum you would find that this question has been asked a few times before - for example: [1](https://datatables.net/forums/discussion/11899), [2](https://datatables.net/forums/discussion/29147), [3](https://datatables.net/forums/discussion/660), [4](http://www.datatables.net/forums/discussion/235).

As noted there, the ordering of the table is defined by the sorting applied to it. So if you want the row at a particularly position, must make the sorting put it there.

**Comment by jamezamm** [comment]
Thanks. You should update the row.add() and rows.add() documentation to reflect what you just told me.

**Comment by DataTables** [comment]
[Committed](https://github.com/DataTables/DataTablesSrc/commit/3cd230e2f12035792318137cd79c8191c6492e69). Thanks!
