### ISSUE TITLE
table header does not scollX with body

### ISSUE THREAD

**Issue by louking** [DataTables/DataTables#760]
I've done some debugging on this and concluded that it is a bug not a configuration problem. I've been found to be mistaken on that before, however. If so, sorry for the noise.

please see https://www.datatables.net/forums/discussion/32625/cell-header-does-not-scrollx-with-body

**Comment by DataTables** [comment]
Looks like an error in a third part CSS file. Let's continue the discussion in [just one place](https://www.datatables.net/forums/discussion/32625).
