### ISSUE TITLE
editor-inline event "key-blur" firing twice (when using tab between columns)

### ISSUE THREAD

**Issue by cloudybrain** [DataTables/DataTables#762]
So I was following the demo described here:

https://editor.datatables.net/examples/inline-editing/tabControl.html

Where I'm tabbing between columns. Everything works as expected. But I wanted to do some validations on each input. So when a user tabs out of a field, a pop up would show up indicating that the value isn't within a valid range.

So I added this:

    ("#example").on('key-blur', function (e, datatable, cell) {
        alert("did you click me?");
    });

So when I hit the "enter" button on my keyboard, nothing shows up. Then when I click on a field, this alert box shows up (which shouldn't happen), and when I blur away, it shows up again. Apparently the demo in that page breaks this kind of functionality. Is there a way for this event to fire if you hit the "enter" button?

Also if you use an alert box, the character of tab gets inserted inside the textbox when tabbing. I'm thinking this event shouldn't really be used in this demo. But I need a way to get functionality during the onBlur part.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). That way everything is searchable in a single place.
