### ISSUE TITLE
Trying to destroy(): TypeError: b.nTableWrapper is null

### ISSUE THREAD

**Issue by ricardovigatti** [DataTables/DataTables#763]
I'm getting this error when trying to destroy.

```TypeError: b.nTableWrapper is null```

Code:
```
var table = $(".dataTable").DataTable();
table.destroy();
```

Could be my jQuery version ? I'm using **jQuery v2.1.4**

**Comment by DataTables** [comment]
Sorry if the contributing document isn't clear enough - could you please direct support requests to the [DataTables forums](https://datatables.net/forums), ensuring that you provide a link to a test page that shows the problem and a full description of the issue. If you require urgent help, [priority support](https://datatables.net/support) is available.

This is a test case showing your code working with jQuery 2.1.4: http://live.datatables.net/waxoxure/1/edit

Could you post a link in this thread to the forum post with the test case showing the issue when you post it. Thanks.

**Comment by ricardovigatti** [comment]
@DataTables thank you for reply. After take a look at the test case you've sented, i could do some tests and i found the problem.

Before initializing my dataTable, i was extending it using the **$.extend**:

    $.extend(true, $.fn.dataTable.**defaults**, {
        "language": {
            "url": "/themes/admin/assets/plugins/datatables/i18n/Portuguese-Brasil.json"
        },
        "pageLength": 25,
        "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "Todos"] ]
    });

When the correct syntax should be:

    $.extend(true, $.fn.dataTable.**settings**, {
        "language": {
            "url": "/themes/admin/assets/plugins/datatables/i18n/Portuguese-Brasil.json"
        },
        "pageLength": 25,
        "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "Todos"] ]
    });

**Comment by DataTables** [comment]
Good to hear you got it working :-)
