### ISSUE TITLE
Server returns data processing

### ISSUE THREAD

**Issue by guohuihot** [DataTables/DataTables#764]
![image](https://cloud.githubusercontent.com/assets/3119995/12742726/5b1b9c0a-c9c3-11e5-828a-7488ac6b4e6f.png)
![image](https://cloud.githubusercontent.com/assets/3119995/12742764/8e2d0dae-c9c3-11e5-8e47-723c1847cb35.png)

The server returns the data in the image above, how to deal with it.

**Comment by DataTables** [comment]
Could you post support requests in the [DataTables forums](//datatables.net/forums) as the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) that GitHub links to on opening a new request mentions please. I'm sorry if that document wasn't clear enough on that topic.

For your question, you would need to use the [`xhr` event](http://datatables.net/reference/event/xhr) or [`ajax` option](https://datatables.net/reference/option/ajax) as a function to modify the return from the server.

**Comment by guohuihot** [comment]
I mean there is no way to deal with the data returned by the server. Like the following
```
$('#xxx').dataTable({
    ajaxDone: function(data) {
          draw: draw,
          recordsTotal: data.index.data.pageCount,
          recordsFildered: data.index.data.pageSize
    }
})
```

**Comment by DataTables** [comment]
You can use one of the options that I mentioned to convert the JSON data from the format returned into the format DataTables required.

**Comment by guohuihot** [comment]
I do not understand your meaning, I want a way to return the data processed into datatable want the data, can give me an example, thank you

**Comment by DataTables** [comment]
Have a look at the documentation for the [xhr event](http://datatables.net/reference/event/xhr).

There you can do something as simple as:

```js
json.recordsTotal = json.index.pageCount;
// etc
```

**Comment by guohuihot** [comment]
oh,I see! thanks

**Comment by guohuihot** [comment]
```
$table
                    .on('xhr1.dt', function ( e, settings, json, xhr ) {
                        console.log(json);
                        var jsonE = {
                            draw : draw,
                            recordsTotal : json.index.pageCount,
                            recordsFildered : json.index.pageCount,
                            data : json.index.data
                        };
                        json = jsonE;

                        console.log(json);
                        // Note no return - manipulate the data directly in the JSON object.
                    } )
                    .dataTable(tableCfg)
```
Hello, is not in the event XHR data format can only be an array, when the data is an object, it is reported to the wrong

**Comment by guohuihot** [comment]
![image](https://cloud.githubusercontent.com/assets/3119995/12772002/8e7945c0-ca68-11e5-86cb-cf7a0f1209c8.png)
![image](https://cloud.githubusercontent.com/assets/3119995/12772044/cc8c9e16-ca68-11e5-8d11-578e08ff5dcc.png)

After debugging, the data is no problem, but json.recordsFildered and json.recordsTotal does not work, only 7 records, but the page is wrong

**Comment by DataTables** [comment]
`recordsFiltered` has a typo in it.

If you are still having an issue with this, please post your question in the [DataTables forums](//datatables.net/forums) and link to a test case showing the issue so I can debug it.
