### ISSUE TITLE
order option index not zero based anymore?

### ISSUE THREAD

**Issue by Argonanth** [DataTables/DataTables#766]
I just upgraded from 1.10.4 to 1.10.10 and I noticed all of my tables were sorting incorrectly with the order option. For example where I used to be using order: [4, 'desc'] I now have to use order: [5, 'desc']. I looked through all the release notes between .4 and .10 but didn't see any mention of this.

Is this a bug or was this done on purpose at some point (Or maybe it's something on my end)?

I should also mention an external plugin I'm using to group rows by columns is also affected by this so it might be something else other than the order option specifically.

**Comment by DataTables** [comment]
No change or bug that I'm aware of in DataTables that would cause this. Indeed the default order uses index 0 and that works.

Could you post support questions in the DataTables forums with a link to a test case in future please (one place for all rather than in multiple locations).

**Comment by DataTables** [comment]
Going to close this on for now as no test case has been provided. If this is still an issue please open a thread in the forums with a link to a test case. Thanks!
