### ISSUE TITLE
Best solution to integrate the html code in rows of DataTables

### ISSUE THREAD

**Issue by walslayer** [DataTables/DataTables#767]
Hi everyone, 

Could you say me what is the best solution to integrate the html code (like a button) in rows of DataTables ?
I use Ajax to populate my table.

Thanks

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums).

In this case you could use the `render` function to create HTML dynamically - [see the documentation](http://datatables.net/manual/data/renderers)
