### ISSUE TITLE
where conditions in ssp php class

### ISSUE THREAD

**Issue by Ghazimetallica** [DataTables/DataTables#769]

**Comment by jhyland87** [comment]
I guess it's a really good thing that Allan can predict what the issue is with absolutely no description in issues at all... or else this would be a really useless ticket... ;-)

**Comment by Ghazimetallica** [comment]
hahahaha in fact i posted this question when i was very tired of coding couldnt figure out the solution
2 min later i solve it
so i tried to remove this post so i dont bother you but failed :p

**Comment by DataTables** [comment]
Thanks for the update.

The contributing document that GitHub links to when opening a new issue notes that support request such as your original question should be directed to the [DataTables forums](//DataTables.net/forums). Thanks.
