### ISSUE TITLE
Select extension: selector-modifier {selected: true} strange behavior

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#773]
Using jQuery DataTables 1.10.10 and Selector extension 1.1.0. 

The following code returns `undefined` even when there are rows selected.

    $('#example').DataTable().column(0, {selected: true}).data();

This returns no data either:

    $('#example').DataTable().columns(0, {selected: true}).data();

However the code below works:

    $('#example').DataTable().rows({selected: true}).data();

See [this jsFiddle](https://jsfiddle.net/xr3bLe7n/) for code and demonstration.

**Comment by DataTables** [comment]
That sounds correct - you noted you have rows selected, not columns. If you have columns selected then `columns( ..., {selected: true})` would get the selected columns.

**Comment by mpryvkin** [comment]
I see now, thanks for explaining.

However documentation never mentions that in order to use `selector-modifier` `{selected: true}` with `cell()`/`cells()` and `column()`/`columns()` I have to use either `select()` API method first with these methods or change `select.items` from `rows` to `columns` or `cells`.

I believe the following sections are unclear about the fact that in order to use `selector-modifier` `{selected: true}` with columns or cells they have to be selected through API or by changing `select.items` option where rows works by default.

http://datatables.net/extensions/select/integration#Selected-items-retrieval
http://datatables.net/extensions/select/examples/api/get.html
http://datatables.net/reference/type/selector-modifier#selected
