### ISSUE TITLE
Datatable width inside bootstrap modal problem

### ISSUE THREAD

**Issue by rhyudek1** [DataTables/DataTables#774]
Hi,

I made an update with bower and now the tables within the bootstrap modal do not reach 100% width. attached screenshots

![captura de pantalla de 2016-02-17 12 14 32](https://cloud.githubusercontent.com/assets/647189/13113956/1fb3fa32-d570-11e5-82d2-baddd0b35ed3.png)

style automatically added?
> style="width: 0px;"

![captura de pantalla de 2016-02-17 12 19 45](https://cloud.githubusercontent.com/assets/647189/13114098/caf1cd0c-d570-11e5-8045-c5529114479e.png)

regards

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please. Also, in future, could you direct support requests to the [DataTables forums](//datatables.net/forums). Thanks.

**Comment by rhyudek1** [comment]
Ok, I'll do for the next time.
The following link is the test case

[http://codepen.io/anon/pen/xZepYa](url)

regards.

**Comment by DataTables** [comment]
Thanks. You need to call the `columns.adjust()` method when the modal is shown. See [this example for a similar use case](http://datatables.net/examples/api/tabs_and_scrolling.html).

Also add `width="100%"` to the table tag (or `style="width:100%"`).

http://codepen.io/anon/pen/QyPREq
