### ISSUE TITLE
oLanguage.sInfo issue

### ISSUE THREAD

**Issue by pisapapiros** [DataTables/DataTables#775]
Hello,

I have a problem translating oLanguage.sInfo when there are more than 999 entries. The variable _TOTAL_ is wrong. 

Eg:
Showing 1 to 50 of 5,601 entries -> 1 bis 50 von 5undefined601 Einträgen

Code:
`$.extend($.fn.dataTable.defaults, {
	"oLanguage": {
		  "sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
		  ...
	}
});`

DataTables version:
1.10.7

I'm not sure if this is actually an issue or I have something wrong in my configuration. Thanks!

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
