### ISSUE TITLE
Is it possible to add a custom orthogonal key to data: or render: coldefs?

### ISSUE THREAD

**Issue by kjhangiani** [DataTables/DataTables#776]
I am currently using the syntax found in this ticket: https://github.com/DataTables/DataTables/issues/496 
to define various data sources for sorting and filtering (using html5 data attributes).  

We use dom sourced initialization, but we define `columns:` in the initialization so that we can access columns via `.columns('<col>:name')`.  However, when defining a `name` attribute in columns, jquery-datatables doesn't respect the `data-order` and `data-filter` attributes on columns.  The ticket linked previously was very helpful here, and I managed to resolve that part of my problem by defining columns as

```
{  name: 'first_name', data: { _: 'first_name.display', sort: 'first_name.@data-order', filter: 'first_name.@data-filter' } }
```

Now however, I am trying to extend this a step further with the buttons extension, specifically the export csv button.  My issue is that I want to define a new attribute called `export` (similar to `type`, `sort`, and `filter`), and use that very clean syntax to do `export: 'first_name@data-export'`

However, this does not seem to work - datatables seems to only recognize keys for the built in ones.  

I know I can use the `render` or `data` helpers as functions, but this makes it rather tedious to access `data-export` as the source because the function has to go through a few hoops to access the dom-node.  

Is there a way to configure datatables to allow a custom key like `export` in the `data` or `render` coldef objects that I can use the cleaner `@data-export` syntax on?

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
