### ISSUE TITLE
Ajax sourced data is not refreshing

### ISSUE THREAD

**Issue by JellyM** [DataTables/DataTables#777]
I'm using jQuery DataTables plugin with ajax source.

It works great as expected. I delete and restore records via ajax request. Once delete / restore request is done, I refresh the data listing.

Unfortunately when there is only 1 data on the table and I delete it, it successfully deletes the record and sends the refresh the data listing request.

The request is successfully executed but since there is no record, it doesn't update the data listing on the table.

If I press F5 to refresh the page, then I get "No Results" text displayed as it should.

I checked the ajax request upon page reload (F5) and when I delete record, both gets the same response which is;

{"sEcho":1,"iTotalRecords":0,"iTotalDisplayRecords":0,"aaData":[]}
I must mention if there are more than 1 records, it successfully updates the records.

Is there a reason why it can't update displayed records when the single record is deleted?

**Comment by morrow95** [comment]
Not sure if this will help you or not, but I use serverSide and to 'refresh' the table whenever I make changes I call `dt.draw();` where dt is the table.

Can you add a snippet of code where your 'refresh' is happening and if whether you are using serverSide or not.

**Comment by JellyM** [comment]
I create them dynamically

    $(".datatable").each(function() {
        var $element            = $(this),
            dataTableUrl        = $element.attr("data-url"),
            dataTable           = $element,
            options             = {
                "bServerSide"       : true,
                "sAjaxSource"       : dataTableUrl,
                "aLengthMenu"       : [[10, 25, 50, 100], [10, 25, 50, 100]],
                "order"             : [[0,"desc"]],
                "bAutoWidth"        : false,
                "paging"            : true,
                "ordering"          : true,
                "info"              : true
             },
        
        // Generate dataTable
        tables[$element.attr("id")] = $element.dataTable(options);
    });

If I call `tables.tableID.draw()` I get `TypeError: tables[table].draw is not a function` however I can refresh it with `tables.tableID.fnDraw()` or loading a new source with `tables.tableID.api().ajax.url("new-source.json").load()`

**Comment by DataTables** [comment]
Hi,

This isn't actually the appropriate place to ask support questions. As the [Contributing document notes](https://github.com/DataTables/DataTables/blob/master/Contributing.md):

> Please direct support requests to the [DataTables forums](https://datatables.net/forums), ensuring that you provide a link to a test page that shows the problem and a full description of the issue.
