### ISSUE TITLE
_fnVisbleColumns doesn't work on invisible tables

### ISSUE THREAD

**Issue by jods4** [DataTables/DataTables#779]
`_fnVisbleColumns` (with a typo) is defined like this:
```javascript
function _fnVisbleColumns(oSettings) {
    return (_pluck(oSettings.aoColumns, 'nTh')).filter(':visible').length;
}
```

The problem is that this will not work if the table is not visible, e.g. inside a `<div style=display:none>`.
In my application we have tabs implemented like that and this is an issue. 
Specifically: when the table is empty, an empty row is added by the following Datatables code:

```javascript
anRows[0] = $('<tr/>', { 'class': iStripes ? asStripeClasses[0] : '' }).append($('<td />', {
    'valign': 'top',
    'colSpan': _fnVisbleColumns(oSettings),
    'class': oSettings.oClasses.sRowEmpty
}).html(sZero))[0];
```

And of course, `_fnVisbleColumns` returns 0, so the `colspan` is all wrong when the tabl gets displayed later on.

I fixed the issue by patching the function like so:
```javascript
function _fnVisbleColumns(oSettings) {
    return oSettings.aoColumns.filter(c => c.bVisible).length;
}
```

And everything seems to work fine (this is ES5 code, you may want the ES3 equivalent in Datatables official distribution).

**Comment by DataTables** [comment]
Thanks for noting this - however that issue should have been fixed here: https://github.com/DataTables/DataTablesSrc/commit/9946f7c81e530c0fcf65f0bd38ea5364741bb268 . I'll rebuild this distribution repo.

Also yes, although arrow functions are awesome (ES6 / ES2015, rather than ES5) DataTables core still supports as far back as IE6 at the moment (albeit not for too much longer!).

**Comment by jods4** [comment]
Nice! 
I upgraded to `1.10.11` and still had the issue, so I assumed it wasn't noticed yet!

Yeah I know... I used `.filter` and arrow functions by convenience because I only support IE11 in my app. :smile:

Do you know when a release wil be available?

**Comment by DataTables** [comment]
Ah - IE11+ only. You are a lucky person!

I'm not sure about the release yet - probably the end of March. Going to wait a bit for any other issues to trickle in.
