### ISSUE TITLE
Access column properties

### ISSUE THREAD

**Issue by brunjick** [DataTables/DataTables#781]
I'm trying to access column properties with `DataTables.Api` object, but can't find out how. I can view `.settings()` object from Chrome debugger and there is `aoColumns` array, which is what I need, but can't access within my code, it returns undefined. I want to clarify that, I don't want to change anything in columns, just need to check if column is declared as `searchable: true`.

**Comment by DataTables** [comment]
`settings()[0].aoColumns[].bSearchable` is the **private** parameter that will give you that information. However, that is a private parameter - it may change in future. There is currently no public API method to get that information - I'll be adding it in future though.

Could you please ask support questions in the [DataTables forums](//datatables.net/forums) in future please, as requested in the Contributing document that github links to when opening a new issue. Thanks.

**Comment by brunjick** [comment]
Ok, now I got it. sorry for that
