### ISSUE TITLE
Broken after jQuery 2.2.1 Update

### ISSUE THREAD

**Issue by Leotomas** [DataTables/DataTables#782]
Hi, 

After we've updated our jQuery version to 2.2.1 (released 9 days ago), datatables stopped working, with the following error : "TypeError: $(...).DataTable is not a function". We therefore rolled back to an earlier version of jQuery.

Cheers,

**Comment by DataTables** [comment]
Seems to work well here - http://live.datatables.net/kebuwode/1/edit . Please link to a test case.

Also, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) that github links to when opening a new issue, please post support requests in the [DataTables forums](//datatables.net/forums).

**Comment by Leotomas** [comment]
We are using dataTables browserified. I can't really link my whole bundled js but we had the above-cited issue until we rolled back jQuery. 

here is the package.json though [http://pastebin.com/4kMXWkKx](http://pastebin.com/4kMXWkKx).

DataTables is called in our JS just simply '$( Element ).DataTable'

**Comment by DataTables** [comment]
I'm afraid I'm not sure what help I can offer - as I noted, there doesn't appear to be any issues with jQuery 2.2.1 and DataTables. My best guess is that jQuery is being loaded twice, but without a link to a page showing the issue there is no help I can offer.

**Comment by Leotomas** [comment]
Alright, I'll link a full test case with the browserified bundle by the end of the day.

**Comment by DataTables** [comment]
No feedback on this issue - going to close for now. Please reopen with a link to a test case if still an issue.
