### ISSUE TITLE
[TWBS4] pagination ellipsis element causes line break

### ISSUE THREAD

**Issue by torbjoernk** [DataTables/DataTables#783]
With Twitter Bootstrap 4 (at least) the pagination has a line break when using _simple_numbers_ as `pagingType`. The line break is caused by the _ellipsis_ button's `li` not having the `page-item` class applied.

The workaround/fix I'm currently using in my project relies on being able to use the full Sass sources of TWBS 4.
Then, simply extend `div.dataTables_wrapper div.dataTables_paginate ul.paginate li` with `.page-item`:
```{sass}
div.dataTables_wrapper div {
  &.dataTables_paginate {
    ul.pagination {
      li {
        @extend .page-item;
      }
    }
  }
}
```

**Comment by DataTables** [comment]
It seems to work without issue on the [Bootstrap 4 example](http://datatables.net/examples/styling/bootstrap4.html). To get the extra rows to show ellipsis in the paging control you can use the following on the browser's console:

```js
var table = $('#example').DataTable();
table.rows.add( table.data() ).draw()
```

Can you link to a test case showing the issue please.

**Comment by torbjoernk** [comment]
See http://torbjoernk.github.io/jlesc.github.io/about/people/ at the very bottom. The fixed version is at http://jlesc.github.io/about/people/.

I've forgotten to mention, that I'm not using TWBS 4.alpha-2 but the current dev-4 branch.

**Comment by DataTables** [comment]
It looks like you are using the Bootstrap 3 integration for DataTables:

In your Javascript it contains:

```
/*! DataTables Bootstrap 3 integration
 * ©2011-2015 SpryMedia Ltd - datatables.net/license
 */
```

You want to use the Bootstrap 4 integration if you are using Bootstrap 4 :-). Those files are available on the DataTables CDN:

* http://cdn.datatables.net/1.10.11/js/dataTables.bootstrap4.min.js
* http://cdn.datatables.net/1.10.11/css/dataTables.bootstrap4.min.css

For grab them from [DataTables/DataTablesSrc](/DataTables/DataTablesSrc) as you prefer.

I should note that the Bootstrap 4 integration for DataTables core is complete, but the extensions haven't yet have their integrations updated.

**Comment by torbjoernk** [comment]
m( I did really messed that up when switching to TWBS4. Sorry for the noise and thanks for the hint.

**Comment by DataTables** [comment]
No worries :-). The BS4 integration for DataTables is very new.
