### ISSUE TITLE
Title tag in Worpress is not working using DataTables plugin

### ISSUE THREAD

**Issue by FacturaPuntoCom** [DataTables/DataTables#784]
Hi. 

I notice my title tag is not working well when I use DataTables.
I'm using it in a Wordpress site. The title of the site change to the URL when finish of load. 
If I comment the line where I import DataTables the title works well.

Do you know if this plugin is not compatible with any other plugins?

Hope you can help me to find the problem solution!

Thanks.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
