### ISSUE TITLE
Documentation for table().node()

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#785]
On the documentation page for [`table().node()`](http://datatables.net/reference/api/table%28%29.node%28%29) correct example should be:

```
var table = $('#example').DataTable( {
    scrollX: "100%"
} );
 
$( table.table().node() )
    .addClass( 'highlight' );
```

**Comment by DataTables** [comment]
Thank you - fix committed [in the src repo](https://github.com/DataTables/DataTablesSrc/commit/b8ace57995131a13bc835e019812ef5eff7d536a).
