### ISSUE TITLE
minimal version of php

### ISSUE THREAD

**Issue by stojankukrika** [DataTables/DataTables#787]
HI,
I use datatable to shows records from database to user. In my localhost it's works great but on client server it's shows me an error "An error occurred while connecting to the database. The error reported by the server was: could not find driver". And I do not know how to solve it. Is that any minimal version of PHP  that datatable req.? I use mysql and php(5.2.8).

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums).

The issue you are seeing here suggests that the PDO driver for MySQL hasn't been installed on the PHP server. You would need to refer to the PHP documentation to install the correct driver. Typically package managers will have a suitable package, particularly if you are using using.

**Comment by stojankukrika** [comment]
OK.TNX. Now I see in phpinfo() -> "PDO drivers-sqlite ". TNX :+1:
