### ISSUE TITLE
There should be three sorting states even after clicking the column title (th).

### ISSUE THREAD

**Issue by Alex1990** [DataTables/DataTables#793]

**Comment by DataTables** [comment]
I'm afraid I don't understand based on just the title. What is the third state?

**Comment by Alex1990** [comment]
Three states:

- Click 1: asc
- Click 2: desc
- Click 3: unsorting or original sorting

But, now, I think it's a little demand. Sorry, I'll close this issue.

**Comment by DataTables** [comment]
You are correct, there doesn't appear to be much demand for this, but there is #526 which asks for exactly the same thing.

Add a :+1: there to vote for it :-)
