### ISSUE TITLE
ajax.data using json.stringify it appends double quote to last parameter

### ISSUE THREAD

**Issue by ezekel** [DataTables/DataTables#797]
Hi @DataTables ,

If i tried to use the JSON.stringify in my serialize formdata, it appends double quotes to the last parameter. it works fine if I remove the JSON.stringify.

```
 ajax:{
                url: 'myurl',
                data:function ( d ) {
                     return JSON.stringify( formdata ); //formdata is serialize
                }
            },

```

**Comment by DataTables** [comment]
Can you provide a link to a test case showing the issue so it can be debugged please.

**Comment by ezekel** [comment]
Hi @DataTables ,

Here is the [fiddle](https://jsfiddle.net/shu7o6xm/17/)

Regards
ezekel

**Comment by ezekel** [comment]
Hi @Datatables,

In the fiddle I just log it in the console and in the parameter tabs you can see the double quotes appended.

Thank you.

**Comment by DataTables** [comment]
Your `formdata` variable is a string already - that's what [`jQuery.serialize` will return](https://api.jquery.com/serialize/). So yes, passing it through `JSON.stringify` will add quotes (you can see the leading quote at the top of the parameters):

```
"fromedate:2016-04-04
frometime:00:02
todate:2016-04-22
totime:23:00"
```

If you want to submit a string, just return the string: https://jsfiddle.net/shu7o6xm/18/ .

I'm not sure you want to submit a string though - I'd imagine you want to get either an object of the values, or a name / value pair array. See [$.serializeArray](https://api.jquery.com/serializeArray/) for the latter. I don't think jQuery as a method for the former (although in this case it would probably be more useful). There are probably plug-ins for it.
