### ISSUE TITLE
Vector icons for column-sorting

### ISSUE THREAD

**Issue by HoldenCreative** [DataTables/DataTables#798]
Thanks as always for DataTables!

Our team revised the column-sort indicators (those little blue-purple triangles).  I thought you may want to use them in the main project since SVG is broadly compatible (note that the disabled indicator also needs to be created, but that should be simple with these files.)

[sort_arrows_svg_19px.zip](https://github.com/DataTables/DataTables/files/210775/sort_arrows_svg_19px.zip)

Due to the way that DataTables calculates the table header width when using "scrollable", SVG use should include a declaration of background-size - and - the SVG "canvas" itself should be matched to the expected rendering size (e.g., 19px, same as the current PNG file).

```
.dataTable thead .sorting {
  background: url("somepath/datatables/sort_both.svg") no-repeat center right;
  background-size: 19px;
}
```

Hope it is useful!

**Comment by DataTables** [comment]
Thanks for this - awesome! However, DataTables core currently supports IE6+ so I need to consider the no SVG case still. 

In the next major update I plan to use either SVG, inline sprites or Utf characters for the sort icons. I'm not sure which yet! My preference is currently Utf characters but it does limit the styling options.

**Comment by HoldenCreative** [comment]
Darn @ IE6.  Modernizer has a nice fallback approach described here, in case it helps:
https://css-tricks.com/svg-fallbacks/

@ Sort Icons - Have you considered using the "border-triangle" trick?  Super simple, easy to modify and IE6 compatible: http://mrcoles.com/blog/callout-box-css-border-triangles-cross-browser/

@ Next Version - You may remember that I wrote up a flexbox (two-way overflow scrolling) version of DataTables CSS.  I use a much more polished-looking version of the same method here.  If you'd be interested in coordinating on an updated CSS stack with fallbacks for older browsers let me know.  I'd have to justify it (somewhat) commercially but I'd like to contribute what time I can either way.

**Comment by DataTables** [comment]
Yes - that is most certainly an option with pseudo elements.

Thanks for offering some help with the updated CSS. I'm not sure I'm going to use flexbox yet. The next major update should still work with IE8 - I haven't decided what level of support to give it though. Likely it will be a few months before I can start on the next major update.

**Comment by HoldenCreative** [comment]
Sounds good.

No worries @ flexbox, yours to use if you want it! ~  Because the flex properties are exclusive, you can always declare it with older-style rules above those declarations for older browsers.  I've done that in a few cases.

Total aside: I also have a "list mode" CSS snippet available if you'd like to see a "table as list" approach.  I've used it in a few cases where I basically wanted the full row to be treated as a "hyperlink >" element.

**Comment by DataTables** [comment]
Sounds interesting. Do you mean something like this: https://css-tricks.com/responsive-data-tables/ ?

**Comment by HoldenCreative** [comment]
Hi Allan,

Actually something more like displaying a data table as a "selectable group of list-items" - random example: http://images.mobile-patterns.com/320/1430144364467-2015-04-26%2015.53.34.png

Incidentally, the reason I went to a flexbox -based DataTables layout here was because I wanted to avoid traditional responsive data tables css re-flows.  I'd had some success with the "flip scroll" method in the past but ultimately I wanted to preserve the visual integrity of the original table.

- Andrew

**Comment by DataTables** [comment]
Thanks for the link. That looks like it could nearly be displayed in a DataTable - although the sub text shown in grey there would need to be in the second cell in the table. Having said that, I can see that might be useful if it is a separate cell!

**Comment by HoldenCreative** [comment]
Thanks Allan,

The approach I took was to render HTML inside a single column DataTable.

I removed all padding via a conditional table CSS class and made the HTML element inside the <td> a single hyperlink, <a>, with properties to act as a flexbox.

From there I added whatever additional HTML I required with the hyperlink element.  This covered getting the clickable behaviours I wanted on all elements within, as well as alignments for chevrons, etc., without influencing DataTables behaviours and JS directly.

Sounds a bit complicated but it's only a few lines of HTML & CSS (and the rendering speed is just fine.)  Thought you may be interested.

**Comment by DataTables** [comment]
Yup - sounds very interesting. Always interested to see how DataTables is being used!

**Comment by HoldenCreative** [comment]
Always great using it! ~ closing this issue now, let me know if I can assist you in the future.
