### ISSUE TITLE
Lazy Loading from javascript function 

### ISSUE THREAD

**Issue by lastMove** [DataTables/DataTables#799]
Add the ability to lazy load datas from a javascript function (not ajax). 
For instance :
I am using parse.com or equivalent. 
Instead of giving a URL to perform an ajax Request (with server-side) ; I want to be able to load lazily supplementary data.
It would be like : add a function in parameter, *that takes ajax.data object and returns (though a callback or a promise) the data according to ajax.data parameters.*

Is it comprehensible ?
Sorry for my english, I am french.
Thanks and regards.

**Comment by DataTables** [comment]
Just use [`rows.add()`](https://datatables.net/reference/api/rows.add()).

**Comment by lastMove** [comment]
Hi @DataTables 
rows.add() doesn't answer to the problem : 
I need to do the *same thing* than from server-side (https://datatables.net/manual/server-side). 
But instead of providing an URL like this 
```javascript
$('#example').DataTable( {
    serverSide: true,
    ajax: {
        url: '/data-source',
        type: 'POST'
    }
} );
```
I want to provide a function 
```javascript
var dataSourceFunction = function(data, cb) {
   var start = data.start;
   // asynchronous call to get corresponding results (example from Parse)
       PFQuery("_User").skip(start).limit(length).then(function(result) {
          cb(result);
       });
}
$('#example').DataTable( {
    serverSide: true,
   dataSource:dataSourceFunction
} );
```

**Comment by DataTables** [comment]
The [`ajax` option](https://datatables.net/reference/option/ajax) can be given as a function.
