### ISSUE TITLE
Clearing order does not work.

### ISSUE THREAD

**Issue by filiphr** [DataTables/DataTables#800]
In order to clear a order on the table I had a look at the https://datatables.net/forums/discussion/1440/how-to-reset-clear-sorting.

However, with the latest version of Datatables this is not possible. When I call ```table().order([]).draw()``` then I have a an exception. The exception is happening in the ```_fnSortFlatten``` function. The reason for this from what I could find out is the following is in the order function there is a check if ```order[0]``` is not array and then ```Array.prototype.slice.call(arguments)``` is called (and returns a list of an empty list). Shouldn't this be ```Array.prototype.slice.call(order)```.

**Comment by DataTables** [comment]
Thanks for noting this. I'll try to get it fixed for the next release. However, not that using `[]` will not result in the original data order being restored (that has never been the case) - you need to use [this plug-in](https://datatables.net/plug-ins/api/order.neutral()) to do that.

**Comment by filiphr** [comment]
I understant that using ```[]``` will not result in the original data order being restored. In my situation I just need the order cleared (the icons disabled on the headers).

Thanks for the plugin, I will also have a look at it, maybe it would be good to use it.

**Comment by DataTables** [comment]
[Fix committed here](https://github.com/DataTables/DataTablesSrc/commit/91a3581a1c030835bead900b938ef07840f44ca5). I'm syncing it to this repo at the moment - it should be in here, and thus in the nightly, shortly.

Thanks for letting me know about this one!

**Comment by filiphr** [comment]
No problem. Thanks for the quick fix.

Cheers
