### ISSUE TITLE
Table with hidden columns is not correctly displayed in Firefox

### ISSUE THREAD

**Issue by filiphr** [DataTables/DataTables#804]
I am not sure if this is a bug in the DataTables plugin or it has something to do with Firefox.

When using ```colgroup``` to define the sizes of the columns and when I have a hidden column via ```columnDefs``` then the table is not rendered correctly in Firefox. The reason for this is that the columns are not there, but the col group is not omitted from the rendered table, and for some reason Firefox treats the colgroups as they are given.
Please have a look at [this jsfiddle](https://jsfiddle.net/tv04qsfc/4/) to see what I mean. In Firefox there is space left on the left side and in Chrome and IE the tables is displayed correctly (100%). Maybe the col from the hidden columns should be removed?

Thanks,
Filip

**Comment by DataTables** [comment]
Hi,

Could you possibly post support questions in the [DataTables forums](//datatables.net/forums) please. That allows all issues to be collected in a single, searchable, location.

It sounds like there is an issue here. I'll try to take a look in the next few weeks. Thanks for letting me know about the issue.

**Comment by filiphr** [comment]
Hi,

I will post a question in the forum as well. I just thought that this is more of some kind of bug.

Cheers,
Filip

**Comment by DataTables** [comment]
It probably is - but I'd prefer to have everything in a single location :-). I'll probably close the issue tracker on this repo in the future.

Thanks for move it over!

**Comment by vsspt** [comment]
@DataTables, could you please inform me what is the state of this issue?

The user @filiphr has created the issue on Datatables forums [here](https://datatables.net/forums/discussion/34592/table-with-hidden-columns-is-not-correctly-displayed-in-firefox), but there is no reply.

Thanks in advance.

**Comment by DataTables** [comment]
I've added a reply now - sorry for the massive delay. Its a limitation in DataTables at the moment.
