### ISSUE TITLE
ajax.reload causes table to "flash" and doesn't keep responsive collapsed rows open.

### ISSUE THREAD

**Issue by tvirelli** [DataTables/DataTables#805]
Is there a way to stop the data from flashing on reload? I believe it is do to "processing" being TRUE or from "loadingRecords". Is there a way to disable this on additional reloads?

Also, on reload, if I use the responsive plugin and click the ( + ) button to see hidden data, on reload it closes again. is there a way to stop that and keep open rows open?

**Comment by DataTables** [comment]
Can you post support questions in the [DataTables forums](//datatables.net/forums) with a link to a page showing the issue, as requested in the GitHub new issue form and the Contributing document. That allows issues to be searchable in a single location. Thanks.
