### ISSUE TITLE
Upgrade from 1.10.7 breaks row highlighting with .active and Bootstrap

### ISSUE THREAD

**Issue by manderson23** [DataTables/DataTables#806]
On 1.10.7 adding "active" to a selected row would result in the following CSS being applied from the Bootstrap CSS and the row clearly highlighted in a dark blue colour.

`.table-striped.dataTable tbody tr.active:nth-child(2n+1) td, .table-striped.dataTable tbody tr.active:nth-child(2n+1) th 
{
    background-color: #017ebc;
}`

From 1.10.8 onwards it seems this selector has been removed and it is no longer obvious that the row is active.

I didn't see anything obvious in the release notes to indicate that this behaviour should change so I'm assuming it is a regression. Unless there is an alternative from 1.10.8 onwards?

**Comment by DataTables** [comment]
Row selection is provided by the [Select extension](//datatables.net/extensions/select) which also provides the required highlighting CSS. It was a bit of a hack how it was before with the CSS being mixed from various modules into the single Bootstrap file.

I did a fair amount of work at that time to fully separate them into individual modules. I had thought that was int he release notes, apologies for missing it! The Select extension is the way forward now - even if you only include the CSS should you not require the JS library.

**Comment by DataTables** [comment]
I forgot to say, could you possibly post support questions in the [DataTables forums](//datatables.net/forums) please, as requested in the github new issue form and the contributing document. I'm trying to built the forum into the go to searchable source for DT questions.
