### ISSUE TITLE
select element change event

### ISSUE THREAD

**Issue by YeZhiqiuSev** [DataTables/DataTables#807]
Hello,I'm trying to catch a event that return the select element's current options.my english is not good. I hope you can understand what i describe.
describe in detail: select array=[5,10 ,15,20]
when i finish the initComplete function ,I got the init length 5.I want get a function that when i change my select option to 10, it will return the length 10.
I'm looking forward to your reply.

**Comment by DataTables** [comment]
Hi - apologies if the "create new issue" template, or the contributing document were not clear enough, but please post support requests [in the DataTables forum](//datatables.net/forums). This is so there is a single searchable source of DataTables support issues.

Please ensure that you also link to a test case showing the issue.
