### ISSUE TITLE
Problems with the amount of columns in the table and the return of ajax

### ISSUE THREAD

**Issue by B1ll1** [DataTables/DataTables#808]
I want to add 2 columns with buttons so i can make some actions and here is my problem:
My ajax response give me 5 results and i want to have 7 columns but always when i try to search with this 2 extra columns i get the error "Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous".
Can I set the data of a column as null? I tried it in different ways but nothing worked. It only works if my ajax response have also 7 results;

**Comment by DataTables** [comment]
Hi - apologies if the "create new issue" template, or the contributing document were not clear enough, but please post support requests [in the DataTables forum](//datatables.net/forums). This is so there is a single searchable source of DataTables support issues.

Please ensure that you also link to a test case showing the issue.
