### ISSUE TITLE
Caching `recordsTotal`

### ISSUE THREAD

**Issue by fabiospampinato** [DataTables/DataTables#811]
When using an InnoDB table, counting how many rows there are at any given time will be surprisingly expensive to do, since it doesn't just store the number of how many rows it contains, like MyIsam does, so a full table scan will be performed no matter what.

This will only be a problem with medium to large sized tables. In my use case I have a table with ~700k rows and performing a `SELECT COUNT(*) as total FROM my_table` on a MacBook Pro takes around 150ms, which is a lot if we have to calculate it hundreds or even thousands of times a day. 

In this kind of case I don't really care if while browsing the table the records become 700.010 or 699.990, so it would be nice if we could not ask the server to calculate this number each time.

IMHO a solution to this will be pretty useful and straightforward to implement, we just have to send the current `recordsTotal` value to the server, which could then have the ability to return it back untouched or recalculate it again.

**Comment by DataTables** [comment]
Hi - could you use the [forums](//datatables.net/forums) for this kind of thing please? I'm trying to keep a single searchable source for DataTables related issues.

If you can estimate the row count, can you not just return that as `recordsTotal`? I don't understand the point about returning it back.

**Comment by fabiospampinato** [comment]
I forgot to say that this is not a problem if the table works fully on the client, but given the amount of rows of such table it would be crazy to do so.

The problem is, basically, that browsing pages from 1 to 10 will require another 10 * 150ms = 1.5s of waiting, which is unreasonable, and since DataTables is designed to always require a `recordsTotal` to be returned there's no easy way to avoid wasting time on this.

I'm just asking for DataTables to be able to not need a fresh `recordsTotal` after each ajax request, and I suggest an easy way to workaround the problem, which is letting the server know the previous estimate of `recordsTotal`.

**Comment by DataTables** [comment]
You could use `ajax.data` to send the current record count back to the server (it allows modification of the data submitted). However, it might be better to store this information in the server's session storage or using a cookie.

I'll think about it, but currently this isn't something I plan to put into DataTables core.

**Comment by fabiospampinato** [comment]
I understand. In case you could change your mind here there are some reasons I believe to be good enough for implementing my suggestion:

- No need for extra client-side code
- Adds an easy way to reduce database usage, and InnoDB is probably the most used storage engine for large tables in MySQL
- The most performance efficient, doesn't require any cookie or session setting on the server
- Backward compatible

A few reasons why using a cookie or a session variable might not be good:

- It needs extra code for assigning an ID to each table, since we may very well browse 2 tables at the same time
- Fails with expiration
  - If we set an expiration time we might face the situation where we make an ajax call after it and need to recalculate the number again, defeating its performance optimization purpose 
  - If we don't set it we might bloat the cookies or our session with useless data
  - In case the session is stored on the disk we'll perform a disk write operation, if it's saved on the database we'll pay for a query as well

Will you merge a pull request for this if I do it?

**Comment by DataTables** [comment]
Thanks for your thoughts on this - much appreciated! However, no, at this time I wouldn't take such a PR into the DataTables core. If there is more demand for it I would likely do so, but I think it would just serve to confuse other users at the moment (many have enough trouble with the existing simple parameters).

**Comment by fabiospampinato** [comment]
Doesn't look like something people could get confused about to me, perhaps just ignore, but it's your call not mine.

In case you'll change your mind my offer will probably still be available.

**Comment by DataTables** [comment]
Thanks :-). Going to close for now.
