### ISSUE TITLE
How to modify CSS of Header in export files and to add empty row after Header in Export?

### ISSUE THREAD

**Issue by bhumiradixweb** [DataTables/DataTables#815]
I am using Datatable Buttons extension and I want to modify Header with background color ,bold text, and font color. I tried below code but not working

 format: {
         //this isn't working....
         header:  function (data, columnIdx) { console.log(data);
              data = '<b>'+data+'</b>';
              return data;
         }
    }
Also, How to add empty row after the header in xls or CSV? Thanks

**NOTE:Support of Datatable forum is very poor, I have posted question there before 2-3 days and it is not approved there yet so posting here.** 

Please post support requests and questions in the [DataTables forums](//datatables.net/forums). Support requests posted here will be closed. This allows all questions to be located in a single, searchable, location.

When you post your question in the DataTables forums, please ensure that you include a link to the page showing the issue so it can be debugged.

**Comment by DataTables** [comment]
I've approved your post and added a [reply here](https://www.datatables.net/forums/discussion/348450).

I'm sorry you think my support is poor. I would ask that you keep in mind that I'm just one person and receive over 30 free support requests per day, in addition to those from paying customers. If you need urgent help there are priority support options available.

**Comment by bhumiradixweb** [comment]
Okay, but I am getting "Discussion not found." Error when clicked on the link.

Also, I can understand that to handle each and every request quickly is difficult but at least question display(approved) in the discussion would be great. There is no status so difficult to understand for a new user that you received a question or it was in spam.

Thanks.

**Comment by DataTables** [comment]
Sorry - I linked to one of the duplicate discussions that I deleted. [This is the correct link](https://www.datatables.net/forums/discussion/34845/).
