### ISSUE TITLE
ColReorder and original indexing

### ISSUE THREAD

**Issue by 719media** [DataTables/DataTables#816]
Original indexing is not respected after a col reorder.

Please see jsfiddle:

https://jsfiddle.net/719media/nwm96nv6/

**Comment by 719media** [comment]
Maybe I'm not understanding this syntax? This also does not work (column hidden)

https://jsfiddle.net/719media/z6r8be5y/

**Comment by DataTables** [comment]
> {'order': 'index'}

This applies to the row ordering, not the columns. [See the `selector-modifier` documentation](https://datatables.net/reference/type/selector-modifier#order):

> The `order` modifier provides the ability to control which order the rows are processed in. 

There is no option to get the columns in original index order using the selectors once a ColReorder has been performed. Having said that you can use the [`colReorder.transpose()` method](https://datatables.net/reference/api/colReorder.transpose()) to convert from a current column index to the original if you require.

**Comment by DataTables** [comment]
It looks like this is a [cross post from the forum](https://www.datatables.net/forums/discussion/3494). Could you post support questions in the forum only in future please? Otherwise its just doubling the work :-)

**Comment by 719media** [comment]
Sorry, I figured it was a bug. I'll try and verify things more thoroughly.

Re-reading the documentation, I can see where I misunderstood:

https://datatables.net/reference/type/selector-modifier#order

> The order modifier provides the ability to control which order the rows are processed in. This can have an effect on the return from chained functions - for example column().data() can return the data for the column in the order that the table currently shows the data, or in the original data order.

the column().data() sounded like it was talking about using the "order" parameter as a column-order filter. I can see now that it's referring to the previous sentence, the "order the rows are processed in" only, and not the column order.

Thanks
