### ISSUE TITLE
Filter issue In _createColumnsFilterStatement() instead of or_where() it should be where() 

### ISSUE THREAD

**Issue by anmolview** [DataTables/DataTables#818]
```
private function _createColumnsFilterStatement($like) {
        $str = "";
        # local filter
        if (!empty($like['local'])) {
            $str = "(" . implode(" OR ", $like['local']) . ")";
        }
        if (!empty($like['global'])) {
            $str = $str . ($str != "" ? ' AND ' : '') . "(" . implode(" OR ", $like['global']) . ")";
        }

        if ($str != "") {
            //$this->ci->db->or_where("(" . $str . ")"); replace with where
            $this->ci->db->where("(" . $str . ")");
        }
        return TRUE;
    } 
```

Filter  must be applied for both clause 'defined by user and search from application '
if we use 
- or_where :  return rows without  filtering user defined clause  
- where : return rows if both where clause's are true.

**Comment by DataTables** [comment]
I'm not sure where that code is in DataTables. I don't immediately recognise it. It looks like it might be some CodeIgniter code? Is that correct? If so, this isn't the correct place to post issues since I haven't published any CI code.

**Comment by DataTables** [comment]
No feedback so going to close this issue.
