### ISSUE TITLE
Unable to scroll columns horizontally

### ISSUE THREAD

**Issue by CodeFinder** [DataTables/DataTables#819]
I created table using fixed Columns and fixed Header of jquery datatables.
When table header is fixed, i can't scroll columns that are not fixed (using fixed columns) horizontally.
![1](https://cloud.githubusercontent.com/assets/5483800/15284238/2f14e47c-1b76-11e6-82a3-168004b2e9b0.PNG)

Pls, help me

**Comment by DataTables** [comment]
Sorry if the "New issue" template text and Contributing documents aren't clear enough. Please post support questions [in the DataTables forums](//datatables.net/forums) with a link to the page showing the issue.
