### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by legshooter** [DataTables/DataTables#823]
Hi Alan,

I know you (usually?) write about new releases on the blog, but I've just got notification about Select, Responsive, RowReorder, Buttons, ColReorder being updated, and I can't seem to find what has been actually updated (AKA a changelog), apart from being able to go over all commits of course.

I'm writing here since this concerns all plugins, so I didn't want to post it under one specific plugin.

I am trying to incorporate DT into my workflow and would like to rely on it heavily, and this is just one of the requirements.

This is also an opportunity to thank you for this project (which I personally look up to), your efforts, and most importantly your personal qualities and the way you conduct yourself, which are truly admirable.

**Comment by DataTables** [comment]
Its coming. I'm releasing all of the software first and will then deploy the release notes onto the site with a site rebuild. That should just be in a few hours once I've done the other things I need to for the release.
