### ISSUE TITLE
Possible to hide rows instead of removing them from the DOM

### ISSUE THREAD

**Issue by Stadly** [DataTables/DataTables#827]
A possibility to let rows that should not be displayed have `style="display: none;"` instead of being removed from the `DOM` would be very useful.

The use case I have in mind is when the table is part of a `<form>`-element and contains `<input>`-elements. When the rows are removed from the `DOM` due to paging or filtering, the contained `<input>`-elements will not be submitted when submitting the form. If the rows were hidden instead of removed, this would work beautifully.

**Comment by DataTables** [comment]
All rows are treated equally in DataTables at this time. Supporting `display:none` rows is not something I currently plan to add (also, even if it were added, it would just throw them away).

If this is something you need, just run `$('#myTable tr:not(:visible)').remove()` before you create the table.

**Comment by Stadly** [comment]
Thanks for the quick response. I don't think I was completely clear in my post.

I don't mean that DataTables should support rows that are not visible in the table, and not show these.

I mean the way DataTables work when hiding and displaying rows due to filtering and paging. Currently rows that are not visible in the current view are removed from the `DOM`. What I request is a way to let all rows remain in the `DOM` at all times, and just be made visible and invisible (for example using `style="display: none;"` on the `<tr>`-element). Then it would be possible to submit `<input>`-elements that are in the table, but not currently visible due to filtering or paging.

**Comment by DataTables** [comment]
I see - thanks for the clarification. I ran into compatibility and performance issues when I've tried that in the past. I think the compatibility is probably sorted in the latest browsers, but it would make options such as `deferRender` irrelevant.
