### ISSUE TITLE
Remove row of datatable is not selected

### ISSUE THREAD

**Issue by AX-NICOLAS** [DataTables/DataTables#828]
Hello,

I want to delete a line from my datatable but I can not. Indeed, I have a table users with a hidden field "id" of it. How can I delete this line ...

My use case is this: I have 5 operators that update at the same time a user list and it must therefore always be updated via WebSocket clients will be notified of the change. This WebSocket sends me "userId" was deleted from the user list.

I can not send indexRow because if other operators are not on the same page it all wrong.

thank you in advance

**Comment by DataTables** [comment]
Hi - my apologies if the information in the "New Issue" template text and "Contributing" document aren't clear enough (any suggestions on how to make them more clear are welcome).

Please post support questions in the [DataTables forums](//datatables.net/forums) with a link to a test page showing the issue.

Closing issue as noted in the template text.
