### ISSUE TITLE
Cant Select All on Input Text Boxes on Sortable Table Headers

### ISSUE THREAD

**Issue by kzap** [DataTables/DataTables#830]
In Chrome 51.0.2704.63 (64-bit) on OSX (doesnt happen on firefox)

The input boxes inside a table header which is sortable dont allow Select All, or CMD+A, or Edit Menu -> Select All.

If you put the input box in header that is not sortable or outside the TH tag, it works fine.

To replicate edit the html one of the sortable TH tags on this page:
https://datatables.net/examples/basic_init/table_sorting.html

From:
```
<th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 137px;">Name</th>
```

to
```
<th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 137px;">Name
<input type="text" name="test" value="test" />
</th>
```

Now try to select all the word test or anything inside the text box. Not a show stopping bug, just annoying and couldnt figure out how to fix it from the javascript code :)

**Comment by DataTables** [comment]
Can you please post support requests and bug reports in the DataTables forums in future.

In this case you should add a `stopPropagation()` to whatever event handler you are using for the input element.

**Comment by kzap** [comment]
ok assumed you were answering here so its ok to post here still, but will do
