### ISSUE TITLE
Problem with ColReorder and ColVis dropdown

### ISSUE THREAD

**Issue by daniapa** [DataTables/DataTables#832]
When I reorder some columns and then I try to hide or show it, the columns show or hide perfect, but in the dropdown of the button Column visibility the class active is removed in the actual column index and not in the column original index.

You can try it in your own page [https://datatables.net/extensions/colreorder/examples/integration/colvis.html](url).
For example, try to reorder the first column "Name" to the third place after "Office", and then try to hide "Name" column. The dropdown shows like if the "Office" column is hided.

And thanks for all, this plugin is awesome!!!

**Comment by DataTables** [comment]
Hi. Thanks for posting this. There was a [thread on the forum](https://www.datatables.net/forums/discussion/35423) about it yesterday. Let's track it just there rather than here as well (I prefer to use the forum as a single location for issue and bug tracking).
