### ISSUE TITLE
on(), off(), one() does not handle multiple events properly

### ISSUE THREAD

**Issue by mbudde** [DataTables/DataTables#836]
From the documentation on `on()` [1]:

> Multiple events can be listened for using a space separator and events can be namespaced, just like with `jQuery().on()`.

But when registering to multiple events (without namespaces) only the last event will trigger:

``` js
table.on('select deselect', ...);
```

The problem is that `on()` (and friends) tries to append the `.dt` namespace but does not take into account that there may be multiple events [2].
A workaround is manually adding the namespaces:

``` js
table.on('select.dt deselect.dt', ...);
```

[1] https://datatables.net/reference/api/on()
[2] https://github.com/DataTables/DataTables/blob/3a432c5/media/js/jquery.dataTables.js#L9172-9175

**Comment by DataTables** [comment]
Thank you. Yes - this is most certainly a bug that needs to be fixed!
