### ISSUE TITLE
Is there any life cycle hook on preCreateRow?

### ISSUE THREAD

**Issue by Emiya0306** [DataTables/DataTables#839]
I think it is very useful that we can add a event before the row create. It can do many custom things on that. 😄

**Comment by DataTables** [comment]
Apologies if the information in the Contributing document and also the GitHub new issue template isn't clear. Please ask support questions in [the DataTables forums](//datatables.net/forums).

Currently DataTables has a `createdRow` callback that you can use to modify the row.

**Comment by Emiya0306** [comment]
@DataTables Yeah~ But I meet some things to deal with must before render the row. Just like open the ServerSide mode, then get the data, finally add a special <td> which has buttons to edit, delete the row at the end of the <tr>. 

The table headers may be ["Article", "Abstract", ""(empty<tr>)], with "createdRow", I need to edit the backend data to ["title string", "content string", ""(empty string)], not a pure data structure. If no empty string, It will have an alert dialog. 

So it is necessary and a good idea to have a event hook before render the table row, and it will be more powerful and flexible to handle any thing with data table. 😎

**Comment by DataTables** [comment]
Thanks for the explanation. There is no option for a pre create callback at the moment. I'm going to look into how to improve the events in future and will consider this then.
