### ISSUE TITLE
Fixed header with filtering - loosing focus after each keypress

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#841]
Hi,

When using the fixed header and putting individual column filters in the header you can't really type into them because after each key type the focus is being lost

[see test case](https://jsfiddle.net/n2ybwhpv/5/)

(yadcf was used only to prevent sorting when clicking on filters)

https://github.com/vedmack/yadcf/issues/310

**Comment by DataTables** [comment]
Already been fixed with the 3.1.2 release of FixedHeader: https://jsfiddle.net/n2ybwhpv/7/ . The example above was using 3.1.1 which did indeed have this bug.
