### ISSUE TITLE
Disabling ordering of the first coulmn

### ISSUE THREAD

**Issue by kviktor** [DataTables/DataTables#843]
It seems that datatables tries to order by the first column by default, even if ordering is disabled on it, see: https://jsfiddle.net/LL6j97b5/ (there is an arrow in the header, if you click "Time" then it dissappears and can't click the first column anymore).

Setting the default order by column to the 2nd one fixes it: https://jsfiddle.net/bjurcdjL/

**Comment by DataTables** [comment]
This is correct. The `columns.orderable` option disabled the end users ability to order the column - the API could still be used. Thus you need to change the default as well.
