### ISSUE TITLE
colVis with ColReorder example is broken

### ISSUE THREAD

**Issue by paulgerman94** [DataTables/DataTables#846]
https://datatables.net/extensions/colreorder/examples/integration/colvis.html

Move columns and then hide one of the columns that you moved.

The column that you click is not the one that hides/shows.

Please fix this :D
Thanks!

**Comment by DataTables** [comment]
[It already is](https://github.com/DataTables/Buttons/commit/040482e4df45d0f2e31399c5138488a53feee632). The fix will be released as Buttons 1.2.2 in the next week or two. Until then use the [nightly version](//datatables.net/download/nightly).
