### ISSUE TITLE
Width difference between .dataTables_wrapper and .dataTable

### ISSUE THREAD

**Issue by legshooter** [DataTables/DataTables#847]
I am witnessing a tiny width difference between `div.dataTables_wrapper` and `table.dataTable`. It seems like `div.dataTables_wrapper` has a float value, while `table.dataTable` has an integer value.

For example, a table I am working with right now:
`div.dataTables_wrapper` width: `1264.52`
`table.dataTable` width: `1264`

I've tried initializing a new, almost completely empty table, with an empty options object, and I see the same phenomenon. 

My gut tells me this is something to do with jQuery rounding values, but I am not sure. 

This is obviously minor, but that half a pixel can be noticeable, and a pixel perfect design would be perfered.

**Comment by DataTables** [comment]
Can you open a [thread in the forums](//datatables.net/forums) with a link to a test case showing the issue so I can track and try to resolve it there please.
