### ISSUE TITLE
Datatables - Whole row child row control - Doesn't work

### ISSUE THREAD

**Issue by Explox** [DataTables/DataTables#848]
Hi,

Since a couple of days, I'm trying to implement the "Whole row child row control" feature at the :
https://datatables.net/extensions/responsive/examples/child-rows/whole-row-control.html
but I can't make it work. I trying like 50 times with differents ways but never worked. Do you have a template or anything that could help me please ?

**Comment by DataTables** [comment]
Feel free to open a thread in the [forums](//datatables.net/forums) with a link to the page you are working on. Closing this thread, since as the template text says, support requests should be made in the DataTables forums.
