### ISSUE TITLE
pageLength does not work with ajax calls

### ISSUE THREAD

**Issue by BafS** [DataTables/DataTables#850]
Hello,

I do some ajax calls with datatable but the lenght that datatable pass to the server (`data.length` here) is stuck at 45 (in fact it is proportional with `scrollY`). It seems to be a bug.

I use the *scroller* extension.

```js
    $('#folders-table').DataTable({
        serverSide: true,
        ordering: false,
        ajax: function (data, callback, settings) {
            console.log(data); // {…start: 0, length: 45…} here the length is stuck at 45

            jQuery.ajax({
                url: "http://localhost:8000/test",
                type: "GET",
                data: {
                    "page": data.start,
                    "length": data.length,
                }
            })
            .done(function (res, textStatus, jqXHR) {
                // ...
            })
        },
        pageLength: 10, // here is the problem
        scrollY: 200,
    });
```

Thanks.

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by DataTables** [comment]
No reply, going to close this issue for now. Please reopen with a link to a test case if this is still a problem.

**Comment by hovermind** [comment]
Closed without solution :(, facing the same problem

**Comment by DataTables** [comment]
As requested above, please link to a test case showing the issue.

**Comment by hovermind** [comment]
```
    $('#historyTable').DataTable({
        serverSide: true,
        pageLength: 50,
        scrollY: 200,
        ajax: function (data, callback, settings) {

            console.log(data.start);
            console.log(data.length);

            jQuery.ajax({
                url: "api/history",
                type: "POST",
                data: {
                    "page": data.start,
                    "length": data.length,
                }
            }).done(function (data) {
               callback(data); // data is properly formatted from server i.e. {data: "", draw: "",  recordsTotal: "" ...}
            });
        }
    });
```
I think Srcoller plugin causing the length issue. Without scroller, the length is ok (50). But when using Scroller, the table is not rendering after receiving json data from API (server is ok & ajax call is successful). So, I logged console.log(data.length) and found:   
- scrollY: 200 => length is 45
- scrollY: 300 => length is 54
- scrollY: 600 => length is 81 ...

Since length is not same as the rows returned from the server (server returns 50 per request), received data is not rendered at all.

**Comment by DataTables** [comment]
Yes - Scroller will change the page length dynamically. Use its [`displayBuffer` option](https://datatables.net/reference/option/scroller.displayBuffer) if you want to control how large an overflow buffer it loads.
