### ISSUE TITLE
Detecting when an object is a DataTables API object

### ISSUE THREAD

**Issue by Polyergic** [DataTables/DataTables#851]
I needed a way to detect when a javascript object is a DataTables API object, and could not find one in the documentation or forums.  I got a solution from [this stackexchange question](http://stackoverflow.com/questions/38667608):

    isDataTablesAPIObject = ( undefined !== myObjectVariable.$ && myObjectVariable.$.__dt_wrapper )

This solution depends on the undocumented property `__dt_wrapper`, so I cannot consider it reliable for future versions of DataTables.  It would be better to have a documented and supported method for detecting when an object is an API object.

**Comment by DataTables** [comment]
You could just use `instanceof` could you not? `myVar instanceof $.fn.dataTable.Api`.

**Comment by Polyergic** [comment]
That also appears to work.  How could I have found that in the documentation?  I tried all of the methods in [this answer](http://stackoverflow.com/a/1249554/776723), but didn't find things to use with `instanceof` or `isPrototypeOf`.  If the constructor is named `$.fn.dataTable.Api`, why does `myVar.constructor.name` return `"Object"`?

**Comment by DataTables** [comment]
In and of itself it isn't in the documentation - however, `instanceof` is [a part of Javascript](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/instanceof) and the fact that `$.fn.dataTable.Api` is the object to create a new API instance [is in the documentation](https://datatables.net/manual/api#Accessing-the-API) so the two follow.

> If the constructor is named $.fn.dataTable.Api, why does myVar.constructor.name return "Object"?

Not sure to be honest.
