### ISSUE TITLE
jQuery 3 Migrate deprecation warnings

### ISSUE THREAD

**Issue by tomascassidy** [DataTables/DataTables#853]
I just upgraded to jQuery 3 and I've loaded the [jQuery 3 migrate plugin](https://github.com/jquery/jquery-migrate).  It is picking up some usages of ```jQuery.fn.bind()``` which has been deprecated.  I'm guessing these could all be switched over to ```jQuery.fn.on()``` without causing any issues.

**Comment by DataTables** [comment]
Thank you - yes they could be. DataTables required jQuery 1.7+ and `.on` was introduced in 1.7, so they should be migrated over. Thanks for flagging this up.

**Comment by morrow95** [comment]
Second this - I just did the same the other day and even though it is only a deprecated warning it should be 'fixed' for clean and up-to-date code.  I didn't notice anything else, but a once over might be a good idea to make sure all the changes in jQuery 3 are taken care of.

**Comment by priley86** [comment]
+1, noticed the same issue. Will incorporate this fix in our [patternfly](https://github.com/patternfly/patternfly) framework once it's ready.

**Comment by DataTables** [comment]
[Fixed here](https://github.com/DataTables/DataTablesSrc/commit/b05edc5fe06e6ddac4e738d8fe580227d363579c). This repo will rebuild with the fix shortly and I'll probably release 1.10.13 before the end of the month.

**Comment by smenzer** [comment]
did you ever get a chance to release the new version with this fix? I don't see it on the CDN...

**Comment by DataTables** [comment]
I got side tracked. 1.10.13 is coming, but it isn't available yet as a release on the CDN.
