### ISSUE TITLE
Responsive and Scroller extensions without scrollCollapse

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#854]
There seems to be an issue with Responsive and Scroller extension when `scrollCollapse: true` option is not used, see [this example](http://jsfiddle.net/2oL768Ln/1/) for demonstration. Responsive extension hides third column even when all content fits the container.

When `scrollCollapse: true` is added, it works as expected, see [this example](http://jsfiddle.net/2oL768Ln/2/).

See [this discussion](http://stackoverflow.com/questions/38779353/datatables-hiding-column-on-its-own) on StackOvervflow for more information.

**Comment by DataTables** [comment]
Thanks for posting this. I've reposted it in [the Scroller repo](https://github.com/DataTables/Scroller/issues/66).
