### ISSUE TITLE
alert() in microtask executation deprecation warning in Chrome

### ISSUE THREAD

**Issue by rrauenza** [DataTables/DataTables#858]
FYI, I'm getting this message in the developer panel of Chrome.  

Since September 2016 is around the corner, I thought I'd make sure you were aware.

>Invoking 'alert()' during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

The stack trace goes back to _fnLog():

```
if ( type == 'alert' ) {
	alert( msg );
}
```

I wonder if it will need to be changed to console.log() to continue to get alerts?

**Comment by DataTables** [comment]
Can you tell me how to trigger that warning in Chrome? I'm not seeing it pop up.

I'm somewhat reluctant to use `console.log` (although it is a configurable option) as the default since the last time I set the default to that I got a _lot_ of questions from developers who didn't see the error message. Yes it means they are poor developers (could be phrased other ways!) or newbies, but the result was I spent a lot of time saying "Look at your console. What is the error message?". The `alert` means they can't miss it and they know that there is something to fix.

**Comment by rrauenza** [comment]
I've modified my code enough experimenting with other things that I've lost how I triggered it ... it's likely I was doing it with columns.data not matching the data in terms of dimensions.  Or my html table didn't match the data available.  

I'm all for keeping the alert() if technically possible -- it just sounds like chrome is deprecating that use case -- and I'm with you, I don't want to lose those alerts.  

I'll post a stack trace if I get it again -- I expect I will!

**Comment by DataTables** [comment]
If you could post a link to a page showing the issue that would be even better so I can debug it live.

**Comment by rrauenza** [comment]
Here's the example, https://jsfiddle.net/rrauenza/hhzqnyfw/, but I think what is going on is that because I'm mixing it with ReactJS, the datatable gets initialized within my component's componentDidMount(), which is probably called within a microtask -- (whatever that is)

....actually, I think my ReactJS component is invoked as part of an ajax call.  So I think that explains the XHR reference here https://www.chromestatus.com/features/5647113010544640

My jsfiddle doesn't include the React part of it .. so you won't see the error message.

Looks like they're delaying the release to M54:  https://groups.google.com/a/chromium.org/forum/#!topic/blink-reviews/Fw8JPVEcCbw

Here's the error message I'm getting, but I think it is irrelevant to the Chrome warning -- any alert done by datatables during an ajax request might be swallowed by Chrome in the future.

![image](https://cloud.githubusercontent.com/assets/1376251/17752839/8e67f658-6482-11e6-923b-4b68aa1857cf.png)

(Regarding my bad datatable config, I'm trying to figure out how to use columns.data on arrays of objects.  It's a work in progress.)

**Comment by rrauenza** [comment]
I'm not sure there's any action for you here, just a heads up that alert() will get swallowed soon on Chrome if any are issued during microtasks -- it's really an integration issue where I might be invoking your code within my own microtasks.  (I suppose it could show up in any internal ajax calls within DataTables.)

https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by DataTables** [comment]
Very interesting. This is the first I've heard of the microtask terminology but it makes a lot of sense and I can absolutely see why the Chrome devs would want to make sure it can't be interrupted with sync tasks.

I'm going to close this issue as "no change required", but its certainly useful knowledge. Thanks!
