### ISSUE TITLE
The Width="100%" attribute is not W3C compliant and produces an error

### ISSUE THREAD

**Issue by Jaded-Design** [DataTables/DataTables#859]
Unless I'm missing something there does not appear to be any way to properly render responsive datatables without using the width="100%" attribute in the table element. The problem is that this is not valid and is resulting in an error. 

Is there any plan to fix this so that tables can still be responsive without having to include this obsolete method?

**Comment by DataTables** [comment]
You can also use `style="width:100%"`.

The reason for that is that it is virtually impossible to get a percentage width from CSS without using either the `width` or `style` attributes.

**Comment by Jaded-Design** [comment]
Awesome, thanks!

**Comment by Jaded-Design** [comment]
Actually, that does not fix the issue. Here is a fiddle to test on: 

https://jsfiddle.net/ryanoc/ebRXw/

What happens is on resizes or changes the datatable will keep expanding and contracting at 100%. But if you take out the width="100%" and replace it with style="width: 100%" the table does not resize back to full window width. 

The reason this becomes a problem in a normal environment is due to datatables being hidden in tabs and in modals. If the width="100%" isn't set then these tables don't take up the whole space on show.

**Comment by DataTables** [comment]
You are using a very old version of DataTables. With 1.10.12 (the current release), this works as expected: https://jsfiddle.net/ebRXw/2111/ .

**Comment by Jaded-Design** [comment]
Knew I was missing something. 

Thanks for the help, it's much appreciated.
