### ISSUE TITLE
json data passed by Ajax POST unserialisable

### ISSUE THREAD

**Issue by swamikevala** [DataTables/DataTables#860]
Request payload is [object Object] when sent as datatables ajax object parameter. But when exact same parameters are issued as a regular $.ajax() request, the request payload is visible as serialised object 

See  [(https://datatables.net/forums/discussion/37099/ajax-object-post-data-error#latest]

**Comment by DataTables** [comment]
Rather than duplicating content, let's continue this discussion in the forum thread you linked to.
