### ISSUE TITLE
When using Ember.JS bug surfaces in _fnFilterCreateSearch

### ISSUE THREAD

**Issue by inventionlabsSydney** [DataTables/DataTables#865]
When using Ember.js version (my version is: `DEBUG: Ember : 2.7.3`) upon loading DataTables you'll receive an error `Uncaught TypeError: word.charAt is not a function` upon attempting to setup the search box.

This is because Ember.JS extends the prototype string by default.
However this only presents a problem on an empty string.

function param `word` results in returning an Ember Prototype string which doesn't have method `charAt` enabled.

```
    function _fnFilterCreateSearch( search, regex, smart, caseInsensitive )
    {
        search = regex ?
            search :
            _fnEscapeRegex( search );

        if ( smart ) {
            /* For smart filtering we want to allow the search to work regardless of
             * word order. We also want double quoted text to be preserved, so word
             * order is important - a la google. So this is what we want to
             * generate:
             * 
             * ^(?=.*?\bone\b)(?=.*?\btwo three\b)(?=.*?\bfour\b).*$
             */
            var a = $.map( search.match( /"[^"]+"|[^ ]+/g ) || '', function ( word ) {
                if ( word.charAt(0) === '"' ) {
                    var m = word.match( /^"(.*)"$/ );
                    word = m ? m[1] : word;
                }

                return word.replace('"', '');
            } );

            search = '^(?=.*?'+a.join( ')(?=.*?' )+').*$';
        }

        return new RegExp( search, caseInsensitive ? 'i' : '' );
    }

```

For anyone who wants to get around this currently I did so by disabling prototype strings on my ember stack in `config/environment.js`

```
  var ENV = {
    EmberENV: {
      EXTEND_PROTOTYPES: {
        String:false
       }
      }
   }
```

Reference to this configuration is located here: https://guides.emberjs.com/v2.8.0/configuring-ember/disabling-prototype-extensions/

I hope this helps someone else, I'm thinking a regular expression is needed to rule out this false positive?

Thanks,
Karl.

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by DataTables** [comment]
Going to close this issue for the moment. If you can provide a test case showing the issue, I'd be happy to look into it.
