### ISSUE TITLE
_fnBrowserDetect incorrect offset calculation

### ISSUE THREAD

**Issue by jddxf** [DataTables/DataTables#866]
Recently I came across an issue where a table is rendered when the document has a horizontal offset and the table header is misaligned.

See the following test case: [http://codepen.io/inamessnow/pen/yaVOpy](http://codepen.io/inamessnow/pen/yaVOpy)

I've found the value of browser.bScrollbarLeft is calculated using $.fn.offset, which gets the offset relative to the document. I think what we actually need here is the offset relative to the viewport, so  maybe getBoundingClientRect should be used.

**Comment by DataTables** [comment]
I suspect its this that is triggering the error:

> $('body').scrollLeft(50);

I'll dig into it a bit more and get back to you. Thanks for flagging this up.

**Comment by jddxf** [comment]
Yes, I added that line of code to simulate a situation where the document has a horizontal offset.

**Comment by DataTables** [comment]
[Fixed here](https://github.com/DataTables/DataTablesSrc/commit/158297910345e32ed34dd8ca2b8decbb3333d277). This repo and the nightly will be update to date shortly.

Thanks again!
