### ISSUE TITLE
Needed option:  columns.escape  |  boolean

### ISSUE THREAD

**Issue by kidplug** [DataTables/DataTables#868]
So that users dont have to define their own "render" function to safely HTML escape the text being inserted into the cells, you should provide a simple boolean option that can be toggled to true on the columns object.

Then internally, if the escape option is on, use a simple escape algorithm:

```
var entityMap = {
 				  "&": "&amp;",
 				  "<": "&lt;",
 				  ">": "&gt;",
 				  '"': '&quot;',
 				  "'": '&#39;',
 				  "/": '&#x2F;'
 				};
 		
		var escapeHtml = function(string) { 			
		  	return String(string).replace(/[&<>"'\/]/g, function (s) {
		    	    return entityMap[s];
		  	});
		}
		
	
```

As it is now, I have to define a render function like this:
```
	/**
		*  This can be used as a columns.render handler
		*/
		var cellEscape = function(data, type){
			if (type=="display"){
				return escapeHtml(data);	
			}
			return data;
		};
```

**Comment by DataTables** [comment]
There is a built in [text](https://datatables.net/manual/data/renderers#Text-helper) renderer which can be used to do this rather than needing to define it yourself.

**Comment by kidplug** [comment]
Cool thanks for the reply!  Might be nice to mention that in the columns.render documentation.

**Comment by DataTables** [comment]
Yup - good point. The examples, manual and reference all really need to link to each other a bit more. [This one is a start](https://github.com/DataTables/DataTablesSrc/commit/cb1442b8abb0c942eed926cec3430aaf9645bcc6).

Will be deployed to the site soon.
