### ISSUE TITLE
New rows not rendering when scroller extension is used

### ISSUE THREAD

**Issue by THemming** [DataTables/DataTables#870]
- DataTables instance that has the Scroller extension enabled
- Fairly large dataset (doesn't happen if the dataset is small)
- Default Scroller options
- Scroll to the last row in the table
- Use the DataTables API to add a row to the end of the table

**Expected**
It should render the new row.

**Actual**
It shows a blank space where the row should be.

This can be reproduced in the JSBin example http://jsbin.com/wuxukayiju/edit?js,output

If you scroll to the top of the table and then back down it draws the new row correctly (I guess this forces redraw and removes rows from the cache).

Also a short-term fix is to set the hidden scroller.boundaryScale option 0.

**Comment by DataTables** [comment]
Thanks for posting this and the test case. That most certainly looks like a bug in Scroller. I'll try to look into it as soon as I can.

**Comment by DataTables** [comment]
Fixed [here](https://github.com/DataTables/Scroller/commit/0d33437599fcfa8ad8a348ae1fc0d62d7bd6c44f). Will be included in the next Scroller release.

Thanks again!
