### ISSUE TITLE
Extra Parameter while ajax request

### ISSUE THREAD

**Issue by kumarchandan41** [DataTables/DataTables#871]
I am using Ajax datatables and when I use ajax request, it automatically appends an extra parameter 
```javascript
$('#users').DataTable( {
          ajax:{
            "url": `http://localhost:1337/users`,
            "dataSrc": ''
          },
          columns: [
            { data: 'id'}
          ]
      } );
```
But the endpoint it requests is `http://localhost:1337/users?_=1475135583469`

The extra parameter value changes everytime. My backend does not accept any extra parameters. How do i remove this?

**Comment by DataTables** [comment]
Apologies if the github "New issue" template and contributing document aren't clear enough. Please post support questions in the DataTables forums.

If you search the forums for your question, you would find this has been asked a number of times already - its the jQuery anti-cache parameter. See [for example this thread](https://datatables.net//forums/discussion/comment/49754).
