### ISSUE TITLE
Ordering on Chrome

### ISSUE THREAD

**Issue by ecesena** [DataTables/DataTables#874]
I have the following example not working on Chrome. It works, for instance, on Safari.
It seems an issue with ordering of strings.

```
<html>
<head>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script src="http://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
</head>
<body>
    <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ver</th>
                <th>sum__num</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>4.3.1</td>
                <td>4.00</td>
            </tr>
            <tr>
                <td>4.4</td>
                <td>1.00</td>
            </tr>
            <tr>
                <td>4.3.2</td>
                <td>2.00</td>
            </tr>
            <tr>
                <td>4.2.3</td>
                <td>5.00</td>
            </tr>
            <tr>
                <td>4.4.3</td>
                <td>5.00</td>
            </tr>
            <tr>
                <td>4.4.4</td>
                <td>1.00</td>
            </tr>
            <tr>
                <td>4.2.5</td>
                <td>3.00</td>
            </tr>
        </tbody>
    </table>
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
</body>
```

**Comment by ecesena** [comment]
Debugging a bit...

In Chrome the formatter is detected as "date-pre", while in Safari it's (correctly?) "string-pre".

This is because `Date.parse('4.3.1')` returns a number in Chrome, and NaN in Safari.

For the record, I'm testing on:
Chrome Version 53.0.2785.143 (64-bit)
Safari Version 10.0 (11602.1.50.0.10)

**Comment by DataTables** [comment]
Thank you. It looks like Chrome has relaxed its `Date.parse()` constrains recently. It was always quite lax, compared to other browsers, but now even things like `a 1` will return a number. This is a problem for certain and I'll need to add some code to protect against this.

I'll update here when done.

**Comment by ecesena** [comment]
Yeah, I've looked around and `Date.parse()` seems to cause issues all over the places :)

BTW, another useful use case would be auto-detecting versions (e.g. a regex with numbers separated by one or two dots?). The string comparison breaks as soon as you have 1.10 or similar expressions.

**Comment by DataTables** [comment]
> BTW, another useful use case would be auto-detecting versions (e.g. a regex with numbers separated by one or two dots?).

I think that would be an ideal use case for a plug-in. I had actually thought that there [was one already](https://www.datatables.net/plug-ins/sorting/) but it doesn't look like it. That would be a useful addition.
