### ISSUE TITLE
Two DataTable in One Page - Second one initialising weird

### ISSUE THREAD

**Issue by bmsedat** [DataTables/DataTables#875]
I opened a [stackoverflow question](http://stackoverflow.com/questions/40014410/two-datatable-in-one-page-second-one-initialising-weird), but I copy the question here too.

I have two dataTable in my page and I have a method like below:

    function ToDataTable()
    {
        $(".dataTable").css("width", "100%");
    
        $(".dataTable").each(function ()
        {
            var $that = $(this);

            /* Start of method */
            function ToDataTableInternal()
            {
               var table = $that.DataTable({
                   responsive: {
                       details: { type: "column", target: -1 },
                   },
                   columnDefs: [{
                           className: "control", orderable: !1, targets: -1,
                       },
                       { orderable: !1 }],
                   "paging": false,
                   "ordering": false,
                   "info": false,
                   "searching": false,
                    retrieve: true
               });
            }
            /* End of method */
    
            if ($that.is(":visible"))
            {
                ToDataTableInternal()
            }
            else
            {
                // Observe all invisible parents or table to trigger
                // ToDataTableInternal method if made visible
                var $arr = $(this).parentsUntil(":visible").filter(function ()
                {
                    return $(this).css("display") === "none";
                }).add($(this));
    
                var observers = [];
    
                $arr.each(function ()
                {
                    var observer = new MutationObserver(function (mutations)
                    {
                        mutations.forEach(function (mutation)
                        {
                            if ((mutation.attributeName === 'style' ||
                                   mutation.attributeName === 'class') && 
                                     $that.is(":visible"))
                            {
                                ToDataTableInternal();
    
                                for (var i = 0; i < observers.length; i++)
                                {
                                    // Disconnect observers
                                    observers[i].disconnect();
                                }
                            }
                        });
                    });
    
                    observers.push(observer);
                    observer.observe(this, {
                        attributes: true
                    });
                });
            }
        });
    }

The reason I have this method is that when table's display is `none`, it really lags browser(especially IE, where I cannot do anything for minimum of 5 seconds) which is the reason of that I'm changing the table to DataTable after it made visible.

But the problem with calling methods individually is the second DataTable doesn't have the same settings which I passed on. Instead, second one has filters, paging, sort elements in it too. 

If I call both at the same time, nothing out of ordinary happens. What may be the problem?

After some look throughs,	
It actually changes both of them to dataTable at the same time, but how? it isn't possible from the way I do things. but the problem I explained still happens.

I think the problem is that I have "dataTable" class in my table element, so it behaves this way,

**Comment by DataTables** [comment]
My apologies if the New Issue template text and Contributing document are not clear enough. Please ask support questions in [the DataTables forums](//datatables.net/forums) with a link to a test case showing the issue so I can help to debug the problem.
