### ISSUE TITLE
Horizontal scrollbar in fixed right column.

### ISSUE THREAD

**Issue by phiterf** [DataTables/DataTables#879]
I'm using the datatables and I have a fixed column with a button inside.

It's showing a horizontal scrollbar on the bottom, only in this one column. What could it be?

This is the code for the Datatable definition:

```
gridPrincipal = $("#grdPrincipal")
                        .DataTable({
                            autoWidth: true,
                            scrollY: 210,
                            scrollX: true,
                            destroy: true,
                            fixedHeader: true,
                            fixedColumns: {
                                leftColumns: 1,
                                rightColumns: 1
                            },
                            paging: false,
                            info: false,
                            searching: false
                        });

```

![sem titulo](https://cloud.githubusercontent.com/assets/12252332/19595504/f4de673c-9768-11e6-89ed-ea9beb11bf79.png)

The scrollbar only goes 1 pixel to both left or right, and I don't know why this happens since I have `autoWidth : true`

There is also a fixed column to the left and this one has no scrollbar, but it has no contents as well. They just have different background color.

**Comment by DataTables** [comment]
Good to hear you have a workaround. I'm afraid that without a test case showing the problem there isn't much I can do - so as you say, I'm going to close this for now.

**Comment by adanay** [comment]
Hello,
Can you explain better "I did fix the problem by reducing the button's padding by 1 pixel. I'm not sure if it will remain like this, but for now it's solved. You may close the issue."

I have exactly the same problem.

**Comment by phiterf** [comment]
@adanay , hello.

The button inside is a bootstrap flat button from AdminLTE's framework. But I did make some changes on it. 
I don't rememer the exact width and padding of the button, but for some reason when I removed 1 pixel of the padding, the scrollbar disappeared. 
Try reducing the padding of the elements within the cell, see if it helps.

**Comment by adanay** [comment]
This is what worked for me:

div.DTFC_RightBodyWrapper table tbody tr td {
  padding-left: 7px; /*bug fix of horizontal scroll-bar showing up in right fixed column*/
}

7 seems to be a magic number. Well there are some padding: 8px here and there (in the inherited styles) so I tried to reduce one pixel for my right fixed column and it made the magic!
