### ISSUE TITLE
visible:false is not work for the `fnStateLoadCallback`.

### ISSUE THREAD

**Issue by chiragsatapara** [DataTables/DataTables#881]
i am using a datatable and save the setting into the database for future set same view for the user.

is there any dependancy of the `time:1477136846997` ????

Here is my setting which is save into the databse:

`{"time":"1477136846997","start":"0","length":"25","order":[["1","asc"]],"search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"},"columns":[{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"false","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"false","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"false","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}},{"visible":"true","search":{"search":"","smart":"true","regex":"false","caseInsensitive":"true"}}]}`

and here is the code using which my setting is bind again to the datatable.

```
fnStateLoadCallback: function(settings) {
            debugger;
            jQuery("#divLoading").show();
            if (user_id != '' && user_id != undefined) {
                var o;
                jQuery.ajax({
                    url: "api/v1/dtsetting/" + orgmethod + '/' + user_id,
                    async: false,
                }).done(function(result) {
                    debugger;
                    result = result['data']; 
                    if (result == null) {
                        sett_id = '';


                    } else {
                        sett_id = result.id;
                        o = result;
                    }
                });
                if (sett_id != '') {
                    debugger;
                    var my_data = JSON.parse(o.settings);
                   // var new_return = set_data(my_data);
                    return my_data;
                } else {
                    return false;
                }

            }
        }
```
but it is display all the column in to the view .

Please help me to solve this issue.

**Comment by chiragsatapara** [comment]
Just need to update the time into the setting and it's work.

  if (sett_id != '') {
                    debugger;
                    var my_data = JSON.parse(o.settings);
                    my_data.time = +new Date();
                    return my_data;
                } else {
                    return false;
                }

**Comment by DataTables** [comment]
Thanks for the update, good to hear you have it working now.

In future, please post support requests in the DataTables forums, as requested in the "New issue" template.
