### ISSUE TITLE
Setting initial search value does not work

### ISSUE THREAD

**Issue by kasparsj** [DataTables/DataTables#882]
Setting search.search in options does not have the desired effect:
`$('#example').dataTable( {
  "search": {
    "search": "Fred"
  }
} );`

**Comment by DataTables** [comment]
It appears to work just fine here: http://live.datatables.net/foxebisu/1/edit .

In future, please post support questions in the forums as requested in the new issue template. Also link to a test case showing the issue.

**Comment by kasparsj** [comment]
Sorry, yes - my problem is the way I'm using it in conjunction with the "saveState" feature.
The default search gets overriden by the saved state search, even if "" is saved.
But I'm looking for a way to provide a default value, that would override the current state.

**Comment by kasparsj** [comment]
I see now, have to use stateLoadParams callback. Thanks!
