### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mData' of undefined

### ISSUE THREAD

**Issue by GuillaumeRossolini** [DataTables/DataTables#886]
Hi,

I just got the following error in Chrome Canary DevTools' console:
```
Uncaught TypeError: Cannot read property 'mData' of undefined
    at HTMLTableCellElement.<anonymous> (datatables.js:76736)
    at Function.each (jquery.js:374)
    at jQuery.fn.init.each (jquery.js:139)
    at HTMLTableElement.<anonymous> (datatables.js:76733)
    at Function.each (jquery.js:374)
    at jQuery.fn.init.each (jquery.js:139)
    at jQuery.fn.init.DataTable [as dataTable] (datatables.js:76408)
    at jQuery.fn.init.$.fn.DataTable (datatables.js:90644)
    at HTMLTableElement.<anonymous> (il.js:4885)
    at Function.each (jquery.js:374)
```

This is in datatables.js on this line:
```
var col = oSettings.aoColumns[i];

if ( col.mData === i ) {
```

One possible fix is to change these lines with:
```
var col = oSettings.aoColumns[i];

if ( col !== undefined && col.mData === i ) {
```

This fix surfaces another similar problem whenever the following is executed:
```
column = columns[i];
```

A fix for this could be to replace these lines with the following on every occurrence:
```
var column = columns[i];
if(column === undefined ) {
	continue;
}
```

Of course, this isn't the best fix. This might be happening because the code is iterating over a different collection (cells VS columns), and that might differ when the HTML isn't perfect or possibly when there is colspan/rowspan usage.

To help you reproduce, here are the comments at the top of the file I'm using:
```
/*
 * This combined file was created by the DataTables downloader builder:
 *   https://datatables.net/download
 *
 * To rebuild or modify this file with the latest versions of the included
 * software please visit:
 *   https://datatables.net/download/#dt/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.12/b-1.2.2/b-colvis-1.2.2/b-html5-1.2.2/b-print-1.2.2/cr-1.3.2/fh-3.1.2/kt-2.1.3/rr-1.1.2/se-1.2.0
 *
 * Included libraries:
 *   JSZip 2.5.0, pdfmake 0.1.18, DataTables 1.10.12, Buttons 1.2.2, Column visibility 1.2.2, HTML5 export 1.2.2, Print view 1.2.2, ColReorder 1.3.2, FixedHeader 3.1.2, KeyTable 2.1.3, RowReorder 1.1.2, Select 1.2.0
 */
```

Best regards,

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by GuillaumeRossolini** [comment]
Unfortunately no, this is for a back office behind authentication. I'll be hard pressed to provide a simple reproduce case.

**Comment by DataTables** [comment]
`col` should never be undefined at that point, which suggests there is another issue somewhere. Without being able to debug the page I can only guess. My guess is that the `columns` array and your HTML don't match in the number of columns.

**Comment by GuillaumeRossolini** [comment]
That's my guess as well, but the fix is easy and I'm sure you will find imperfect HTML everywhere, so maybe this is something you could include in a future release?

**Comment by DataTables** [comment]
Sorry - but that's invalid input. The HTML is probably fine, but the number of columns defined in the HTML must match the number in the `columns` array if you are using both.

**Comment by GuillaumeRossolini** [comment]
Which `columns` array? I'm not defining it, this is handled by the library.

Here are my initialization options:
```
let datatableOptions = {
	dom: 'Blfrtip',
	processing: true,
	colReorder: true,
	pageLength: currentPageLength,
	lengthChange: enablePagination,
	paging: enablePagination,
	ordering: hasPostForm ? false : true,
	order: [],
	searching: hasPostForm ? false : true,
	buttons: uiButtons,
	select: !hasPostForm,
	fixedHeader: {
		header: true,
		footer: false
	}
};
```

**Comment by DataTables** [comment]
As I said - I was guessing. Without the full information that's all I can do. If you could use JSFiddle or similar to reproduce a test case showing the issue, I would be happy to identify any issues in DataTables and fix them.

**Comment by GuillaumeRossolini** [comment]
Ok I found the core issue. There was a `table` that had a `tfoot` element but no `thead`. This breaks DataTable.

**Comment by DataTables** [comment]
Yes - [the `thead` is mandatory](https://datatables.net/manual/installation#HTML).

Thanks for posting back - good to hear you have it working now.

**Comment by GuillaumeRossolini** [comment]
Would you mind pointing me to the HTML spec on that, or is this specific to dt? I can always add a `thead` and hide it, or change my base selector on my end.
Could DataTable maybe ignore `table`s that don't have any `thead` element, even if there is a `tbody`?

**Comment by DataTables** [comment]
Specific to DataTables. [The `thead` is optional in HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table).

The reason it is required in DataTables is that it is used to get the column information. The only other option was to use the first row in the table if there was no `thead`. However, I didn't see an issue with requiring `thead` and it is also good for accessibility.

**Comment by GuillaumeRossolini** [comment]
The issue is not with requiring `thead`, I agree this is a good prerequisite. The issue is when there is a `tbody` but no `thead` in the same `table`: AFAIK this is allowed by HTML and browsers have never complained about it, but it breaks DT (when you apply DT globally on a back-office app, as we did).

**Comment by DataTables** [comment]
Yes- DataTables requires the `thead` as the documentation notes. You are correct that it is still valid HTML not to have that, but it isn't something that DataTables handles.
