### ISSUE TITLE
Documentation - rowCallback

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#888]
Link to `createdRow` is broken because of the missing backtick, see [`rowCallback.xml`](https://github.com/DataTables/DataTablesSrc/blob/master/docs/option/rowCallback.xml#L24). Should be fixed with 

    `dt-init createdRow`

**Comment by DataTables** [comment]
Thanks! [Fixed here](https://github.com/DataTables/DataTablesSrc/commit/0eb2fcf5ad965bf2f13fc4378a489282369792c9) and will be pushed out to the site soon.
