### ISSUE TITLE
with angular or vue, registerd event don't fire

### ISSUE THREAD

**Issue by luqingxuan** [DataTables/DataTables#890]
i use vue.js and datatable plugin in my project 
when i test my page with pc, it works fine,
 but when switch to phone, the responsive column,  just buttons, don't fire,
code like this:
\<td class="col-1"\>{{record.id}}\</td\>
\<td class="col-2"\>{{record.name}}\</td\>
....
\<td class="col-N"\>
    \<button @click="onClick1();"\>click1\</button\>
   \<button @click="onClick2();"\>click2\</button\>
\</td\>

there is a description(in chinese, but code, u konw),  when i search answer, it likes my question,
[https://github.com/ssy341/datatables-cn/issues/42)](https://github.com/ssy341/datatables-cn/issues/42)

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by DataTables** [comment]
Going to close this for the moment. If this is still causing a problem, please link to a test case showing the problem.
