### ISSUE TITLE
Column Reordering (colReorder) not working when calling the callback function in stateLoadCallback

### ISSUE THREAD

**Issue by vonboth** [DataTables/DataTables#891]
I'm using colReorder Plugin with DT 1.10.13 and colReorder 1.3.2
When returning the current state like so 
```
stateLoadCallback: function (settings) {
        var o;
        $.ajax( {
            url: 'some_url',
            async: false,
            dataType: 'json',
            success: function (json) {
                o = json;
            }
        } );
        return o;
    }
```
everything works just fine and the columns are reordered like saved in the state

But when using the new callback function in this way
```
$.ajax( {
            url: 'some_url',
            dataType: 'json',
            success: function (json) {
                callback( json );
            }
        } );
```
nearly everything works just fine except column re-ordering.
They are rendered like the initial state and are saved this way again back to the state.
E.g. instead ordering [0,2,1,3] they are ordered and saved [0,1,2,3]

**Comment by DataTables** [comment]
Apologies if the template text for new issues isn't clear enough. Please ask support questions in the [DataTables forums](//datatables.net/forums) with a link to a test case showing the issue. Thanks!
