### ISSUE TITLE
Table being entirely rerendered on column.visible() calls

### ISSUE THREAD

**Issue by brauliobo** [DataTables/DataTables#897]
In a table with 20 columns, every time I toggle visibility on a few columns, I can see that the entire table left is being rerendered, even on exclusive visible `false` calls. I can track rerendering through the custom render function. This is taking a few seconds (1-2s) even for hidding a couple of columns.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged and in this case a performance trace taken.

**Comment by brauliobo** [comment]
This isn't a question but a performance issue

**Comment by DataTables** [comment]
Could you post it in the forum with a link to a page showing the issue regardless please. The forums are the primary channel for DataTables support / issues.

**Comment by brauliobo** [comment]
the problem was with `redrawCalculations` which is on by default. it seems quite weird to have it on by default
