### ISSUE TITLE
language definition file blocked by cors

### ISSUE THREAD

**Issue by ChazyTheBest** [DataTables/DataTables#901]
Hi, my server is configured for cors, only this ajax request is being blocked and none of my other requests (css/js html requests) are.

So I think maybe the headers are missing in the ajax request?

**Comment by DataTables** [comment]
Possibly. We'd need a test case showing the issue.

Could you also ask support questions in the forums as the issue template and contributing documents request. Thanks!

**Comment by ChazyTheBest** [comment]
Thanks for the answer. But nvm, it was my fault, there was a typo in the config that wasn't enabling the header. The other requests (css/js imports) were not being blocked by cors because they are not subjected to the same-origin policy (sorry again, i wasn't well documented).

Also, the header is automatically sent by the browser, so all is good here :) And btw, thanks for this awesome plugin!
