### ISSUE TITLE
Multiple datatables export only the first's table data

### ISSUE THREAD

**Issue by gkio** [DataTables/DataTables#902]
i am trying to initialize 3 datatables with difference data but when i try to export data from second or first its return the data only from first table how cna i fix it

**Comment by DataTables** [comment]
Thanks for your question. However, per the new issue text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
