### ISSUE TITLE
Browser Compatiblity

### ISSUE THREAD

**Issue by HarsharanSingh007** [DataTables/DataTables#903]
Hi,

I am facing an browser compatibility issue with all versions of IE. It's working fine with Chrome, Mozilla and Microsoft Edge but not with IE. I searched and i got the solutions but i haven't found plugins in your site for IE as you have given. What are those extensions that i have to link to my datatables. Below is the screenshot attached for your page and of IE too.
![ie view](https://cloud.githubusercontent.com/assets/23027414/21796033/d3ee2bea-d72b-11e6-92e9-12d23ca1937b.png)
![compatibility](https://cloud.githubusercontent.com/assets/23027414/21796040/def12330-d72b-11e6-9768-d0d6209f8bf1.png)

Thanks in advance

**Comment by DataTables** [comment]
Thanks for your question. However, per the template "new issue" text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
