### ISSUE TITLE
jQuery is bundled with Browserify even if jQuery object is provided

### ISSUE THREAD

**Issue by luboskmetko** [DataTables/DataTables#905]
According documentation you can provide a jQuery object to DataTables require, otherwise it should do its own require. I assume if you provide the object, Browserify shouldn't bundle jQuery but in my tests it does.

```js
{
  "name": "test-datatables",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "browserify": "^13.3.0"
  },
  "dependencies": {
    "datatables.net": "^1.10.13"
  }
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test DataTables and Browserify</title>
</head>
<body>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="bundle.js"></script>
</body>
</html>
```

```js
console.log($);
var dt = require( 'datatables.net' )( window, $ );
console.log(dt);
```

Then when you run

```bash
browserify app.js -o bundle.js
```

the bundle.js includes jQuery. Not sure if this is a bug or I have wrong expectations here. The use case is when jQuery is already included on page for whatever reason, and how to avoid including it twice.

**Comment by DataTables** [comment]
I think what is happening here is that DataTables specifies jQuery as a dependency, so even although you are passing your own jQuery in, browserify is still seeing that dependency and thus including jQuery.

I don't really see a way around that without providing a separate repo that doesn't have that dependency.

**Comment by luboskmetko** [comment]
Thank you. I've just figured out that this can be avoided by using `--external` option.

```
browserify -x jquery app.js -o bundle.js
```

or for example in Gulp

```js
browserify(props).external('jquery').bundle();
```

**Comment by DataTables** [comment]
That's useful info - thanks!
