### ISSUE TITLE
Checkbox selection - thead checkbox

### ISSUE THREAD

**Issue by Thibault34** [DataTables/DataTables#907]
Hello,
In checkbox selection, the checkbox in thead not found.
Is this normal please?

https://datatables.net/extensions/select/examples/initialisation/checkbox.html

**Comment by DataTables** [comment]
No it shouldn't be there! Thanks for letting me know about that.

It was [caused by this commit](https://github.com/DataTables/Select/commit/062318c306cb06f86d753669b1d32c394dc739af).

[Fixed here](https://github.com/DataTables/Select/commit/b2045fe12566242388765877f55e209fd9b821b4).

**Comment by Thibault34** [comment]
It's possible add a checkbox for select all in thead please ?

**Comment by DataTables** [comment]
Yes, that is a feature I would like to add in future. I don't have a date for when I expect to implement it yet.

**Comment by Thibault34** [comment]
Thank you
