### ISSUE TITLE
Update nb selected row whene rows(selector).remove()

### ISSUE THREAD

**Issue by Thibault34** [DataTables/DataTables#910]
Hello,
When I use table.rows('.myClass').remove(), the number of select row is not updated.

I must be used :
table.rows('.myClass').deselect().remove().draw();

Can you help me please ?

**Comment by DataTables** [comment]
Yes - very happy to help. Can you post your question in the [DataTables forums](//datatables.net/forums) as indicated in the "New issue" template text. Thanks.
