### ISSUE TITLE
Language Settings requires "sThousands" to work

### ISSUE THREAD

**Issue by Nushio** [DataTables/DataTables#912]
Hi there!

I'm guessing this is rather uncommon, but while testing dataTables in Spanish I noticed that the "sInfoThousands" field wasn't being respected. 

I took the Spanish file from the CDN, and when displaying a table with over 1,000 rows, it would display "1undefined000" instead. Likewise, filtering would display undefined instead of ",". 

https://cdn.datatables.net/plug-ins/1.10.13/i18n/

To fix this locally, I added "sThousands": "," to my Spanish file. 

My guess is that fnFormatNumber is reading the sThousands property before it's been defined. 

I tested this with dataTables 1.10.13.

**Comment by DataTables** [comment]
Could you give me a link to a page showing the issue please? I've just tried it and it appears to work okay: http://live.datatables.net/jogajinu/1/edit .

**Comment by Nushio** [comment]
I see...

I think the problem is how I'm loading the language file. 

http://live.datatables.net/jogajinu/2/

**Comment by DataTables** [comment]
If you extend `language` rather than `oLanguage` it works okay: http://live.datatables.net/jogajinu/3/edit

**Comment by Nushio** [comment]
Hmm, alright! Then I guess this is a non-bug then. Sorry, and thanks for your time!

**Comment by DataTables** [comment]
I think it probably is a bug to be honest. But equally, its not one that I'm going to be able to prioritise fixing I'm afraid since the old hungarian notation is well on its way out now.

**Comment by Nushio** [comment]
I used oLanguage because that's how it worked back in 1.9. 

If it's going to be deprecated, I don't think it should be a bug, but it's up to you :-)
