### ISSUE TITLE
SSP.class.php - add socket configuration

### ISSUE THREAD

**Issue by srgraham** [DataTables/DataTables#914]
It would be useful to be able to edit the `socket` attribute when running `SSP::sql_connect($sql_details)` within `ssp.class.php`

Right now, I'm using a hack of setting `$sql_details['host']` to `'localhost;unix_socket=/path/to/socket'`

**Comment by DataTables** [comment]
That's a good hack :-).

The SSP script is really designed to be a demo script only. It is not designed to be the be all and end all. Instead, I would rather it was customised to suit different needs as they arise, such as this.

As such, I'm probably not going to make any chanced to the SSP class for this at the moment, unless there are others who want to vote for it as well.
