### ISSUE TITLE
Save The Last Page Number After Sorting Column In Jquery Datatable

### ISSUE THREAD

**Issue by dvlprsftwr** [DataTables/DataTables#922]
I am using jquery datatable to show data. I customize the paging function. For example each page has 10 record. First my function take 10 records. If user click next button then my function take more than 10 records. If user click 'previous' button and then my function save last page. Because if user click 'next' button then same records are not pull again. Existing records are shown. Thus the same records don't occur. But if the user never clicked the back button. And for example on page 3, if user sort coloumn and then table show first page with out saving last page number. So that if user click next button, after that same records will be fetch one more time. And same records wiil be shown on table. So that i must save last page number after sorting coloumn in jquery table. I searched this problem to find solution. I find solutions only like as below:

```
$('#example').dataTable( {
  stateSave: true
} );
```
How can i save last page number, after coloumn sorting (because of showing first page). And how can i store this last page number on variable to use when i fetch data from server.

**Comment by DataTables** [comment]
Hi. My apologies if the template text for new issues and the contributing document aren't clear enough on the topic of support questions. Could you please direct all support questions to the [DataTables forums](//datatables.net/forums) with a link to a test case showing the issue.
