### ISSUE TITLE
A semantic ui styled pager will extend past the segment border when the responsive datatable is compressed.

### ISSUE THREAD

**Issue by kmd1970** [DataTables/DataTables#924]
Firstly, _thank you_ Allan for completing the Semantic UI style for DataTables. :+1:  

**Minor Tweak**

A semantic ui styled pager will extend past the segment border when the responsive datatable is compressed (like mobile view). In most cases the right end (button) of the pager will not be visible to the user.

The issue can be seen in this image.

![pager](http://i.imgur.com/QAcQJg1.jpg)

Fortunately, the simple solution is to add the `stackable` class to the `ui pagination menu` div.  The `stackable` class will automatically stack rows to a single columns when the container is compressed.

In **dataTables.semanticui.js** line 181 change:
```javascript
attach(
        $(host).empty().html('<div class="ui pagination menu"/>').children(),
	 buttons
 );
```
to
```javascript
attach(
        $(host).empty().html('<div class="ui stackable pagination menu"/>').children(),
	 buttons
 );
```
Which results in this when compressed.

![pager](http://i.imgur.com/u1EtAZL.jpg)

Another suggestion, you could also automatically change the `pagerType` to something shorter like `full` or `simple` (no numbers) when the table is compressed and back to original, when its not.

**Comment by DataTables** [comment]
Thanks for flagging this up! I've made both the grid container for the DataTable and the pagination control stackable ([commit](https://github.com/DataTables/DataTablesSrc/commit/8e074c395171a932f4d09a55602c07ee0fcc0719)).

The stackable pagination is a bit on the ugly side for me, but it does work short term. Longer term, switching the pagination types is the way forward here I think! Thanks.
