### ISSUE TITLE
First load doesn't apply correct first column width  

### ISSUE THREAD

**Issue by vislogurov** [DataTables/DataTables#926]
Hi Allen,

When DataTables is loaded it's show the table  with incorrect image column width(collapsed) [see here](http://s.csssr.ru/U0FMPH83W/2017-04-04-1854-i9llnsa1ma.png)

But when I click on the head cell  , it's automatically show the correct width  [see here ](http://s.csssr.ru/U0FMPH83W/2017-04-04-1853-tuqjiz5e31.png)

Hope you help me)

**Comment by DataTables** [comment]
Apologies if the new issue template text and contributing document aren't clear on the topic of support questions. Please ask support questions in the [DataTables forums](//datatables.net/forums). Please ensure that you post a link to a test case showing the issue as well.

When you've posted a thread there please post the link here so it can be cross tracked.

My guess is that you have scrolling enabled and the width is being applied to the columns before the images are loaded. You need to call the `columns.adjust()` method once the images have loaded.
