### ISSUE TITLE
Not able to maintain row index for serial number

### ISSUE THREAD

**Issue by shahidsalamkhan** [DataTables/DataTables#927]
<div >    
    <table id="provider-grid" cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
        <thead>
        <tr role="row">
            <th>No</th>
            <th>Provider Code</th>
            <th>Provider name (AR)</th>
            <th>Provider name (EN)</th>
            <th>City</th>
            <th>Tel</th>
            <th>Email</th>
            <th>Status</th>
            <th></th>
            <th></th>
            <th></th>
         </tr>
        </thead>
        <thead>
            <tr>
                <td></td>
                <td></td>
                <td><input type="text" data-column="0" class="search-input-NameAR"></td>
                <td><input type="text" data-column="0" class="search-input-NameEN"></td>
                <td><input type="text" data-column="0" class="search-input-City"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                
            </tr>
        </thead>
    </table>

    <div id="dialog" style="display: none">
    </div>

    <div id="dialog-confirm" style=" display:none;">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:3px 12px 20px 0;"></span>This provider will be deleted. Are you sure?</p>
    </div>
</div>

$('#provider-grid').DataTable({
                    data: providersList,
                    "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                        $("td:first", nRow).html(iDisplayIndex + 1);
                        return nRow;
                    }, "searching": false,
                    searchHighlight: true,
                    columns: [{ title: "No", data: null, sortable: false, searchable: false },
                        { title: "Provider Code", data: 'AP_CODE' },
                        { title: "Provider name (AR)", data: 'AP_NAME_AR' },
                        { title: "Provider name (EN)", data: 'AP_NAME_LA' },
                        { title: "City", data: 'CITY_NAME' },
                        { title: "Tel", data: 'AP_TEL' },
                        { title: "Email", data: 'AP_EMAIL' },
                        {
                            mData: [9],
                            sortable: true,
                            "mRender": function (data, type, full) {
                                debugger;
                                if (full.AP_STATUS) return '<img src="/Images/true.png" title="click here to disable provider." height="25px" width="25px" style="cursor:pointer;" class="btnStatus"/>';
                                else return '<img src="/Images/false.png" height="25px" title="click here to enable provider." width="25px" style="cursor:pointer;" class="btnStatus"/>';

                            }
                        },
                        {
                            mData: null,
                            sortable: false,
                            "mRender": function (o) { return '<img src="/Images/edit.png" height="25px" width="25px" style="cursor:pointer;" class="btnEdit"/>'; }
                        },
                        {
                            mData: null,
                            sortable: false,
                            "mRender": function (o) { return '<img src="/Images/del.png" height="25px" width="25px" style="cursor:pointer;" class="btnDel"/>'; }
                        },
                        {
                            mData: null,
                            sortable: false,
                            "mRender": function (o) { return '<input type="hidden" value="' + o.AP_CODE + '" />'; }
                        }

                    ],
                    "order": [[3, "asc"]],
                    dom: 'Bfrtip',
                    buttons: [
         'print', 'excelHtml5',
            'pdfHtml5',
                        {
                            text: 'Add New',
                            action: function (e, dt, node, config) {
                                //alert('Button 1 clicked on');
                                $.ajax({
                                    type: "POST",
                                    url: "/Home/AddNewProvider",
                                    data: '',
                                    contentType: "application/json; charset=utf-8",
                                    dataType: "html",
                                    success: function (response) {

                                        $('#dialog').html(response);
                                        $('#dialog').dialog('option', 'title', 'Add Provider');
                                        $('#dialog').dialog('open');
                                        $(".overlay").show();
                                    },
                                    failure: function (response) {
                                        alert(response.responseText);
                                    },
                                    error: function (response) {
                                        alert(response.responseText);
                                    }
                                });
                            }
                        }
                    ]
                });

**Comment by DataTables** [comment]
Thanks for your question. However, per the new issue template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
