### ISSUE TITLE
New version introduces "a.slice is not a function" error

### ISSUE THREAD

**Issue by robertaboukhalil** [DataTables/DataTables#928]
The example at [this page](https://datatables.net/examples/api/multi_filter_select.html) gives the following error: `a.slice is not a function at jquery.dataTables.min.js:95:404`

This error only appears with v1.10.14 (released today) but not v1.10.13.

**Comment by DataTables** [comment]
Thank you!

This is an important enough fix that I'm going to drop 1.10.15 immediately. Its building at the moment...

**Comment by robertaboukhalil** [comment]
It works great, thank you!
