### ISSUE TITLE
option pageLength should be number？

### ISSUE THREAD

**Issue by henryzp** [DataTables/DataTables#929]
when I use the option:

```
{
      "pageLength": "5"
}
```

it get not expected result。

but if the "5" is a number， like this:

```
{
      "pageLength": 5
}
```

it correct。。

so it can fix ? allow me to string?

**Comment by DataTables** [comment]
[As the documentation notes](https://datatables.net/reference/option/pageLength) it should indeed be a number. It should not be given as a string.
