### ISSUE TITLE
datatables.net-md , could this be for material design ?

### ISSUE THREAD

**Issue by yamenarahman** [DataTables/DataTables#930]
I was wondering if you would specify material design with a package with npm support instead of using cdn for that.

Thanks.

**Comment by DataTables** [comment]
Not yet. The Material Design integration for DataTables isn't really complete and ready for use in production yet I'm afraid. Its really just a preview so I can get feedback.

**Comment by zLegend-210** [comment]
please chech [this](http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/paper-datatable-card/full-implementation.html)

It will be great

**Comment by DataTables** [comment]
Going to close this for now. There hasn't been much interested in the Material Design styling to be honest and there is still a fair amount of work that I know I need to do to get DataTables and its extensions ready for use with it. Keep an eye on the blog for information about this when I do get to it - I would like to add MD support properly!
