### ISSUE TITLE
Override sorting class

### ISSUE THREAD

**Issue by quentincurtet** [DataTables/DataTables#933]
Hi,

I think it would be great to allowed the overriding of sorting class.
For example, we save the current datatable (with specific sorting) in a DataBase and the you load it, it could be nice to display the appropriated class (sorting_asc or sorting_desc) for sorting instead default one (sorting).

Thanks for help.

Cordially.

**Comment by DataTables** [comment]
DataTables should automatically show the correct class based on either saved state or the `order` option. I'm not such which it is you are using. If this is still an issue, can you open a thread in the forums with a link to a test case please?
