### ISSUE TITLE
Speed issue in 1.10

### ISSUE THREAD

**Issue by Angelixion** [DataTables/DataTables#934]
I have found that doing the same datatable(A basic datatable) witht the same dataset, in 1.9.4 is way faster than 1.10.*.

If i use 1.9.4 with 13000 rows with 9 columns it takes 2 seconds to populate the datatable, while in 1.10.* it jumps to 6-7 seconds, and if you have to do more complex things with the data, formatting and the like, it multiplies five-fold the time, while in the 1.9.4 it just consumes more time because of the extra things.

**Comment by DataTables** [comment]
Happy to take a look at a test case showing the issue.

**Comment by Angelixion** [comment]
Here are you test cases:

(1.9.4) https://jsfiddle.net/4qwn1wtz/ 
(1.10.15) https://jsfiddle.net/Angelixion/nvc2oag3/

(1.9.4) https://jsfiddle.net/prpyc51y/
(1.10.15) https://jsfiddle.net/Angelixionhzx33ud3/

**Comment by DataTables** [comment]
Thanks for the links. Using the new API rather than the legacy one, it appears that 1.10 is actually faster: https://jsfiddle.net/nvc2oag3/1/ when using `rows.add()` to add the rows to the table.
