### ISSUE TITLE
Table header doubles

### ISSUE THREAD

**Issue by oninross** [DataTables/DataTables#935]
I followed exactly as shown in the link [https://www.datatables.net/examples/data_sources/ajax.html](url).  I npm-ed the plugin just to let you know and did not download it from github.  I have initialized it and see the image below of the results.  The header is doubling up.

![screenshot_051817_103024_am](https://cloud.githubusercontent.com/assets/2233813/26181623/01bb6cde-3bb5-11e7-8ed4-1c5e1bf4714f.jpg)

**Comment by oninross** [comment]
You need to update your examples.  The way to get rid of the double headers is to declare the tbody as well in the HTML.

**Comment by DataTables** [comment]
Can you link to the example that shows the issue please? Also, in future please can you post support requests in the DataTables forums as requested in the "New issue" text.

[This example](https://datatables.net/manual/api#Accessing-the-API) shows that the tbody does not need to be declared when Ajax loading data and it does not result in a double header.

**Comment by oninross** [comment]
Apologies for the late reply.

Its kind of weird that your example and the codepen version ([https://codepen.io/oninross/pen/LyJMpa](https://codepen.io/oninross/pen/LyJMpa)) does not need to declare the tbody.  But the one in my local machine needs to be declared.  

The only difference I see here is that Im using Yeogurt static site generator and modules.  I will paste it below.  Other than that, its the same. 

**CODE:**
'use strict';

import $ from 'jquery';
import dataTable from 'datatables';

let table,
    processedReferralVal = '';

export default class Datatables {
    constructor() {
        let that = this;

        table = $('.dataTable').DataTable({
            ajax: {
                url: '/api/getReferralQueue.json',
                type: "GET",
                data: {
                    "processedReferral": processedReferralVal,
                    "dateFrom": $('#dateFrom').val(),
                    "dateTo": $('#dateTo').val(),
                    "referral": $('#referralSearch').val()
                }
            },
            // responsive: true,
            // processing: true,      // enable when integrating with server
            // serverSide: true,      // enable when integrating with server
            dom: '<"">frtip',
            info: false,
            autoWidth: false,
            search: {
                caseInsensitive: false,
                smart: false
            },
            columns: [
                {
                    data: "referral"
                },
                {
                    data: "submitted"
                },
                {
                    data: "accessible",
                    searchable: false
                },
                {
                    data: "agency",
                    searchable: false
                },
                {
                    data: "defendant",
                    searchable: false
                },
                {
                    data: "type",
                    searchable: false
                },
                {
                    data: "status"
                },
                {
                    data: "viewReferral",
                    searchable: false,
                    orderable: false
                },
                {
                    data: "viewFiles",
                    searchable: false,
                    orderable: false
                },
            ]
        });

        $('#referralSearch').keyup(function () {
            that.searchTable($(this).val());
        });

        $('#dateFrom, #dateTo').change(function () {
            table.draw();
        });

        $('[name="processedReferral"]').on('change', function () {
            processedReferralVal = '';

            $('[name="processedReferral"]:checked').each(function (i, v) {
                processedReferralVal += ' ' + $(this).val();
            });

            processedReferralVal = processedReferralVal.trim();
            that.searchTable(processedReferralVal);
        });
    }

    searchTable(value) {
        console.log('searchTable')
        table.search(value).draw();
    }
}

**Comment by DataTables** [comment]
We'd really need a link to a page showing the issue I'm afraid. [This is the code](https://github.com/DataTables/DataTablesSrc/blob/d484e85534a1c8eb28542be5169d4c28690cae48/js/core/core.constructor.js#L374) where DataTables will insert the `tbody` if there isn't one. The example I gave shows that is working. We'd really need a running test case showing the issue to be able to help.

**Comment by DataTables** [comment]
Going to close for now. If you are able to reproduce the error with a test case, please feel free to reopen the issue.
