### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by oninross** [DataTables/DataTables#936]
You have documentations in Yarn, Npm, Git and your own website.  There seems to be some inconsistencies.  Sometimes I see **$(elem).DataTables();** or **$(elem).dataTables();**  Yarn still uses 1.10.13 while npm still uses 1.10.15.  npm uses datatables.net while yarn uses datatables.

~Regardless the version, Im still getting #935~

**EDIT** Issue #935 solved but example needs updating

**Comment by DataTables** [comment]
Hi,

I don't actually publish any information about using yarn with DataTables yet as I've not looked into it yet. If there is a yarn DataTables package then it isn't officially published by myself. That is something I need to look into though!

> Sometimes I see $(elem).DataTables(); or $(elem).dataTables(); 

They return different things - see [the documentation for details](https://datatables.net/manual/api#Accessing-the-API).

**Comment by DataTables** [comment]
Oops - I slightly misunderstood Yarn. Its a client to the existing npm repository, so `datatables.net` is the correct package to use, just like with npm and it is also v1.10.15.

**Comment by oninross** [comment]
Oopsies! I didnt see it in the Yarn repo.  Its there all right :)  

Closing this
