### ISSUE TITLE
204 No content

### ISSUE THREAD

**Issue by lfaveur** [DataTables/DataTables#939]
Hi  this is about a call server-side, the ajax call ask a list to something as cars.
The response is 204 No-content but the datatable sent an error js 'Uncaught TypeError: Cannot read property 'error' of undefined' just because the status code is 204 ! if the status code is 200 all are good but to do REST the response is 204 because there is no content ... there is a hack or something to avoid this error ? or any suggestions with a sample code ? Thanks

**Comment by DataTables** [comment]
Good point - I hadn't considered this one before. At the moment DataTables always expects a JSON response, but 204 is a valid exception.

I'll post back here when I've committed something for that.

**Comment by lfaveur** [comment]
@DataTables ok Thanks :+1:

**Comment by DataTables** [comment]
[Committed here](https://github.com/DataTables/DataTablesSrc/commit/8f300673a0e7ad18c0c4eccdc4ab86c57b9b525f).

I've committed it into the _2_ branch as I feel that this is a new feature (ish), and I want to keep the new stuff for v2. Its probably going to be a while before 2.0.0 drops, but it does build and work if you want to try it out (there isn't that much new stuff in it yet - just the start :) ).
