### ISSUE TITLE
Does not work with mysqli

### ISSUE THREAD

**Issue by xoceunder** [DataTables/DataTables#940]
Does not work with mysqli

**Comment by DataTables** [comment]
DataTables doesn't really "care" (in so much as software can care) about what your database interface is. If you can serve up the response in JSON then DataTables should be able to consume it. Full details are [available here](https://datatables.net/manual/data/).

**Comment by xoceunder** [comment]
Until recently I was working now change to php7 and mysqli and stopped working

**Comment by DataTables** [comment]
I'm not sure how that relates to DataTables? You'd probably need to ask about that on a PHP list.
