### ISSUE TITLE
How to change the width of column by mouse dragging

### ISSUE THREAD

**Issue by Gabrielkaliboy** [DataTables/DataTables#941]
How to change the width of column by mouse dragging
如何通过鼠标拖动改变列的宽度？
找不到相关的示例
I can not find the API or example about it;

**Comment by DataTables** [comment]
> I can not find the API or example about it;

That's because this feature doesn't currently exist in DataTables. See [this recent thread](https://datatables.net//forums/discussion/comment/112220/#Comment_112220) for information about a community developed plug-in.
