### ISSUE TITLE
Uncaught TypeError: Cannot set property '$' of undefined

### ISSUE THREAD

**Issue by mathishuettl** [DataTables/DataTables#942]
Hello,

I wanted to use DataTables in my wordpress theme but it doesn't work. I get the error above...

I installed DataTables with npm. My main.js looks like this:

```
var $ = jQuery;
var dt = require("datatables.net")();


$(document).ready(function() {
    $(".datatable").DataTable();
});

```

**Comment by DataTables** [comment]
Hi,

My apologies if the new issue template text and contributing document aren't clear enough. Could you please post support questions in the [DataTables forums](//datatables.net/forums) with a link to a test case showing the issue so it can be debugged please.

Thanks,
Allan
