### ISSUE TITLE
ajax.reload holding aasort (multi-column) position

### ISSUE THREAD

**Issue by adamyi** [DataTables/DataTables#943]
Currently, ajax.reload() with holdPosition parameter set to true can hold the sorting and pagination. Yet, it does not work with aasort (multi column sorting). It reverts back to the situation that the data is sorted by only one column.

**Comment by DataTables** [comment]
Seems to work okay here: http://live.datatables.net/tiliyana/1/edit . Please post a link to a test case showing the issue.

Also, my apologies if the new issue template text and contributing document aren't clear enough. Could you please post support questions in the DataTables forums.
