### ISSUE TITLE
Exporting .xls file

### ISSUE THREAD

**Issue by MihirPalkhiwala** [DataTables/DataTables#944]
Hello,

We just tried export to excel feature and its working fine with **Filename.xlsx**
But is there any way that we can make it **Filename.xls**

**Comment by DataTables** [comment]
Not really - because it is an xlsx file.

You'd need to rewrite it to create the old binary format if you wanted to use true xls.

Why would you want to use xls over xlsx?

**Comment by MihirPalkhiwala** [comment]
Actually system on which our web site is hosted is not supporting xlsx. Thats why i am looking for xls one.

**Comment by DataTables** [comment]
The site hosting shouldn't have any effect since the file is built on the client-side.

**Comment by DataTables** [comment]
Going to close this for now, as xls support is not currently on the roadmap.
