### ISSUE TITLE
FR: Show HTML content and keep table height when search failed

### ISSUE THREAD

**Issue by stanleyxu2005** [DataTables/DataTables#946]
I'm very picky, so I found this amazing project! I still have some feature request to make it even fancier. Here is the story:

I set table with particular height `scrollY:"50vh"`. I hope two things:
1. Whatever I search, the table keeps the height unchanged.
2. If search has no matches, the table keeps the height unchanges. (so that I can put some nice picture to tell user, no records found) 

Normal state
![Normal state](https://user-images.githubusercontent.com/5162687/27803494-50fb1440-605c-11e7-9fd9-d1a84292606c.PNG)

After search, the table is smaller. As you can see, the text "Bottom" moves up now.
![After search, the table is smaller](https://user-images.githubusercontent.com/5162687/27803502-643c67de-605c-11e7-8214-6f3bd0cc9498.PNG)

I'm using the latest version (1.10.15).

**Comment by DataTables** [comment]
Do you have the `scrollCollapse` setting enabled? If so, disable it. It is disabled by default.

**Comment by stanleyxu2005** [comment]
Oh. cool. Thanks. that works
