### ISSUE TITLE
FR: Please dont insert label tag to search box, if search text is empty

### ISSUE THREAD

**Issue by stanleyxu2005** [DataTables/DataTables#947]
We can change the text of search input box. However, if I choose to use a search icon instead of showing text "Search:", datatables will still insert a `<label>` tag. This might break things. I need to use customized toolbar to show a text-less search box. Could you check whether `language.sSearch` is not empyt and then append the `<label>` tag?

```
		var filter = $('<div/>', {
				'id': ! features.f ? tableId+'_filter' : null,
				'class': classes.sFilter
			} );
                 if (language.sSearch) {
			filter = filter.append( $('<label/>' ).append( str ) );
                 } else {
			filter = filter.append( str );
                 }
```

**Comment by DataTables** [comment]
Thing is - that might also break existing styling!

I take the point that is perhaps isn't all that useful to have the `label` when it doesn't have any text it in, but its something that's being in DataTables styling more or less since the start.

Unless there is a major benefit that I'm not seeing, this probably won't go in. What would it break as it is?

**Comment by stanleyxu2005** [comment]
I don't mean to remove label by default. I mean if user set `language.sSearch=''`, which means user does not want to show any text before search box, can we not add an empty label tag in this case?

**Comment by DataTables** [comment]
Yeah - my point was that some might already be doing that and still styling based on the fact that the label is there.

**Comment by stanleyxu2005** [comment]
Yeah. Now I use a more customized search box with `table.columns(0).search(text)`. Close the issue as dev team don't think it will be changed.
