### ISSUE TITLE
clicking on paging number fired searh.dt event

### ISSUE THREAD

**Issue by ruchisheth** [DataTables/DataTables#948]
clicking on paging number fired searh.dt event.

**Comment by DataTables** [comment]
Doesn't appear to here: http://live.datatables.net/fofawojo/1/edit

Please link to a test case should the issue.

**Comment by ruchisheth** [comment]
I set the option server side to **true**

**Comment by ruchisheth** [comment]
https://github.com/yajra/laravel-datatables using this plugin. I think it may be issue of that plugin

**Comment by DataTables** [comment]
When server-side processing is used, then yes the `search` event would be triggered with every draw since it is basically redrawing the table.

The issue is that the client-side doesn't really know when the server-side has new or filtered data, so the full draw is activated.
