### ISSUE TITLE
No Content with AJAX

### ISSUE THREAD

**Issue by Vico1993** [DataTables/DataTables#949]
Hi everyone, 

I have some issue with dataTable and AJAX. 

There is my configuration :  http://zupimages.net/viewer.php?id=17/27/blsv.png

When I display my data with the success of my Ajax request, i have all of my row. But datatable just display "No data available in the table".

There is something I miss ? 

Thanks for your help.

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) and new issue template text, please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.
