### ISSUE TITLE
Json response Error with German Umlaute ÄÖÜ

### ISSUE THREAD

**Issue by dazzafact** [DataTables/DataTables#951]
PLease add support for json with umlaute: ÖÄÜ etc

This works for me
	$db = @new PDO(
				"mysql:host={$sql_details['host']};dbname={$sql_details['db']}",
				$sql_details['user'],
				$sql_details['pass'],
				array( PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,PDO::MYSQL_ATTR_INIT_COMMAND => **"SET NAMES utf8")**

**Comment by DataTables** [comment]
DataTables already fully supports UTF8.

If it isn't for you, please link to a test case showing the issue by posting in the [forums](//datatables.net/forums).

Thanks
