### ISSUE TITLE
How to auto fit parent container height like in a flexbox

### ISSUE THREAD

**Issue by stanleyxu2005** [DataTables/DataTables#952]
I am using the master branch version with the scroller plugin. I can set `scrollY: '100vh'` to align with the whole window, but not its parent container. In my case, I have a 30px header above the table, how to set the `scrollY` setting correctly? 

I've solved my problem by using `scrollY: 'calc(100vh - 30px)'`, but I'd like to know, whether this is the only way to go?

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) and new issue template text, please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged.

You might also be interested in [this blog post on this topic](https://datatables.net/blog/2015-04-10).
