### ISSUE TITLE
2个表 通过同一个json文件导入数据的问题~

### ISSUE THREAD

**Issue by linguihe** [DataTables/DataTables#954]
请问？ 2个表 都是通过同一个json文件导入数据 但不同字段 比如说 A表10个字段 B表8个字段 但都在"data"{}对象中 如何避免报错？
"data": [
{
"zlzs_xmmc": "宁夏旅博会",
"zlzs_jbjs": "1",
"zlzs_zq": "4",
"zlzs_mzlmj": "20000",
"zlzs_jzlmj": "6,633",
"zlzs_qwzlmj": "2000",
"zlzs_qwzlmjbl": "30.15",
"zlzs_zssl": "530",
"zlzs_qwzssl": "400",
"zlzs_qwzsbl": "400",
"zlzs_gzsl": "4300"
},
{
"zlzs_xmmc": "宠物展",
"zlzs_jbjs": "2",
"zlzs_zq": "5",
"zlzs_mzlmj": "9200",
"zlzs_jzlmj": "4,590",
"zlzs_qwzlmj": "2070",
"zlzs_qwzlmjbl": "45.10",
"zlzs_zssl": "360",
"zlzs_qwzssl": "89",
"zlzs_qwzsbl": "24.72",
"zlzs_gzsl": "50000"
},
{
"zlzs_xmmc": "茶博会",
"zlzs_jbjs": "2",
"zlzs_zq": "5",
"zlzs_mzlmj": "35000",
"zlzs_jzlmj": "3,627",
"zlzs_qwzlmj": "2358",
"zlzs_qwzlmjbl": "65.01",
"zlzs_zssl": "178",
"zlzs_qwzssl": "98",
"zlzs_qwzsbl": "55.06",
"zlzs_gzsl": "100000"
},
{
"hylt_xmmc": "卫生论坛",
"hylt_jbjs": "1",
"hylt_hq": "5",
"hylt_chgm": "419",
"hylt_qwchdbs": "167",
"hylt_qwchdbbl": "39.86",
"hylt_yjjb": "50",
"hylt_qwyjjbsl": "48",
"hylt_qwyjjbbl": "96"
},
{
"hylt_xmmc": "人力资源论坛",
"hylt_jbjs": "1",
"hylt_hq": "2",
"hylt_chgm": "343",
"hylt_qwchdbs": "55",
"hylt_qwchdbbl": "16.03",
"hylt_yjjb": "8",
"hylt_qwyjjbsl": "5",
"hylt_qwyjjbbl": "62.5"
},
{
"hylt_xmmc": "会展教育论坛",
"hylt_jbjs": "1",
"hylt_hq": "3",
"hylt_chgm": "704",
"hylt_qwchdbs": "111",
"hylt_qwchdbbl": "15.77",
"hylt_yjjb": "9",
"hylt_qwyjjbsl": "4",
"hylt_qwyjjbbl": "44.44"
}
]

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) and new issue template text, please post support requests in the [DataTables forums](//datatables.net/forums).

With regard to this issue, you would need to use `$.ajax` to get the JSON data yourself and then use the `rows.add()` method of DataTables to add the data from the JSON file.
