### ISSUE TITLE
autowidth:false and scrollX: true resize out-of-sync

### ISSUE THREAD

**Issue by smasala** [DataTables/DataTables#956]
Config
```json
{
   autoWidth: false,
   scrollX: true
}
````
Table: 
```html
<table style="width: 100%"></table>
```

Steps:
1. Start DT in small browser window size
2. Maximise browser
3. Columns have expanded but the headers haven't, no longer insync with each other.

What does it mean for docs?
https://datatables.net/reference/option/autoWidth

**Comment by smasala** [comment]
The question is also... is it correct that when resizing a table (larger than at its original size) with `autoWidth: false` that the columns still expand?

**Comment by DataTables** [comment]
Its because the `autoWidth` parameter is disabled - therefore DataTables won't automatically resize the columns. You need to call `columns.adjust()` yourself instead: http://live.datatables.net/layajowu/1/edit .

Disabling autoWidth is something I wouldn't recommend doing. I've actually been toying with the idea of removing that option in a future update - but haven't really thought it through properly yet.

**Comment by smasala** [comment]
I mean: https://jsfiddle.net/zppuznsb/ with or without `width` property. Expand the `js` window to replicate.

**Comment by DataTables** [comment]
Without `autoWidth: false` it does resize the columns correctly: https://jsfiddle.net/zppuznsb/1/ . It uses throttling so it doesn't crush the CPU, although that does mean there can be a noticeable lag.

**Comment by smasala** [comment]
`autoWidth: false` shouldn't the size of the table remain fixed on resize and all the columns (tbody) stay within the table and not overflow? After all, the table is given a `width` property and fixed pixel size.

**Comment by DataTables** [comment]
Sort of. Basically what it does is automatically call `columns.adjust()` for you - perhaps "autoSize` would be a better name.

Since scrolling is enabled, `columns.adjust()` must be called either internally or externally when the table is resized. The table is split into component parts (i.e. header, body footer in different tables) which are all aligned with Javascript when scrolling is enabled. This is the only way I've found of making scrolling work reliably across browsers.

Remove the scrolling option and you don't have this problem any more since it is all one table. Even if the column calculations aren't redone, the browser will still force them to align.

This is one of the reasons why I've been thinking of dropping it!

**Comment by smasala** [comment]
Ok..... I think I get it :) :)

What about placing the table inside a div and setting an `overflow: auto` on it? I had to do something similar for the colResize extension: https://github.com/smasala/ColResize/blob/master/js/dataTables.colResize.js#L221

**Comment by DataTables** [comment]
For x scrolling - yes that works okay (its what Bootstrap do for their responsive tables). But it doesn't work for y-scrolling tables. At least not if you want to still see the header and footer at the top and bottom of the table.

**Comment by smasala** [comment]
Of course..... what about a CSS solution? Here's a very basic example I quickly put together: https://jsfiddle.net/3f1g6v1f/

The problem with the current example is that the width needs to be set for all the `tbody th` and `tbody td` elements. Rather than just the `th's` which I would find more acceptable. But like I said, just a quick example :)

P.s. forgot about `scrollY` heights + fixed headers... will need to revisit that for my ColResize extension :) What's the default `scrollY` value? Docs don't mention it and `true|false` have the same DOM manipulation outcome.

**Comment by DataTables** [comment]
I don't have IE handy, but does it work in IE8+? DataTables core supports IE6+ at the moment, but that will change soon to 8+.

The problem I see with it is that the scrollbar is off the scrolling view port, so you can't get a visual clue that the table scrolls horizontally.

Having said all that, I do like this method and if it can be made to work, it would shave about 10KB of the size of DataTables core I think

> What's the default scrollY value?

Disabled (`null` I think is the actual value, it might be `false`).

**Comment by smasala** [comment]
I was on the Mac there, so you don't see the scroll bar :)
To see the scroll bars we'll need a bit of JS I think. 

Wasn't able to test IE9+ because JSFiddle doesn't support it anymore and the page can't load :)
IE10+ https://jsfiddle.net/jz5mot1e/2/

For those browsers that don't support transform IE<=8 (I haven't tested it :+1: )
https://jsfiddle.net/u1zg8of7/
Obviously this one (last example) isn't complete, because the position of the `scroller-wrapper` is hard-coded however, if you are saying that 10kb is currently needed... then maybe this could be a lightweight version alternative?

**Comment by DataTables** [comment]
That's brilliant! The scrolling aspect of DataTables has always been by far the most complex bit of the software. I've forked to DataTables v2 to start adding some new features for v2, and I will very much be looking at incorporating this. I can't say when exactly its going to be available, but this looks super promising.

IE11 does a double horizontal scroll bar, but that might be something that is resolvable.

**Comment by smasala** [comment]
> IE11 does a double horizontal scroll bar, but that might be something that is resolvable.

I don't see a double X scroll bar in IE11. Have you got some doc/compatibility mode set in dev console?

**Comment by smasala** [comment]
> > What's the default scrollY value?

> Disabled (null I think is the actual value, it might be false).

`true` and `false` and `null` all cause dom manipulation. `""` (empty string) doesn't.

**Comment by DataTables** [comment]
That sounds like a bug - false and null shouldn't split the table (unless x scroll is enabled). I'll check that out.

For IE11 I didn't have any compatibility mode enabled. However, I'm reasonably sure that will be something that can be resolved - it looks like a padding issue.

**Comment by smasala** [comment]
I'll close this issue in the meantime :)
