### ISSUE TITLE
How to using DataTables with React ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [DataTables/DataTables#959]
# How to using DataTables with React ?

I just want to know that it's possible to combine DataTables with React!

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

Regarding your question, [this article](https://medium.com/@zbzzn/integrating-react-and-datatables-not-as-hard-as-advertised-f3364f395dfa) might be of some interest.
