### ISSUE TITLE
footerCallback first argument is undefined

### ISSUE THREAD

**Issue by smasala** [DataTables/DataTables#960]
template:

```html
<table>
    <thead></thead>
    </tfoot></tfoot>
</table>
```
JS:
```js
build dt with data
```

The first argument of `headerCallback()` is the `<tr>` element inside the `<thead>`. However, the first argument of `footerCallback()` is `undefined`. 

If you add an empty `<tr></tr>` into the `<tfoot></tfoot>` then you get the `<tr>` element as the `footerCallback()` first argument. 

The `headerCallback` provides the `row` element because it is built by DT and the `columns` dataset. However, in both cases this is incorrect.

Shouldn't both callbacks return the parent element `<thead>` and `<tfoot>` and not the `<tr>` element it contains as the docs mention?
https://datatables.net/reference/option/headerCallback
https://datatables.net/reference/option/footerCallback

**Comment by DataTables** [comment]
I fear that's going to be a double bug. Yes I agree, it should return the containing element, but given that its probably always been that way for the 1.x series that's not something that I can really change now lest it break loads of code that relies upon that.

The correct thing to do is probably to change the documentation to reflect the current behaviour and then for v2 introduce new events which do give the containing elements.

Thanks for flagging this up.

**Comment by smasala** [comment]
👍 sounds good :)
