### ISSUE TITLE
About  Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by tsaomichael** [DataTables/DataTables#961]
Hi admin:  I get this error. Can you help me? I have three page use datatables change link, first time this dataTables is working but change link back not working. This page no data result. My table not used rowspan and colspan.

chrome console:
<td class="dataTables_empty">no results</td>
jquery.dataTables.js:670 Uncaught TypeError: Cannot read property 'className' of undefined
    at _fnGatherData (jquery.dataTables.js:670)

`if ( bClass ){
	console.log(nCell);
	nCell.className += ' '+oCol.sClass;
  }`

$(document).ready(function(){
  $(".example").dataTable({
    aoColumnDefs: [
      { sType: "currency", aTargets: [1, 2, 3, 4, 6] }
    ],
    sPaginationType: "full_numbers", //bootstrap pagination
    iDisplayLength: 20,
    aLengthMenu: [[20, 50, 100, -1], [20, 50, 100, "All"]],
    defaultContent: "-",
    targets: "_all"
  });
});

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
