### ISSUE TITLE
Fixed columns : extra cell visible on IE9

### ISSUE THREAD

**Issue by Vatvat99** [DataTables/DataTables#962]
Hello.

There is a problem wis misscalculated height in IE9, for fixed columns.

You can see it on this page : https://datatables.net/extensions/fixedcolumns/examples/styling/bootstrap.html
![capture-datatable](https://user-images.githubusercontent.com/10259673/28865241-7e3e4d62-776f-11e7-88fc-e90dc4240cac.jpg)

At the bottom of the fixed columns, there is one extra cell. I can't find a way to fix that. Seems to append only with the bootstrap theme.

I have tested on a virtual machine with the real IE9, and Windows 7.

**Comment by DataTables** [comment]
Thanks for letting me know about this. I'll take a look into it for the next FixedColumns release.

**Comment by DataTables** [comment]
Moved to [FixedColumns #66](https://github.com/DataTables/FixedColumns/issues/66).
