### ISSUE TITLE
JQuery-UI 1.12.1 - Carat Vs Caret

### ISSUE THREAD

**Issue by martingraham** [DataTables/DataTables#963]
Using JQueryUI 1.12.1 and the JQuery-UI flavoured version of Datatables I noticed (eventually) that one of the pair of sorting arrows were missing from columns, apparently this is because this version of JQueryUI (amongst lots of other changes, but nothing else I've noticed affecting datatables) has changed the spelling of carat to caret so some icons aren't getting picked up?

https://jqueryui.com/upgrade-guide/1.12/#removed-ui-icon-carat-classes-renamed-to-ui-icon-caret

Workaround: These classes are in $.fn.dataTable.ext.oJUIClasses and I can get round it by search and replacing the values in there: "-carat-" to "-caret-"; but just thought anyone else who comes across this might like the heads-up

I don't know whether datatables itself could eventually run a test on which version of JQuery-UI ($.ui.version) is running to do this swap automatically?

**Comment by DataTables** [comment]
Thanks for letting me know about that!

I've [committed the fix in](https://github.com/DataTables/DataTablesSrc/commit/7d13bc71553149aabb50de5281ac3a410edf7bd0) and it will be merged to this repo soon.
