### ISSUE TITLE
Bootstrap pagination focus

### ISSUE THREAD

**Issue by olemoign** [DataTables/DataTables#965]
With bootstrap styling, after moving to a different page, dataTables restores focus to the clicked `<li>` https://github.com/DataTables/DataTables/blob/7494262db18b1cbc69dcc1d64a5a8d0cd757d58c/media/js/dataTables.bootstrap.js#L159-L177
Problem is, if the table has many pages, the page numbers can slide left and right after navigation. The focus being restored to the `<li>` according to idx, we then have one `<li>` with the active class (the one we are on, we clicked on, but which moved) and another one with the focus, like this:

![image](https://user-images.githubusercontent.com/11632871/29214224-cd11abc6-7ea6-11e7-9faa-34496ffbe6bd.png)
I'm willing to correct this and submit a PR, but first I wanted to ask if it's the intended behaviour ?

PS: I'm never sure if an issue ticket is the right place to do this, but I wanted to thank you for the good work.

**Comment by DataTables** [comment]
Hi,

Thanks for bringing this up. The [DataTablesSrc repo](/datatables/datatablesrc) is where PRs of this sort would go.

I'm not quite 100% sure I understand the issue though. If you click the "6" in your above screenshot, the new "7" should then be focused. Is that not happening?

**Comment by olemoign** [comment]
I consider this a - small - issue and I wanted to make sure if you did or not.
For me, it's surprising that the active '<li>' isn't the one focused (in your example, for me, the "6" should be active and focused). But if the current behaviour is in line with your intentions, then I'll accept it. :)

**Comment by DataTables** [comment]
The view I was taking was that the focus should stay in the same position for keyboard users. I felt that anything else might be confusing - although I'm happy to be corrected by anyone who primarily uses the keyboard and JAWS or similar.

**Comment by olemoign** [comment]
Ok that makes sense to me. I guess you can close the ticket.
