### ISSUE TITLE
dataTable.moment conflicting with serverSide Processing

### ISSUE THREAD

**Issue by annajeanine** [DataTables/DataTables#966]
I'm not 100% sure if I found a bug or not but I have enabled the moment.js to sort the dates in my table with are now formatted 'dddd D MMMM YYYY'. The code which I have now: 

```
$(document).ready(function(){
        $.fn.dataTable.moment('dddd D MMMM YYYY');

        $('#users').dataTable({
            processing: true,
//        serverSide: true,
            responsive: true,
            ajax: '{{ route('admin.datatables.subscription.users', ['subscription' => $subscription->id]) }}',
            language: {
                url: "//cdn.datatables.net/plug-ins/1.10.13/i18n/Dutch.json"
            },
            columns: [
                {data: 'username', name: 'username'},
                {data: 'start_at', name: 'start_at'},
                {data: 'stop_at', name: 'stop_at'},
                {data: 'action', name: 'action', searchable: false, orderable: false}
            ]
        })
    });
```

When I re-enable the serverSide: true option the moment sorting fails and sorts alphabetically instead of based on the yyyy/mm/dd.
I'm not 100% sure if this is just a bug in my code of a conflict from both serverSide and moment.js?

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

Regarding your question - server-side processing means that the ordering will happen at the server-side. That's the whole point of server-side processing! So any client-side plug-in isn't going to have any effect.
