### ISSUE TITLE
Fixed columns : locking columns can alone scroll on IE9

### ISSUE THREAD

**Issue by LawlietNot** [DataTables/DataTables#967]
This problem will appear in IE
![image](https://user-images.githubusercontent.com/6241768/29419114-d77fb77a-83a0-11e7-9ad1-182388d780da.png)
In fixedcolumns examples have appeared，
The column marked in the picture can be scrolled individually
https://datatables.net/extensions/fixedcolumns/examples/styling/bootstrap.html

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

**Comment by DataTables** [comment]
Btw - I do recognise that this is a bug, and my apologies for that. I just want everything to go to the forum so there is a single location for searching information of this sort and also for me to keep track of.
