### ISSUE TITLE
Update "empty" information colspan when resizing responsive table

### ISSUE THREAD

**Issue by jrysig** [DataTables/DataTables#968]
If the table is empty, the sEmptyTable or sZeroRecords information appears in <td> with class "dataTables_empty". Colspan is properly calculated, but it isn't updated when table is resized. 

If you expand the table (and some hidden columns are displayed), "empty" information will not expand to the full table width.

**Comment by DataTables** [comment]
I believe this was fixed [here](https://github.com/DataTables/Responsive/commit/169a61c0b10883f32225630f4b7e6afafd9faa5b).

Could you post future support requests in the forums please? For example [this thread](https://www.datatables.net/forums/discussion/41632) already covers this topic.
