### ISSUE TITLE
EmptyDataTable and sInfo

### ISSUE THREAD

**Issue by balthazarl** [DataTables/DataTables#970]
Hello,
Asp:GridView with an EmptyDataTemplate property, renders a row when datasource is empty.
After that, DataTables display footer with number of rows=1 because of that row.

Is there a way in this plugin to walk around this issue ?
Thanks.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
