### ISSUE TITLE
Slow when 15,000 records are added to the static table

### ISSUE THREAD

**Issue by jkathir** [DataTables/DataTables#972]
Hi, 

I have 15,000 table rows defined in a html file. It takes more time to render 15,000 rows. With pagination it is faster however the export options export only the rows being displayed.

Any efficient way to render 15,000 rows and also provide export options to download 15,000 rows as csv, excel, pdf, word, png etc.,

Thanks.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
