### ISSUE TITLE
CDNJS is not informed of version 1.10.16

### ISSUE THREAD

**Issue by holtkamp** [DataTables/DataTables#973]
It seems that version `1.10.16` is not tagged in GitHub, this commit: https://github.com/DataTables/DataTables/commit/75a665f64f02982c0f4666b15a25c4670e5e6b18

The releases:
- https://github.com/DataTables/DataTables/releases

Now version `1.10.16` is not available at CDNJS: https://cdnjs.com/libraries/datatables

Simply tagging the version in GitHub should resolve this "problem" 😄 

**Note**
Note that the following repo's ARE properly updated to `1.10.16`:

- https://www.npmjs.com/package/datatables.net
- https://www.npmjs.com/package/datatables.net-bs

**Comment by holtkamp** [comment]
Aah, here it is: https://github.com/DataTables/Dist-DataTables/releases, probably the CDNJS autoupdate configuration is incorrect?

**Comment by DataTables** [comment]
Its [on this repo now](https://github.com/DataTables/DataTables/tree/1.10.16) as well. This is actually a legacy repo - the _Dist_ repos are the preferred ones, but this one is still used a fair bit externally, so I keep it in sync. Or at least try to!

**Comment by holtkamp** [comment]
> This is actually a legacy repo

Aah, ok, good to know. 

https://cdnjs.com/libraries/datatables-fixedheader seems also not updated automatically. Maybe we have to change the autoupdate configuration at CDNJS to use the new *Dist* repositories...?

**Comment by DataTables** [comment]
There has been [some discussion on that topic already](https://github.com/DataTables/FixedHeader/issues/83).

From my point of view the "main" repos are for the source code, while the `Dist-` repos are for distribution (i.e. any build / compiled code). That seems to work well from an npm point of view - but I'm not sure how well it works for CDNJS?
