### ISSUE TITLE
Incorrect version in link to CDN after clicking Button on WebSite / releases

### ISSUE THREAD

**Issue by holtkamp** [DataTables/DataTables#974]
The newest version is `1.10.16`, but when clicking a button like "Bootstrap" on  https://datatables.net/download/release, then `1.10.15` is referred to. 

![screen shot 2017-09-02 at 13 21 43](https://user-images.githubusercontent.com/776405/29995102-f7f2c3d8-8fe1-11e7-9c7d-d9a157f5437f.png)

**Comment by DataTables** [comment]
Thanks. I've not quite brought the download builder up to speed with the latest releases as I've got some work I want to do to it first. The Javascript stuff is actually populated slightly differently from the static - which is why there is a discrepancy. It will correctly shortly!

**Comment by DataTables** [comment]
All fixed and up to date now :-)

**Comment by holtkamp** [comment]
https://datatables.net/download/index

wow, that is some fancy download page you got there! Respect++ 😄
