### ISSUE TITLE
Add support for orderFixed on column or make possible to specify sorting direction on orderData

### ISSUE THREAD

**Issue by Seb33300** [DataTables/DataTables#977]
Hello,

I am asking for a feature request since I didn't found an easy way to do this.

I would like to apply the `orderFixed` option to force the sorting direction (asc or desc) on another column but only when I am ordering a specific column of my datatable.

So maybe the we can add a `columns.orderFixed` option.
Or just improve the current `columns.orderData` option to make it able to force the sorting direction:
```javascript
$(document).ready(function() {
    $('#example').DataTable( {
        columnDefs: [ {
            targets: [ 0 ],
            orderData: [ 0, [ 1, 'asc' ] ] // force to always sort ASC the column 1
        }, {
            targets: [ 1 ],
            orderData: [ 1, 0 ]
        }, {
            targets: [ 4 ],
            orderData: [ 4, 0 ]
        } ]
    } );
} );
```
(Based on this example: https://datatables.net/examples/basic_init/multi_col_sort.html)

Thanks!

**Comment by DataTables** [comment]
Thanks for the suggestion - its a good one. There is already a [forum thread on this topic](https://www.datatables.net/forums/discussion/34637), so I'll close this issue in favour of the forum thread.

**Comment by Seb33300** [comment]
Thanks for the replay.

Unfortunately, the discussion is closed so I am not able to reply.

> One thing I haven't sorted out with the interaction yet though is - presumably the direction should be inverted. So for example when you sort column index 3 ascending you want 3-asc, 2-asc, 1-desc and then when descending you want 3-desc, 2-desc, 1-asc?

This could be de default `orderData` behavior as the example provided in my first post.

And we can add the `columns.orderFixed` option to force the direction (which will not change when sorting the related column asc / desc)

**Comment by DataTables** [comment]
> orderData: [ 0, [ 1, 'asc' ] ]

Would column index 1 there _always_ be 'asc' sorted (when using that column), regardless of what direction its parent column index 0 is?

**Comment by Seb33300** [comment]
No, it's a bad example because default sort is asc.

With this example:
```javascript
columnDefs: [ {
            targets: [ 0 ],
            orderData: [ 0, [ 1, 'desc' ] ]
        }, {
            targets: [ 1 ]
        } ]
```

Sorting column 0 asc will result in: 0-asc, 1-desc
Sorting column 0 desc will result in: 0-desc, 1-asc

If you want to have column 1 always be asc or desc sorted, we can use a new `columns.orderFixed` option working the same as [datatable orderFixed](https://datatables.net/reference/option/orderFixed) option:
```javascript
columnDefs: [ {
            targets: [ 0 ],
            orderData: [ 0, 1 ]
            orderFixed: [ 0, 'asc' ]
        }, {
            targets: [ 1 ]
        } ]
```

**Comment by DataTables** [comment]
Thanks for the suggestion - that does sound good. I wonder if another way would be to use an object to define the sort (which really I should have done in the first place):

```js
orderData: [
  0,
  {
    index: 1,
    seq: 'desc'
  }
]
```

then `seq` can be an array that would be applied in sequence, or a string as above where it would be fixed to always be desc.
