### ISSUE TITLE
Columns hide way too early when collapsing table with the Responsive & FixedHeader extension

### ISSUE THREAD

**Issue by halloei** [DataTables/DataTables#978]
I'm using the Responsive extension and I'm just trying out the FixedHeader one. Now I experienced a bug:
When the fixed header is shown and you start to drag the table smaller, the columns disappear too early.

Steps to reproduce:
1. visit the [offical example](https://datatables.net/extensions/fixedheader/examples/integration/responsive.html)
2. resize the window so all columns are visible
3. scroll down a bit so the fixed header becomes active
4. start resizing the window horizontally (make it smaller)

You will see there will be only the first column left soon. Then, when you resize the window to become bigger, it needs to be really wide for the other columns to appear again (if they appear again at all).

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

**Comment by halloei** [comment]
I did post that in the [forums](https://datatables.net/forums/discussion/39160/columns-hide-way-too-early-when-collapsing-table-with-the-responsive-fixedheader-extension) 10 months ago. However it got no answers and has been closed.

**Comment by DataTables** [comment]
Thank you - I've posted back there and reopened that discussion.
