### ISSUE TITLE
datatable coulmn render value dymanically

### ISSUE THREAD

**Issue by pranathi3105** [DataTables/DataTables#979]
the datatable columns are binding dynamically hoe to the values using render

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
