### ISSUE TITLE
Alignment classes are absent in dataTables.bootstrap.css

### ISSUE THREAD

**Issue by itelmenko** [DataTables/DataTables#982]
In [dataTables.bootstrap.css](https://github.com/DataTables/DataTables/blob/master/media/css/dataTables.bootstrap.css) we don't have [alignment classes](https://datatables.net/manual/styling/classes):

> dt[-head\|-body]-left | Left aligned text
> dt[-head\|-body]-center | Center aligned text
> dt[-head\|-body]-right | Right aligned text
> dt[-head\|-body]-justify | Justify aligned text
> dt[-head\|-body]-nowrap | nowrap aligned text
> 

It is old bug https://datatables.net/forums/discussion/27547/bootstrap-3-align-classes-for-body-or-head-only

**Comment by DataTables** [comment]
Bootstrap has [its own text-alignment classes](https://getbootstrap.com/docs/4.0/utilities/text/#text-alignment). Rather than duplicating code, I think its probably best to use the ones from Bootstrap.

**Comment by itelmenko** [comment]
@DataTables, sorry, how can I use these classes if I need centered alignment for column titles and right alignment for column cells?

**Comment by DataTables** [comment]
Probably one for the Bootstrap list to be honest. You'd need to assign `text-center` for the `th` elements (I guess they are in your HTML already), perhaps with a `!important` for that CSS rule.

Then if the table rows are generated then you'd use the `columns.className` option to assign `text-right` to the rest.

Fair point though - the Bootstrap classes aren't quite as flexible here.

**Comment by itelmenko** [comment]
I think, it is not correct way....   Because each developer must create own css rules for headers alignments.

My opinion is that dt-* alignment classes need to be added in dataTables.bootstrap.css also. 
Or dataTables.bootstrap.css need contain css rules based on bootstrap classes (without !important of cause):

```css
th.text-center {
    text-align: center
}
```
