### ISSUE TITLE
summing columns when grouping rows

### ISSUE THREAD

**Issue by mosxe** [DataTables/DataTables#983]
Hello, faced one problem.
I grouped the rows in the table using "drawCallback". For each grouping,  need to calculate the amount.
To calculate the amount I use "rowGroup".
And here I am faced with one problem
In the "rowGroup" in the "dataScr" as I figured out, can specify 1 only the data source (in this case I pass the data in the json- format) and specify the name of the column. It sums it up correctly, but I need to sum up 2 columns, not one. 
Here is the code snippet:
`"rowGroup": {
                    dataSrc: 'short_name',
                    startRender: null,
                    endRender: function ( rows, group) {
                        console.log(rows);
                        var numFormat = window.getFormatNumberTable().display;
                        var saldo1 = rows
                            .data()
                            .pluck('saldo1')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);
    
                        var oborot_db = rows
                            .data()
                            .pluck('oborot_db')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);
                            
                        var div_name_up = rows
                            .data()
                            .pluck('div_name_up')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);
                            
                        var oborot_cr = rows
                            .data()
                            .pluck('oborot_cr')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);
                            
                        var saldo2 = rows
                            .data()
                            .pluck('saldo2')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);
                            
                        var razn = rows
                            .data()
                            .pluck('razn')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);
                            
                        var div_name = rows
                            .data()
                            .pluck('div_name')
                            .reduce( function (a, b) {
                                return a + b;
                            }, 0);

                    return $('<tr/>')
                        .append(`<td colspan="1">Итого по ${group}:</td>`)
                        .append(`<td class = 'fortd'> ${numFormat(saldo1)}</td>`)
                        .append(`<td class = 'fortd'> ${numFormat(oborot_db)}</td>`)
                        .append(`<td></td>`)
                        .append(`<td class = 'fortd'>${numFormat(oborot_cr)}</td>`)
                        .append(`<td class = 'fortd'>${numFormat(saldo2)}</td>`)
                        .append(`<td class = 'fortd'>${numFormat(razn)}</td>`)
                        .append(`<td></td>`);
                    },
                },`

Can I specify two data sources or is there another way
Thank you in advance

http://fastpic.ru/view/96/2017/1002/0a8db2075eba9afd693a019e66f549c8.jpg.html
http://i95.fastpic.ru/big/2017/1002/82/61e162dd3059a9d7b173712fff02cf82.jpg

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

Regarding the question - could you simply do `oborot_cr + saldo2` (or whatever parameters it is you actually want to join)?

Your other option is to use the `cells()` selector to select data from multiple columns - [docs](https://datatables.net/reference/api/cells()).

**Comment by mosxe** [comment]
Thank you.
It does not work unfortunately or I do something wrong.
Made a couple of demo options. 
https://jsfiddle.net/mosxe/ucju154p/1/
https://jsfiddle.net/mosxe/ucju154p/2/
The main problem for me is that I do not know how to specify two data sources in the "RowGroup" "dataSrc:"

**Comment by DataTables** [comment]
Could you open a new thread in the forums please?

**Comment by mosxe** [comment]
Sure. 
Thanks, DataTables.
