### ISSUE TITLE
DB Mysql DataTables not support utf8 charset

### ISSUE THREAD

**Issue by lechidung** [DataTables/DataTables#986]
Connect DB mysql DataTables not support utf8 charset. I think update ```charset=utf8``` in line below:
https://github.com/DataTables/DataTables/blob/master/examples/server_side/scripts/ssp.class.php#L388
to:
```
"mysql:host={$sql_details['host']};dbname={$sql_details['db']};charset=utf8",
```
Thanks

**Comment by DataTables** [comment]
Thanks for this - however, if your MySQL server is setup to use utf8 by default that shouldn't be required. It can be useful and thanks for posting this so others can find it, but it isn't always required, so it isn't something I'll merge in at the moment.
