### ISSUE TITLE
HTML5 data- attributes and row.add() API method

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#987]
When using `data-` attributes, specifically `data-order` attribute, calling `row.add()` API method fails with the following message:

>DataTables warning: table id=example - Requested unknown parameter '[object Object]' for row 3, column 0. For more information about this error, please see http://datatables.net/tn/4

See [this example](https://jsfiddle.net/2yu7mLL3/7/) for code and demonstration.

I understand that this may not be a bug because order of rows is modified via `data-` attribute and newly added row is missing that attribute.

However one or all of the following solutions might be necessary.

* Modify error message to be more descriptive
* Document this behavior on `row.add()` API method page
* Document this behavior on [HTML5 data-* attributes - cell data](https://datatables.net/examples/advanced_init/html5-data-attributes.html) page

Current workaround is to construct a node before adding it with `row.add()` API method, see [my answer on StackOverflow](https://stackoverflow.com/a/46811182/3549014).

**Comment by DataTables** [comment]
You need to add the data in the same format as DataTables has read the data in with the orthogonal data:

```
{
    "0": "001",
    "1": "Task #1",
    "2": "100",
    "3": {
        "display": "6th June 10:00",
        "@data-order": "1496739600000"
    },
    "4": "2017/06/06"
}
```

See [this thread](https://datatables.net//forums/discussion/comment/112032/#Comment_112032) for more information.

**Comment by mpryvkin** [comment]
Properties starting with `@` are not documented on [Orthogonal data](https://datatables.net/manual/data/orthogonal-data) page.

I understand about the warning and just proposing this use case to be added to the documentation.

**Comment by mpryvkin** [comment]
By the way, your suggested fix doesn't work, see [this example](https://jsfiddle.net/2yu7mLL3/10/).

**Comment by DataTables** [comment]
It doesn't in that example because DataTables hasn't and can't detect the HTML data attributes from the original table - since it doesn't have any. There aren't any rows in the table, so you'd need to have configured the orthogonal data options in DataTables to feed in the formatted object that is now being fed in.

**Comment by mpryvkin** [comment]
Allan, I added column definitions, see https://jsfiddle.net/2yu7mLL3/11/

However it is not clear how to use properties starting with `@` as attributes, since it's not documented anywhere.

**Comment by DataTables** [comment]
Yup - that needs to be improved! Thanks.

**Comment by jjhesk** [comment]
@DataTable when your solution will be working? 
```
{
    "0": "001",
    "1": "Task #1",
    "2": "100",
    "3": {
        "display": "6th June 10:00",
        "@data-order": "1496739600000"
    },
    "4": "2017/06/06"
}
```
now its only with full dom insert working. http://live.datatables.net/johenazi/5/edit

**Comment by jjhesk** [comment]
just enhancement purposes
here is the code for reading the object
```javascript

function tabkeinject(data) {
    if (!Array.isArray(data)) return "";
    let sql = "";
    sql += '<tr>';
    data.forEach((item) => {
        sql += '<td ';
        if (item["@data-order"]) {
            sql += 'data-order="' + item["@data-order"] + '"';
        }
        sql += '>' + item.display + '</td>';
    });
    sql += '</tr>';
    return sql;
}
```

**Comment by DataTables** [comment]
The example you linked to appears to be working as expected. Can you link to a test case showing it not working please?
