### ISSUE TITLE
Big memory leak if in AngularJs we use $compile in createdRow()

### ISSUE THREAD

**Issue by falinsin** [DataTables/DataTables#989]
I've noticed that if we use angularJs $compile on a datatable createdRow()
When reload reloadData grow numbre of detached  watchers and unattended DOM stuff

Even when use pagination is growing this becouse in paginations datatable execute  createdRow()

Is it possible destroy previous $compiles Rows before enter in createdRows and avoid this Big memory leak?

We use angularJs $compile because We whant render the datatable rows with some interaction as buttons ng-click and we want this interaction  with functions in the $scope of the controller Wehre the datatable is created.

Sorry my English

Please if you know an alternative idea or a solution let me know. 

Thank you in advance for your help and support.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
