### ISSUE TITLE
datatables some numbers are too large, show 4.68951E + 07, I hope the original number, do not convert, how do?

### ISSUE THREAD

**Issue by 3031213101** [DataTables/DataTables#991]
datatables some numbers are too large, show 4.68951E + 07, I hope the original number, do not convert, how do?

Thank you for your help!

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
