### ISSUE TITLE
data tables search and pagination not working after rendering server side

### ISSUE THREAD

**Issue by jane223** [DataTables/DataTables#993]
I am currently rendering a table using the following code (which renders the table and the info fine, but the pagination or search features do not work)

https://jsfiddle.net/m3bs6bbg/

I need to pass todays date to my controller method in order to get the information needed, I then need to append the body of the table to show this info. What exactly am I doing wrong? The table renders perfectly but the use of the data tables functionality is gone when I do this. I know the aoData is relevant to making the pagination and search work, but how exactly am I working that into my code?
Many Thanks!

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
