### ISSUE TITLE
Fixed Header and  scrolling

### ISSUE THREAD

**Issue by xdevnull** [DataTables/DataTables#998]
Hello,

Not quite sure this should consider as "bug" or "enhancement" 

When we have multiple columns that don't fit the page (scrolling required).  and the Fixed header options is enabled.

The table fixed header doesn't scroll a long with table content.

Inital: 
https://imgur.com/6vqxctQ

After scrolling:
https://imgur.com/a/2PEyu

**Comment by DataTables** [comment]
Hi,

I'm afraid that FixedHeader and scrolling cannot currently be used together, as [noted in the compatibility table](https://datatables.net/download/compatibility).
