### ISSUE TITLE
IE8, class reserved word

### ISSUE THREAD

**Issue by Worthy7** [DataTables/DataTables#999]
//#########################
	// Class Definition Table #
	//#########################
	var ClassRangeRecord = new r.Struct({
	  start: r.uint16,
	  end: r.uint16,
	  class: r.uint16
	});

This code doesn't work in IE8 because you called the property `class`.
Please rename it and all instances for the next version :)

**Comment by Worthy7** [comment]
Separate issue, Not wanting to spam you, but the .delete is also not allowed in IE8.
I thought this was supposed to be IE8 compatible. Did I download the wrong version?

**Comment by Worthy7** [comment]
ill report this in pdfmake

**Comment by DataTables** [comment]
Thanks for posting back. I was confused initially as I didn't recognise the code!
